### ISSUE TITLE
Ensure that 3DOM capability filter is comprehensively patching things

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1001]
As of #992, we will have a basic implementation of 3DOM. In this implementation, the capability filter patches immediate properties but doesn't check to make sure all properties in the prototype chain are properly patched:

https://github.com/google/model-viewer/blob/77f91baa00e482aca391653a76000bc79d0ec1f4/packages/3dom/src/context/generate-capability-filter.ts#L50-L73

We should ensure that the whole chain gets patched.

**Comment by elalish** [comment]
This doesn't exist anymore
