### ISSUE TITLE
Implement and observe specified scene graph traversal order

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1002]
For 3DOM, we have tentatively agreed to the following scene graph traversal semantic below. We need to implement this traversal order in the current implementation of 3DOM.

## Scene Graph

A **scene graph** is a finite, hierarchical tree structure.
In **scene graph order** is preorder, depth-first traversal of a scene graph.
A **scene graph element** is an object that participates in a scene graph.
A **scene graph root** is a scene graph element from which all other scene graph elements can be referenced during scene graph traversal.
A **descendant** of scene graph element A is any scene graph element B that may be referenced from scene graph element A, and also has a reference to the scene graph root.
A **recurring scene graph element** is any scene graph element that can be said to be a descendant of at least two other scene graph elements of the same scene graph.

### Basic traversal

**Basic traversal** visits all scene graph elements in scene graph order.
Recurring scene graph elements are visited every time they are encountered during traversal.

### Sparse traversal

**Sparse traversal** visits all scene graph elements in scene graph order.
Recurring scene graph elements are only visited the first time they are encountered during traversal.

**Comment by elalish** [comment]
I think this is done, at least for material nodes.
