### ISSUE TITLE
Decide how to handle elements in inactive scenes

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1003]
In the current 3DOM implementation, we only operate on the "primary" scene of a glTF. That is, the scene that is assigned to the top-level `scene` property of the glTF. Any materials or other elements that are not directly accessible by traversing the primary scene are currently ignored and not represented in e.g., `model.materials`.

Should we ignore them? What happens if and when the scene changes (note: this is not currently supported by `<model-viewer>`)?

Note that this dovetails a bit with #195

**Comment by elalish** [comment]
This isn't true anymore.
