### ISSUE TITLE
annotation-container missing. Adding Hotspots to a model does not work

### ISSUE THREAD

**Issue by CalvinLloyd117** [google/model-viewer#1014]
When using the sample code found at https://modelviewer.dev/examples/annotations.html to add annotations/hotspots to a model, the added buttons are missing/not displayed like they are in the demo code. After using chrome to inspect the live version at the link provided, and comparing it to my (identical) code, it appears that the annotation container found in the shadow-root (and by extension the annotation wrapper and generated slots for the buttons) are missing/not being generated correctly. 

The annotation-container div is also found in all of the examples found at https://modelviewer.dev/ even if the example does not use annotations. This container is missing from all of my replications of the examples using the code provided.

#### Live Demo

Code used found at https://modelviewer.dev/examples/annotations.html

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions

- model-viewer: v0.8.1
 as well as at "https://unpkg.com/@google/model-viewer/dist/model-viewer.js" (v0.7.2)
- three.js: r79.0.0

**Comment by cdata** [comment]
@CalvinLloyd117 I apologize for the confusion. Our docs are always deployed from the master branch on our Github project, but if you get `<model-viewer>` from unpkg.com or NPM, it will be the latest release.

We are working on adding versioning to our docs (#818), but that work is still ongoing. In the mean time, we have a release coming up at the end of this sprint (v0.9.0) that will include annotations. If you want to experiment with it early, you can build `<model-viewer>` from our master branch, or use the version from our docs (https://modelviewer.dev/dist/model-viewer.js). Just be advised that our master branch is not guaranteed to remain stable, and the URLs in our docs can break at any time.

**Comment by CalvinLloyd117** [comment]
Thank you so much for getting back to me! The master branch supplied does include the feature, working as intended.

**Comment by anuraghakeem** [comment]
Hi, I wanted to add the annotation hotspots to the AR module. Is there a way to do the same with annotation-container?
