### ISSUE TITLE
QuickLook on iOS Chrome does not work with .reality files, even with correct Content-Type Headers

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1017]
### Description

A similar issue came up in #534, however, it seems that this time Chrome actually has an issue.
QuickLook supports both .usdz files (model/vnd.usdz+zip) and .reality files (model/vnd.reality). However, even with QuickLook chrome integration enabled, only .usdz files properly display in AR, .reality files always get downloaded (they work fine in Safari).

**Expected:** .reality opens in QuickLook in iOS Chrome when pressing AR button
**Actual:** .reality is downloaded in iOS Chrome when pressing AR button

#### Live Demo
https://prefrontalcortex.de/labs/model-viewer/penguin-audio/
(can't use glitch since it does not serve correct Content-Type anyways)

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by cdata** [comment]
@soraryu thanks for catching this. This may, in fact, be considered a feature request by the Chrome team (just speculating). IIRC they had to manually implement support for `.usdz`, so it is likely that they would have to do the same for `.reality`. 

My recommendation would be to file a bug at https://crbug.com. If you do, I will reach out to some folks I know on the iOS Chrome team and see what they have to say 👍

**Comment by soraryu** [comment]
I reported a bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1051609
Thanks for forwarding this!

**Comment by DA-NDI** [comment]
Hello. Any news on .reality support in model-viewer?

**Comment by cdata** [comment]
This bug is about `.reality` file issues in iOS Chrome. At this time, I do not know of a reason why `.reality` files would fail in iOS Safari. @DA-NDI Can you confirm that `.reality` files fail with `<model-viewer> in **iOS Safari** (not Chrome)?

**Comment by soraryu** [comment]
Quick update: just got a notification that the bug is fixed in Chrome, so hopefully at some point in the future this will work properly.

https://bugs.chromium.org/p/chromium/issues/detail?id=1051609#c4
https://chromium.googlesource.com/chromium/src.git/+/e4e00438348f37dd35349aeb084564eee2e53502

**Comment by soraryu** [comment]
Seems this will release in Chrome 85, already in Canary.
