### ISSUE TITLE
Feature request: UI enhancement during plane detection

### ISSUE THREAD

**Issue by nicolocarpignoli** [google/model-viewer#1022]
Hi there,
I don't know if this is the right place to ask. Anyway, I'll try.

I used with success Google's Native AR (to see animals in AR, for example, from Google Search - I think it's called Scene Viewer) and then I used model-viewer component from this repo. To me, it's practically the same, but I was not able to do some stuff with model-viewer component, that is crucial for some projects: to customize UI.
See the picture below: the alert on the bottom that is saying to 'detect the plane' and the animation on the center of the screen are crucial for the user to understand what he/her has to do. I can't add it or have control on when the plane is detected, in order to remove it.

<img src="https://user-images.githubusercontent.com/22395670/74383365-5a8e0200-4def-11ea-8fbb-943cd59ed14e.png" width="300" height="500">

So, is there any way to customize this? I was not able to do that. Am I missing something? 
Thank you in advance.

**Comment by jakecjones** [comment]
Scene Viewer is a separate app launched from the browser so (I am guessing) there is no way to customize it.

**Comment by cdata** [comment]
@nicolocarpignoli depending on whether you are talking about Scene Viewer or `<model-viewer>`, the answer is going to be a bit different. The bottom line, though, is that right now you cannot customize the UI in AR view. Eventually, you will be able to customize it for `<model-viewer>` + WebXR-based AR, but we are still a ways from making that happen.

**Comment by nicolocarpignoli** [comment]
Ok, got it!
