### ISSUE TITLE
Annotations Not Working in React

### ISSUE THREAD

**Issue by theranbrig** [google/model-viewer#1031]
As of now getting annotations to work has been impossible.  I am not sure if it is because of the fact that I am using the model viewer in React with Styled Components.  I have the model viewer wrapped in a component with all of the CSS from the example.  But no animations show up.  

The buttons do appear when I remove the slot attribute, but are pushed up into the corner as expected.   This is with the test astronaut file.  I have used it as a project file and as a linked file.  I am not sure if has something to do with the lifecycle method of React?

Not sure if

```
import React, { useState } from 'react';
import styled from 'styled-components';

const ModelStyles = styled.div`
  button {
    display: block;
    width: 20px;
    height: 20px;
    border-radius: 10px;
    border: none;
    background-color: blue;
    box-sizing: border-box;
  }

  button[slot='hotspot-hand'] {
    --min-hotspot-opacity: 0;
    background-color: red;
  }

  button[slot='hotspot-foot']:not([data-visible]) {
    background-color: transparent;
    border: 3px solid blue;
  }

  #annotation {
    background-color: #888888;
    position: absolute;
    transform: translate(10px, 10px);
    border-radius: 10px;
    padding: 10px;
  }
  /* This keeps child nodes hidden while the element loads */
  :not(:defined) > * {
    display: none;
  }
`;

const ModelViewer = () => {
  const [stateGLB, setStateGLB] = useState('');
  const history = useHistory();
  return (
    <ModelStyles className='model-box'>
      <model-viewer
        id='hotspot-demo'
        camera-controls
        src='../assets/images/Astronaut.glb'
        alt='A 3D model of an astronaut.'>
        <button slot='hotspot-visor' data-position='0 1.75 0.35' data-normal='0 0 1'></button>
        <button slot='hotspot-hand' data-position='-0.55 0.95 0.1' data-normal='-1 0 1'>
          <div id='annotation'>This hotspot disappears completely</div>
        </button>
        <button
          slot='hotspot-foot'
          data-position='0.16 0.11 0.15'
          data-normal='0 1 0.75'
          data-visibility-attribute='visible'></button>
      </model-viewer>
    </ModelStyles>
  );
};

export default ModelViewer;

```

**Comment by cdata** [comment]
@theranbrig thanks for reaching out! It kind of sounds like you might not have the right version of `<model-viewer>`. Can you confirm how you are currently installing `<model-viewer>` and what version you have?

Some things to keep in mind: although our docs always show the latest build that passes our tests on Github, `npm install @google/model-viewer` will only give you the latest release. So, it's possible that you have a version of `<model-viewer>` that doesn't have annotations in it yet.

Anyway, I'm sure we can figure this out together. Looking forward to your response 👍

**Comment by cdata** [comment]
(BTW we are cutting our first release with annotations - v0.9.0 - today; I'm assembling the release notes right now)

**Comment by cdata** [comment]
v0.9.0 is now officially published, in case that is what the problem was 👍

**Comment by theranbrig** [comment]
I will give 0.9.0 a look and get back to you soon.

**Comment by cdata** [comment]
@theranbrig any updates? Were you able to get annotations to work?

**Comment by theranbrig** [comment]
@cdata 
Sorry.  Had another ticket come up that I got put on first.
Tested it out and everything is working.  Upgraded my `package.json` to `0.9.0` and it is working perfectly.  Thank you for everything.
