### ISSUE TITLE
Shadow does not disappear when shadow-intensity property set to zero

### ISSUE THREAD

**Issue by fivelive** [google/model-viewer#1032]
The model-viewer documentation for property `shadow-intensity` states that "
Controls the opacity of the shadow. Set to 0 to turn off the shadow entirely. Defaults to 0.",  but even when set to zero, the shadow does not disappear.

**Comment by cdata** [comment]
@fivelive Thanks for the report. Can you share a screenshot of what you mean?

Also can you confirm what browser, browser version, device, version of `<model-viewer>` etc. you are seeing this with?

**Comment by fivelive** [comment]
Hi, I'm using Chrome Version 79.0.3945.130 on a MBP 16 inch. This issue happens on both `model-viewer` v0.8.1 and 0.9.0 (I haven't tried it on other versions though).

So here is the scenario:

1. I initialized a model-viewer with `shadow-intensity` set to zero, and it works fine. (No shadow is appearing as expected)
![image](https://user-images.githubusercontent.com/39774571/74923921-97359c80-539f-11ea-8775-4ac7a2e148f4.png)

2. Then I set the `shadow-intensity` to 10, and still works fine (A strong shaddow appears)
![image](https://user-images.githubusercontent.com/39774571/74924068-cf3cdf80-539f-11ea-9091-8e6a888c92e8.png)

3. Then here appears the issue, I now set the `shadow-intensity` to 0, and nothing happens. (the strong shadow of previous step is still appearing)
![image](https://user-images.githubusercontent.com/39774571/74924188-03180500-53a0-11ea-9a49-78f3bae4c99f.png)

4. Just to make sure, as an extra step, I now set the `shadow-intensity` to 1, and it works fine. (A light shadow appears)
![image](https://user-images.githubusercontent.com/39774571/74924306-35296700-53a0-11ea-9e0e-f8b236e2f714.png)


The issue really seems to happen when you try to update the `shadow-intensity` to zero.

Here is an extra screenshot to explain the scenario:
![image](https://user-images.githubusercontent.com/39774571/74925024-7ec68180-53a1-11ea-9c5f-47f6b5a1ffd6.png)

**Comment by cdata** [comment]
@fivelive thanks for the additional detail, this looks like a plausible bug on our side. I'll take a look!
