### ISSUE TITLE
Stand Alone version ? Possible/Legal ?

### ISSUE THREAD

**Issue by IvanNov7** [google/model-viewer#1035]
Hello,
I want to ask if its possible to locate model-viewer script on my site host and not load it from link?
And is it legal at all?
Trying to find if there is a way to get static version without updates.
Thank you!

**Comment by cdata** [comment]
Yes, it is possible, you can just download it from the link or you can clone our source repository and build it for yourself. The instructions to build it are in our README.

And, it's totally legal 👍 the whole project is licensed under the Apache 2.0 license. Here is the TL;DR for that license: https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

So, it's free to use for personal or commercial reasons, free to change, free to redistribute etc. The only things the license says you cannot do are sue us and market with our names or trademarks.

**Comment by cdata** [comment]
Also, if you just want to keep it from auto-updating, you can use a URL like this: https://unpkg.com/@google/model-viewer@0.9.0/dist/model-viewer.js

See how the version is built-in to the URL? That will pin it to a specific release, so it won't change over time.

**Comment by IvanNov7** [comment]
Thank you for answer!
I can just download it from github ? What folders should i include ?
Or maybe its just enough to locate on my host ?

> model-viewer.js

  and  

> model-viewer-legacy.js

Sorry for so simple questions)

**Comment by cdata** [comment]
@IvanNov7 if you download from Github, you will get the source code. You will need to build it using the steps described in our README. Please note that the steps assume you have experience with Node.js and NPM.

If install it from NPM or download it from unpkg.com, you can get pre-built bundles. This would save you from having to build it yourself.

At the most basic level, you would need the `model-viewer.js` bundle (https://unpkg.com/@google/model-viewer@0.9.0/dist/model-viewer.js). For IE11 support, you should also get the "legacy" bundle (https://unpkg.com/@google/model-viewer@0.9.0/dist/model-viewer-legacy.js). It is just fine to download those URLs from unpkg.com and save them to your local machine  👍 they are the same URLs that we publish to NPM.

I'm happy to help you build the bundles yourself, too, if you run into issues trying to do that. But, if you are new to Node.js and NPM you might be better served reading up on that elsewhere.

**Comment by IvanNov7** [comment]
Got it.
Thanks a lot for so great and wide answers!
