### ISSUE TITLE
Problem with AR on IOS

### ISSUE THREAD

**Issue by IvanNov7** [google/model-viewer#1036]
Hi,
*Maybe its wrong place to ask, and if so - i will immediately remove this post .*

I try to run my model with USDZ file on iPad but always get error of "ZERO KB".
Same with demo model on modelviewer-dev website.
Anyone maybe know where is the problem ? ... 

Here is my model example:

> https://in3dreal.net/links/P2.html
![IMG_0006](https://user-images.githubusercontent.com/54315481/74827647-ce179e00-531e-11ea-8254-ab421b7b6ce4.PNG)

**Comment by theranbrig** [comment]
How big is the file you are using and how complex is it?  We had issues with files that had really high polygon counts and were over 10mb failing to load.

**Comment by IvanNov7** [comment]
Hi, my file almost 14mb.
But the problem that even demo model from https://modelviewer.dev/ - the astronaut, gives me same error.
