### ISSUE TITLE
Animated Model Not working in AR Mode

### ISSUE THREAD

**Issue by Adhil98** [google/model-viewer#1037]
Rigged Model With Animation is not working. When i preview in AR it shows
![Error](https://user-images.githubusercontent.com/43722374/74837279-26629600-5347-11ea-8c40-7f33f5b5eff2.jpg)
I tried with another model like a sofa, it's working fine.
Here is the model I used on my project
 https://sketchfab.com/3d-models/junko-chan-cf23816acbca40d0aba77665a9a163d9
Below is the webAR link
https://adhil98-webarforandroidandios.glitch.me
I tried using Mixamo rig, but it also not working. The Example Model(RobotExpressive.glb) in the Github works fine. Can someone suggest to me what I did wrong?

**Comment by Adhil98** [comment]
Tried with Another model working fine.

**Comment by ronpadz** [comment]
I get this same error with an animated model that worked correctly prior to the last version update. See example at http://bit.ly/2VhTybP
