### ISSUE TITLE
Access assets globally

### ISSUE THREAD

**Issue by whiteyhat** [google/model-viewer#1044]
### Description
I want to load my `gtlf` assets from an external host. Eg: My s3 CloudFront.

#### Problem
The `poster` parameter obviously works. But when it loads the `gtlf` is configured to only work locally

### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.9.0
- three.js: latest

**Comment by cdata** [comment]
@whiteyhat are you sending proper CORS headers with the response? Permissive CORS are necessary when serving glTF models from any web server, and for Amazing S3 I know they do not set them by default (you have to configure them). 

Here is another issue where I gave a similar answer: https://github.com/google/model-viewer/issues/1015

Here is a help article that describes how to enable CORS for an Amazon S3 bucket: https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors

**Comment by niloriver** [comment]
Hi guys. 
In my case I'm allowing everything and having the same problem.

**No 'Access-Control-Allow-Origin' header is present on the requested resource.**

But other mime-types it loads from anywhere with no problem.
