### ISSUE TITLE
Request for maintaining a Changelog!

### ISSUE THREAD

**Issue by KingYapster** [google/model-viewer#1045]
Request for maintaining a changelog!

I'm checking this repository after a long time. I had last used v0.7.0, I would like to know what new functionalities have been added!

**Comment by cdata** [comment]
@KingYapster We actually do keep a changelog in the "releases" section of our Github project: https://github.com/google/model-viewer/releases

Please let me know if that's what you were hoping to find!

**Comment by KingYapster** [comment]
Thanks! @cdata
