### ISSUE TITLE
Animation doesn't work in WebXR

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#1057]
I tried putting the `unstable-webxr` attribute on our animation samples and found the model is rendered statically in AR mode. The problem is the logic we have in our Renderer class regarding animation, exposure, and shadows, which does not exist in the ARRenderer class. Looks like we need a bit of refactoring to share this code.

**Comment by cdata** [comment]
> Looks like we need a bit of refactoring to share this code.

Definitely 👍
