### ISSUE TITLE
Overflowing Method Names

### ISSUE THREAD

**Issue by karanganesan** [google/model-viewer#1058]
### Description

<img width="1269" alt="Screenshot 2020-02-28 at 12 57 55 PM" src="https://user-images.githubusercontent.com/6049925/75520036-926d8a00-5a2a-11ea-91f5-89051a567678.png">

Do something for overflowing text 
may be add it to next line or 
decrease the size of text

#### Live Demo
https://modelviewer.dev/

### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions
- model-viewer: latest
- three.js: latest

**Comment by cdata** [comment]
Thanks for reporting @karanganesan , and good catch! I'm actually working on revising our whole docs page right now, so I think we will have this fixed when #970 lands.

**Comment by elalish** [comment]
Fixed.
