### ISSUE TITLE
Shadow rendering hides transparent objects

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1065]
### Description

Shadow rendering hides/ overlays rendering of transparent objects in what seems to be a render order issue. This only happens from specific camera angles (usually pretty low angle of attack).

Should look like this: (note circular floor elements)
![Screenshot_2020-03-01-09-20-24-486_com android chrome](https://user-images.githubusercontent.com/2693840/75622230-7c80d600-5b9e-11ea-8b07-669f8790138a.jpg)

Does look like this from specific angles:
![Screenshot_2020-03-01-09-20-19-438_com android chrome](https://user-images.githubusercontent.com/2693840/75622250-a803c080-5b9e-11ea-8352-502571f8985b.jpg)
![Screenshot_2020-03-01-09-20-13-172_com android chrome](https://user-images.githubusercontent.com/2693840/75622251-acc87480-5b9e-11ea-8d6c-19b5c8eddfb1.jpg)

Note that besides the shadow issue there's also a floor object missing and some sorting order issues only visible during the animation. "Ground Truth" on Sketchfab:
![IMG_20200301_093605](https://user-images.githubusercontent.com/2693840/75622423-3a589400-5ba0-11ea-8f1c-2b96e1ee3729.jpg)

#### Live Demo
https://glitch.com/edit/#!/wax-citrine-cress

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

### Versions
latest dist

**Comment by elalish** [comment]
@soraryu It doesn't look like a render order issue to me; I think what you're seeing is actually bright reflections off the transparent floor layers. I think the main difference may simply be the default environment lighting between model-viewer and sketchfab. However, I'm not sure about the purple floor layer that seems to be gone entirely. I'll have to look into that.

**Comment by soraryu** [comment]
I think you're right, part of the effect is the reflection. Setting exposure=0 looks ok (in terms of shadow).
Seems when setting shadow-intensity to anything >0 the floor plane is gone; setting shadow-intensity=0 makes the floor plane appear:
![image](https://user-images.githubusercontent.com/2693840/75720385-b35a0780-5cd6-11ea-940f-edc76a590bfa.png)
