### ISSUE TITLE
Transparency rendering is broken when both texture and emission texture are used in gltf

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1068]
### Description

I also reported the issue directly to the three.js repo here:  https://github.com/mrdoob/three.js/issues/18796

I'm opening this issue here so that you're aware of it and hopefully update the used three.js version once this is resolved. A weird workaround exists (using KHR_Texture_Transform in affected materials).

![image](https://user-images.githubusercontent.com/2693840/75698261-ac1f0380-5cae-11ea-9f73-96f55e6dc855.png)

![image](https://user-images.githubusercontent.com/2693840/75698264-b04b2100-5cae-11ea-8acb-461978068ba3.png)

#### Live Demo
https://glitch.com/edit/#!/spice-water-dormouse

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [X] Safari

### OS

- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by cdata** [comment]
Thanks for discovering that workaround @soraryu . Depending on what that extension is doing, it's possible that we could apply the fix manually for now.

The two potential culprits seem to include cloning the texture: 

https://github.com/mrdoob/three.js/blob/d62a3ddc9e1633e9723d8526a06643dc1fe45d14/examples/jsm/loaders/GLTFLoader.js#L632

And flagging it with `needsUpdate`: 

https://github.com/mrdoob/three.js/blob/d62a3ddc9e1633e9723d8526a06643dc1fe45d14/examples/jsm/loaders/GLTFLoader.js#L658

**Comment by elalish** [comment]
Fixed.
