### ISSUE TITLE
Disable the default button in AR view

### ISSUE THREAD

**Issue by JIMMYSE** [google/model-viewer#1079]
3D modeling is transparent by surrounding objects due to buttons in the attached file. Can you start with this button disabled?
![cap](https://user-images.githubusercontent.com/17997093/76514416-32033180-649b-11ea-8cf8-54aa6d586e16.PNG)

**Comment by cdata** [comment]
This UI is part of the native app Scene Viewer, and we cannot control it AFAIK.

cc @tpsiaki

**Comment by elalish** [comment]
Now off by default and configurable.
