### ISSUE TITLE
Feature Request: Add ar-src attribute

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1084]
### Description

We have a number of usecases where we want/need to load a different model in model-viewer than in SceneViewer, same as is currently possible with QuickLook.

One of those is where the model displayed in the web has a longer / different animation with much more interactive control over which animation to play etc, but the model displayed in AR has a shorter animation since there's currently not much control over it.

Another usecase is that both SceneViewer and QuickLook have their own sets of rendering and animation bugs that we need to work around. In some cases that means we want to show a different model there that might look a bit different since the one we want to use in model-viewer bugs out in SceneViewer.

Yet another usecase is annotations - since model-viewer is supporting those now, we can show specific annotations directly there but still need to show "baked in" annotations in the AR model, resulting in the need for multiple GLB files with different set-ups.

---------------

For ios, we can currently specify that with ios-src. And we have a workaround to set the android source right when the AR button is pressed (and changing it back afterwards), but that is hacky and potentially adds more download load (as both browser and SceneViewer download the new glb file).
I understand that the original motivation for ios-src was just that it needs an USDZ; maybe the right name for such an attribute would be "ar-src"? Not sure. In the future, there might be different needs for different platforms (e.g. models for Magic Leap might also need to be different).

**Comment by cdata** [comment]
Thanks @soraryu that's a totally fair request and I think we can accommodate it.

Given what you have described, I'm inclined to suggest that this should be a Scene Viewer-specific model URL, not an AR-specific model URL. As you say, the bugs and UX you are working around are specific to Scene Viewer. Does that sound acceptable to you?

One consideration to keep in mind: we already incur a "double download" when activating Scene Viewer because Scene Viewer has to download models separately from `<model-viewer>`. I hope we can work together to avoid this "double download" cost when using WebXR.

**Comment by soraryu** [comment]
Yes, down the line I think the ability to specify the file per-platform makes total sense.

Please note that from a UX perspective there might also be the need to have a separate model for WebXR - e.g. with shorter animation, larger text, ... Which in a sense would just be another "<platform>_src" attribute then I guess.

**Comment by cdata** [comment]
@soraryu I agree that it may be inevitable that we need to have a way to specify a separate model for WebXR-based AR in some cases. However, for both performance and UX reasons, I think it would be ideal if we encourage users to craft models that work well in both inline and WebXR rendering scenarios.

I think we would expose a mechanism to let folks load models via 3DOM and pair that with information about the presentation mode, for example (pseudocode):

```html
<model-viewer>
  <script type="experimental-scene-graph-worklet" allow="load-models; presentation-state">
const arModelLoads = self.importModel('ar-specific-model.glb');

self.addEventListener('presentation-change', async () => {
  const arModel = await arModelLoads;

  if (self.presentationState === PresentationState.AR) {    
    hideModel(self.model);
    showModel(arModel);
  } else {
    hideModel(arModel);
    showModel(self.model);
  }
});
  </script>
</model-viewer>
```

**Comment by elalish** [comment]
I think the first workaround described is a reasonable approach here. The second download can be avoided by first changing the interaction-policy to manual.
