### ISSUE TITLE
model viewer test page crashes Chrome, Edge

### ISSUE THREAD

**Issue by stevesan** [google/model-viewer#1089]
### Description

When I visit the page (https://modelviewer.dev/examples/tester.html), my screen flashes black and I see this:
![image](https://user-images.githubusercontent.com/1388372/76874878-2bcbd700-6846-11ea-8baf-ab18f9ffe1d9.png)

My DXDIAG:
![image](https://user-images.githubusercontent.com/1388372/76875008-57e75800-6846-11ea-8e94-2ea3946bea90.png)

#### Live Demo
https://modelviewer.dev/examples/tester.html

### Browser Affected

- [x ] Chrome
- [x ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x ] Windows

### Versions
Live deployed at: https://modelviewer.dev/examples/tester.html

**Comment by stevesan** [comment]
Also happens on my macbook air (~5 years old). Specs:
![image](https://user-images.githubusercontent.com/1388372/76876765-c9280a80-6848-11ea-9262-bdef58797aa3.png)

**Comment by elalish** [comment]
@stevesan Can you check some other non-chromium browsers like Safari and Firefox? If they work properly, then I'm thinking this may be an offscreenCanvas issue. Also, do you get the same behavior on all of our docs pages? Particularly those with a single model-viewer element vs several?

**Comment by stevesan** [comment]
This seems to happen even with the astronaut in modelviewer.dev. Also with the [animation example](https://modelviewer.dev/examples/animation.html)

However, it's not totally broken: I still see the animations and real time shadows. It's just all the shading is black: 
![image](https://user-images.githubusercontent.com/1388372/77079944-18984300-69cf-11ea-8147-ab72afbe8283.png)

**Comment by stevesan** [comment]
Tried Firefox. Even more severe: my computer locks up a bit, then Firefox doesn't show anything at all.

Confirmed that after restarting Firefox, threeJS examples and Poly do work fine.

**Comment by elalish** [comment]
@stevesan Can you try again, this time appending `?model-viewer-debug-mode` to the end of any URL? That will cause it to spit out any shader compilation errors to the console. If you find any, please paste them here. Also, are you getting a context loss on all browsers on all model-viewer page loads? We surface a context loss event, so you might be able to set a breakpoint there and figure out what's causing that. Your help is much appreciated since I don't have a machine I can repro this on yet.

**Comment by stevesan** [comment]
(followed up offline with debug log)

Another data point: Today, everything started working just fine on my MacBook Air. Interesting..maybe I had too many tabs open? GPU memory issue?

**Comment by elalish** [comment]
Ah, very interesting. I'm not really sure what happens when you run out of
GPU memory, but my guess is it's not good. We should probably try to find a
way to detect it and fail more gracefully. Meanwhile, please keep me posted
on anything you find where it does repro consistently.

Thanks!

-Emmett

**Comment by stevesan** [comment]
OK this was determined to be caused by the PMREMGenerator in threeJS. A PR is in progress: https://github.com/mrdoob/three.js/pull/18935
