### ISSUE TITLE
3d Model not loading in Scene Viewer

### ISSUE THREAD

**Issue by Esteban26** [google/model-viewer#1091]
The GLB model we are trying to use cannot be opened by scene viewer. It seems to be a problem with Scene viewer because we have some other 3d models working properly. And we are also able to validate the model in some pages like this:

https://model-viewer-tester.glitch.me/

This is the GLB file we're trying to display with the model viewer tool.

https://drive.google.com/file/d/1Bvk27lwhYdZg-SRKvpDBE2lRos_hcGgW/view?usp=sharing

- [X ] Chrome
- [X ] Android

**Comment by MaartenBreeedveld** [comment]
@Esteban26 
You'd best use [This previewer](https://arvr.google.com/scene-viewer-preview)
It's much more informative,
The model you've uploaded contains reference errors, So it won't load..
![image](https://user-images.githubusercontent.com/23651802/77225387-f6d5c200-6b6e-11ea-966c-1f7c21cd1ccf.png)

**Comment by cdata** [comment]
@Esteban26 the previewer linked by @MaartenBreeedveld is a web-based version of the same model loading / rendering implementation used by the Scene Viewer native app, so if you can get it to loading/render without errors in that previewer it is more likely (but not guaranteed) to work in Scene Viewer as well.

**Comment by cdata** [comment]
cc @tpsiaki for visibility

**Comment by Esteban26** [comment]
thank you guys @MaartenBreeedveld  @cdata
