### ISSUE TITLE
Scene Viewer doesn't load Cloudfront pre-signed urls

### ISSUE THREAD

**Issue by MaartenBreeedveld** [google/model-viewer#1095]
### Description
When i'm trying to view a model from **a signed cloudfront url**
![Screenshot_20200324-123259_Google](https://user-images.githubusercontent.com/23651802/77421753-a5c30980-6dcc-11ea-98be-07a9b7ffcf93.jpg)
It's Dutch for the famous **'Can't load object'** message.

I've created a scenario to test this.
[**The first url**](https://api.i-see-3d.com/viewer/test) displays the Astronaut model and loads the files from S3
[**The second url**](https://api.i-see-3d.com/viewer/5e79f0b02230e306a289a923) loads the exact same model only from cloudfront using a presigned URL

The first one loads happily in Scene Viewer, The second displays the message above.
The ThreeJS viewer loads everything just fine.

iOS seems to show a blank screen.

So i'm wondering if:
- You can't have query parameters in the file's url?
- Presigned is off limits?

### OS

- [ x ] Android
- [ x ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: latest

**Comment by cdata** [comment]
@MaartenBreeedveld thanks for reporting.

The first thing I can think of regarding the CloudFront URL is that we append a couple of query parameters to the request (we attempt to preserve any existing ones). We use these parameters to configure the `title` and `link` of the card shown in Scene Viewer.

We have an outstanding task to update to a more recent version of the intent scheme for Scene Viewer. I think I forgot to file an issue for it, so here it is now: https://github.com/google/model-viewer/issues/1097

The new intent scheme might allow us to preserve the query string as-is.

I tried navigating directly to the CloudFront URL to see if manipulating the query string made a difference. It does seem to cause an `AccessDenied` error for me. So #1097 is probably the issue you want to track to fix this 👍

**Comment by MaartenBreeedveld** [comment]
@cdata Thanks a lot for looking into this!
I'm wondering, are there currently <model-viewers> versions that don't have this issue?
Just to be sure, the CF url is valid for only 5 minutes after the pagerequest, afterwards an 'Access Denied' error is shown.

**Comment by cdata** [comment]
@MaartenBreeedveld yeah, I noticed there was a time limit on the requests, so I re-attempted the request a few times to make sure. It appears as though appending an unexpected query parameter causes the request to be denied immediately, even in cases where I successfully made the request without the query parameter just moments before.

There are current versions of the Scene Viewer intent that will work, but we need to update our use of the intent in order to benefit from that. We will probably do this update very soon, but at this time we are working with diminished resources on account of the COVID-19 pandemic and related response efforts, so I'm hesitant to make any promises.

**Comment by pushmatrix** [comment]
That's too bad that scene viewer removed query params in the intent.

We were relying on this for https://size.link, where our api for generating a box of any size was https://size.link/box.gltf?w=1&h=2&l=3&units=cm

It works for model viewer, but then if you try to view in AR, the dimensions get stripped :(

So we had to change our api to be

https://size.link/1/2/3/cm/box.gltf

**Comment by elalish** [comment]
@pushmatrix If I understand you correctly, model-viewer is passing the URL including your query parameters to the SceneViewer intent, but SceneViewer is stripping them and therefore failing to load your model URL? @tpsiaki would you consider this a SceneViewer bug?

**Comment by pushmatrix** [comment]
@elalish Correct. Check this glitch out: https://brave-closed-scarecrow.glitch.me/

Model-viewer shows the correct box, but when you go to view it in scene-viewer all sides have the same dimension.

**Comment by pushmatrix** [comment]
<img width="391" alt="Screen Shot 2020-06-12 at 10 09 16 PM" src="https://user-images.githubusercontent.com/190692/84557460-67692680-acf9-11ea-8d33-54bd208d4446.png">

<img width="403" alt="Screen Shot 2020-06-12 at 10 09 22 PM" src="https://user-images.githubusercontent.com/190692/84557462-69cb8080-acf9-11ea-8550-6dc166fc307d.png">

**Comment by kanthiganesh** [comment]
I am getting this issue when i try the cloud front signed url in model-viewer I am using the latest https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js file. Below is the model url that I am trying. 
https://d1erdcan2pozd1.cloudfront.net/armodels/asdf/1614847425128_meter.glb?Expires=1615447785&Key-Pair-Id=KT624S8U7SF18&Signature=bPjN0W58GI-aaGoSyExRVFno-v5ZFl0nqigo~EQIoIkqq41tx8hqRS7ALXRSauRHpASvHSCTQIGet88xBHjy-u9msuTkQRjKgWY8gdcqTMIabwqWvC2nnNkiKvkiBZtexpllSrvtzztinIXHLVTUqf51m84Jz0xdMfnpRKXbXAjDkic53xxxZerRfNkHhuAuT5kaVvKxQ9F28amx2FJGCzcO-h296uQJIaYFXPeI27Rkz7VR5vM1oYXC9-VBTL3bTPoNU3kxwgIIOHig39~1fgneacFv6HDmY34urCMvuzlrKq46cROkQ6YU458qVzx40PgWJTIR-470uas51KPBqw__

**Comment by elalish** [comment]
Can you be very specific what you mean by "I am getting this issue"? Did you read the rest of the thread above?

**Comment by kanthiganesh** [comment]
The issue is I am using cloud front pre signed url for glb model in model-viewer tag. It was loading perfectly in model-viewer tag. When I am viewing AR in scene-viewer mode the model is not loading.

**Comment by elalish** [comment]
@tpsiaki Is there something I can do on our intent to improve this? Or is this just a security block between the browser and app?

**Comment by kanthiganesh** [comment]
[$openSceneViewer]() {
            // This is necessary because the original URL might have query
            // parameters. Since we're appending the whole URL as query parameter,
            // ? needs to be turned into & to not lose any of them.
            const gltfSrc = this.src;
            const location = self.location.toString();
            const locationUrl = new URL(location);
            const modelUrl = new URL(gltfSrc, location);
            locationUrl.hash = noArViewerSigil;
            // modelUrl can contain title/link/sound etc.
            // These are already URL-encoded, so we shouldn't do that again here.
            let intentParams = `?file=${encodeURIComponent(modelUrl)}&mode=ar_only`;  

   When I did above changes in older version of model-viewer.js file, it is working.

**Comment by elalish** [comment]
Thanks, would you mind opening a PR with your change? I'll be happy to review, but these comments are not the best code diffing view 😁.

**Comment by greinerjb** [comment]
Here is how you can solve the cloudfront issue.
Instead of pointing to the cloudfront link in src (<model-viewer src="'cloudfront'"), 
point to a handler file (<model-viewer src="handler"). Then use this handler file to serve the cloudfront content. This can avoids issues with parameters.
