### ISSUE TITLE
Specialized camera configuration associated with a hotspot

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1100]
It should be possible to specify a specialized camera configuration to be associated with a given hotspot. Doing so (perhaps in tandem with some additional global flag) could enable us to automatically interpolate the camera towards the specialized configuration as hotspots become "activated."

This capability supports use cases such as product / object tours, where the author would like the user to focus on specific details of a model as hotspots become activated.

**Comment by jan-erik-a** [comment]
this would be an awesome feature!

**Comment by elalish** [comment]
I don't plan to add this to our API anytime soon, but you can achieve this already with a little bit of JavaScript. Just put a click listener on your hotspot and set the `cameraOrbit` property of model-viewer as desired.
