### ISSUE TITLE
Ability to specify a floor-plane image or model

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1102]
For editor cases, it can be extremely desirable to display a grid on the "floor plane" to get a relative sense of where the model is positioned.

For product staging cases, it is often desirable to display a "pedestal", "table" or similar surface when presenting the model.

We should support the ability to declaratively configure a floor plane texture or auxiliary model.

**Comment by elalish** [comment]
I've been thinking this could also take the form of a floor height that the skybox is projected onto. If this was matched to the height of the camera ball and the ground was reasonably flat, I believe it could look pretty convincing.

**Comment by phreak** [comment]
I also 2nd that. Adding a floor image would significantly improve visual representation possibilities. Additional fall off blur could simulate the sort of a depth of field.
