### ISSUE TITLE
Support for configuring KHR_lights_punctual

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1104]
https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_lights_punctual

We should support configuration KHR_lights_punctual via 3DOM so that folks can add, remove and/or manipulate punctual lights in a scene.

Corresponding support for this extension would also need to be added to `<model-viewer>`.

**Comment by elalish** [comment]
I actually don't want to do this. It opens up a lot of complexity regarding shadows and it's also less efficient than baking all lights into the IBL. I would prefer to make a light baking feature in our editor.
