### ISSUE TITLE
Specify timing function and duration of transition between hotspot camera states

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1106]
As a follow-on to https://github.com/google/model-viewer/issues/1100, it should be possible for users to specify a timing function and a duration for transitioning between configured camera states on hotspots.

For timing functions, we should initially limit ourselves to what is already supported in CSS: https://developer.mozilla.org/en-US/docs/Web/CSS/animation-timing-function

**Comment by elalish** [comment]
Dupe, and we'll be taking a simpler approach since we don't use CSS-style timing functions anyway.
