### ISSUE TITLE
Generate USDZ from a source model

### ISSUE THREAD

**Issue by ronpadz** [google/model-viewer#1108]
Many using <model-viewer> as a means to generate AR experiences require a USDZ version of the model for AR Quick Look compatibility on iOS devices, but the means to generate USDZ models requires the use of a Mac and/or the installation and configuration of a relatively complex stack of enabling technologies (i.e. [usd_from_gltf](https://github.com/google/usd_from_gltf)) and the use of command line interfaces.

In an editor workflow, users should be able to benefit from automatic, lightly configurable generation of USDZ assets from glTF in an intuitive interface.

The editor should enable users to preview the result of the conversion.

**Comment by MaartenBreeedveld** [comment]
USDZ is kind of Apples fault, 
But a suggestion
But if you want to freebee, 
[Use docker and heroku](https://medium.com/travis-on-docker/how-to-run-dockerized-apps-on-heroku-and-its-pretty-great-76e07e610e22)
spin up this container [container](https://github.com/Giorat/docker-gltf-to-udsz)

**Comment by smalls** [comment]
Absolutely agreed, this is a long standing feature request. Some conversations have already happened in #278. Does that cover your requirements, and should we continue the conversation there?

**Comment by ronpadz** [comment]
Agreed that #278 is representative of this issue. I will close this.
