### ISSUE TITLE
.currentTime is ignored when paused

### ISSUE THREAD

**Issue by soraryu** [google/model-viewer#1113]
### Description

We have a couple of usecases where we
- are playing back synced audio with model-viewer animation
- are pausing model-viewer animations at specific points in time
- allow jumping to other points in time, both in play and pause mode

While it's possible to achieve I think I found a bug -
currentTime is ignored when model-viewer is currently paused. This means that to get the behaviour, we currently have to keep model-viewer playing all the time and run a requestAnimationFrame to force it to a specific time. This doesn't feel right and makes this more complicated than it should be.

Note that the Live Demo has some other interesting things we found for audio support - so this is related to
#425, https://github.com/google/model-viewer/issues/483#issuecomment-579449685. 

Also note that autoplay on mobile is handled by browser policy (if you have often pressed play on a website it allows autoplay, if not then not) and is handled in this example by showing a screen overlay.

I started a PR for this but am unsure about some details, see here: #1114 

#### Live Demo
https://glitch.com/edit/#!/chatter-sleet-restaurant

As-is, this shows the broken behaviour - when you pause the audio, you can neither scrub the timeline nor press the buttons to jump to specific seconds, despite modelViewer currentTime being updated (and logged in the console).

If you comment in lines 103..114, this "fixes" it by forcing the currentTime.

**Comment by elalish** [comment]
Thanks for starting a PR!

**Comment by cdata** [comment]
Awesome, thanks for reporting @soraryu we should definitely fix this.
