### ISSUE TITLE
Zooming: with certain settings, initially can't zoom out until you zoom in

### ISSUE THREAD

**Issue by stevesan** [google/model-viewer#1115]
### Description

Using these settings:
<model-viewer
  style="width: 100%; height: 100%;"
  src="winter_time/scene.gltf"
  camera-controls
  auto-rotate
  camera-target='0m 100m -40m'

  min-camera-orbit='auto auto 50m'
  max-camera-orbit='auto auto 1000m'
  camera-orbit='5.14rad 1.03rad 50m'

  field-of-view='60deg'
  min-field-of-view='auto'
  max-field-of-view='auto'
>

..I am initially unable to zoom out, ie. mouse wheeling out does nothing. But once I zoom in, THEN I can zoom out all the way (to 1000m).

### Browser Affected

- [x ] Chrome 80
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x ] Windows 10

### Versions
- model-viewer: at HEAD

**Comment by cdata** [comment]
Thanks for reporting @stevesan , looks like @elalish is on it 👍
