### ISSUE TITLE
Zooming: disallowing any FOV change makes zooming impossible

### ISSUE THREAD

**Issue by stevesan** [google/model-viewer#1116]
### Description

Using these settings:
<model-viewer
  style="width: 100%; height: 100%;"
  src="winter_time/scene.gltf"
  camera-controls
  auto-rotate
  camera-target='0m 100m -40m'

  min-camera-orbit='auto auto 50m'
  max-camera-orbit='auto auto 1000m'
  camera-orbit='5.14rad 1.03rad 50m'

  field-of-view='60deg'
  min-field-of-view='60deg'
  max-field-of-view='60deg'
>

..I am unable to zoom at all. Note that the model, which I can't provide publicly, is quite large (~radius of 2000m/units)

### Browser Affected

- [x ] Chrome 80
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x ] Windows 10

### Versions
- model-viewer: at HEAD

**Comment by cdata** [comment]
Thanks for reporting, @stevesan ! I'm interested to hear what you would expect to happen in this case.

@elalish curious to hear your opinion on this one as well.
