### ISSUE TITLE
Failure to load on Vue

### ISSUE THREAD

**Issue by imers** [google/model-viewer#1117]
### Description

Does this library work with Vue? It could show the top loading bar but not any model.
![image](https://user-images.githubusercontent.com/14811704/77813415-cd40fd00-707e-11ea-8037-a90966434585.png)

### Browser Affected

- [ 80.0.3987.149] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ 10] Windows

### Versions

- model-viewer: ^0.9.0

**Comment by leonzuendel** [comment]
did you find a solution for that?

**Comment by CarlVitasa** [comment]
Was there a solution for this?

**Comment by mcndt** [comment]
Would like to bump this, I am having the same issue. It doesn't cause any errors in the console but it doesn't load either. Tried with .glb files

**Comment by elalish** [comment]
Does #2122 help? Generally you'll find better help searching the discussions than the closed issues.

**Comment by mcndt** [comment]
> Does #2122 help? Generally you'll find better help searching the discussions than the closed issues.

The issue in my case was that my model wasn’t in the public folder of my Vue project. There’s no console warnings or anything about this failure though. Was there another way I could have captured this error? I ended  up finding this cause by trial and error

**Comment by elalish** [comment]
I'm guessing this is a Vue-specific thing? I get a 404 console error when I try to load a GLB that doesn't exist: https://modelviewer.dev/examples/loading/index.html#noModel
