### ISSUE TITLE
Improve Poster generation and display

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1119]
### Description

https://modelviewer.dev/examples/tester.html is great for quickly generating poster images.
It would be even better if it 

1. supported camera-target
2. supported freezing animations to first frame (currently dropping an animated model will autoplay the animation, which makes poster generation harder than it should be)
3. supported selecting an animation to show & freeze
4. allowed setting the camera-orbit (e.g. make the camera-orbit output also writeable)

Some of these issues have a workaround (directly manipulating the model-viewer HTML in Debug Tools) but would be great to have this as features.

Additionally, when a poster image is displayed, there seems to be a short moment of double viewing where both the poster and the model are shown.

This is especially an issue with animated models where the animation starts immediately:

![20200330-160844](https://user-images.githubusercontent.com/2693840/77922042-d0b3ce80-72a0-11ea-96fa-1724bf403022.gif)
(this shows three issues - offset camera-center, animation overlap, and first frame of animation being different than without animation)

#### Live Demo
Try to generate a poster for any model with either
- camera-center
- animation

**Comment by elalish** [comment]
@soraryu Thanks, I was wondering if these types of controls would be useful to people so your feedback is very helpful.

**Comment by elalish** [comment]
I believe this is all working now in the editor.
