### ISSUE TITLE
Hotspot button is obscured by footer on interactive demo page

### ISSUE THREAD

**Issue by elbobo** [google/model-viewer#1120]
Hi,

The add/remove hotspot button feature is great on this page

https://modelviewer.dev/examples/tester.html

however they are obscured by the footer text (on chrome) it seems the elements overlap. (see attached image)

<img width="1189" alt="Screenshot 2020-03-31 at 11 35 55" src="https://user-images.githubusercontent.com/5732982/78017264-e928f500-7343-11ea-8e76-149fd489c8b0.png">

**Comment by cdata** [comment]
@elbobo thanks for reporting! I can't reproduce this issue in Chrome. Can you share more details about the screen dimensions, hardware, Chrome version etc?
