### ISSUE TITLE
parseExpressions doesn't handle exponents

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#1122]
I found a case where the hotspot is not hidden at the proper orientation (this hotpot is on the front bevel, so shouldn't be visible):
<img width="583" alt="Screen Shot 2020-04-01 at 7 12 44 AM" src="https://user-images.githubusercontent.com/1649964/78147473-69089b00-73e8-11ea-9a90-f4b84dc9b217.png">
It turns out the problem is that the normal = '-5.5e-17m 0.59m 0.8m', and parse expressions turns it into [-5.5, -17, 0.59]. @cdata I would normally just fix it, but I'm not very familiar with the regular expressions you used here; I'm hoping this is a quick one for you.

**Comment by cdata** [comment]
Good catch, this is a deficiency in our parser that slipped by. We should be able to fix it fairly easily.

**Comment by cdata** [comment]
Definition of `<number>` type in CSS: https://drafts.csswg.org/css-values-3/#number-value
And grammar: https://www.w3.org/TR/css-syntax/#number-token-diagram
