### ISSUE TITLE
readme has broken Documentation link

### ISSUE THREAD

**Issue by giles7777** [google/model-viewer#1123]
### Description

Clicking on the "Documentation" link of the readme gives a 404.  It's linked to this page: https://googlewebcomponents.github.io/model-viewer/index.html

#### Live Demo
https://github.com/google/model-viewer/tree/master/packages/model-viewer

### Browser Affected

- [X ] Chrome
- [X ] Edge
- [X ] Firefox
- [X ] Helios
- [X ] IE
- [X ] Safari

### OS

- [X ] Android
- [X] iOS
- [X ] Linux
- [X ] MacOS
- [X ] Windows

### Versions
all

**Comment by cdata** [comment]
Thanks for reporting this @giles7777 ! We'll get it fixed.
