### ISSUE TITLE
How to use model-viewer so that Google displays "View in 3D" on search results?

### ISSUE THREAD

**Issue by aviggiano** [google/model-viewer#1131]
### Description

I've recently watched [a talk](https://www.youtube.com/watch?v=lsScEabNutA) in which @cdata talks about search engines displaying 3D models automatically, and saw that for some websites this is already happening. Do I need to configure anything else so that Google does the same for my websites? 

#### Live Demo

Search for "Muscle flex visible body" --> "View in 3D" button is displayed on search results from [the website](https://www.visiblebody.com/blog/3d-muscular-system-five-common-muscle-actions)
![Image from iOS (2)](https://user-images.githubusercontent.com/3029017/78574247-1e2fbe80-7800-11ea-9923-8d91d8d6cd92.png)

Search for "Lumini ufo t" --> "View in 3D" button is not displayed, even though the `model-viewer` is present on [the website](https://lojavirtual.lumini.com.br/produtos/ufo-t)

![IMG_9671](https://user-images.githubusercontent.com/3029017/78574488-7070df80-7800-11ea-8007-571b9aeb4026.PNG)

**Comment by lanxinger** [comment]
@aviggiano: don't think Google has released any documentation on that. But I think once they open this up for developers you will be able to find that info here:
https://developers.google.com/search/docs/guides/search-gallery

**Comment by aviggiano** [comment]
Thanks @lanxinger, I didn't know about that link. I'll close this issue then.

**Comment by lanxinger** [comment]
@aviggiano I am just guessing here. Maybe someone from the Google team here can comment more if that really is the case.

**Comment by lanxinger** [comment]
@aviggiano actually just found this:
https://developers.google.com/search/docs/guides/3d-ar

You can register for early access.

**Comment by Sbstnlhmchr** [comment]
@lanxinger @aviggiano i founds this: 
https://developers.google.com/ar/develop/java/scene-viewer#3d-or-ar

but I don't know how to use it

**Comment by lanxinger** [comment]
@Sbstnlhmchr yes, this is android's new default AR model viewer. I have used it and it works well. but model viewer is much more flexible.
