### ISSUE TITLE
Specifying animation-name without autoplay enabled throws warning in console

### ISSUE THREAD

**Issue by efreeman15** [google/model-viewer#1132]
### Description

Specifying animation-name without autoplay enabled throws warning` Cannot play animation (model does not have any animations)` when the model has animations. Upon `autoplay=true` or `play()` the animation does correctly play.

#### Live Demo
[https://glitch.com/edit/#!/clammy-sassy-dreadnought?path=index.html:36:33](https://glitch.com/edit/#!/clammy-sassy-dreadnought?path=index.html:36:33)

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [x] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.9.0

**Comment by cdata** [comment]
Thanks for reporting this @efreeman15 ! Sounds like a bug to me 👍
