### ISSUE TITLE
Implementation to angular.

### ISSUE THREAD

**Issue by ArnasPenkaitis** [google/model-viewer#1136]
Good day colleagues,

I'm trying to implement model-viewer to my bachelor degree project and I'm confused how to do that.

Maybe there is anyone to help and guide me through implementation steps to Angular 8-9? 

I did Npm install and after that i copied this code to my HTML files.

model-viewer src="https://cdn.glitch.com/36cb8393-65c6-408d-a538-055ada20431b/Astronaut.glb?1542147958948"
                  alt="A 3D model of an astronaut"
                  shadow-intensity="1"
                  camera-controls
                  interaction-prompt="auto"
                  auto-rotate ar magic-leap>
    </model-viewer

I'm getting no errors no warnings, but somehow the 3D model doesn't appear.

Thank you for you time. :)

**Comment by cdata** [comment]
@ArnasPenkaitis are you importing the module? `import '@google/model-viewer'`

**Comment by mehmetranas** [comment]
Did you solve problem?

**Comment by AhrenFullStop** [comment]
I am importing the module in the component using the component, but still getting error: "error NG8001: 'model-viewer' is not a known element:"

Where should I import this? is there a 'declare' that I can do to shut this error up because it actually runs.

**Comment by anders8** [comment]
It's "not a known element" because it has a dash in the element, which Angular generally doesn't like. in app.module, you'll need to add two things.
import { CUSTOM_ELEMENTS_SCHEMA }   from '@angular/core'; 

and to to @ngModule:
schemas: [CUSTOM_ELEMENTS_SCHEMA]
