### ISSUE TITLE
Make &mode=ar_preferred default for SceneViewer

### ISSUE THREAD

**Issue by soraryu** [google/model-viewer#1151]
### Description

Commented about this [here](https://github.com/google/model-viewer/issues/1097#issuecomment-604318718) but I think it got lost.

Coming from model-viewer, users have seen a 3D model on a webpage that they can interact with. Pressing the AR button, currently they see ... a 3D model on a different webpage that they can interact with. They have to press AR again to actually get what they expected!

The _mode=ar_preferred_ flag can change that and I think it should be the default to avoid user confusion (we had a lot of confused clients and users until we found that flag).
This would also match QuickLook behaviour which has AR by default and allows people to go back to non-AR if they want.

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by ronpadz** [comment]
I'm going to pile on here and say that the current default behavior has
often needed to be explained to users as it is not intuitive. I was happy
to find the ar_preferred flag too, but the product would be greatly
improved with the more intuitive default UX as described by @soraryu

**Comment by cdata** [comment]
I'm happy to share that we are imminently releasing `v0.10.0` using the revised Scene Viewer intent scheme. However, we opted for `mode=ar_only`. @soraryu @ronpadz can you comment on your preference for `ar_preferred`? It seems to me like we would not want them to be able to switch to a 3D view that isn't the originating web page..

**Comment by soraryu** [comment]
I think that's fine! As long as the default isn't the difficult-to-explain 3D view anymore that's good. Great that you changed this.

(so far we're using `ar_preferred` to match QuickLook behaviour - from a UX perspective I also think the 3D mode isn't necessary there)

**Comment by cdata** [comment]
@soraryu thank you for confirming that. We will probably keep it set to `ar_only` barring strong evidence that `ar_preferred` is better.

FWIW we do still have https://github.com/google/model-viewer/issues/1085 on the books, which would let you change the mode to `ar_preferred` if you really wanted that.
