### ISSUE TITLE
Open 'old' version of Scene Viewer

### ISSUE THREAD

**Issue by nicolocarpignoli** [google/model-viewer#1156]
### Description

Using a basic model-viewer example, on my Huawei P20 now crashes after some interactions with the model, in AR mode.
This is weird, because nothing is wrong with the scene (works great on iPhones, as I provided also usdz) and most of all, I tried this code some months ago, and it works great.

Now, the difference (my guess) may be on Scene Viewer, not model viewer.
I can tell this because the 'AR' scene is different (before it was not showing the camera button, to take pictures). Scene Viewer it's clearly changed during this last months.

So my question is: is it possible to trigger a specific version (in this case, not the last one) of Scene Viewer? Can I do that in some way?

#### Live Demo

No particular code is needed, apart from my example, I tried also basic examples from https://modelviewer.dev/ adding 'ar' propertyu without changing anything, and it crashes. It worked some months ago with the other Scene Viewer version.

EDIT: it crashes also on Scene Viewer triggered from Google Search, when you search animals like 'cat' (on Android). So it's a Scene Viewer bug I guess, but It was not on earlier versions.

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.10.0

**Comment by cdata** [comment]
Scene Viewer has an old intent scheme that will eventually be deprecated. In v0.10.0, we updated to the newest intent scheme, which I believe is what leads to the new Scene Viewer UI you are describing. We have an outstanding issue https://github.com/google/model-viewer/issues/1085 to allow folks to customize the intent, which theoretically would allow you to revert to the old intent scheme. However, this is not recommended and I doubt that the old scheme will be supported for very much longer.

cc @tpsiaki for the Scene Viewer crashing feedback

**Comment by tpsiaki** [comment]
@nicolocarpignoli Would you check which version of the Google app you have installed so we can investigate?  Settings > Apps & Notiffications > See all apps > Google > Advanced - version number is at the bottom of the screen.

**Comment by nicolocarpignoli** [comment]
> @nicolocarpignoli Would you check which version of the Google app you have installed so we can investigate? Settings > Apps & Notiffications > See all apps > Google > Advanced - version number is at the bottom of the screen.

Google app is version 11.4.9.21.arm64
Google Play Services For AR is version 1.16.200302046 (don't know if useful)

**Comment by nicolocarpignoli** [comment]
So basically it's related on the Google app installed on the device? Is scene viewer part of the Google app?

**Comment by tpsiaki** [comment]
Yes Scene Viewer is a feature of the Google app.  It uses Google Play Services for AR to provide AR mode though, so both of the installations are relevant (and you need both installed in order for launch-to-Scene Viewer to trigger to AR from <model-viewer>)

**Comment by nicolocarpignoli** [comment]
@cdata I found out that even with 0.9.0 version and 0.8.0 version of model viewer I got the same Scene Viewer (the newest).

I will try to trigger the 'old' specific intent manually and see if changes. Unfortunately, If I remember correctly, that may fix the 'crash' but I will lost the camera button feature
