### ISSUE TITLE
Load event does not fire event until model displayed

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#116]
See `loading.html` example when #113 lands, "Preload with poster and show model on interaction": I'd expect the load event to be fired when it loads, before user interaction, yet not hide the poster until interaction, rather than firing the event once interacted with

```html
<model-viewer id="interaction" preload poster="assets/poster.png" src="assets/reflective-sphere.gltf"></model-viewer>
<script>
    $('#interaction').addEventListener('load', e => {
        e.target.style.border = '2px solid red';
    }, { once: true });
</script>
```

**Comment by cdata** [comment]
This is actually working as designed. There is a distinction between `load` and `preload`. The circumstances that invoke `load` do not occur until the model is about to be presented, but the `preload` event does fire even while the poster is visible.

We can change this with a suitable refactor of `Model` and `ModelScene`, but for now they are tightly coupled to loading (which is kind of a smell anyway and is worth revisiting).

**Comment by elalish** [comment]
Working as intended.
