### ISSUE TITLE
Better demos for creating/using posters

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1163]
We should include better demos to help folks understand posters, how to configure them and create their own. Specifically, we should cover cases like how to use the tester, how to generate their own posters and how transparency / seamless transitions work.

Please refer to discussion here for context: https://spectrum.chat/model-viewer/general/is-modelviewer-dev-always-using-a-newer-version-or-always-using-the-same-version-as-dist~b2785734-3a09-44a0-a0c1-0fb0ad892eaa?m=MTU4NzQwOTQ1MDcwMA==

**Comment by elalish** [comment]
I think we've done pretty well here at this point, between the new examples and the editor.
