### ISSUE TITLE
models served without SSL are not shown in AR mode

### ISSUE THREAD

**Issue by gromgull** [google/model-viewer#1170]
### Description

Serving the glb file without SSL will only work with fallback ar mode. (i.e. fullscreen, but not AR)

Moving the same file to a host with SSL / https will work fine in webxr. 

Maybe at least document this somewhere? 

### Browser Affected
- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: latest from unpkg

**Comment by elalish** [comment]
Good call on documentation; this is indeed a requirement of the WebXR API.
