### ISSUE TITLE
activateAR in chrome not working

### ISSUE THREAD

**Issue by vargavd** [google/model-viewer#1176]
In the "Load" event hander, I am trying to call activateAR on mobile. It is working in Firefox and in Safari, but not in Chrome.
Maybe it is not a bug, it is the intended working on Chrome, due to the limitation to the browser to not imitate user interaction. Can you clarify on this?

[Example](https://swisstomato.ch/en/delonghi-mv/)

Code:
```
<script type="module" src="..model-viewer.js"></script>
 <model-viewer id="model-viewer" src="..Delonghi-machine.glb" ios-src="..Delonghi-machine.usdz" alt="Machine" auto-rotate camera-controls ar magic-leap>
        <button id="mv-ar-button" slot="ar-button" style="...">View in your space</button>
 /model-viewer>

...
<script>
var modelViewer = document.getElementById('model-viewer');
modelViewer.addEventListener('load', function () { 
    modelViewer.activateAR(); 
});
</script>
```

**Comment by elalish** [comment]
Does this [comment](https://github.com/google/model-viewer/blob/3ef0948d4217a660627e62bb03c7fe404d0a57ed/packages/model-viewer/src/features/ar.ts#L205) help? Does it work better if you put `webxr` ahead of `scene-viewer` in `ar-modes`?
