### ISSUE TITLE
AR not working supported devices

### ISSUE THREAD

**Issue by Arumugamhns** [google/model-viewer#1177]
Sometime Activate Ar button is hide or not working in supported device.

if i click Activate button it displayed in full screen 

Link
https://audiindia.in/for_webar/index.html

**Comment by elalish** [comment]
Can you give us specific devices / browsers where it's not working? If you try a different order of `ar-modes` does that give different results?

**Comment by ybinstock** [comment]
I'm getting the same issue. See the attachment for the error. 
<img width="1086" alt="Screenshot 2020-05-11 at 10 52 01" src="https://user-images.githubusercontent.com/8645066/81542778-7b75dd00-9375-11ea-8c5a-88d5af2dc471.png">

Here is my code https://github.com/ybinstock/dailySculptureAR/blob/gh-pages/index.html

**Comment by elalish** [comment]
I think this was fixed.
