### ISSUE TITLE
Add note in README that the size should be set with CSS `width` and `height` properties

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#118]

**Comment by eLBati** [comment]
Hello, I can't find references to width and height in README anymore.

My problem is that I can't display a `model-viewer` with dimensions different from 300px x 150px. Is it possible to change them?

Thanks!

**Comment by eLBati** [comment]
It seems I just have to add CSS `width` and `height` to `model-viewer`...

**Comment by elalish** [comment]
@eLBati Correct; as a custom element, it inherits most of the generic CSS attributes.
