### ISSUE TITLE
New PR came in as third-party and ran a minimal number of tests

### ISSUE THREAD

**Issue by smalls** [google/model-viewer#1181]
See https://github.com/google/model-viewer/pull/1180/checks for an example. More context available at https://github.com/google/model-viewer/pull/1180#issuecomment-621250809.

**Comment by elalish** [comment]
@smalls This is desired behavior for third-party contributors; the issue is just that you shouldn't be a third-party.

**Comment by smalls** [comment]
Further investigation, this is expected - I tend to work out of a forked repo, rather than a branch in this repo, and we've currently chosen to run a smaller number of tests for forked repos.
