### ISSUE TITLE
Loading bar inconsistencies

### ISSUE THREAD

**Issue by gjcope** [google/model-viewer#1182]
### Description

I'm seeing different behavior with the loading bar when identical content is loaded from different sources. Not sure if this is a <model-viewer> issue or not but thought I would share.

When loading from a local source (or CDN in the Glitch demo) it acts as expected and completes shortly before the model displays. When loading from our 3d API the bar quickly fills and there is an extended wait until something shows.

#### Live Demo

https://fierce-expensive-source.glitch.me/

### Browser Affected

- [x ] Chrome
- [x ] Firefox

### OS

- [x ] Android
- [ x] Windows

### Versions

- model-viewer: v0.10.0

**Comment by elalish** [comment]
Interesting; can you tell me more about your 3D API? And have you tried both glTF and glb models?

**Comment by gjcope** [comment]
This is the Smithsonian 3D API. Right now we are just serving the glbs. It's not a roadblock for us, but just thought it was interesting that there was inconsistent behavior. Thanks for taking a look!

-Jamie

**Comment by elalish** [comment]
@cdata Since you wrote the progress tracking code, do you have any thoughts on why the behavior is not consistent?

**Comment by elalish** [comment]
I'm moving this to a discussion as I'm pretty sure this is a server thing rather than a model-viewer issue. @gjcope Are you still seeing this?
