### ISSUE TITLE
Customize Custom Action Button in AR Quick Look mode

### ISSUE THREAD

**Issue by FilipK999** [google/model-viewer#1183]
### Description
Is there currently any way to customize the custom action button/apple pay button in AR Quick look mode?

Specifically, make the browser redirect to a url when the button is clicked?
In [Apple docs] (https://developer.apple.com/documentation/arkit/adding_an_apple_pay_button_or_a_custom_action_in_ar_quick_look)
they say you're supposed to add an event listener to the anchor tag that gets created. Tried that (using `document.querySelector("a[rel='ar']")` since the the id isn't created in openIOSARQuickLook.)

But this doesn't seem to work at all.

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: 0.10.0
- three.js: r115

**Comment by elalish** [comment]
We have another thread going on this topic [here](https://spectrum.chat/model-viewer/general/google-apple-pay-buttons-in-model-viewer~9fc1aeb6-f0d1-4e80-9faf-216c0fed036a). The short answer is not currently, but we're working on making this awesome for webXR. Not sure what to do for Quick Look yet.
