### ISSUE TITLE
"Cannot read property 'expandTo' of undefined"

### ISSUE THREAD

**Issue by karanganesan** [google/model-viewer#1186]
### Description

Was trying to add model-viewer to a Create React App application, and ended up in this error.

#### Live Demo
https://codesandbox.io/s/model-viewer-demo-8z4x4?file=/src/App.js
https://8z4x4.csb.app/

### Browser Affected
- [x] Chrome
- [x] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.10.0
- three.js: r115

![Screenshot 2020-05-04 at 8 25 27 PM](https://user-images.githubusercontent.com/6049925/80980080-d70c0c00-8e45-11ea-9672-2ba06dcc15d3.png)
![Screenshot 2020-05-04 at 8 25 31 PM](https://user-images.githubusercontent.com/6049925/80980092-dbd0c000-8e45-11ea-9dae-2225d51608c1.png)
<img width="1392" alt="Screenshot 2020-05-04 at 8 27 38 PM" src="https://user-images.githubusercontent.com/6049925/80980095-dd01ed00-8e45-11ea-86ff-dbe909871ab4.png">

**Comment by karanganesan** [comment]
First of all doing 

```js
import "@google/model-viewer";
```

is this correct to add a web component inside react?

**Comment by elalish** [comment]
We don't know much about React around here, but I'd recommend looking at the discussion in #690 for hints.
