### ISSUE TITLE
AR support on Firefox and Chrome for iOS

### ISSUE THREAD

**Issue by zivschneider** [google/model-viewer#1189]
### Description

AR button in Firefox on iOS prompts a download instead of AR. Works on Safari. on Chrome I am not seeing the AR button at all*. 

*I looked for the Chrome webXR flags but they're not on the list.

#### Live Demo

https://sourdough-ar.glitch.me/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v10
- three.js: rXX

**Comment by otri** [comment]
+1, Chrome and Firefox browsers on iOS is very commonly used.

Detection method is the same:
```
    // Check if AR quicklook is available on iOS
    var isARAvailable = function() {
      const a = document.createElement("a");
      return a.relList.supports("ar");
    }
```

**Comment by elalish** [comment]
If the AR button is showing up and not launching AR, then it's a bug on iOS Firefox/Chrome, as we are checking if it supports AR.
