### ISSUE TITLE
ar-scale="fixed" not working as expected

### ISSUE THREAD

**Issue by DamianoBuscemi** [google/model-viewer#1194]
Hello I am not able to block the scaling of the object while dispayed in Quick Look, the code is below:

https://areatest.popcornmedia.it/arstorewebsite/espositori.html
model-viewer@0.3.1

<model-viewer
                alt="A 3D model of mine."
                src="3d/Expo_Popcorn/Expo_Popcorn.gltf"
                ios-src="3d/Expo_Popcorn.usdz"
                magic-leap ar
                auto-rotate
                camera-controls
                background-color="#EEEEEE"
                shadow-intensity="1"
                ar-scale="fixed"
                poster="img/espositore_picture.png"
                camera-orbit="-20deg 75deg 2m">
</model-viewer>

**Comment by elalish** [comment]
Last I checked, Quick Look doesn't have a way to disable scaling, so this is only respected in WebXR and SceneViewer. We should probably mention that in our docs...

You're not really on version 0.3.1, right? That would be very outdated.

**Comment by DamianoBuscemi** [comment]
Thank you elalish!
You are right I updated the version to the last one.
I was able to force not scaling adding this at the end of the File https://developer.apple.com/arkit/gallery/toy_biplane.usdz#allowsContentScaling=0

As mentioned here https://cwervo.com/writing/quicklook-web/

Maybe It could be included in the next release?

Damiano

**Comment by elalish** [comment]
@DamianoBuscemi Thank you for the tip! Sure, I'll add this to the milestone.
