### ISSUE TITLE
Metalness strange behaviour in model viewer using Oppo Realme Pro 5

### ISSUE THREAD

**Issue by areavisuale** [google/model-viewer#1202]
### Description

I noticed that the same 3d model appear very different inside model viewer if I use the device OPPO Realme Pro 5. In particular the problem is in the metalness value that is 0 and seems to be overwritten and the model appear completely metallic. This happens only in model viewer, when I go in AR mode the model appears correctly. I tried to see the model in the PC browser and in another Android device, always using chrome as browser, and the result is always correct. I noticed also that if I remove the normal map from the model the metalness returns correct also in the OPPO device.

#### Live Demo

https://www.areavisuale.it/ar/webxr2.html

the model is: https://www.areavisuale.it/ar/assets/giuditta6.glb

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.10.0
- three.js: rXX

**Comment by elalish** [comment]
Thanks for the report! This has the smell of a driver bug in that phone. There's a chance we can find a workaround for it in three.js (there are plenty of others there), but I don't have a phone to repro it on. Can you repro it [here](https://gltf-viewer.donmccurdy.com/)? If so, you can file a bug on three.js and it's more likely someone there might have the same phone.

**Comment by areavisuale** [comment]
I verified that the problem appear also in that viewer. I just written in the three.js forum

**Comment by elalish** [comment]
I believe this has been fixed.
