### ISSUE TITLE
Rescaling .glb files

### ISSUE THREAD

**Issue by GabrielArakaki** [google/model-viewer#1203]
### Description

Hi! I have a few thousand 3d models exported as `glb`, but they were exported by a supplier with their scale units in centimeters, so in AR we have models 100x bigger than they should.

That said, is it possible to resolve this issue in one of the following:
1 - Set the AR scale fixed, but to a % value, such as 1%?
2 - Change the scale of the AR platform to centimeters instead of meters?

Or the only option available is to change the scale in the original glb files?

Best Regards,

**Comment by jithinagiboson** [comment]
i am also having the same doubt i thought **ar-scale** property can accept scale in percentage but did not work

**Comment by elalish** [comment]
Yes, we introduced a scale attribute for this: https://modelviewer.dev/docs/#entrydocs-scenegraph-attributes-scale
