### ISSUE TITLE
image target for AR Mode

### ISSUE THREAD

**Issue by Arumugamhns** [google/model-viewer#1219]
I have one business card. 
i need to show the model in AR mode by place the camera view on that business
is it possibile in model-viewer

**Comment by elalish** [comment]
Not currently. I'm not aware of this being supported in either SceneViewer or QuickLook, and I don't believe there's a webXR API for image tracking yet either, but I think there has been some discussion of it. @klausw if you have anything to add here.

**Comment by elalish** [comment]
Closing as a duplicate of #1516.
