### ISSUE TITLE
Please add an option to allow the model to render and be visible before model-viewer is in the viewport

### ISSUE THREAD

**Issue by mqg734** [google/model-viewer#1220]
There are ads use-cases where the ad slot starts below-the-fold. The entire ad needs to already be rendered off-screen before it comes into view. Currently, you can load the model offscreen, but there is still a delay when the model is rendered as the model first enters the viewport.

Live Demo at:
The model-viewer is at the bottom of the page. When you scroll down to the bottom (3000px), you will see the model-viewer's progress bar advance and the model come into view. If you need to see the issue again, please refresh the browser and repeat.

https://glitch.com/~peppermint-lime-hortensia

### Browser Affected
I only checked on Chrome, but this will happen with any browser that supports IntersectionObserver because model-viewer relies on IntersectionObserver to control visibility - https://github.com/google/model-viewer/blob/9d75b2564ed923e26bb34a36ec515f05c716d697/packages/model-viewer/src/model-viewer-base.ts#L252

- [X] Chrome Version 83.0.4103.61 (Official Build) (64-bit)
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
I only tested on MacOS.
- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.10.0
- three.js: r115

**Comment by elalish** [comment]
Thanks! Would a method like `forceRender()` work for you, which would force a single render when called?

**Comment by elalish** [comment]
@mqg734 I repro'ed the issue and this is definitely a bug. Sorry about not testing my first fix thoroughly enough.
