### ISSUE TITLE
Poster generation with toDataURL and toBlob fails in some browsers

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#1225]
### Description

Poster generation does not work on some browsers. Using Safari or Firefox on Mac, generating poster images using `toDataURL` or `toBlob` methods generates a blank / empty image rather than a screenshot of the ModelViewer content. Both methods _do_ work in Chrome on Mac though.

#### Live Demo

My demo
https://model-viewer-poster.glitch.me/

Your demo
https://modelviewer.dev/examples/tester.html

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [x] Firefox (v76.0.1)
- [ ] Helios
- [ ] IE
- [x] Safari (v13.1)

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS (v10.15.4)
- [ ] Windows

### Versions

- model-viewer: v0.10.0

**Comment by milesgreen** [comment]
Further to the above, this link shows an example of three.js rendering a screenshot to a file using toBlob:

https://threejsfundamentals.org/threejs/lessons/threejs-tips.html

This example does work on the above browsers in which ModelViewer fails to render a poster. 

I don't know if it's anything to do with the WebGL canvas drawing buffer getting automatically cleared, as mentioned in this article?

The use case I'm working on is to allow end users to rotate a model and export their own images.

**Comment by elalish** [comment]
Thank you, I just noticed this actually got broken even on Chrome when I disabled OffscreenCanvas (which then uses the same render path as Firefox/Safari): #1249. I need to look into what's happening in that render path.
