### ISSUE TITLE
Some unexpected hotspot visibility behavior?

### ISSUE THREAD

**Issue by stevesan** [google/model-viewer#1232]
### Description

Just added a hotspot to the robot's front, and it doesn't seem to be "visible" (ie. solidly opaque) as expected. See this screenshot: 
![image](https://user-images.githubusercontent.com/1388372/83157727-ee02ee80-a0d1-11ea-9a60-70227e60fd33.png)

And this:
![image](https://user-images.githubusercontent.com/1388372/83157780-fa874700-a0d1-11ea-81f0-35c150c9044d.png)

But sometimes when I move the camera around to the same positions, it does work:
![image](https://user-images.githubusercontent.com/1388372/83157837-0b37bd00-a0d2-11ea-9014-b10006821955.png)

#### Live Demo
Just using the live tester with the robot: https://modelviewer.dev/examples/tester.html

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions
- model-viewer: v0.10.0
- three.js: ?

**Comment by elalish** [comment]
I've reproed it, thanks. Hopefully this is specific to animated models, as hotspots don't really support animation yet anyway. I'll probably fix this as part of #1053.

**Comment by motinados** [comment]
it may not be only problem with animated model.

added a hotspot to lantern's front.
![lantern_a](https://user-images.githubusercontent.com/69296148/90864701-22820000-e3cc-11ea-9efe-f72174107b29.jpg)
and lotated it.
![lantern_b](https://user-images.githubusercontent.com/69296148/90864743-37f72a00-e3cc-11ea-9f29-212058f7ec01.jpg)

Shouldn't the z-normal be positive in this case?

**Comment by motinados** [comment]
The bottom hotspot of lantern works well.
![lantern_c](https://user-images.githubusercontent.com/69296148/90866359-bbb21600-e3ce-11ea-9d08-2f52fb61475e.jpg)

**Comment by elalish** [comment]
@motinados upon further inspection, you are exactly correct. I was not transforming the normals to the proper coordinate space. Should be fixed shortly, though animated models will have to wait.
