### ISSUE TITLE
How to use the camera from gtlf file.

### ISSUE THREAD

**Issue by rafeekwassef** [google/model-viewer#1238]
Hi,

I'm wondering is it possible to use the camera that has been set into the gltf file?

 "cameras": [
        {
            "name": "active",
            "perspective": {
                "aspectRatio": 1,
                "yfov": 0.1795163487444869,
                "zfar": 878.5548095703125,
                "znear": 810.1922607421875
            },
            "type": "perspective"

This is the code from gltf
I tried on https://threejs.org/editor/ and it is working and possible to select the camera from the top right corner.

So how to do it with the <model-viewer>?

Thanks,

**Comment by elalish** [comment]
@rafeekwassef We don't support this yet, but we've been considering it. Can you tell me about your use case? One thing that concerns me somewhat is that a gltf camera specifies an aspectRatio, but that is defined by the model-viewer element's dimensions. How would you go about rationalizing those?

**Comment by rafeekwassef** [comment]
Thanks for your replay, I guess that it should be achievable by something like PerspectiveCamera in the three.js 
PerspectiveCamera( fov : Number, aspect : Number, near : Number, far : Number )

Anyhow, I already got so close result by:
camera-orbit= "0deg 90deg 878.55m"
camera-target= "0m 58.457m 844.374m"

Here is a screenshot from https://threejs.org/editor/
<img width="275" alt="Screen Shot 2020-06-02 at 6 28 04 AM" src="https://user-images.githubusercontent.com/48543105/83479928-3e939680-a49a-11ea-88f2-54911ebc74cd.png">

And to fix the aspectRatio issue, I had to play around with the FOV
min-field-of-view= "1deg"
field-of-view= "8.5deg"

This is the most closer result for me till now.

**Comment by methot-ilya-3ds** [comment]
I'll bump this as I think this is an important feature.

For example, I would like to have an animation includes camera movement. In some cases I could see an html scroll bar progressing the animation, or just a ui scrubbing bar.

Without access to the perspective of the camera with the embedded animation data it would make it much more difficult to orchestrate camera movement. I could see someone setting individual locations for the camera to move to using scripting but this seems like a tedious workaround.

**Comment by elalish** [comment]
@methot-ilya-3ds Thanks for the use case; that makes sense. Reading the [spec](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#perspective), it seems this will work fine so long as aspectRatio is unspecified. In the event it is specified, is it better to ignore it and print a console warning, or use it and show a stretched render?

**Comment by methot-ilya-3ds** [comment]
In my opinion by showing a stretched render it could cause confusion for users. If the display is stretched people might believe that the solution would be to resize the canvas rather than looking for the console error which explains the problem in more detail.

**Comment by elalish** [comment]
@sun765 In addition to the use cases already outlined, this will allow us to clean up our render fidelity tests by using a camera in the models instead of defined in our config. 3D Commerce is already building their test models this way (which we will use) and I bet glTF would be happy if we updated their samples with cameras. We just need to consider how to expose the API.

**Comment by elalish** [comment]
We have a different issue for this already.

**Comment by dmnkwrl** [comment]
Sorry to write in this issue again but how is this marked as done? I can't find any reference for the camera inside a gLTF file to use with model-viewer

**Comment by elalish** [comment]
It's not done, it's a dupe of #2063. PRs welcome!
