### ISSUE TITLE
How to get SceneViewer in Version 1.0.0?

### ISSUE THREAD

**Issue by Piflyer** [google/model-viewer#1263]
### Description
Version 1.0.0 doesn't show the typical AR container UI with an object blending other features. It was available on version 0.10.0 but not version 1.0.0.

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v1.0.0

**Comment by lupohirp** [comment]
are you using scene-viewer?
