### ISSUE TITLE
Overturned 3D model in NPM Package

### ISSUE THREAD

**Issue by lupohirp** [google/model-viewer#1267]
Hi,

i've updated the NPM package of model-viewer to 1.0.0 version, but unfortunately with this version i saw the 3D Model overturned,

![image](https://user-images.githubusercontent.com/1065547/84382034-4e258480-abea-11ea-8451-5d3ec7dfd5f5.png).

With 0.10.0 i saw the model correctly. I'm using latest Chrome ( 83.0.4103.97 ). 

How can i fix it ?

**Comment by elalish** [comment]
@lupohirp We just fixed this bug for ChromeOS, but it looks like it may be a broader problem. Can you tell me what device or devices you are seeing this on? This may require a quick point release.

**Comment by elalish** [comment]
@lupohirp I would really like to ensure this is fixed; can you tell me what device you see this on? It might also help to see your `navigator.userAgent` string.

**Comment by elalish** [comment]
Closing as no repro.
