### ISSUE TITLE
Plane detection is not working and model is opening immediately after camera turn on.

### ISSUE THREAD

**Issue by Jibin-John** [google/model-viewer#1268]
### Description

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: vX.X.X
- three.js: rXX

**Comment by elalish** [comment]
@Jibin-John Can you please provide a detailed description of the bug? It sounds like you may just be seeing a difference between SceneViewer and WebXR, as webXR now shows the model immediately, but only places it on the floor once the floor plane is found. You can return to the old behavior with `ar-modes="scene-viewer webxr quick-look"`.
