### ISSUE TITLE
Declining WebXR permission request freezes page

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1269]
### Description

In the new WebXR flow users are asked for permission to use the camera for AR purposes. Declining that request, however, freezes the entire page instead of letting the user continue exploring the page and trying again at a later point.
Once the permission is declined, it seems after refreshing the page, clicking the "AR" button freezes immediately (without asking again).

#### Live Demo
pfc-writingball.glitch.me

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: latest dist

**Comment by elalish** [comment]
@hybridherbst Thank you! I'll look into whether this is a model-viewer or webxr bug and get it fixed in either case.
