### ISSUE TITLE
PWA Cannot open webxr AR

### ISSUE THREAD

**Issue by lupohirp** [google/model-viewer#1271]
Cannot open webxr AR from PWA. 

The error is the follow : 

![image](https://user-images.githubusercontent.com/1065547/84398978-e3337800-ac00-11ea-8883-2cb33d948d05.png)

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

- model-viewer: v1.0.0

**Comment by elalish** [comment]
@lupohirp Interesting, can you give us some more details? If you can remix our [Glitch](https://glitch.com/edit/#!/model-viewer) so that we can reproduce, that would be ideal.

**Comment by lupohirp** [comment]
i've requested to join project....i cannot edit your glitch :(

**Comment by elalish** [comment]
Sorry, you just have to create a free account. Then click remix and you’ll
get your own copy.

**Comment by lupohirp** [comment]
Sorry @elalish , never used Glitch because here in Italy i cannot see the preview, only the code, even if i use Google DNSs. Howewer this is the remix edited : https://glitch.com/edit/#!/join/44f27629-1dcd-4db0-991f-26fb68534c24. Should work, i cannot test for the motive that i said before. Honestly i think that it's not completely your problem. PWAs (correct me if i'm wrong ) uses Android webview. If i use the scene-viewer, it works correctly. if i set webxr, it doesn't work...seems that Android webview doesn't know what to open, and then you can't attach the XRSession from model-viewer.....

**Comment by elalish** [comment]
@lupohirp Sorry, I didn't realize Glitch was [broken](https://support.glitch.com/t/cant-view-project-previews-glitch-me-domain-cant-be-resolved-in-italy-host-not-found/15224) in Italy. Perhaps you could try Stackblitz instead? In any case, your Glitch is working perfectly for me. I don't believe there's any requirement between PWAs and webviews; in general PWAs simply load in your browser when you navigate to their URL. Perhaps you're thinking of PWAs packaged for the Play Store? In that case, you might find this [information](https://web.dev/using-a-pwa-in-your-android-app/) helpful.

**Comment by lupohirp** [comment]
cannot connect unfortunately.....even with cloudflare DNS. So with my example in PWA it works? maybe it's a problem by my side?

**Comment by lupohirp** [comment]
HI @elalish as i suspected, it was a Chrome problem. With Chrome beta, it works well. Tnx anyway for the support. I close the issue
