### ISSUE TITLE
Customise & match lighting conditions to the ones from Poly

### ISSUE THREAD

**Issue by nick-sp** [google/model-viewer#1274]
I''m trying to host some models on my website, the same ones I was hosting on Poly before. 
The problem is that the lighting conditions and appearance are very different, as you can see in the screenshots (1st photo is hosting from Poly / 2nd photo is self-hosting on website). 

When hosting directly on my site the model texture becomes glossy and the lighting changes as well. I tried using a skybox or environment-image with an image a user uploaded here, but the model became completely dark (3rd screenshot).

Is there a way to match the lighting conditions to the ones that are used when hosting and serving from Poly?

<img width="486" alt="Screenshot 2020-06-12 at 17 21 46" src="https://user-images.githubusercontent.com/66315633/84521076-2fec8100-acdd-11ea-94d7-e2264463e59e.png">
<img width="475" alt="Screenshot 2020-06-12 at 17 25 23" src="https://user-images.githubusercontent.com/66315633/84521141-44307e00-acdd-11ea-9bad-47e13dc74708.png">
<img width="510" alt="Screenshot 2020-06-12 at 18 48 27" src="https://user-images.githubusercontent.com/66315633/84521183-53afc700-acdd-11ea-9987-529f4cae99bf.png">

**Comment by elalish** [comment]
@nick-sp Can you post links to these examples? That would give me a much better chance of understanding what's wrong.

**Comment by gproud** [comment]
If I may hijack this thread @elalish I am having the same issue. When I apply any skybox or environment image I get the third image @nick-sp posted. 

https://glitch.com/edit/#!/join/e3a84155-04fe-402e-bf5c-d64c46980c60

This is a link to my glitch project illustrating the issue. With no hdri the colours show correctly and the model also looks fine on https://gltf-viewer.donmccurdy.com/ so I'm assuming it's not a model issue.

Side note, I can't seem to host my .glb files anywhere but on glitch and succesfully load the model viewer. Squarespace, googledrive, anonfile, and I think amazon don't ever load. But that's a different issue to the above.

**Comment by elalish** [comment]
@gproud It looks like it's either failing to find or failing to decode your hdri. Can you try some examples from HDRI Haven? You might also want to check just serving it locally. As for not working on googledrive and such, I think the problem is that you need the CORS headers set properly; there should be console warnings about that.

**Comment by gproud** [comment]
Hi @elalish thanks for responding, I have used the example hdri on the model-viewer site and the current is a second from hdri haven, both 1k.

This isn't my natural arena, so I will look into what you mean by CORS and let you know how I get on with that.

**Comment by elalish** [comment]
@gproud Yeah, I'm seeing this in the console on your website, so I think CORS is the answer:
```
Access to XMLHttpRequest at 'https://cube-sealion-kxw7.squarespace.com/s/piazza_san_marco_1k.hdr' from origin 'https://www.proud-studio.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by gproud** [comment]
@elalish Just to update you, I've managed to get around it with a CORS proxy for the moment (https://cors-anywhere.herokuapp.com/), I feel that it has marginally increased load times, but that may just be because it is loading the HDR as well now.

I'm very grateful for your help and work on this project!

**Comment by gproud** [comment]
@elalish However, now on iOS the same .usdz file which was held on glitch, now called through the proxy, returns a 'object requires a newer version of iOS' when going into AR mode. The glitch source stills works fine, it's only when calling the file through the proxy that it is unhappy.

**Comment by gproud** [comment]
@elalish Bafflingly calling the .usdz directly doesn't seem to have the same issues as calling the .glb or HDR as described, so it's seemingly all in working order

**Comment by elalish** [comment]
@gproud That is strange, but sounds like an iOS error. Hopefully the apple forums can help out. If you figure it out, please let us know here!
