### ISSUE TITLE
Model viewer vs Aframe AR.js

### ISSUE THREAD

**Issue by Jibin-John** [google/model-viewer#1278]
### Description

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: vX.X.X
- three.js: rXX

**Comment by elalish** [comment]
@Jibin-John This is the second bug you've left here with no description at all; is Github not saving your edits or something? If you can leave a description of what you're asking, I'd be happy to respond.
