### ISSUE TITLE
Reduce repo's package size

### ISSUE THREAD

**Issue by sun765** [google/model-viewer#1282]
### Description

The size of current repo is really large and it will become larger and larger. The reason is that the golden pictures are contained in every commits. This is not scalable because we will definitely add more commits. Besides, we are also integrating more renderers which means more golden pictures. One possible solution is to make a separate package just for golden pictures and users will only need to fetch the exact version of goldens when they need to.

**Comment by elalish** [comment]
We decided to tell people to clone with depth=1 instead as a workaround.
