### ISSUE TITLE
FullScreen Icon for window

### ISSUE THREAD

**Issue by IvanNov7** [google/model-viewer#1291]
Hi everyone,
I want to add full screen trigger option on model-viewer.
Some small icon that will make the iframe or whole windows fullscreen mode on desktop and mobile.
Is there any option for this right now?
Thank you

**Comment by elalish** [comment]
There is a generic [fullscreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) on the web, which I believe should work the same way for model-viewer as for any other DOM element. We don't build in any special affordance.
