### ISSUE TITLE
Update copyright year on modelviewer.dev

### ISSUE THREAD

**Issue by rkochman** [google/model-viewer#1292]
Modelviewer.dev pages currently display 2018 as the copyright date. It should instead show 2018-2020.

**Comment by elalish** [comment]
Should the code headers also do that?

**Comment by rkochman** [comment]
Yes, the two years should be the initial year and the year of last
modification, I believe.

**Comment by elalish** [comment]
@rkochman It appears the second year is optional: https://g3doc.corp.google.com/company/teams/opensource/copyright.md?cl=head#the-year
In light of this, do you mind if I skip this to avoid having to continually update them?

**Comment by rkochman** [comment]
That's fine for the code, but can we update it on the homepage? It makes the content seem "fresher" IMO.
