### ISSUE TITLE
Angular 9: Module not found: Error: Can't resolve '@google/model-viewer'

### ISSUE THREAD

**Issue by takarka** [google/model-viewer#1300]
### Description

I can not use <model-viewer> web component in Angular 9; I did everything that shows them [there ](https://vaadin.com/learn/tutorials/using-web-components-in-angular)

**Comment by elalish** [comment]
We had a similar report in #969. Could you remix our [Glitch](https://model-viewer.glitch.me/) to demonstrate the trouble, or point us to some other link that we can debug?

**Comment by lupohirp** [comment]
can you import this? 

import '@google/model-viewer/dist/model-viewer';

**Comment by SaintJacques** [comment]
import "@google/model-viewer"
