### ISSUE TITLE
Focus Ring & Responsiveness 

### ISSUE THREAD

**Issue by reubenkib** [google/model-viewer#1304]
I'd imagine these fixes are simple, but I'm having trouble resolving them.

1. On desktop, when interacting with model-viewer, a blue border appears (focus ring). On other sites that use model-viewer, I noticed that they don't have this which is what I am trying to achieve. Is there a way to disable this but also comply with user accessibility so when the keyboard is being used, it will appear only then?

2. I read that model-viewer is responsive out of the box. I am able to set width, height but it is not responsive. How can I achieve the same UI as shows on modelviewer.dev?

Thank you.

**Comment by reubenkib** [comment]
I was able to sort out the responsiveness, it was an error on my end. 

I still can't manage to get rid of the focus ring on the mouse but still useable on keyboard. I looked at focus-visible documents and added the script then added the CSS - still nothing as the focus ring is always appearing.

**Comment by reubenkib** [comment]
Both issue resolved. It was an error on my end.

**Comment by eLBati** [comment]
Hi @reubenkib , how did you solve?
