### ISSUE TITLE
Change the camera Y position

### ISSUE THREAD

**Issue by mpulock** [google/model-viewer#1305]
Hi,

I have been playing with model-viewer for while.
 I have been facing one issue. I've searched through the documentation, but was unable to find it. When, I import a character model, the camera focuses on the crotch area :)

I've tried changing the 'camera-orbit' attribute, and I know If increase the distance value, that'll zoom out the model. But, I like the current distance, just want the camera to go upwards. Is there any way i can do  that? 

![issue](https://user-images.githubusercontent.com/58793382/85212912-900aa500-b325-11ea-9236-44a999da2b86.PNG)

Thank you.

Regards,
Maheen

**Comment by elalish** [comment]
Yes, you’re looking for the camera-target attribute. It takes x , y, and z.

**Comment by mpulock** [comment]
Thanks, Emmett! Keep up the awesome work!
