### ISSUE TITLE
Content placement changes in Edge browser

### ISSUE THREAD

**Issue by mpulock** [google/model-viewer#1306]
Hi,

I have used model-viewer in my website. It looks really good in Google Chrome. But, when, i open it in Edge, there is an yellow progress bar in middle, which doesn't disappear when the model is loaded. And, the Grid container is supposed to cover the whole page, but it doesn't. Not sure what am i doing wrong. 

Website link: https://www.maheencg.com/

Hope you can help me with the issue.

Regards,
Maheen

**Comment by elalish** [comment]
@mpulock Thank you, this prompted me to install Edge, which I hadn't even realized was available on macOS. Anyway, your site loads just fine for me and looks the same as with Chrome, which makes sense since they are both Chromium-based browsers. Can you give me some details on your OS and GPU?

**Comment by mpulock** [comment]
> @mpulock Thank you, this prompted me to install Edge, which I hadn't even realized was available on macOS. Anyway, your site loads just fine for me and looks the same as with Chrome, which makes sense since they are both Chromium-based browsers. Can you give me some details on your OS and GPU?

@elalish Thanks for  the reply. I am in Windows 10 Version 1909. My GPU is Nvidia geforce rtx 2080 ti. Here is how the website looks like in Edge. Sorry, I don't own mac or ios device. So, am not sure, how is the performance in Safari. But, In Chrome and Firefox, the website loads pretty fast. You did some real magic there. :)

![Edge](https://user-images.githubusercontent.com/58793382/85315601-5c489000-b489-11ea-8a1b-7e81167a74e0.PNG)

Also, don't want to spam adding more issues, but, I can't test my website through Page Speed Insights. It gives following error: 

" Lighthouse returned error: INTERNAL: Extension result empty. Lighthouse calling Page.navigate with https://www.maheencg.com/ Uncaught (in promise) Error: Extension timed out. No call to exit() before render timeout. at wrs.Extension.onTimeout_ (http://ghost-rider/devtools_script_api.js:5606:13) at http://ghost-rider/devtools_script_api.js:655:11 "

I am not a JavaScript person. so have no clue what's wrong. :(

**Comment by elalish** [comment]
@mpulock Well, I can say with confidence that yellow bar is not coming from model-viewer. I'm not sure what it is, but perhaps there's some interaction with something else on your site. As for lighthouse, our scores there are not great at the moment, though I'm very pleased you like our performance. They test slow bandwidth, so I'd guess you may be serving a large enough model that they time out before it loads. Have you looked at DRACO compression?

**Comment by mpulock** [comment]
@elalish I tried as much as I can to compress my model. But, it's still around 5mb. I haven't heard about DRACO compression. But, I'll definitely look into it. Thanks for the info.  I am not really much worried about Edge though. Who even uses it :) 

My future requests for this Christmas would be:

1. Allow to Implement particles;
2. Allow to implement emission and transparent materials; (I wanted to add glass particles, but, it didn't work. May be that's GLTF format issue?)

Keep up the awesome work!

Regards,
Maheen
