### ISSUE TITLE
React: this[$prepare] is not a function

### ISSUE THREAD

**Issue by zeekrey** [google/model-viewer#1310]
### Description

When doing this:

```javascript
 function upload() {
    if (!file) return;

    let formData = new FormData();
    formData.append("myModel", file);

    fetch("https://httpbin.org/post", {
      method: "POST",
      body: formData
    })
      .then(res => res.json())
      .then(res =>
        fetch(res.files.myModel)
          .then(res => res.blob())
          .then(res => setModel(URL.createObjectURL(res)))
      );
  }
```
And assign the `URL.createObjectURL(res)` as src, I get the following error:

```
"TypeError: this[$prepare] is not a function
    at Function.prepare (https://rho5h.csb.app/node_modules/@google/model-viewer/dist/model-viewer.js:1:1182774)
    at eval (https://rho5h.csb.app/node_modules/@google/model-viewer/dist/model-viewer.js:1:1152989)"
```

Edit: I thought it could be a problem with the blob itself. So I assigned a static file reference to the src attribute but I still get the same error. :(

### Live Demo

https://codesandbox.io/s/webvr-stuff-rho5h?file=/src/App.js

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions

- model-viewer: v1.0.0

**Comment by elalish** [comment]
Thanks for adding a demo; it looks like you're using React, which can be a little tricky with web components sometimes. I'd recommend looking through these issues, as there have been some helpful comments from users with more React experience than I have: https://github.com/google/model-viewer/issues?q=is%3Aissue+is%3Aopen+react

Have you verified that you can get a barebones model-viewer element working in React first?

**Comment by zeekrey** [comment]
I read the other issues and seems like I got the same problem as https://github.com/google/model-viewer/issues/690#issuecomment-629552413 

I've attached event listeners and received error events when the page loaded. But the event payload is empty:

`onError: {"isTrusted":false} `
