### ISSUE TITLE
Firefox slow zoom

### ISSUE THREAD

**Issue by tskaiste** [google/model-viewer#1312]
### Description

In the given model-viewer tester example, zoom in/out works very slowly when using Firefox browser.

#### Live Demo
https://modelviewer.dev/examples/tester.html

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
@tskaiste Interesting, it's working fine on my mac. Is this using a mouse scroll wheel or touchpad gesture?

**Comment by methot-ilya-3ds** [comment]
I have the same problem on my computer when using the trackpad scroll. The problem is not present in Chrome or Microsoft Edge.

Firefox Version: 68.9.0esr

**Comment by elalish** [comment]
@methot-ilya-3ds Hmm, that's pretty old; I'm on Firefox 77. Does it still repro on the latest? And is this also on Windows?

**Comment by methot-ilya-3ds** [comment]
@elalish I've updated to version 77.01 and the problem remains. I am on a windows machine. 

There is one particular console error which is not present for the other browsers:

`WebGL warning: drawElementsInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)  three.module.js:16389:5 `

**Comment by elalish** [comment]
@methot-ilya-3ds Thanks, that warning is interesting, but I bet it's a rounding issue and I think unrelated to scroll. Does the trackpad scroll page contents at the same rate in Chrome and Firefox on Windows? Unfortunately I don't have a Windows machine to repro on, so this won't be easy for me to diagnose. @sun765 Can you repro this?

**Comment by methot-ilya-3ds** [comment]
The contents zoom much faster on Chrome and Microsoft Edge than in Firefox. The Firefox scroll is perhaps 10% the speed of Chrome's.

**Comment by tskaiste** [comment]
@elalish I'm using mouse wheel, @methot-ilya-3ds is correct, the Firefox scroll is much slower than in Chrome, and you need to scroll for a good minute to zoom in fully on a model. I'm using Firefox version 77.0.1

**Comment by hjeldin** [comment]
Can confirm on Ubuntu 19.10 / Firefox 78.0.1

**Comment by gjcope** [comment]
Running into this issue as well. Windows 10 / Firefox 78.0.1
