### ISSUE TITLE
addEventListener on iOS

### ISSUE THREAD

**Issue by jozkr8** [google/model-viewer#1314]
Apple added new capability with buttons and the implementation is via ID - but it doesn’t seem to work. I’ve had a look at the model-viewer.js where <a> is created dynamically and then with rel=ar and even managed to dynamically ad ID but it’s not working when calling it. Any wisdom on this plz? 

document.getElementById("ar-link-3").addEventListener("message", function (event) {   
    if (event.data == "_apple_ar_quicklook_button_tapped") {
        window.location.assign("https://developer.apple.com/documentation/arkit/previewing_a_model_with_ar_quick_look");
    }
}, false);

**Comment by elalish** [comment]
@jozkr8 Interesting, I don't know anything about this new capability; can you point me to some documentation? It's a little hard for me to imagine how a webpage would be able to listen for an event from a native app like QuickLook.

**Comment by jozkr8** [comment]
https://developer.apple.com/wwdc20/10604

https://developer.apple.com/augmented-reality/quick-look/ - if you scroll down you’ll find them :)
