### ISSUE TITLE
Changing textures on a model in model-viewer

### ISSUE THREAD

**Issue by ZenDerDio** [google/model-viewer#1316]
### Changing textures on a model in model-viewer

Hi, I have an issue with changing textures on model while using model-viewer v1.0.0, I am trying to solve this based on https://github.com/google/model-viewer/pull/1245 and 3DOM demo.

Model viewer with a script that should change texture:

    <model-viewer
      id="astronaut"
      camera-controls
      src="https://modelviewer.dev/shared-assets/models/Astronaut.glb"
    >
      <script
        type="experimental-scene-graph-worklet"
        allow="messaging; material-properties"
      >
        self.addEventListener('model-change', () => {
          const {model} = event;
          model.materials[0].pbrMetallicRoughness.baseColorTexture.texture.source.setURI(texture1.jpg);
        });
      </script>
    </model-viewer>

Three.Js does "see" my texture and resizes it (I also tried with .png/web URLs), but I get this error: 

![obraz](https://user-images.githubusercontent.com/44141209/86007966-77cb1200-ba18-11ea-81a0-14b060b26f9e.png)

Am I missing something or doing something in the wrong way?

### OS

-  Windows

### Versions

- model-viewer: v1.0.0

**Comment by elalish** [comment]
@ZenDerDio Stay tuned, I'm in the process of changing the 3DOM API heavily.

**Comment by elalish** [comment]
There is now a new, simplified scene-graph API released in v1.1: https://modelviewer.dev/examples/scene-graph.html

**Comment by Mariogg96** [comment]
hi, Is there a way to modify how the variants are displayed?

**Comment by elalish** [comment]
How they look is up to your HTML: https://modelviewer.dev/examples/scenegraph/#variants
