### ISSUE TITLE
Weird behaviour of SceneViewer launch intent when http is used

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1327]
### Description

For local development, I'm using a simple http server to serve model-viewer.
However, SceneViewer does not launch.
After some testing with the intent URL, the behaviour is indeed weird:
An intent such as
```
<a href="intent://arvr.google.com/scene-viewer/1.0?file=http://192.168.86.184/gramophone.glb#Intent;scheme=https;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;">Avocado</a>
```
will work (file uses http but schema is https), but the one model-viewer uses would be
```
<a href="intent://arvr.google.com/scene-viewer/1.0?file=http://192.168.86.184/gramophone.glb#Intent;scheme=http;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;">Avocado</a>
```
which does exactly nothing - also doesnt launch the fallback (this is with the schema automatically extracted from the URL).

I want the first behaviour to have it work :)
I guess there are three questions here; "what does that schema thing even do", "why do the two need to be different for this to work", "would it be possible to work around this"?

#### Live Demo
You'll need to use the above code locally (with any simple local http-server) and serve a glb file.

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Thank you, this looks like a bug to me. @tpsiaki, can you comment on the http vs https thing here? I'm a little surprised changing the intent in this way makes it work.

**Comment by hybridherbst** [comment]
SceneViewer officially only supports the HTTPS intent;
@tpsiaki please don't take this workaround away from me for local testing 🙏

**Comment by elalish** [comment]
Thanks for finding this workaround for local testing of SceneViewer. I decided to hard-code https into the intent to make this easier in #1475.

**Comment by hybridherbst** [comment]
Oooh, this is great, thanks - I didn't dare make a PR with such a hack 🧷 (changed it locally in our fork).
