### ISSUE TITLE
[Regression] "Invalid URL" for regular relative URLs

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1328]
### Description

I'm seeing a lot of this recently:

```
model-viewer.js:62357 Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at model-viewer.js:62357
    at HTMLElement.activateAR (model-viewer.js:62446)
    at HTMLDivElement.ARModelViewerElement.<computed> (model-viewer.js:62418)
```

for plain old relative urls (e.g. src="myModel.glb"). This seems to be a regression, when I switch to 0.9.0 this works fine.

#### Live Demo
https://prefrontalcortex.de/labs/model-viewer/upload/MultiMaterial-URLBug/

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
I believe this is a dupe of #1286. Can you verify this is fixed on master?

**Comment by hybridherbst** [comment]
Yes fixed! Sorry I didn't see the duplicate
