### ISSUE TITLE
Spam-clicking AR button causes AR to break (fullscreen behavior takes over)

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1329]
### Description

We have reports from people that model-viewer gets stuck in fullscreen mode after repeatedly pressing the AR button. 
From our tests, this seems to be caused because multiple AR open requests are sent and thus the fullscreen fallback kicks in, preventing any further AR use (even if the device actually supports it).
Reproduces with all SceneViewer using scenes/devices.

This kind of "spam clicking behavior" is especially common for kids and elderly it seems.

**Comment by elalish** [comment]
We actually removed the fullscreen fallback in 1.0, since it was flakey at best. If this is happening on the latest, can you give a screenshot of what you mean by "fullscreen mode"?

**Comment by hybridherbst** [comment]
I think fullscreen fallback is gone but the internal bool for "has tried fallback" or so is still there, that's what I meant. There's no fullscreen happening but ... basically nothing.
