### ISSUE TITLE
Can't set src to a blob url in firefox

### ISSUE THREAD

**Issue by ziyanma** [google/model-viewer#1332]
### Description
Setting src of model-viewer to a blob url causes model-viewer breakage: no model is rendered. After setting the url back to regular static url, model-viewer still renders no model.

#### Live Demo
https://glitch.com/edit/#!/model-viewer-src-blob-url-firefox

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions
- model-viewer: v1.0.0
- three.js: rXX

**Comment by elalish** [comment]
Thanks, in fact this also repros in our [interactive example](https://modelviewer.dev/examples/tester.html). No console warnings or caught exceptions; ugh.
