### ISSUE TITLE
WebXR doesn't work in Firefox' WebXR Viewer

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1343]
### Description

Mozilla has an iOS app for testing WebXR on iOS.
Seems model-viewer does not detect it as AR-capable;
there's https://github.com/MozillaReality/webxr-ios-js/issues/83 open on their end but I wanted to have something open here as well so this can be tracked, because I'm not entirely sure whose bug this is.

When opening a page (e.g. https://modelviewer.dev/examples/augmented-reality.html) there's no AR button; after forcing the page to "mobile page" via ... menu the button is shown but just downloads the USDZ (just for future reference, I opened https://github.com/MozillaReality/webxr-ios-js/issues/109 with them).

#### Live Demo
https://modelviewer.dev/examples/augmented-reality.html

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [X] Firefox (Mozilla WebXR Viewer)
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Thanks, yes we actually chatted offline about this with them and other webXR folks and decided their implementation is not following the spec. Hopefully they'll be updating it soon, but we may loosen our tests as well. Unfortunately detecting the readiness of webXR is a tricky business, but we're making improvements.

**Comment by mmdt12** [comment]
"Hopefully they'll be updating it soon"....

is it Updated??

how we can use model-viewer in ios mozila webxrViewer?

**Comment by elalish** [comment]
I don't know - do they have a place to file bugs? Would be great to link to a discussion on their side.
