### ISSUE TITLE
Some scenarios of babylonjs are not rendered correctly in fidelity test page

### ISSUE THREAD

**Issue by sun765** [google/model-viewer#1360]
### Description

There are three types of scenarios of Babylonjs are not rendered correctly in fidelity page (https://modelviewer.dev/fidelity/):

1. khronos-2CylinderEngine:  the model is actually rendered but it can't be seen until you rotate it. It's probably that the model is somehow clipped by the skybox

2. khronos-MetalRoughSpheres-LDR, FurnaceTest, DirectionalLightTest:  the HDR/LDR file is not loaded correctly

3. Sponza, khronos-VC:  Only clear color can be seen. Probably because these two scenarios are pretty big and it may be clipped by the far clip.

**Comment by elalish** [comment]
@sun765 Is this fixed now?

**Comment by sun765** [comment]
Everything is fixed except for part hdr files still can't be loaded. Since Sebastien said he won't add support for these hdr files, so i guess i should closed it now?

**Comment by elalish** [comment]
Yeah, I think this is all good now.
