### ISSUE TITLE
modelViewer is not defined at HTMLButtonElement(Animations are not working)

### ISSUE THREAD

**Issue by hellovarun** [google/model-viewer#1371]
### Description

Hello Guys, I'm experiencing a wired bug with animations all of sudden and animations stopped working and console throw's this error.
"Uncaught ReferenceError: modelViewer is not defined at HTMLButtonElement."

#### Live Demo
https://glitch.com/~humdrum-half-wanderer

- model-viewer: 0.9.0

**Comment by elalish** [comment]
I think you're just missing `const modelViewer = document.querySelector('#your-id');`

**Comment by hellovarun** [comment]
> I think you're just missing `const modelViewer = document.querySelector('#your-id');`

thank you, @elalish I have declared const but button click still not calling animations and everything was working fine before 2days

https://glitch.com/edit/#!/join/21998466-27a6-4fe4-b41b-735f0fdad32f

![image](https://user-images.githubusercontent.com/67313361/87743473-a31a7300-c806-11ea-8483-858a4ac58130.png)
