### ISSUE TITLE
FOV orthogonal views

### ISSUE THREAD

**Issue by ABakker30** [google/model-viewer#1375]
FOV lower bound currently is 10. Could FOV lower bound be extended to 0 or 1 to support orthogonal views?

**Comment by elalish** [comment]
We have not supported orthogonal views as they complicate the math too much. They are especially a problem for skyboxes, as a skybox is meaningless to an orthographic camera. What is your use case?

**Comment by ABakker30** [comment]
Working on a multi vertical model viewer portal. One vertical is art. My personal mathematical art benefits greatly from close to orthogonal views with minimal FOV distortion. Currently use SketchFab, their lower bound is 1 and does great. Two examples of my work (viewer dev and math art). Both with FOV at 10. Select animation tab.
1. https://virtualexhibits-qa.azurewebsites.net/viewer/artwork/6a3d3a9b-512e-4096-8e50-aab8769acf15
2. https://virtualexhibits-qa.azurewebsites.net/viewer/artwork/c9812c0e-e3c4-4b20-9978-4bdcdc3410de

Any lowering to even 1 or 2 degrees would be very beneficial. I understand the challenge with truely orthogonal at 0 :)

**Comment by elalish** [comment]
You can set the `min-field-of-view` [attribute](https://modelviewer.dev/), just don't set it to zero :). 1 degree should be no problem.

**Comment by ABakker30** [comment]
Awesome!

**Comment by ABakker30** [comment]
Would that allow me to see an object at a distance with FOV = 1?
I tried the min-field-of-view = 1 result -> https://virtualexhibits-qa.azurewebsites.net/viewer/artwork/6a3d3a9b-512e-4096-8e50-aab8769acf15

**Comment by elalish** [comment]
Please read through the rest of the attributes. You'll want to increase max-orbit radius so you can set a sufficiently large radius.

**Comment by ABakker30** [comment]
:)
Closing out the issue. 
Thanks again.
