### ISSUE TITLE
Glitch shows partial renders outside modelviewer in Safari on MacOS and iOS

### ISSUE THREAD

**Issue by MATTJ0NES** [google/model-viewer#1379]
Hi, I'm experiencing an issue where I have multiple models on a page in Safari (on both MacOS and iOS) and have a strange glitch (not sure how else to describe) where there seem to be multiple renders of each model happening outside the modelviewer itself. The models are set to autorotate and the glitch appears once rotation starts.

An image attached which hopefully gives the idea. You can see the straight line underneath the blue glow effect which shows where the modelviewer ends, and how the part renders appear outside of this.

Is this a known issue as can't find it in previous logged issues.

Thanks!

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions
Using this version of modelviewer:
unpkg.com/@google/model-viewer/dist/model-viewer.min.js

<img width="299" alt="Screenshot 2020-07-17 at 17 56 56" src="https://user-images.githubusercontent.com/1336955/87816312-06d08a80-c85f-11ea-9a7a-dca176e417c6.png">

**Comment by elalish** [comment]
Thanks, I have not seen this before, though I am working on a different iOS bug that might be related. Would it be possible to remix our Glitch in the issue template to reproduce this? That would help enormously with debug.

**Comment by MATTJ0NES** [comment]
Thanks for looking. I've not used Glitch before so which way would be best - to use all the same css and models that I have in my project or upload my models to Glitch? 

Would be happy to share a link to the project with you but prefer not to do publicly here as it is a work in progress.

Just to note, it's Safari on desktop as well as iOS.

Thanks again!

**Comment by elalish** [comment]
A simplified repro on Glitch, probably using generic models would be best. If you'd rather, you can DM me on twitter to share your existing project: @EmmettLalish.

**Comment by MATTJ0NES** [comment]
Thanks Emmett, much appreciated. I've recreated the issue here, using the default Glitch and adding in how I am using the model, just with some bits removed that identify it.

If you look after the second and third models in Safari on either desktop or iOS you should hopefully see it. FYI all OS and browsers are up to date with latest versions.

https://towering-surf-sleet.glitch.me

**Comment by MATTJ0NES** [comment]
Not sure if this is related to the cause of the issue but I see that the model viewer has a style of ["contain: strict"](https://developer.mozilla.org/en-US/docs/Web/CSS/contain) which is an unsupported property name in Safari.

<img width="863" alt="Screenshot 2020-07-18 at 14 57 07" src="https://user-images.githubusercontent.com/1336955/87854143-929df180-c907-11ea-9484-a7261d42b9f6.png">

**Comment by elalish** [comment]
I have been unable to repro your problem on either my mac or my iPhone SE. Also, could you post a link to the editable version of your glitch so I can see what you're doing? Are you intentionally layering model-viewer elements over each other? Regardless, I did find some Safari-specific bugs related to rendering multiple scenes, so I'm hoping #1387 also fixes your issue. Please let me know either way.

**Comment by MATTJ0NES** [comment]
Thanks. The editable version here https://glitch.com/edit/#!/towering-surf-sleet?path=index.html%3A112%3A0

I don't get it if Safari is resized to small dimensions but certainly get it at full screen on a 13in Macbook.

Current version of Safari is 13.1.1 and MacOS is Catalina, 10.15.5.

**Comment by elalish** [comment]
Thank you, I can repro it now. Digging in...
