### ISSUE TITLE
Shadow doesn't move when cameraTarget changed

### ISSUE THREAD

**Issue by deers** [google/model-viewer#1397]
### Description

Hi, I try using cameraTarget, but the shadow doesn't move. You can see in the demo below the shadow is being cut after I change the value to "0.6m auto auto". Is there a way to fix this?

![Capture](https://user-images.githubusercontent.com/814376/88377806-6afccc80-cdd2-11ea-9ff6-3854f26d46a7.JPG)

#### Live Demo

https://glitch.com/~shadow-cameratarget

**Comment by elalish** [comment]
Your link isn't working for me; is there a chance you made it private?

**Comment by deers** [comment]
@elalish ups, sorry I forgot to untick the private box. Now you should be able to open the link.

**Comment by elalish** [comment]
@deers Thanks, yes that's clearly a bug. Let me see if I can get it fixed for our upcoming release.
