### ISSUE TITLE
AR mode shows object too small

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1399]
Hello all!

![IMG_0416](https://user-images.githubusercontent.com/68244546/88289269-ac6f7800-ccfd-11ea-897b-8ebc678c1b64.PNG)

 Object is too small on AR. Anyone knows whats the problem ? Ps: I designed obj via Blender. and tried it with scaling object maximum but still when I open in AR mode it goes too small. As you see in the picture its %1000 zoom  but still its too small. 

Thanks

**Comment by elalish** [comment]
Cute jacket! The trouble is that glTF specifies that the units for all models are meters. Most modeling programs are pretty loose with their units, so it's easy to accidentally export something that is at completely the wrong scale. It looks like this one might be in units of km? A top-level transform of 100x or 1000x will probably fix it. 

If that doesn't work, you might want to check some other things. Sometimes models are placed at a position that is absurdly far from the origin, and that can confuse things down the road. You might also want to check if you get the same results in our WebXR, SceneViewer and QuickLook AR modes.

**Comment by sercandemirtas** [comment]
> Cute jacket! The trouble is that glTF specifies that the units for all models are meters. Most modeling programs are pretty loose with their units, so it's easy to accidentally export something that is at completely the wrong scale. It looks like this one might be in units of km? A top-level transform of 100x or 1000x will probably fix it.
> 
> If that doesn't work, you might want to check some other things. Sometimes models are placed at a position that is absurdly far from the origin, and that can confuse things down the road. You might also want to check if you get the same results in our WebXR, SceneViewer and QuickLook AR modes.


Thank you dude. Fixed.. 

By the way thas the jacket.. I shared pic of jacket cuz of you may wanna see full size :)



![IMG_0424](https://user-images.githubusercontent.com/68244546/88314021-0469a700-cd1d-11ea-9d56-832ee5ab0ae3.PNG)

**Comment by sercandemirtas** [comment]
I have one more question to you. What about lights on AR mode ? As you see below Web version and AR version are different. Can we make light setup for AR mode ?


![IMG_0424](https://user-images.githubusercontent.com/68244546/88315673-44ca2480-cd1f-11ea-9281-94eec728237f.jpg)

**Comment by elalish** [comment]
Great! The lighting is intentionally different in AR, as both SceneViewer and QuickLook attempt to estimate the local lighting in the room and apply that to make the object seem more real (but it's ML, so it's not always perfect). WebXR doesn't have this feature yet, so right now the only way to get consistent lighting between 3D and AR in model-viewer is to use the default WebXR AR mode (only available on Chrome Android). See #964

**Comment by Saicopate** [comment]
What is the maximum size of the object displayed in AR? 
I found that some large objects (etc building 3D models) are auto-resized to fit a specific bounding box.

**Comment by elalish** [comment]
@Saicopate I believe that is a feature of SceneViewer (and possibly QuickLook?). WebXR mode does not currently auto scale at all. I don't actually know the answer, but hopefully their documentation will say something about it.
