### ISSUE TITLE
When AR is launched, getting a black screen on Android

### ISSUE THREAD

**Issue by rvootukur** [google/model-viewer#1402]
### Description
when trying to open a .glb model in AR, we are getting a black screen. Getting the following error in the console:

ar.js:203 TypeError: Failed to construct 'XRRay': Direction's `w` component must be set to 0.0f!
    at Sb.present (ARRenderer.js:204)
    at async Wb.present (Renderer.js:138)
    at async HTMLElement.[enterARWithWebXR] (ar.js:198)
    at async HTMLElement.activateAR (ar.js:149)

The error is coming from:
webpack:///./node_modules/@google/model-viewer/lib/three-components/ARRenderer.js

Here is the definition of DOMPoint:
interface DOMPoint extends DOMPointReadOnly {
    w: number;
    x: number;
    y: number;
    z: number;
}

declare var DOMPoint: {
    prototype: DOMPoint;
    new(x?: number, y?: number, z?: number, w?: number): DOMPoint;
    fromPoint(other?: DOMPointInit): DOMPoint;
};

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Browser Affected

- [] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.10.0
- three.js: r0.115.0
Chrome version on Pixel 3 XL - 84.0.4147.89

**Comment by elalish** [comment]
I believe this was fixed by #1187. Can you try v1.0 to verify?

**Comment by rvootukur** [comment]
This is the code I am seeing in the console:
const ray = new XRRay(new DOMPoint(0, 0, 0), { x: 0, y: -Math.sin(radians), z: -Math.cos(radians) });

**Comment by elalish** [comment]
Yes, but that code only exists in v0.10; can you try v1.0 instead?

**Comment by rvootukur** [comment]
On our dev platform we are already using v1.0 but unfortunately things are in broken state and couldn't test. will let you know as soon as I can test.

**Comment by rvootukur** [comment]
The code from v1.0.0:
const ray = new XRRay(new DOMPoint(0, 0, 0), { x: 0, y: -Math.sin(radians), z: -Math.cos(radians) });

**Comment by elalish** [comment]
Yes, but that should default to w = 0. Are you getting the same error as above?

**Comment by rvootukur** [comment]
The issue is fixed with V1.0.0. Thank you very much.
I highly appreciate your prompt replies and keep it going.
