### ISSUE TITLE
Remove unnecessary permissions from AR mode

### ISSUE THREAD

**Issue by pi0neerpat** [google/model-viewer#1417]
### Description

Upon entering AR mode, I am prompted to give permissions for my device: **camera**, **record audio**, and **access files**. The **record audio** and **access files** are completely unnecessary, and should be removed for the sake of privacy. 

Mozilla A-Frame / WebVR does not require this permissions to run their AR components.

![image](https://user-images.githubusercontent.com/35622595/88679919-f40b5080-d0bd-11ea-82ab-6108bb0d855a.png)

![image](https://user-images.githubusercontent.com/35622595/88679935-f8d00480-d0bd-11ea-99aa-0fea210e629b.png)

#### Live Demo

https://model-viewer.glitch.me/

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: latest
- webcomponentsjs@2.1.3
- intersection-observer@0.5.1
- resize-observer-polyfill@1.5.0
- focus-visible@5.0.2

**Comment by elalish** [comment]
From the look of it, you're launching SceneViewer rather than WebXR, which makes sense since Firefox doesn't support WebXR yet. SceneViewer is a native app and has nothing to do with the browser, so you're seeing generic Android permissions. It asks for all of those because it can record videos of your AR sessions and you can share them. On the plus side, I don't think it'll ask you for those permissions ever again.

**Comment by pi0neerpat** [comment]
I see. I think I was expecting WebXR to launch rather than SceneViewer, since that is what A-Frame does. 

One thing that could be really helpful is the option to choose how to display AR, rather than forcing SceneViewer. I am assuming that the only action taken now is to immediately deeplink e.g.

 Chrome v84
**Current behavior**: click AR button -> opens SceneViewer
**Expected behavior**: click AR button -> Asks me if I want to open SceneViewer or WebXR

**Comment by elalish** [comment]
@pi0neerpat Hmm, your original post said Firefox, but now you say Chrome 84. On Chrome 84 it should definitely be launching webXR by default. We do give you the choice of which AR experience you want to launch, through the `ar-modes` attribute. I may not be understanding: What is your current bug?

**Comment by pi0neerpat** [comment]
I've been trying with both. Closing since this is related to SceneViewer
