### ISSUE TITLE
Turning off scroll listener?

### ISSUE THREAD

**Issue by g3master** [google/model-viewer#1424]
### Description

Is it possible to turn off only the scrolling listener from the model viewer, but keeping the drag controls on? I have the model viewer expanded on full page width. When a user scrolls down he can't process on the page because he got stuck in the model zooming. In general is it possible to turn off the zooming? 

#### Live Demo
http://sterman.g3kunden.de/produkte/spindelbaugruppen

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions

- model-viewer: v1.1.0
- three.js: r0.117.1

**Comment by elalish** [comment]
Thank you for filing this, as this has been on my mind for awhile. The trouble is that scroll and drag are pretty intimately linked. We may want an optional mode where vertical drags are passed through to scroll. Does that sound good?

**Comment by g3master** [comment]
That would be awesome. I tried quite a while to overwrite the scroll event but as you mentioned either the drag is gone as well or both listener still exist.

**Comment by ZeusLT** [comment]
any news on this?

**Comment by thomaslecoeur** [comment]
That is an important feature to implement in my opinion !

**Comment by thomaslecoeur** [comment]
@elalish Thanks for the pull, unfortunately it only resolves the issue for touch devices. The mouse scroll isn't taken into consideration by the touch-action. Therefore it's still impossible to scroll a 100vw/100vh model-viewer on desktop...

**Comment by elalish** [comment]
@thomaslecoeur Thanks, we considered it to be a bigger issue on mobile since the screen is small and so you want it full width. Do you find this is also necessary on desktop?

**Comment by marcdstudio** [comment]
@elalish We'd love to have an option for this on desktop as well!

**Comment by thomaslecoeur** [comment]
@elalish I'm using ModelViewer in a fullscreen div, with content below it that is accessible after a scroll of the body. In my use case, it would be a pleasure to have this feature ! 👍

**Comment by elalish** [comment]
Okay, I'll reopen this to represent the desktop case. I'm thinking of an attribute `disable-zoom` that defaults to false (current behavior) and when true will disable zooming of the model and no longer swallow the associated scroll events from a mouse wheel and such.

**Comment by thibaud-be** [comment]
Digging an old one...
The current behavior seems to let the vertical scroll, scroll the view on mobile, and thus prevents camera movement when scrolling (touch) in the y direction.
This isn't desirable in a situation where you have a single fixed 100% height 3dviewer. 
I'm having a hard time figuring out how to change that either through .css or .js
am I missing something ?

**Comment by elalish** [comment]
You're looking for our attribute `touch-action="none"`: https://modelviewer.dev/docs/index.html#entrydocs-stagingandcameras-attributes-touch-action
