### ISSUE TITLE
modelviewer.dev/editor poster workflow is broken / weird

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1428]
### Description

1. After clicking "Display Poster" it seems the page is stuck, "Delete Poster" doesn't do anything (can't interact with the page)
1. Poster is in incorrect aspect ratio (not in page aspect ratio)
1. Poster isn't used as model-viewer poster and thus behaves differently than an actual poster (can't test responsive behaviour)
![image](https://user-images.githubusercontent.com/2693840/89059094-dad5fe80-d360-11ea-8945-ed6b8f3893b0.png)
1. Resizing the page while a poster is displayed breaks it, created posters afterwards are blank
1. Poster aspect ratio seems to be from model bounding box (?), breaks if zoomed in when generating poster (e.g. for city models)
![image](https://user-images.githubusercontent.com/2693840/89059331-4ae48480-d361-11ea-8c81-d6b1347db6a9.png)

#### Live Demo
https://modelviewer.dev/editor/

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
Indeed, I have a repro on that; that's pretty bad. I had tested this, I wonder when it broke?

**Comment by hybridherbst** [comment]
Great to hear! This is really something that I feel is very, very important as we try to build more model-viewer experiences, and something we're still struggling with.

To give some context on what the "poster workflow" ideally does:
- allows me to generate and download a poster
- for a target viewpoint and target camera orientation that I can define
- that works as responsive poster across mobile, desktop, landscape, portrait
- that can either have a transparent background or a skybox background
- that I can preview and "hold" (so, exactly the behaviour a user would see if this is set as poster) and test for responsiveness on various aspect ratios (e.g. by rescaling the browser window)
- that gives me an easy way to copy camera-target, camera-orbit

Plus, and I think that might be a separate issue
- that doesn't have weird cut off sides anywhere in a range of aspect ratios I can set (e.g. I say "I want this to work from 3:1 to 1:3" and I get a poster that does exactly that)

My understanding is that this last point might require additional changes to how posters work; e.g. if I want a poster to support these two cases:
![image](https://user-images.githubusercontent.com/2693840/89061160-86cd1900-d364-11ea-870c-f9b01f47b262.png)
and
![image](https://user-images.githubusercontent.com/2693840/89061179-90ef1780-d364-11ea-9b23-db63fe9e5c40.png)
then the generated poster would need to look like this:
![image](https://user-images.githubusercontent.com/2693840/89061248-ad8b4f80-d364-11ea-9dec-a4bff9cd8b31.png)
but at that aspect ratio it should be displayed like this:
![image](https://user-images.githubusercontent.com/2693840/89061304-c98ef100-d364-11ea-95de-472152bcc0f0.png)

I don't think that is currently supported on model-viewer, so for our projects we usually fall back to transparent posters on "some background that looks similar to the skybox and scales with the page" but for actual "lazy loading" and "seamless transitions" something like above would be required. In the icebox I guess ;)

**Comment by elalish** [comment]
@hybridherbst Okay, I fixed the primary problem, which was just a regression I introduced. Thankfully it is unlikely to affect anything but our own configurators. As to your comment on aspect ratios; we do make a seamless poster that works for all aspect ratios, but with the caveat you identified which is that it's letter-boxed when using a skybox. In general, the skybox is not our #1 concern as it's not used very much, and simply having a transparent poster over a skybox model still gives a fairly reasonable transition. If this is a major blocker for you, please file a new issue and we can discuss options.
