### ISSUE TITLE
modelviewer.dev/editor sliders are very coarse

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1429]
### Description

The sliders on the editor seem to only increment in steps of 1. This makes them hard to use for smaller models and larger models. (Note the few pixels I move the mouse)

![200731-191138](https://user-images.githubusercontent.com/2693840/89059640-d6f6ac00-d361-11ea-998c-45c066eced6b.gif)

#### Live Demo
https://modelviewer.dev/editor/

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
Yes, the UX could use a fair bit of cleanup, though that probably won't happen soon unless we get contributors. At least you can type values in at arbitrary precision.
