### ISSUE TITLE
Position of AR mode button

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1432]
Hello all!

Is it possible to change position of AR button on mobile devices ? Default version it is in the right buttom but I want it to move right top.

Thanks..

### Version

- model-viewer: v1.1.0

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ x] IE
- [x ] Safari

### OS

- [x ] Android
- [x ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by sercandemirtas** [comment]
Actually I dont want custom button. I just want to change position of default one.

**Comment by sercandemirtas** [comment]
Its ok. I did it.

**Comment by SaluzMaharjan1** [comment]
> Actually I dont want custom button. I just want to change position of default one.

Can you tell me the solution? I'm struggling with this one as well.

**Comment by elalemanyo** [comment]
@elalish I know this is an old issue, but what does it mean `Scope your CSS to model-viewer::part(default-ar-button)`?
How can I change css from elements inside `model-viewer`?
Thanks for the help

**Comment by elalish** [comment]
That's the beauty of `::part`! It allows you to apply your own CSS to our internal elements that we have exposed for you (in this case, `default-ar-button`). Try out:
```
model-viewer::part(default-ar-button) {
  background-color: red;
}
```
