### ISSUE TITLE
demo doesn't work when I try to host.

### ISSUE THREAD

**Issue by marcusx2** [google/model-viewer#1434]
### Description

I tried simply copying the .html and .css from this demo project: https://model-viewer.glitch.me/ and hosting them at https://awesome-brown-86efb4.netlify.app/. However it doesn't work! When I click to see the AR the astronaut just floats around and I can't interact with it! I even used the developer tools to see the network traffic, it's all the same. Is there any additional configuration on the server side that needs to be done or something?

### Version
- model-viewer: v1.1.0

### Browser Affected
- [x] Chrome

### OS
- [x] Android

**Comment by elalish** [comment]
When you say "floats around", I'm pretty sure that means you're in webXR mode before ARCore has found your floor. We have that intermediate mode where the object is in the middle of the screen and the orientation is controlled by the orientation of the floor. In order for ARCore to find your floor, you have to move your phone side-to-side and have some texture to look at. If you look at our [demo](https://modelviewer.dev/examples/webxr.html), you'll see we add a prompt to help guide users to do this. I'd recommend adding something similar to yours as well.

**Comment by marcusx2** [comment]
> When you say "floats around", I'm pretty sure that means you're in webXR mode before ARCore has found your floor. We have that intermediate mode where the object is in the middle of the screen and the orientation is controlled by the orientation of the floor. In order for ARCore to find your floor, you have to move your phone side-to-side and have some texture to look at. If you look at our [demo](https://modelviewer.dev/examples/webxr.html), you'll see we add a prompt to help guide users to do this. I'd recommend adding something similar to yours as well.

Yes, please load the URL I provided on your phone. It's the exact same code as the demo. But for some reason on my upload, I don't get the prompt to find the floor. It doesn't work.

**Comment by elalish** [comment]
I don't see any instructions in our glitch version either; it's very simple and we only added that to our webXR demo. It is accomplished by the HTML and CSS related to `id="ar-prompt"`. Keep in mind that if you use scene-viewer instead of webxr, you'll get a different (and non-customizable) experience.

**Comment by marcusx2** [comment]
Here's a gif showing what I see when I load the demo. There are definitely instructions!
![ezgif com-optimize](https://user-images.githubusercontent.com/5656275/89204377-5f589500-d58c-11ea-8784-ae476454f2dd.gif)

> Keep in mind that if you use scene-viewer instead of webxr, you'll get a different (and non-customizable) experience.
I don't understand what you mean, like I said I'm using the same code from the demo.

**Comment by elalish** [comment]
Your GIF is definitely showing scene-viewer. It should choose webxr by default; what browser version are you using? I would recommend experimenting with our `ar-modes` attribute to help you diagnose, since you can use that to restrict what AR modes it will try.

**Comment by marcusx2** [comment]
Chrome 84.0.4147.111 on Android. So you're saying that on the official demo it opens using scene-viewer but on my upload it opens using webxr?

**Comment by elalish** [comment]
That is what you're reporting. It's odd because the official demo opens webxr for me. If you'd be up for setting some break points and letting me know why it choses the wrong AR mode, that would be very helpful. What device is it?

**Comment by marcusx2** [comment]
> That is what you're reporting. It's odd because the official demo opens webxr for me. If you'd be up for setting some break points and letting me know why it choses the wrong AR mode, that would be very helpful. What device is it?

Awesome! It worked! I just changed my code to `ar-modes="scene-viewer"` and I got the experience I want. I'm using Samsung s8. Why should I use webxr when the scene-viewer does the job?

**Comment by elalish** [comment]
Great! They have different pros and cons, so it depends what you want. SceneViewer is a separate app, so you have to download the file a second time and it leaves your website, so you don't know what your user is doing. WebXR stays in the browser, so it's fully customizable with HTML and CSS. Also, the rendering is more consistent since it uses the same engine.

**Comment by marcusx2** [comment]
> Great! They have different pros and cons, so it depends what you want. SceneViewer is a separate app, so you have to download the file a second time and it leaves your website, so you don't know what your user is doing. WebXR stays in the browser, so it's fully customizable with HTML and CSS. Also, the rendering is more consistent since it uses the same engine.

Hm...I see! I tried this [demo](https://modelviewer.dev/examples/webxr.html), which uses webxr and has instructions. However, I can't scale the objects for some reason? Also, it's harder to rotate than on scene-viewer. It seems I need to click on a specific place to rotate the objects, while on scene-viewer I can just use 2 fingers to do it. However, I agree, it's more smooth than scene-viewer.

**Comment by elalish** [comment]
Yes, if you look at the attributes you'll see `ar-scale="fixed"`, since that is often desirable for commercial products. Two-finger rotation is on my todo list.

**Comment by marcusx2** [comment]
I am interested in helping you with discovering why it chooses the wrong ar mode. Where should I place breakpoints?

**Comment by elalish** [comment]
Thanks! Search for this line: `if (value === 'webxr' && IS_WEBXR_AR_CANDIDATE` for your break point. I'd expect this whole if statement to be true, but it seems to be false. If you can figure out which part is returning false (and maybe dig a little deeper), that would be very helpful.

**Comment by marcusx2** [comment]
The problem is that `IS_WEBXR_AR_CANDIDATE` returns undefined. On `constants.js`, `HAS_WEBXR_DEVICE_API` returns false because `navigator.xr` is `undefined`

![image](https://user-images.githubusercontent.com/5656275/89217829-3d1e4180-d5a3-11ea-9c2f-e0436566f5f3.png)

**Comment by elalish** [comment]
Argh, thank you! I should have noticed this before. WebXR is only allowed on https; If you try to use it on http, `navigator.xr` will be undefined. The problem I've noticed on Android is that when you type in a web address it defaults to http, hence the failure.

**Comment by marcusx2** [comment]
> Argh, thank you! I should have noticed this before. WebXR is only allowed on https; If you try to use it on http, `navigator.xr` will be undefined. The problem I've noticed on Android is that when you type in a web address it defaults to http, hence the failure.

Loooooooooooooool. It was something so simple! Good to know!

**Comment by marcusx2** [comment]
Another thing that I noticed, on WebXR when you scale the object, you don't see the percentage on top. I think it's a nice touch that is available on scene viewer and should be on WebXR as well.

**Comment by marcusx2** [comment]
And one last thing... this [demo ](https://modelviewer.dev/examples/webxr.html) doesn't work iPhone. Not on Safari, not on chrome. This [demo](https://model-viewer.glitch.me/), however, works on safari but not on chrome(iPhone). So on iPhone, I can only use the scene viewer, and only on safari?

**Comment by elalish** [comment]
quick-look is the only thing available on iOS at the moment: https://modelviewer.dev/examples/augmented-reality.html. You'll also want to set quick-look-browsers to "safari chrome".

**Comment by marcusx2** [comment]
Thanks! That worked! Now, when I open the scene viewer, is there a way to remove the blue `visit` button that appears? It fills space in the screen unnecessarily.

**Comment by marcusx2** [comment]
I see you talk about the issue [here](https://github.com/google/model-viewer/issues/1143), and that it was closed. So there is a way already, but how? Sorry I couldn't figure it out haha.

**Comment by marcusx2** [comment]
Problem solved.
