### ISSUE TITLE
Ver 1.1.0 Ar Button Does not Seem

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1436]
Hello all again.

I changed model viewer version "0.3.1 to 1.1.0". After that change Ar button started to does not seem in mobile Google Chrome ? Anyone having that problem too? or am I doing something wrong. 

ps:I checked Safari mobile and there is no problem with that.

These are the my codes.

    <model-viewer class="a"
                  src="/Assets/m4/m4.glb"
                  alt="3D Koltuk by BaseBros"
                  id="reveal" 
                  loading="eager"
                  poster="Assets/loading.gif" 
                  background-color="#fff"
                  camera-controls
                  camera-orbit="-15deg 75deg m"
                  ar
                  auto-rotate
                  ios-src="Assets/m4/m4.usdz"
                  shadow-intensity="1" 
                  stage-light-intensity="1" environment-intensity="1"
                 
                  ></model-viewer>

                <script nomodule src="https://unpkg.com/@google/model-viewer@v1.1.0/dist/model-viewer-legacy.js">
                <script type="module" src="https://unpkg.com/@google/model-viewer@v1.1.0/dist/model-viewer.js">
                <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.1.3/webcomponents-loader.js"></script>
                <script src="https://unpkg.com/intersection-observer@0.5.1/intersection-observer.js"></script>
                <script src="https://unpkg.com/resize-observer-polyfill@1.5.0/dist/ResizeObserver.js"></script>

Thanks.. 

### Version
-->
- model-viewer: v1.1.0

### Browser Affected

- [x ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by AytoMaximo** [comment]
Hi! I guess there is `quick-look-browsers="safari chrome"` attribute is missing :)

**Comment by sercandemirtas** [comment]
Upss. I got it. I missed that. Now it worked. Thank you AytoMaximo!
