### ISSUE TITLE
How do I remove link and title from Scene Viewer?

### ISSUE THREAD

**Issue by marcusx2** [google/model-viewer#1439]
### Description
I want to remove the bottom bar from the scene viewer, which contains the link and title. [This issue](https://github.com/google/model-viewer/issues/1143), which was closed, also describes the problem. It seems to me that it was fixed and it's already possible to do what I want, but I can't figure out how.

### Version
- model-viewer: v1.1.0

### Browser Affected
- [x] Chrome

### OS
- [x] Android

**Comment by sercandemirtas** [comment]
What do you mean by link and title? Can you send picture or link of your project

**Comment by marcusx2** [comment]
![79169529-899a0300-7da1-11ea-8098-a45c3b9ff101](https://user-images.githubusercontent.com/5656275/89657427-73113d80-d8a3-11ea-8356-2b54c0f5c812.png)

Remove the part in red

**Comment by marcusx2** [comment]
@elalish Is there simply no way, or?...

**Comment by marcusx2** [comment]
@elalish @cdata @jsantell @stevesan @smalls @yuinchien @mrdoob @yiyix @pushmatrix 

Anyone? I'd appreciate some information. If it's not possible that's ok too.

**Comment by elalish** [comment]
@marcusx2 Sorry, #1143 was closed erroneously; I had made that change in a PR, but this part was reverted. No, there is not currently a way to customize or remove the link and title from SceneViewer. Most of our focus now is on WebXR features instead.

None of us works on the weekend, so thanks for your patience :)

**Comment by marcusx2** [comment]
> No, there is not currently a way to customize or remove the link and title from SceneViewer.

Aah ok, thank you.

**Comment by marcusx2** [comment]
Issue clarified.
