### ISSUE TITLE
viewer.min.js:1010 Error

### ISSUE THREAD

**Issue by billschnoebelen** [google/model-viewer#1443]
### Description

This is working fine on my localhost. 

I uploaded to Digital Ocean droplet. Nothing shows up in canvas. I get the following uncaught error: 

Chrome:
_createForOfIteratorHelper.js:51 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at HTMLElement.value (model-viewer.min.js:1010)
    at HTMLElement.value (model-viewer.min.js:1010)
    at HTMLElement.value (model-viewer.min.js:1010)
    at HTMLElement.value (model-viewer.min.js:1010)
    at n.value (model-viewer.min.js:528)
    at n.value (model-viewer.min.js:528)
    at model-viewer.min.js:528
    at model-viewer.min.js:252_

Firefox:

TypeError: n is undefinedmodel-viewer.min.js:1010:21956
    value model-viewer.min.js:1010
    value model-viewer.min.js:1010
    value model-viewer.min.js:1010
    value model-viewer.min.js:1010
    value model-viewer.min.js:528
    value model-viewer.min.js:528
    value model-viewer.min.js:528
    ji model-viewer.min.js:252
    r model-viewer.min.js:252

#### Live Demo

https://machinedplates.com/
must login to see it.

### Version

"@google/model-viewer": "^1.1.0",

### Browser Affected

- [X] Chrome
- [X] Edge
- [X] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by billschnoebelen** [comment]
This is a React App

Solved by #1437

This solved it:
import "@google/model-viewer/dist/model-viewer-legacy";

This worked locally, but not on server:
import "@google/model-viewer";

**Comment by SuperBlockchainMan** [comment]
Version
"@google/model-viewer": "^1.8.0"

In this version, there is no "@google/model-viewer/dist/model-viewer-legacy"
So you should use "@google/model-viewer/dist/model-viewer-umd"

I hope this is helpful.
Thank you

**Comment by SuperBlockchainMan** [comment]
Version
"@google/model-viewer": "^1.8.0"

In this version, there is no "@google/model-viewer/dist/model-viewer-legacy"
So you should use "@google/model-viewer/dist/model-viewer-umd"

I hope this is helpful.
Thank you
