### ISSUE TITLE
model-viewer.min.js net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by AytoMaximo** [google/model-viewer#1446]
Hi! I can't load your package from https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js
So.. where is it now? I feel really confused, 'cas our products stoped working all at once. It's not a good idea to delete everything from  public repository.

**Comment by pankajbaviskar** [comment]
I'm also facing the same issue, looks like some issue with unpkg.com again

**Comment by yordiverbeeck** [comment]
Got the same issue but seems to be fixed again now

**Comment by pankajbaviskar** [comment]
yes, working for me as well.
