### ISSUE TITLE
Scene Viewer not working

### ISSUE THREAD

**Issue by Esteban26** [google/model-viewer#1454]
Hi google team,

I've implemented the Scene viewer tool directly with <a> tags

https://developers.google.com/ar/develop/java/scene-viewer

So I have something like this:

```
<a href="intent://arvr.google.com/scene-viewer/1.0?file=https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf#Intent;scheme=https;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;">Avocado</a>
```
The problem I'm facing is when I tap the AR link, last week it was working perfectly, but today I'm getting this:

First Google chrome shows a modal that indicates that I need to update my Google App

![WhatsApp Image 2020-08-12 at 10 18 50 AM](https://user-images.githubusercontent.com/1881501/90033766-73378180-dc85-11ea-98ca-baa1a700d52f.jpeg)

But when I try to upgrade my google app, it is already updated so I'm getting this:

![WhatsApp Image 2020-08-12 at 10 18 50 AM (1)](https://user-images.githubusercontent.com/1881501/90033765-72065480-dc85-11ea-8aeb-7c219acab4fa.jpeg)

Device:
Hawuei mate 20 lite

Browser Affected
Chrome

OS
Android

**Comment by tpsiaki** [comment]
Hi @Esteban26 - Thanks for the report.  Will you double-check the link you're using to launch.  This error indicates that you're launching to the com.google.ar.core package rather than com.google.android.googlequicksearchbox, and the error could be a result of launching with the gltf file url directly.

The link you shared above seems to work, but using a link like the following can repro what you report:

```<a href="intent://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Avocado/glTF/Avocado.gltf#Intent;scheme=https;package=com.google.ar.core;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;">Avocado ARCore/Legacy</a>```

If you're using the gltf file url (the deprecated intent scheme) rather than the arvr.google.com/scene-viewer/1.0?file=... intent then the fix is to update to this scheme which is now the only supported version.

**Comment by Esteban26** [comment]
intent://s3.amazonaws.com/test.cylindev.com/AR/4656/MG002128/VELVET_BLACK.glb?link=https%3A%2F%2Fviewer.cylindo.com%2F3.x%2Fv3.3.1%2Ftools%2Fpreviewer%2Findex.html%3Faccount-id%3D4656%26sku%3DMG002128%23FABRIC%3DVELVET_BLACK%26FINISH%3DNATURAL&title=3d%20Model#Intent;scheme=https;package=com.google.ar.core;action=android.intent.action.VIEW;S.browser_fallback_url=https%3A%2F%2Fviewer.cylindo.com%2F3.x%2Fv3.3.1%2Ftools%2Fpreviewer%2Findex.html%3Faccount-id%3D4656%26sku%3DMG002128%23model-viewer-no-ar-fallback;end;

**Comment by Esteban26** [comment]
Yes, I checked and using the new intent schema it works, just one question, when did you deprecated it? because until last week it was working properly?

**Comment by NEONFIVE** [comment]
Same problem here, we're using very old version of modelviewer like v0.5 - sceneviewer launch is broken and an update google dialog pops up.

**With the latest version v1.1.0, scene viewer launched correctly.** 

Any hints how we could use old versions of modelviewer without loosing the AR functionality?

**Comment by elalish** [comment]
@NEONFIVE No, the only support I can offer for old versions of model-viewer is newer versions. Is there a reason you're using v0.5? The rendering fidelity and device compatibility have been dramatically improved since then, not to mention many bugs fixed.

**Comment by NEONFIVE** [comment]
@elalish thanks for the feedback. atm we're using v.1.1, just want to let you know that the sceneviewer functionality is broken in old versions like 0.5.
