### ISSUE TITLE
Metallic Roughness Texture Repeat not working in Modelviewer 1.1.0

### ISSUE THREAD

**Issue by NEONFIVE** [google/model-viewer#1462]
### Description

Texture Repeat settings on metallic / roughness imagenode seems to be ignored in modelviewer 1.1.0. 

Normally we set texture repeat on imagenode in Blender to use tileable textures for meshes. 
These repeat settings works fine for basecolor and normalmaps but seems to be broken on metallic/ roughness imagetextures. Looks like an importer issue in modelviewer v1.1 because same glb file works great in sceneviewer / threejs editor / babylon **and also with old modelviewer v0.5**. 

![repeat_texture_01](https://user-images.githubusercontent.com/56956825/90397434-1e867300-e098-11ea-8d05-38223e5027e7.jpg)
![repeat_texture_02](https://user-images.githubusercontent.com/56956825/90397436-1fb7a000-e098-11ea-8690-aefb1854b0a9.jpg)
![repeat_texture_03](https://user-images.githubusercontent.com/56956825/90397439-20503680-e098-11ea-87d3-de0da7623a6f.jpg)
![repeat_texture_04](https://user-images.githubusercontent.com/56956825/90397440-20e8cd00-e098-11ea-8dca-24e293778b8c.jpg)
![repeat_texture_05](https://user-images.githubusercontent.com/56956825/90397790-a9676d80-e098-11ea-9418-68b445815fe4.jpg)

### Version

- model-viewer: v1.1.0

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

**Comment by elalish** [comment]
Can you post your example GLB so I can repro locally? We inherit our GLB parsing from three.js, so it's odd if you're getting different results there.

**Comment by NEONFIVE** [comment]
sure - here is the test glb.
[test.zip](https://github.com/google/model-viewer/files/5089620/test.zip)

**Comment by NEONFIVE** [comment]
@elalish Any news here?

**Comment by elalish** [comment]
Yes, I can repro, and I think I know the problem. glTF and three.js use different defaults for wrapping mode and in creating a new texture I think I failed to transfer the value. Thanks!

**Comment by elalish** [comment]
This will get fixed when we pull in three.js r120.

**Comment by NEONFIVE** [comment]
@elalish any time information when three.js r120 will pull in modelviewer?
