### ISSUE TITLE
Issue with uploading transparent model 

### ISSUE THREAD

**Issue by livermodel** [google/model-viewer#1469]
Hi! I am fairly new to code and 3D models, I am working on a project and was having trouble uploding a file via model viewer. I an using Blender and when exporting the model as a .glb, and then using this model on Github via model viewer, the component of the mesh which is supposed to be transparent is showing up as opaque. I have added an image of how the model is supposed to look like and how it actually looks like when uploaded. I have also included the code I used to upload the model. The model is two separate models appended together with the transparent portion using Alpha blend using Blender 2.82a. Thank you for any help/input! 

How I want it to look like: 
<img width="658" alt="livermodel" src="https://user-images.githubusercontent.com/68698934/90674929-d0a07500-e227-11ea-9a88-f670525a1b53.png">

How it actually looks like: 
<img width="594" alt="Screen Shot 2020-08-19 at 2 25 37 PM" src="https://user-images.githubusercontent.com/68698934/90674993-e57d0880-e227-11ea-8bc6-640d44021c04.png">

Code Used: 
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>

	<model-viewer
 	 alt="Model of Liver vasculature"
         src="Veinswithtranslucentouter1.glb"     
    	 style="width: 100%; height: 800px;"
    	 preload
    	 reveal-when-loaded
    	 auto-rotate
    	 camera-controls
	 shadow-intensity="1"
	></model-viewer>

### Browser Affected

- [yes] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [yes ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
This looks like a glb export issue, unless you get different results with another viewer like https://gltf-viewer.donmccurdy.com/. I don't know Blender well enough to help much here, so I'd check with their forum. Also make sure you're on the latest version, as many of these glb exporters are in flux with bugs being fixed regularly.
