### ISSUE TITLE
Request - Adjust Camera Near / Far plane

### ISSUE THREAD

**Issue by NEONFIVE** [google/model-viewer#1471]
### Description

To avoid z-fight on some of our models it would be nice to add parameters on camera for near and far range. 

https://threejs.org/docs/#api/en/cameras/PerspectiveCamera

PerspectiveCamera( fov : Number, aspect : Number, near : Number, far : Number )
fov — Camera frustum vertical field of view.
aspect — Camera frustum aspect ratio.
near — Camera frustum near plane.
far — Camera frustum far plane.

### Version

- model-viewer: v1.1.0X

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Can you post your example of z-fighting? In model-viewer I already set the near and far planes close to the boundaries of the model, so I'm not sure you'll be able to do much better.

**Comment by NEONFIVE** [comment]
@elalish here's the example GLB. If i change near value to 0.05 in three.js editor it works as expected.


[test_ZFight.zip](https://github.com/google/model-viewer/files/5107764/test_ZFight.zip)

**Comment by mcnichols** [comment]
This is preventing me from using the library in production. I can't change my models, they are based on CAD designs for my company, the physical proportions of the model are based on the real life proportions. I need to be able to adjust the near field.

**Comment by elalish** [comment]
@mcnichols Would our new `scale` attribute suffice for your use case? https://modelviewer.dev/docs/#entrydocs-scenegraph-attributes-scale
