### ISSUE TITLE
Model viewer editor showing empty screen

### ISSUE THREAD

**Issue by ArvindSharda78** [google/model-viewer#1485]
### Description

From today morning https://modelviewer.dev/editor/ is showing empty page

#### Live Demo
https://modelviewer.dev/editor/

### Version

![image](https://user-images.githubusercontent.com/60726530/91536343-35e41c80-e932-11ea-9969-d866dcba7d81.png)

### Browser Affected

- 

- [x]  Chrome
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x ] Windows

**Comment by nguyenbs** [comment]
When I run the model viewer editor in my local WSL2 Ubuntu instance, it's also showing empty screen.
Browser: Chrome, Firefox,
OS: Windows 10.

The failed URL is:
http://127.0.0.1:8080/packages/modelviewer.dev/editor

![image](https://user-images.githubusercontent.com/4568193/97989597-57b9be00-1e11-11eb-985b-36cd2a7c0b09.png)

**Comment by elalish** [comment]
@nguyenbs Yes, we move it to a different location on deployment to create a shorter URL. You can find it by navigating to the space-opera package, then to editor. Is there a reason you're using the editor from a local build instead of the published one?

**Comment by elalish** [comment]
You likely forgot `npm run build` at the repro root. Take a look through the README for local build instructions.
