### ISSUE TITLE
Anti-aliasing issues in some browsers

### ISSUE THREAD

**Issue by wezside** [google/model-viewer#1486]
### Description

We've been noticing aliasing issues in some desktop browsers when the interaction prompt animation runs but also in some instances when the user interacts. Once interaction stops the aliasing will disappear. We even see this with the demo version. Attached is a video + model (had to zip it) which shows this. This doesn't happen in Firefox at all. 

#### Live Demo

http://www.modelviewer.dev/

### Version

- model-viewer: v1.1.0

### Attachment

[ModelViewer-Aliasing.zip](https://github.com/google/model-viewer/files/5141314/ModelViewer-Aliasing.zip)

### Browser Affected

- [x] Chrome
- [x] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [x] Windows

**Comment by elalish** [comment]
In fact that's a feature, not a bug. It's not aliasing, but low-resolution rendering. We does this now automatically when we detect the frame rate dropping, then crank it back up when the GPU load decreases (like when the model stops moving). This is what keeps the motion smooth. 

The next question is why is the rendering so slow? It could be a slow GPU, but it may also be possible to optimize the model to render faster. For instance, I see it has four separate materials. You should be able to combine these into a single material with a texture atlas, which will cut down the number of render passes and increase performance.

**Comment by wezside** [comment]
That is great info thanks @elalish . I'll pass this info on to the 3D designers who made the model. Just for reference here are the two machines we tested on. One a laptop and the other a mini PC. I would expect the mini to struggle but not so much the laptop which is a decent spec Acer Predator G9-791. So this leads me to believe it could be the model and/or textures?  

![Pasted File at August 27, 2020 2_45 PM](https://user-images.githubusercontent.com/109842/91590887-545f0d80-e95c-11ea-9178-3ea4e1ede99a.png)
![WhatsApp Image 2020-08-27 at 14 18 55](https://user-images.githubusercontent.com/109842/91590890-5628d100-e95c-11ea-80a3-3e0adfe17d82.jpeg)

**Comment by wezside** [comment]
Just on this @elalish - why would we see the same model appear differently in different browsers. Left is Chrome and right is Firefox. What we don't understand is how this FPS feature can determine it should render a low res for Chrome but Firefox is fine. Could you possibly elaborate on this? This happens with the demo Astronaut model as well. 

![Screen Shot 2020-08-28 at 15 13 20](https://user-images.githubusercontent.com/109842/91607543-55039e00-e974-11ea-8a49-4f268bfdd901.png)
![Screen Shot 2020-08-28 at 15 20 13](https://user-images.githubusercontent.com/109842/91607595-6b115e80-e974-11ea-9bd5-e3a2d97962c8.png)

**Comment by elalish** [comment]
So, it makes sense because each browser implements canvas and webGL differently, so they are not the same speed. However, I would tend to expect Chrome to be faster if anything, so it's strange that it's slower than firefox on the same device. Can you paste here the specifics of your device, GPU, OS version and browser versions? This might be a Chrome performance bug.

**Comment by wezside** [comment]
OS: windows 10
Device: Acer Predator G9-791
Chrome version: 85.0.4183.83
GPU: NVIDIA GeForce GTX 980M

**Comment by wezside** [comment]
Just an update on this. Turns out this machine's Chrome had the Hardware Acceleration option disabled. Sorry for the run around and thanks for feeding back on this question. We still have this issue on an older Mac Book but now everything adds up. 

Keep up the good work we love working with modelviewer!
