### ISSUE TITLE
Something happened and now AR doesn't work

### ISSUE THREAD

**Issue by burungiu** [google/model-viewer#1494]
Hello, guys

I had developed a project last two weekend and the last modification was 10 days ago, everything worked perfect.
Now it says that "Couldn't open object". 

Project could be reached at: https://spital.imipasadegorj.ro
What happened?

- model-viewer: latest

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by burungiu** [comment]
Downgrade to 1.1.0 solved the problem, hmm, what's wrong? 
I changed on https://spital.imipasadegorj.ro version from 1.2.0 to 1.1.0 and now it's working. could you please analyse what it wrong with my code (10 lines) that it doesn't work properly with 1.2.0?

**Comment by sercanov** [comment]
Same with us too. USDZ and GLB's are downloaded fine.

You can check it out on; https://app.diner.com.tr/house-of-b/menu

**Comment by burungiu** [comment]
> Same with us too. USDZ and GLB's are downloaded fine.
> 
> You can check it out on; https://app.diner.com.tr/house-of-b/menu
How did you scanned the products? Photogrametry? Which soft did you used?

**Comment by sercanov** [comment]
> How did you scanned the products? Photogrametry? Which soft did you used?
> 
> > Same with us too. USDZ and GLB's are downloaded fine.
> > You can check it out on; https://app.diner.com.tr/house-of-b/menu

Yeah, we used photogrammetry with some other tooling stack we've put together. Models are %90 computer generated.

**Comment by Wulff2099** [comment]
Sorry for asking you use this?
https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer-legacy.js
https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer.js
??

**Comment by burungiu** [comment]
> Sorry for asking you use this?
> https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer-legacy.js
> https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer.js
> ??

Yes, until today I used the latest version, I hope modelviewer dev will bring a solution for 1.2.0, or a fix if the problem is on their side.

**Comment by Wulff2099** [comment]
Because i can see the page in android ok but in iphone is not working
this is the page
https://virtualdesign.es/projects/47streetest/

**Comment by elalish** [comment]
Thanks, I have a repro; looking into it. I'll probably have a 1.2.1 out shortly. Appreciate your patience and rapid reporting!

**Comment by Wulff2099** [comment]
I dont know why if i use this 2 links
still not working in iphone
https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer-legacy.js
https://unpkg.com/browse/@google/model-viewer@1.1.0/dist/model-viewer.js

in my page
https://virtualdesign.es/projects/47streetest/index2.html

**Comment by elalish** [comment]
Okay, v1.2.1 with this fix is now up on npm and unpkg. Would anyone be so kind as to confirm it is now working as expected?

**Comment by elalish** [comment]
@Wulff2099 I believe your problem is including 'browse'; try something like this instead: https://unpkg.com/@google/model-viewer@1.2.1/dist/model-viewer.js

**Comment by Wulff2099** [comment]
Same problem cant open the object
![WhatsApp Image 2020-09-02 at 14 43 00](https://user-images.githubusercontent.com/46904084/92017893-d0759e80-ed2a-11ea-983e-20d0a1274a05.jpeg)

**Comment by elalish** [comment]
@Wulff2099 your `ios-src` is pointing at the same `.glb` as your `src`, instead of pointing at a `.usdz` or `.reality` file.

**Comment by Wulff2099** [comment]
ios-src is pointing to .usdz file

**Comment by elalish** [comment]
@Wulff2099 When I view source on your website above, I see this:
```
<model-viewer environment-image="assets/whipple_creek_regional_park_04_1k.hdr"
                  src="assets/zapa01.glb"
                  ios-src="assets/zapa01.glb"
                  alt="A 3D model of an astronaut"
                  shadow-intensity="1"
                  exposure ="1"
                  camera-controls
                  auto-rotate ar>
    </model-viewer>
```

**Comment by jeanieherold** [comment]
I can confirm the fix is working now in ios on safari, chrome and FF

**Comment by Wulff2099** [comment]
Upss! i fix it and works Thanks my bad, sorry

**Comment by VRJGaming** [comment]
> Same problem cant open the object
> ![WhatsApp Image 2020-09-02 at 14 43 00](https://user-images.githubusercontent.com/46904084/92017893-d0759e80-ed2a-11ea-983e-20d0a1274a05.jpeg)


have you solved iOS AR

**Comment by VRJGaming** [comment]
> Upss! i fix it and works Thanks my bad, sorry

how?

**Comment by Wulff2099** [comment]
> > Upss! i fix it and works Thanks my bad, sorry
> 
> how?

Whats your problem VRJGAMING?
