### ISSUE TITLE
Download .glb file instead of starting QuickLook on iOS

### ISSUE THREAD

**Issue by benjamindelmee** [google/model-viewer#1495]
### Description

Hello,

When using the latest version of ModelViewer (currently 1.2.0) on my iPhone (IOS 13.6.1) with Google Chrome (v84.0), the .glb file is downloaded when I click on the 3D icon instead of launching the QuickLook viewer.

I downgraded to ModelViewer 1.1.0 and everything works fine again.

### Version
- model-viewer: v1.2.0

### Browser Affected
- [X] Chrome : v84.0
- [ ] Edge: not tested
- [ ] Firefox: not tested
- [ ] IE: not tested
- [ ] Safari: not tested

### OS
- [ ] Android: not tested
- [X] iOS: 13.6.1
- [ ] Linux: not tested
- [ ] MacOS: not tested
- [ ] Windows: not tested

**Comment by kelvin-vl17** [comment]
Hi @benjamindelmee, we encountered the same problem! So glad you shared this.
How do I downgrade to ModelViewer 1.1.0?

**Comment by benjamindelmee** [comment]
> Hi @benjamindelmee, we encountered the same problem! So glad you shared this.
> How do I downgrade to ModelViewer 1.1.0?

When you import the library, use this code:

`<script type="module"
    src="https://unpkg.com/@google/model-viewer@1.1.0/dist/model-viewer.min.js">
</script>`

**Comment by kelvin-vl17** [comment]
> > Hi @benjamindelmee, we encountered the same problem! So glad you shared this.
> > How do I downgrade to ModelViewer 1.1.0?
> 
> When you import the library, use this code:
> 
> `<script type="module" src="https://unpkg.com/@google/model-viewer@1.1.0/dist/model-viewer.min.js"> </script>`

Awesome, thanks!

**Comment by elalish** [comment]
Okay, v1.2.1 with this fix is now up on npm and unpkg. Would anyone be so kind as to confirm it is now working as expected?

**Comment by kelvin-vl17** [comment]
> Okay, v1.2.1 with this fix is now up on npm and unpkg. Would anyone be so kind as to confirm it is now working as expected?

I checked it, works like charm again, cheers!

**Comment by benjamindelmee** [comment]
Checked, it works for me too! Thanks for the fix 👍
