### ISSUE TITLE
AR Quick Look is broken on iOS.

### ISSUE THREAD

**Issue by pixlhero** [google/model-viewer#1496]
### Description

AR Quick look seems to be broken on iOS devices. 
Open https://modelviewer.dev/examples/augmented-reality.html on an iOS device in safari. The astronaut model is displayed correctly here. When I click on the AR Button I get the screen with "Object could not be openend" as seen in the attached screenshot.

On Android modelviewer seems to work like always.

![IMG_4C86CFFAB5F2-1](https://user-images.githubusercontent.com/9341604/91979493-2a279a00-ed26-11ea-8ef3-adc556ff7085.jpeg)

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS (iPhone 11 iOS 14 Beta, iPhone 7 iOS 13.3)
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by burungiu** [comment]
You probably use 1.2.0 version, downgrade it to 1.1.0. Model viewer released 1.2.0  less than 20hours ago.

**Comment by Wulff2099** [comment]
Same problem works all perfect i went crazy thinking it was me. Thanks pixlhero

**Comment by MikeFesta** [comment]
I can confirm that I am seeing the same iOS issue with the latest push (1.2.0). In addition, chrome on iOS downloads the .glb when the AR button is pressed.

**Comment by elalish** [comment]
Thanks for the report! I'll have a look and probably get a 1.2.1 out soon.

**Comment by jeanieherold** [comment]
I can verify issue is on all browsers on ios. 

Can someone provide the link for me to set up model-viewer using this version mentioned by @burungiu ??:
"You probably use 1.2.0 version, downgrade it to 1.1.0. Model viewer released 1.2.0 less than 20hours ago."

I am currently using the following to add model-viewer to page but would like to be able to use a version edition so I can control when I put new releases into our project:

<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>

**Comment by elalish** [comment]
Okay, v1.2.1 with this fix is now up on npm and unpkg. Would anyone be so kind as to confirm it is now working as expected?

**Comment by jeanieherold** [comment]
@elalish 
it is working now in iphone 7 - safari and chrome and firefox. 
I have several others testing and will let you know if any adverse results that were previously ok. 

Thank you!!! 

Is there a way to use the unpkg with a version number?

**Comment by elalish** [comment]
@jeanieherold Yes, here is an example: https://unpkg.com/@google/model-viewer@1.2.1/dist/model-viewer.js

**Comment by MikeFesta** [comment]
I can confirm that it is working as expected on my iPad in both Safari and Chrome. Thanks for turning this around so quick!
