### ISSUE TITLE
Poster greyed out

### ISSUE THREAD

**Issue by kelvin-vl17** [google/model-viewer#1504]
### Description

When I use a poster for lazy loading and set the loading to "auto" or "lazy" the poster will show as greyed out.
When I activate loading "eager" it shows up correctly but then the loading time is huge.

Is there a workaround for maintaining the faster loading time using the "load 3D model" button and showing the poster correct?

#### Live Demo
http://virtuallab17.nl/website_iframes/augmented_shop_experience/fest/
https://virtuallab.brndz.nl/augmented-reality/augmented-shop-experience/

### Version
- model-viewer: v1.2.1

**Comment by elalish** [comment]
I'm not able to repro your problem so far. Can you fill out the rest of the OS and Browser info from the issue template? And maybe attach a screen recording of what you're experiencing?
