### ISSUE TITLE
[Editor] Animations stop playing when dropping a model with animations for the 2nd time

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1508]
### Description

When dropping an animated GLB into modelviewer.dev/editor, the animation plays in a loop. However, dropping that model for the 2nd time (or, as in my case, a new file with some fixes) seems to break animation playback with no way to recover (only page reload).

#### Live Demo
[AR-Teapot.zip](https://github.com/google/model-viewer/files/5173895/AR-Teapot.zip)
Drop this into modelviewer.dev/editor, note anim plays
Drop it again, note anim does not play
Toggle "play animation" or "autoplay", anim does not play

**Comment by elalish** [comment]
Thanks, I have a repro. If your model has multiple animations, then selecting a different one fixes it.

**Comment by hybridherbst** [comment]
Just wanted to report a bug and fortunately found my old bug about this 🗡️ 
Still happens, no workaround when model only has a single animation. Only page refresh, then drop model again helps
