### ISSUE TITLE
[Regression] Error when trying to access HDR environment/skybox with absolute path

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1509]
### Description

This was working fine in the past but seems to not work right now, with an error saying
`model-viewer.js:63249 Uncaught (in promise) Event` (seems in env generation)

![image](https://user-images.githubusercontent.com/2693840/92227753-02ac0b00-eea7-11ea-9eec-69c0eaeb1273.png)

and resulting in a black rendering (as if the image was not found).
![image](https://user-images.githubusercontent.com/2693840/92227930-574f8600-eea7-11ea-823c-593af84b9e66.png)

#### Live Demo
https://glitch.com/edit/#!/olivine-sturdy-hawk

### Version

- model-viewer: v1.2.1

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
I've run across this before with Glitch. I have to remove the `?v=...` from the end of the URL to get it to work. I'm not quite sure why three chokes on the URL wit the query param, but it could be a bug on their side.
