### ISSUE TITLE
[Question] : social networks in-app browser

### ISSUE THREAD

**Issue by ryancrunchi** [google/model-viewer#1511]
I tested my URLs to AR models by sharing them on social networks (fb, twitter and linkedin for now).
When you open an AR model from their native iOS app, they open it in their integrated browser. Here are the result of testing `modelViewer.canActivateAR` in different iOS browsers :
- Safari : true
- Chrome : true
- Facebook in-app : false
- Linkedin in-app : false
- Twitter in-app : true

For fb and linkedin, is this because they use a custom browser with not all features available (camera, XR etc..) ?
For twitter, is this because they use a default iOS safari view controller which enables all features ?
Can I force my links (https://) to open in safari when clicked in fb or linkedin app ?

**Comment by elalish** [comment]
I believe you are correct; we have similar problems with XR not being available in an Android WebView, which is basically equivalent. I have no idea what control you may have over where your links open.
