### ISSUE TITLE
AR mode failure moves to previous page

### ISSUE THREAD

**Issue by konradby** [google/model-viewer#1513]
### Description

When the AR mode fails browser goes back to previous page. It's probably related with `history.back();` in the code.

Second model on:
https://modelviewer.dev/examples/augmented-reality.html

Steps for Chrome: 
- open incognito window
- try to enter AR view
- allow to access external resources
- exit AR mode
- try again enter AR mode
- do NOT allow external resources
- browser page is navigated to previous page

Steps for Firefox:
- disable "Open link in apps" in browser settings
- go on the refferring page to page with the model on the same domain (https://modelviewer.dev/)
- click link to page where <model-viewer> is placed (https://modelviewer.dev/examples/augmented-reality.html)
- try open model in AR
- browser automatically goes to previous referral page

### Version
- model-viewer: v1.2.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Thanks, I have a repro. At least it's not a problem for webXR...

**Comment by elalish** [comment]
I believe this was fixed.
