### ISSUE TITLE
Change Material Base Color

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1515]
Hello all. 

I want to change material with button as you see in the pictures I added buttons Color1 and Color2. How do I know which material it changing ? What do I have to add to codes for specific material which I want to change ? For example I want to change "profiller" material. (you can see in the pictures)

Thank you.

<img width="1440" alt="Ekran Resmi 2020-09-08 10 21 58" src="https://user-images.githubusercontent.com/68244546/92446222-2bd9dd80-f1be-11ea-8190-c4b0beb69f31.png">

<img width="536" alt="Ekran Resmi 2020-09-08 10 28 39" src="https://user-images.githubusercontent.com/68244546/92446433-7b200e00-f1be-11ea-8624-b485b2e30e84.png">

<img width="1440" alt="Ekran Resmi 2020-09-08 10 21 04" src="https://user-images.githubusercontent.com/68244546/92446448-807d5880-f1be-11ea-867b-6363d337f75a.png">

**Comment by elalish** [comment]
This is not very ergonomic right now; there is an array of materials which is populated in a depth-first search of the glTF. Based on this, you can select the material you want by index and change it. It would be nicer to be able to also select a material by name. Shall we turn this issue into that feature request?

**Comment by sercandemirtas** [comment]
Hey Elalish. Thank you for answer. Yes It would be very nice select a material by name so we can turn this issue into request. Actually it is not an issue :)

**Comment by cristianonescu** [comment]
@sercandemirtas did you found a way to do this? I am looking to achieve the same
