### ISSUE TITLE
[AR] Texture/Material Fails to Load in AR

### ISSUE THREAD

**Issue by sepigraph** [google/model-viewer#1517]
Hello,

I'm trying to diagnose an issue where a texture fails to load in AR, but appears perfectly fine on the mesh when in the model viewer. The problem seems to be only happening on Android devices. 

You can preview the model [here](https://adminpages.viewinyourspace.com/demo_page/floyd_com/FloydTestingAR).

The affected area is the front face of the cabinet doors. They will simply fail to draw and disappear in AR, while the rest of the mesh loads clearly.

I've looked at the .gltf in VS-Code with no sign or warning of blatant issues (just some 'unused object' notifications). What I'm trying to determine is if I'm not following some sort of rule for the image formats that the .gltf loads. The textures are in JPG format. There's a plywood edge texture at 512x4096 resolution, and the problematic one at a resolution of 4096x2048. 

I've tested these at lower resolutions and the same problem persists for the affected material. It does not make sense to me however that model displays correctly in the viewer, but not in AR.

Would greatly appreciate any insights on the matter.

**Comment by elalish** [comment]
Which AR mode are you referring to? I would imagine this is SceneViewer, as webXR uses the same renderer as in non-AR. If you're not sure, you can set a single `ar-modes` value. A screenshot would also help. Also, can you fill in the rest of the issue template regarding OS and browser versions?

**Comment by sepigraph** [comment]
OS is Windows 10. But AR experience is on Android. 

Browser is Chrome on Android (Version 85.0.4183.81)

Here the model loads without an issue in the viewer, then in AR.

![AR-Issue](https://user-images.githubusercontent.com/70975811/92521593-1aef9300-f1e3-11ea-904e-956b528d397e.jpg)


I'm not 100% sure what version of model viewer (I did not implement/create the site where we host our files), but yes pretty sure it's scene viewer.

**Comment by sepigraph** [comment]
I brought the .gltf into Blender and re-exported. Issue has been resolved.

Appreciate your time.
