### ISSUE TITLE
 iOS issue Preview Universal scere Description(mobile)

### ISSUE THREAD

**Issue by VRJGaming** [google/model-viewer#1524]
Hi friends,

I am using the model-viewer model is working in the browser, Android. but not working in iOS(OS is 13.7)
In iOS device When I click on the AR Button I get the screen with "Preview Universal scere Description(mobile)zero kb".
Anyone have an idea on this issue. .usdz model  Tris:145,842( 3.90 MB)
![ios2](https://user-images.githubusercontent.com/48409358/92920740-69ee3000-f450-11ea-980f-ad253b136d9d.jpeg)

first got above image error after iOS OS Updated to 13.7 below error 

![iOS](https://user-images.githubusercontent.com/48409358/92920539-10860100-f450-11ea-9566-7b0121f91ccf.png)

**Comment by elalish** [comment]
This is a problem with your `ios-src`; are you using a USDZ or a .reality file? How did you create it? You might want to ask Apple's QuickLook support.

**Comment by VRJGaming** [comment]
Thanks for Replay me. I am using a blender to created .usdz ( ios-src=" Model.usdz" )

**Comment by Michele-Telesca** [comment]
I am getting the same error message. @VRJGaming  have you then solved? Thanks

**Comment by trylaarsdam** [comment]
I've got the same message, has anyone been able to make headway?

**Comment by elalish** [comment]
This is an old, closed thread. I'd recommend you start a new discussion with some details about your problem, since there are none here. Make sure to include a repro  link and what software you used to create your USDZ if you have one.

**Comment by Ashishkuldeep23** [comment]
I'm getting same error in my new AR application. Can anyone find a solution for this? Please solve this.

**Comment by elalish** [comment]
Generally this means Apple made a breaking change to USDZ and you need to regenerate it using their latest versions. FYI @grorg.
