### ISSUE TITLE
Android Scene-Viewer not openning

### ISSUE THREAD

**Issue by lucasmatheustesta** [google/model-viewer#1526]
I had an experience working just fine a few weeks ago and today openning a ar using scene-viewer (ar-modes="scene-viewer quick-look") is not working. The device is a Samsung S10 which supports ARCore and the "Google Play Services for AR" is up to date.

When the user clicks on the button to open R.A. the page reload and nothing happens (calls the fallback).

- model-viewer: v1.2.1

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Can you please post a link so I can try to repro?

**Comment by lucasmatheustesta** [comment]
Yes, of course: https://intro-suvinil-xgb.herokuapp.com/home/index.html

Thank you

**Comment by lucasmatheustesta** [comment]
[144d7eeb-b476-442c-9aa1-5d95aafca259.MP4.zip](https://github.com/google/model-viewer/files/5210671/144d7eeb-b476-442c-9aa1-5d95aafca259.MP4.zip)

Follows a video showing what happens in this exactly same URL

**Comment by elalish** [comment]
I'm seeing `ar-modes="webxr quick-look"`. Did you update it?

**Comment by lucasmatheustesta** [comment]
Sorry, I was testing last night, I just rollback to scene-viewer.

**Comment by lucasmatheustesta** [comment]
![WhatsApp Image 2020-09-11 at 14 17 49](https://user-images.githubusercontent.com/6788136/92954527-fccfa000-f439-11ea-94c1-2e39b290708f.jpeg)
![WhatsApp Image 2020-09-11 at 14 17 50](https://user-images.githubusercontent.com/6788136/92954531-fd683680-f439-11ea-8566-5fcb22f7ba73.jpeg)


Those are the Samsung S10+ device configuration

**Comment by elalish** [comment]
Hmm, SceneViewer seems to be working fine on my Pixel 3 with your site. @tpsiaki since this sounds like a SceneViewer regression.

**Comment by lucasmatheustesta** [comment]
Thank you. Any suspicious about what is going on? Since in the video provided it won't open?

**Comment by lucasmatheustesta** [comment]
I found the issue. The user was openning the link through a webview.
