### ISSUE TITLE
Poster generated at quarter resolution on slow machines

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#1529]
### Description

When running Model-Viewer on a slow machine, the Poster images generated via toBlob are at a quarter of the resolution of the Model-Viewer object (half original width and height).

This seems to only happen when the 3D rendering has been downscaled (automatically by Three.js when framerate is slow?). The toBlob method must be capturing the image data at the downscaled resolution, rather than the original canvas pixel dimensions. 

This is possibly a three.js issue rather than Model-Viewer issue. Unless there's some way to force Three.js to render out at the specific full resolution for the toBlob capture?

Only noticed this as I was doing some cross-platform testing and was using a (low end) cloud-based remote desktop session for Windows testing. In the real world, maybe people wouldn't be using such a low spec machine.

#### Live Demo
https://modelviewer.dev/examples/tester.html

### Version
- model-viewer: v1.2.1

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [x] Firefox v78.0.2
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

This screenshot shows the poster generation demo side by side with the generated image:
![Screenshot 2020-09-11 at 21 37 38](https://user-images.githubusercontent.com/53870482/92971936-455a7e00-f479-11ea-8f14-4f8ed3a2ad76.png)

**Comment by milesgreen** [comment]
Exploring this a bit more, and I see there is a `minimumRenderScale` setting that I can force to `1` to prevent downscaling at the time of capture. So that workaround is fine for my needs.

**Comment by elalish** [comment]
Perfect, yes I should have mentioned that.
