### ISSUE TITLE
Transparency issue when compress/ optimize the baseColor png file

### ISSUE THREAD

**Issue by vanlicht** [google/model-viewer#1530]
### Description

The glb assets with transparency in the baseColor map as a compressed/ optimized png. The same asset displayed correctly in BabylonJS Sandbox player, donmccurdy's ThreeJS player, but not in the Model Viewer or, the ThreeJS online editor.

### Version
The test is done online https://modelviewer.dev/editor/ as of September 11th, 2020.

### Browser Affected

- [v ] Chrome

### OS
- [v] Windows

**Comment by elalish** [comment]
I believe this is the same issue, and it seems to be fixed now: https://github.com/mrdoob/three.js/issues/20362

I'll close this when we update to the next version of three.js, which should be before our next release.

**Comment by vanlicht** [comment]
That's great thank you!

**Comment by elalish** [comment]
Closed by #1577
