### ISSUE TITLE
Autoplay All Animation

### ISSUE THREAD

**Issue by FaradayNova** [google/model-viewer#1531]
### Description

I have done significant research to find a similar answer, and have found questions close, but either not entirely relevant or not fully pertaining to my exact question

I am exporting from Blender's gltf glb exporter. and have 144 individual objects and 144 nla tracks. 1 track per each
in <modelviewer> i am able to call upon individual animation tracks, and switch between them, including cross fade between animation tracks. This is not what I need

I would like to know if there is a way to play all NLA tracks simultaneously with a single auto play command?

https://gltf-viewer.donmccurdy.com/ had the desired result,(animations - "Play All")

I can't seem to find code or attributes that correlate with the same "Play All" function on https://gltf-viewer.donmccurdy.com/

### Version
- model-viewer: v1.2.1

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
Indeed, model-viewer's API only plays a single animation at a time, cross-fading between. This was simply because animation hasn't been getting a lot of use and this was a simple API. It may be time to expand that now. I'd like to get a bit more information about use cases and API ideas to figure out what would be best to add next. I don't really want to expose all of the three.js animation API, as it's pretty complex.

Also, if you just want to "play all", why not pack them all into a single animation?

**Comment by mithru** [comment]
This is something my team is also exploring. Literally last week, we decided to use three.js over MV directly for this specific use case:  animation of product interacting with a secondary object which is also animated - the secondary object changes while the product stays. Our 3D team found it simpler to animate the objects individually so it can be mixed and matched with other similar 3D objects. 

Right now, we're just using a static model for glb, and for iOS AR we're using a .reality file that includes the animation. We weren't happy with the inconsistency, so switching to threejs.

**Comment by elalish** [comment]
@mithru could you share a link so I can see your use case? Our animation support certainly needs work. Also, PRs are welcome if you have an idea for what would be helpful to expose. Should be fairly easy if you're already familiar with three's API.

**Comment by mithru** [comment]
Got into trouble last time I shared an ongoing project. Sharing something similar instead. Hopefully this explains things better. My apologies if not. 

https://mithru.github.io/AR-test/model-viewer-template/ (please excuse the weird scale here)

In the link above, there are 2 characters in a single loaded GLB. Both of them have separate animations (only one plays on the link I sent, but if you download and open the GLB, you'll see them both animate). The 2 animations could be packaged into a single animation, but that starts to get messy when you want to create multiple combinations of characters with the same choreographed animation. It's not a big lift for smaller sets or one-off animations, but the moment we hit a few combinations, every iteration / design review will have us redo all the GLBs. 

Allowing all animations in the GLB to play at one go would be a quick fix for this particular case. 

What we're building involves a few other things (like mirror materials) that I'm not sure makes sense for MV, so we'll use threejs regardless for this particular project. 

However, I have had a few times in the past where I had to ask my 3D team to send me GLBs with packaged animation. They were small projects so wasn't a big deal to send it back really.

**Comment by elalish** [comment]
@mithru Thanks, that makes sense.
