### ISSUE TITLE
Example of threejs integration

### ISSUE THREAD

**Issue by ThomasRutzer** [google/model-viewer#1533]
Hi, would be super nice if you could provide a simple example of whats the best way to use modelviewer together with threejs. I can only find the src at `src/three-components`.

Thank you very much!

**Comment by elalish** [comment]
I'm not sure what you mean. model-viewer is based on three.js, so they are integrated. Are you saying you want access to the underlying three.js API? That's outside the scope of what we support, though the scene-graph API is going a little in that direction. Is there a specific feature you're looking for? This being JavaScript, there are ways to hack down to that layer, but I will make absolutely no promises about how much that will get broken in future releases.

**Comment by ThomasRutzer** [comment]
Ah ok, from what I've been reading, I didn't realize that it is integrating threejs, but sure the [package.json](https://github.com/google/model-viewer/blob/master/packages/model-viewer/package.json) explains.
Thanks for your clarification, I'm closing this issue.
