### ISSUE TITLE
Texture on certain models are "washed out" it would be good to have control over metallic and roughness parameters

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1540]
### Description

It would be good to have a metallic and roughness parameters as options to be changed. Certain models look soft and less reflective as compared to other viewers like Babylon. 

#### Screenshots

Babylon on Safari 

<img width="579" alt="Screen Shot 2020-09-15 at 4 51 58 PM" src="https://user-images.githubusercontent.com/70779749/93276187-c6fd2500-f773-11ea-98b6-b02908390f6e.png">

ModelViewer on Safari
<img width="655" alt="Screen Shot 2020-09-15 at 4 52 25 PM" src="https://user-images.githubusercontent.com/70779749/93276208-d7150480-f773-11ea-8cbe-0ea09aa34b04.png">

### Version
Latest version
- model-viewer: v1.3.0

### Browser Affected

- [ Yes] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ Yes] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ Yes] MacOS
- [ Yes] Windows

**Comment by elalish** [comment]
We do! Check out the second example here: https://modelviewer.dev/examples/scene-graph.html

Looking at our [fidelity comparisons](https://modelviewer.dev/fidelity/) generally babylon and model-viewer are in pretty good agreement. This difference may have to do with using different lighting. Also, there are some tricks to setting up bablylon's lighting well.

**Comment by dhruvadhia1** [comment]
Thanks for quick reply, I will check out scene-graph. As far as the lighting is concerned, we are using the exact same HDR map.
