### ISSUE TITLE
Feature request/ Question: Rotate Skybox/Environment-image/Environment Map

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1541]
### Description

It would be great to press a key and then use mouse to rotate the skybox/environment-image. Normally when user drags, it rotates the model. But rotating environment lighting can be very handy like in sketchfab.com
#### Live Demo
refer sketchfab.com  example
https://sketchfab.com/3d-models/grey-jeep-a109cae45a554766badad465279ae17a

pressing alt + left click can rotate environment image/map
### Version
latest version of model viewer

### Browser Affected

- [ Y] Chrome
- [ ] Edge
- [ Y] Firefox
- [ ] IE
- [ Y] Safari

### OS

- [ ] Android
- [ ] iOS
- [ Y] Linux
- [ Y] MacOS
- [ Y] Windows

**Comment by elalish** [comment]
Good idea; I don't want to make the default UX more complex since that affects everyone. We have a `resetTurntableRotation()` function now that sets the autorotation turntable back to zero (which turns the model relative to the skybox). I could update that to take an argument and you could use your own event listeners to check `getCameraOrbit()` and set the turntable to the `-theta` value to keep it still. Does that sound reasonable?

**Comment by dhruvadhia1** [comment]
Thanks for the suggestion and I was hunting through issues to see if I can find something, I did find this which is about background rotation 

  <script>
	  const modelViewer = document.querySelector("model-viewer");
	  
	  const updateOrbit = () => {
	    const orbit = modelViewer.getCameraOrbit();
	    modelViewer.cameraOrbit = `${orbit.theta + 0.01}rad ${orbit.phi}rad ${orbit.radius}m`;
	    modelViewer.jumpCameraToGoal();
	    requestAnimationFrame(() => updateOrbit());
	  };
	  updateOrbit();
</script>

But I am getting this error
Uncaught TypeError: modelViewer.getCameraOrbit is not a function

and yes it would be great to have it as a part of API and an example code will be much appreciated.

**Comment by elalish** [comment]
Hmm, what version of model-viewer are you using? It's odd that it would not find that function. Perhaps it hasn't upgraded yet? You might need `<script type="module">` to get it to load after our library has.

**Comment by dhruvadhia1** [comment]
Ok, thanks, 

I got some result here,

https://thecela.com/configurator/koi/GLTF/

however, I see that the shoe is also rotating as the camera is orbiting around the shoe. What I was thinking more was that model remains static and it's only the environment-image that is rotating.

**Comment by elalish** [comment]
Yeah, so it looks like all you're missing is for us to expose `resetTurntableRotation(theta)` and you should be able to achieve what you want. Would you be up for making a small PR to add that?

**Comment by dhruvadhia1** [comment]
small PR? sorry I didnt get that.

**Comment by elalish** [comment]
Pull Request; would you like to contribute this feature to model-viewer?

**Comment by dhruvadhia1** [comment]
Oh I see, to be honest I am bit new to github, i am more old school on svn. If you mean committing the code that I commented above then I am more than happy for you to be using that code. Otherwise I can probably make a pull request, but you will have show me that last bit on resetTurntableRotation(theta).

Thanks

**Comment by elalish** [comment]
It's okay, I'll do it. Just looking to entice contributors :)

**Comment by dhruvadhia1** [comment]
I spent an hour just looking through this whole idea of pull request and do look forward to contribute various other ideas that I have applied on three js library. I think I have some idea now. And I see you have separate branch for it. Looking forward to what you have got so far. Cheers and much thanks.

**Comment by dhruvadhia1** [comment]
Also I see that you have committed some code, will I be able to access it through latest release

`<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>`

also is this how we are looking for the implementation for rotating environment image? 

` const updateOrbit = () => {
	    const orbit = modelViewer.getCameraOrbit();
	    modelViewer.cameraOrbit = `${orbit.theta + 0.01}rad ${orbit.phi}rad ${orbit.radius}m`;
	    modelViewer.jumpCameraToGoal();
	    requestAnimationFrame(() => updateOrbit());
	  };
	  
	  updateOrbit();
	  modelViewer.resetTurntableRotation();`

**Comment by elalish** [comment]
Yes, once it is released, which will be v1.3 in a month or so. If you want to test it early you can build it locally. I think you'll want `modelViewer.resetTurntableRotation(-1 * orbit.theta);` inside your `updateOrbit` function in order to cancel out the environment rotation.

**Comment by dhruvadhia1** [comment]
ok, btw is this only applicable when auto-rotate is given as one of the parameters in model viewer?

**Comment by elalish** [comment]
No, it's independent.
