### ISSUE TITLE
CastShadow and ReceiveShadow

### ISSUE THREAD

**Issue by deers** [google/model-viewer#1545]
### Description

Hi, I have this cone and sphere object as a model, and I want to show sphere shadow on top the cone object, I try to change castShadow and receiveShadow value to true, but it seem doesn't work. Is a little bit weird when you see the whole model shadow drop on the floor but the shadow from the sphere doesn't show on the cone object.

![cs](https://user-images.githubusercontent.com/814376/93430300-0dc65880-f8f5-11ea-9b7f-b926df2271dc.png)

#### Live Demo

https://glitch.com/~cast-receive-shadow

### Version

- model-viewer: https://unpkg.com/@google/model-viewer/dist/model-viewer.js

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Yes, our shadows are very simple currently. This is partly to keep performance good on the broadest range of devices as shadows can get quite complicated and costly. A cheaper and generally better-looking alternative is to bake internal shadows like this into the occlusion channel of the glTF. I don't want to complicate our shadow API as it will be difficult to explain to non-experts.

**Comment by toknpp** [comment]
> _our shadows are very simple currently_

Has this changed? Or is there still no way to render "internal" shadows (even simple hard ones)?
