### ISSUE TITLE
Pan example does not behave as expected after camera rotation

### ISSUE THREAD

**Issue by aviggiano** [google/model-viewer#1552]
### Description

First of all, thank you very much for #1547, it will be very helpful.
I've noticed however that the [pan behavior](https://modelviewer.dev/examples/staging-and-camera-control.html#demo-container-7) is buggy when we rotate the camera. I've also added a video of the Sketchfab viewer showing the expected behavior.

#### Live Demo

- [@google/model-viewer](https://photos.app.goo.gl/uC4gp18yHaxhsMbDA)
- [Sketchfab](https://photos.app.goo.gl/8eba2wVPfQ1TW1qe8)

### Version
- model-viewer: v1.2.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Good call, I've got a repro. Thought I fixed that, but apparently not quite.
