### ISSUE TITLE
multi-model interaction?how can I do

### ISSUE THREAD

**Issue by AIRS-EXR** [google/model-viewer#1554]
### Description

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

- model-viewer: vX.X.X

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

**Comment by sercandemirtas** [comment]
What do you mean by "multi-model interaction" ? Can you explain with details

**Comment by AIRS-EXR** [comment]
like one scene have desk, TV and chairs, how can I use model-viewer to interact with each of them in reality?

**Comment by AIRS-EXR** [comment]
> What do you mean by "multi-model interaction" ? Can you explain with details

like one scene have desk, TV and chairs, how can I use model-viewer to interact with each of them in reality?

**Comment by elalish** [comment]
We don't have multi-model support in model-viewer yet. Would you want users to be able to move the individual models around in the 3D view as well, or only in AR?

**Comment by david-rhodes** [comment]
Sorry to necro this ticket @elalish but I noticed it was only recently closed (and I just found it). 

Are you aware of any plans to support multiple models in the future? I could see this being useful in trying to build more efficient configurators with model-viewer. For example, assets/products could be constructed from multiple components or modules (a TV stand that has base and shelf separated).

I can create a separate ticket for this as a feature request, but I wanted to know if this was closed for a specific reason, first (not in the plans).

Thank you!

**Comment by elalish** [comment]
Yes, we do plan to, and there are several related tickets still open. This was just closed as part of a general clean up. The first step will be making the scene-graph editable via script. Building multi-model placement UX in WebXR will be considerably more work. Contributions welcome, especially in the form of UX mocks.

**Comment by david-rhodes** [comment]
Thanks @elalish. I definitely think scene-graph API first is the right approach!
