### ISSUE TITLE
Video textures on Model Viewer

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1555]
Hello friends,

Is it possible to add video texture to model viewer?

Im using blender to export glb. I added video texture to my object and added simple animations to keyframes. When I played animation on Blender video texture and animation works well. On model viewer animations works but texture of object just shows first frame. Do I have to use specific video format or Model Viewer does not support video textures ?

**Comment by elalish** [comment]
No, video textures are not part of the glTF spec, and hence are not supported by us. You could put this feature request to the Khronos 3D formats working group.
