### ISSUE TITLE
Photo/Video button not appearing on Andoird

### ISSUE THREAD

**Issue by sas1ni69** [google/model-viewer#1556]
### Description

When activating the AR on an Android browser, it does not prompt the photo/video taking button like it does on iOS.

It works on iOS but no luck on Android. It loads the asset correctly and it can be viewed with the AR layout but just does not prompt the camera button.

#### Live Demo
To view: https://iced-rambunctious-lifter.glitch.me/

https://glitch.com/edit/#!/iced-rambunctious-lifter?path=index.html%3A12%3A24

### Version
Tried on multiple versions but using latest now:
https://unpkg.com/@google/model-viewer/dist/model-viewer.js
https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Yes, this is currently a limitation of webXR that we're working to resolve (the ability to record sessions). In the meanwhile, you can use `ar-modes="scene-viewer quick-look webxr"` if this functionality it important to you, as the native SceneViewer app does have this functionality on Android. However, you will loose any DOM customization you've applied.

**Comment by sas1ni69** [comment]
Thank you so much @elalish changing the order worked for me. I’ll close this issue to reduce clutter but please feel free to reopen if you think it’s necessary to keep it open.
