### ISSUE TITLE
Interaction prompt for moving the phone until the model is placed when using webxr mode of <model-viewer>

### ISSUE THREAD

**Issue by v-prgmr** [google/model-viewer#1562]
### Description

When using the scene-viewer mode for deploying the content in AR, a animated-prompt which suggests the user to move the phone pops up until the plane is identified for placing the AR model. How can the same animated-prompt be activated while using the "webxr" mode of model-viewer

#### Live Demo
![WhatsApp Image 2020-09-24 at 2 18 02 PM](https://user-images.githubusercontent.com/39503553/94144188-1e387f00-fe71-11ea-8159-900dba8b3b91.jpeg)

### Version
model-viewer: v1.0

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
In webXR this can be done any way you prefer using standard HTML. See the [webXR demo](https://modelviewer.dev/examples/webxr.html) and look for `ar-prompt`. The key is turning it on and off using CSS based on the `ar-status` attribute.
