### ISSUE TITLE
Get animation list

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1573]
Question:

### Description

It would be great to get animation list for each model with lets say a method. 

#### Live Demo
There is such functionality on editor but I couldn't find much documentation about getting list of animations for particular model on the website. 

https://modelviewer.dev/editor/

**Comment by elalish** [comment]
Yes, in fact we just noticed this was missing from our docs as well. We're in the process of doing a major update on them, so this should be fixed soon. Meanwhile, there is a readonly property `availableAnimations` that returns an array of strings that can be used for `animation-name`.

**Comment by dhruvadhia1** [comment]
Thank you.

**Comment by dhruvadhia1** [comment]
@elalish I did give this a quick try. 

```
const modelViewer = document.querySelector("model-viewer");
console.log(modelViewer.availableAnimations);
```

and I get some huge list, but hard to find where the names for the animations are. I am using your sample RobotExpression.glb file just to test it.

**Comment by elalish** [comment]
It has quite a few animations, I think that's the list you're looking at. Did you try selecting any of them?

**Comment by dhruvadhia1** [comment]
![Screen Shot 2020-09-30 at 10 26 54 AM](https://user-images.githubusercontent.com/70779749/94719049-7820c500-0307-11eb-932e-a9830b40e790.png)

this is what I see. here is the example link. https://thecela.com/configurator/experiment/

if you inspect the console, you will see what I am trying to mention through that screenshot.

**Comment by elalish** [comment]
I think that's just a quirk of `console.log()`, since `availableAnimations` is a getter function. If you just open dev tools, select your model-viewer element and type `$0.availableAnimations`, it works just fine. Would probably work in the log if you saved the result to a const and logged that instead.

**Comment by dhruvadhia1** [comment]
@elalish that seems to be throwing error as $0 is not defined. And with a bit googling I found others facing similar problems as that is a special variable reserved for console only? any direction from here would help. Thanks

**Comment by dhruvadhia1** [comment]
Also if you mean that this code 

```
const modelViewer = document.querySelector("model-viewer");
console.log(modelViewer.availableAnimations);
```

does not work only in console is true, but neither this or 

$0 variable works in the javascript if you meant that. Tried number of different variations including storing that $0 variable in the n, but no luck so far. 

Let me know if there is anything I am missing. Anyways looking forward to the updated docs. 

Thanks

**Comment by elalish** [comment]
$0 works once you have actually selected an element in dev tools. Meanwhile, from your JS, the problem is you're not logging what you think you're logging. Try:
```
const names = document.querySelector("model-viewer").availableAnimations;
console.log(names);
```

**Comment by elalish** [comment]
Oh, right. You need to wait for the model to load in order to query it. Try:
```
const modelViewer = document.querySelector("model-viewer");
modelViewer.addEventListener('load',()=>{
      const names = modelViewer.availableAnimations;
      console.log(names);
    });
```

**Comment by dhruvadhia1** [comment]
Perfect @elalish much thanks.
