### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by Geometrified** [google/model-viewer#1582]

**Comment by Geometrified** [comment]
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Model Viewer</title>
  <script src="https://unpkg.com/@webcomponents/webcomponentsjs@2.1.3/webcomponents-loader.js"></script>
  <script src="https://unpkg.com/intersection-observer@0.5.1/intersection-observer.js"></script>
  <script src="https://unpkg.com/resize-observer-polyfill@1.5.0/dist/ResizeObserver.js"></script>
  <script src="https://unpkg.com/focus-visible@5.0.2/dist/focus-visible.js" defer></script>
  <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
  <script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>
  <style>
    model-viewer{
    width: 100%;
    height: 500px;
    margin: 0 auto;
    }
  </style>
  <style>
  model-viewer#reveal {
    --poster-color: transparent;
  }
    </style>
</head>
<body>                                                                                      
  <model-viewer id="reveal"
                loading="lazy"
                src="https://cdn.glitch.com/fc249e81-c87f-4f2e-9750-38acf502de81%2FPillowSubstance.glb?v=1596538135520"
                ios-src="https://cdn.glitch.com/fc249e81-c87f-4f2e-9750-38acf502de81%2Fpillow%20.usdz?v=1596538118816"
                quick-look-browsers="safari chrome"
                shadow-intensity="1"
                exposure="0.71"
                alt="Model 3D poduszki"
                camera-controls
                auto-rotate ar
                title="Poduszka">
    </model-viewer>                                           
    <script type="module"
      src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js">
  </script>
  <script nomodule
      src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js">
  </script>
</body>
</html>

**Comment by elalish** [comment]
What versions of iOS are you using? It seems like there has been some regression in iOS 14 Safari that I'm looking into. Also, can you post screenshots of blurry vs not? And can you test a possible workaround by adding: `customElements.get("model-viewer").minimumRenderScale = 1`. If that fixes it, then I'll know roughly where the problem is.

**Comment by Geometrified** [comment]
> What versions of iOS are you using? It seems like there has been some regression in iOS 14 Safari that I'm looking into. Also, can you post screenshots of blurry vs not? And can you test a possible workaround by adding: `customElements.get("model-viewer").minimumRenderScale = 1`. If that fixes it, then I'll know roughly where the problem is.

Yesterday I had some older iOS version from at least 4 months ago, but I'm not sure which one was it. Today I updated the system to 14.0.1 and the same blurr occurs. It's not that bad although I wish models loaded in maximum quality like on Android. SS below.
![blur](https://user-images.githubusercontent.com/69237537/94905227-cf0bd300-049c-11eb-8aee-1217583777fa.jpg)

![after clicking once](https://user-images.githubusercontent.com/69237537/94905271-e3e86680-049c-11eb-9122-5a01d0d7b310.jpg)

**Comment by Geometrified** [comment]
It looks much worse when models are zoomed out at deafult load.

**Comment by Geometrified** [comment]
**But I think it has to be my code because other models from different sites as well as Astronaut for the original <model viewer> loads in full quality with no problem.**
