### ISSUE TITLE
Playing animation only once

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1584]
### Description

Playing animation only once after clicking play for example instead of constant looping. One idea I had is that if I can get total duration of animation then too I can stop animation from playing once it reaches the end. But it would also be good to have method like playOnce().

#### Live Demo

https://glitch.com/edit/#!/model-viewer

https://thecela.com/configurator/TEo1Y29KUzBuSjlocVRJbXFOPT0=/QVF0PQ==/cDJBdW90PT0=

### Version

Latest version

### Browser Affected

All
### OS

All

**Comment by dhruvadhia1** [comment]
@elalish I have a questions regarding events. Do we have something like 'timeudpate' event like <audio> tag? In that way if I can get the value of currentTime in realtime then it is possible to play only once. When current time arrives at 0 again, then we can pause the animation and the current time can be reset again.

**Comment by elalish** [comment]
No, for now your best bet is `setTimeout()`.

**Comment by dhruvadhia1** [comment]
Here is a way i got it working, if others are looking for solutions. 

```
 // non looping animation
	  const modelViewer = document.querySelector("model-viewer");
	  modelViewer.animationName = 'All Animations';
	  var extremelySmallIntervalTime = 0.05;
	  var j=0;
	  
	  setInterval(function(){ 
       
		  //console.log(modelViewer.currentTime);	
		  if(modelViewer.currentTime > 0 && modelViewer.currentTime < extremelySmallIntervalTime)
		  {
			   
			  if ( j > 0 )
 			  {
 				  modelViewer.pause();
 				  modelViewer.currentTime = 0;
 			  }
			   
			   j++;
			   console.log(j);
		  }
  	  }, extremelySmallIntervalTime*1000);
```

Its not perfect. but works.

**Comment by sercandemirtas** [comment]
@dhruvadhia1 hey man. I added this codes to js but It is not working. Animation still in loop. Any other solutions ?

**Comment by elalish** [comment]
How about something like:

```
const animationLength = 1000; // ms
const modelViewer = document.querySelector("#your-id");
modelViewer.play();
self.setTimeout(()=>{modelViewer.pause();}, animationLength);
```

**Comment by dhruvadhia1** [comment]
@elalish , this code will pause any given animation after 1 second. However, the length of the animation could vary. 

@sercandemirtas 

try this code 


```
modelViewer.play();

  var extremelySmallIntervalTime = 0.05;
  var j=0;
  const interval = setInterval(function(){
  console.log(modelViewer.currentTime);
  if(modelViewer.currentTime > 0 && modelViewer.currentTime < (extremelySmallIntervalTime - 0.01))
  { ++j;
  console.log(j);
  if ( j > 0 ){
  modelViewer.pause();
  //modelViewer.currentTime = 0;
  j = 0;
  clearInterval(interval);
  }
   
  }else if(modelViewer.currentTime == 0)
  {
  modelViewer.play();
  }
  }, extremelySmallIntervalTime*1000);
```

**Comment by sercandemirtas** [comment]
@elalish @dhruvadhia1 I tried both of your codes but animation still  in loop maybe Im doing sth wrong or there is problem with codes. Did you try this codes on your project? If you dont mind can I see project?

**Comment by dhruvadhia1** [comment]
try this link

https://thecela.com/configurator/TEo1Y29GMTBNS0EwWUdWPQ==/QVF0PQ==/cDJBdW90PT0=#

when you click on different hotspots, it will play animation either in loop or once.

**Comment by archeo56** [comment]
for me a more easy way is to use setTimeout
for exemple :

`<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script> 

<div style ="height: 50px; width: 50px; border-style : outset; border-width:1px;border-radius : 10px;box-shadow :3px 3px 3px #969696 ;padding:1px 10px 0px 10px;cursor:pointer;" onclick="play_to_end()">Try it</div>
<model-viewer id="homme"  camera-controls  style="width: 400px; height: 400px;" interaction-prompt="none" src="{root_url}/uploads/images/histoire/homme/cranes/scene(20).glb" alt="">

</model-viewer>

<script>
function play_to_end (){
//play to end or rewind if animation is at end//
const modelViewer = document.querySelector('#homme');
modelViewer.play();
t=modelViewer.duration;

t=t*1000/2 // because duration is in second and time to play and rewind//
setTimeout(stop, t)
}
function stop(){
const modelViewer = document.querySelector('#homme');
modelViewer.pause();
}
</script>`

you can try [http://www.evolution-biologique.org/test-anim.html](url)

**Comment by archeo56** [comment]
I use a "setTimeout" to play and stop at the end

```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script> 

<div style ="height: 50px; width: 50px; border-style : outset; border-width:1px;border-radius : 10px;box-shadow :3px 3px 3px #969696 ;padding:1px 10px 0px 10px;cursor:pointer;" onclick="play_to_end()">Try it</div>

<model-viewer id="homme"  camera-controls  style="width: 400px; height: 400px;" interaction-prompt="none" src="{root_url}/uploads/images/histoire/homme/cranes/scene(20).glb" alt="">

</model-viewer>

<script>
function play_to_end (){
//play to end or rewind if animation is at end//
	const modelViewer = document.querySelector('#homme');
	modelViewer.play();
	t=modelViewer.duration;
	t=t*1000/2 ;// because duration is in second and time to play and rewind//
	setTimeout(stop, t);
}
function stop(){
const modelViewer = document.querySelector('#homme');
modelViewer.pause();
}
</script>
```

you can see the result here [http://www.evolution-biologique.org/test-anim.html](url)
