### ISSUE TITLE
How to play a background sound in scene viewer? 

### ISSUE THREAD

**Issue by Gaurav-chopra** [google/model-viewer#1593]
I tried using the sound attribute and sound URL but it deosnt work. Has anyone tried or was successful in using background sound in scene?

**Comment by omerts** [comment]
@Gaurav-chopra Did you manage to play sound?

**Comment by AbejaCruz** [comment]
@Gaurav-chopra could you use the sound attribute?

**Comment by Kite54** [comment]
could somebody tell me how it works?
