### ISSUE TITLE
Is there any way that i could show dimensions of 3d Model

### ISSUE THREAD

**Issue by balrajg** [google/model-viewer#1599]
I wanted to show dimensions of 3d models, Is there any method where i can access size of the model.

**Comment by elalish** [comment]
You mean a bounding box size? We calculate that internally, so it wouldn't be hard to expose, but it's not currently part of our API.

**Comment by balrajg** [comment]
@elalish yes i mean bounding box size, it will be very helpful if we get it via api.

**Comment by buddy90210** [comment]
>so it wouldn't be hard to expose

Can you say how?

**Comment by elalish** [comment]
@buddy90210 It's a member of the Model.ts class. You could put a getter on loading.ts to return it as a `Vector3D`, which we use for the `getCameraTarget()` method, for instance. Would you like to make a PR?

**Comment by balrajg** [comment]
@elalish yes please, can you make a PR??
