### ISSUE TITLE
Is it possible to change the color of meshes?

### ISSUE THREAD

**Issue by likhita-biyyala** [google/model-viewer#1600]
Hi,
Using the model-viewer I have loaded a 3d-model, in that i am looking for way that how can I apply colour to particular mesh of the model.
For example,If i want to apply colour to head part of the robot, is it possible to do in model-viewer?
3D-Model mesh names:[FootL,LowerLegL,LegL,LowerLegR,LegR,Head_0Head_1,Head_2,ArmL,ShoulderL,ArmR,ShoulderR,Torso_0,Torso_1,FootR,
Hand.R_0,Hand.R_1,Hand.L_0,Hand.L_1]

I am trying to achieve similiar to this image (applyling colour meshes Ex: head,torso,arm etc).
<img width="551" alt="robot" src="https://user-images.githubusercontent.com/55802411/95063695-50bd6400-071c-11eb-8daa-698ef69f55b5.png">

Here is my[glitch-code](https://glitch.com/edit/#!/regular-billowy-page?path=index.html%3A93%3A9)
when i tried to apply color,this is how it was coming
<img width="546" alt="mycode" src="https://user-images.githubusercontent.com/55802411/95065111-3ab0a300-071e-11eb-91ea-32f1f4046a3b.png">

Is there any reference document that i can go through?

**Comment by elalish** [comment]
In glTF colors are associated with materials, not meshes. This model has only three materials, and they are applied across several meshes. You can change them using https://modelviewer.dev/editor/ and these can also be done via the scene-graph API in JS. For anything more complex, you'll need a fully-featured editor like Blender.

**Comment by likhita-biyyala** [comment]
Thank you @elalish 
my issue is solved.
