### ISSUE TITLE
All hotspots around the object show on load

### ISSUE THREAD

**Issue by AndresMercado** [google/model-viewer#1601]
Hello friends, this is Andrés from Lima, Peru. I am having a problem with the hotspots, they all show up when the object loads, even the hotspots behind the object, they only anchor in place once the object is manually rotated. Can´t find a way to make the hotspots in the back hide. Please help!

http://peruvirtualtour.com/museo-larco/copa-lambayeque/copa-lambayeque.html

<model-viewer 
        ar
        ar-modes="scene-viewer quick-look webxr"
        src="copa-lambayeque.gltf"
        ios-src="copa-lambayeque.usdz"
        alt="Copa Lambayeque"
        poster=""
        camera-orbit="0deg 85.55deg 2.5m"
        loading="eager"
        shadow-intensity=".4"
        shadow-softness="1" 
        exposure="1"
        stage-light-intensity="2" 
        environment-intensity="1"
        camera-controls
        auto-rotate="true"
        auto-rotate-delay="5000"
        quick-look-browsers="safari chrome"
        id="modelViewer"
        class="modelViewer"
        load="showPoint()">

        
        <button slot="hotspot-1" class="hotspot radius hide"
            data-position="0.0012480082366329534m 0.04523582552365768m 0.06857084629098123m"
            data-normal="0.02273211681219893m -0.7138027707619056m 0.6999777534449672m">
            <div class="annotation">
                <h3 class="titulo">La Diosa Madre de Peces y Crustáceos</h3>
                <audio controls style="max-width: 200px;">
                    <source src="DiosaMadrePecesCrustaceos.mp3" type="audio/mpeg">
                    <source src="DiosaMadrePecesCrustaceos.ogg" type="audio/ogg">
                </audio>
                <img class="imagen" src="DiosaPeces.jpg" alt="La Diosa Madre de Peces y Crustáceos">
            </div>
        </button>

        
        <button slot="hotspot-2" class="hotspot radius hide"
            data-position="0.0028474212293774686m 0.030516736152702617m -0.048608037305169605m"
            data-normal="0.046121708312746125m -0.8239660879675734m -0.5647589520332784m">
            <div class="annotation">
                <h3 class="titulo">El Dios Spondylus</h3>
                <audio controls style="max-width:200px;">
                    <source src="DiosSpondylus.mp3" type="audio/mpeg">
                    <source src="DiosSpondylus.ogg" type="audio/ogg">
                </audio>
                <img class="imagen" src="DiosSpondylus.jpg" alt="El Dios Spondylus">
            </div>
        </button>

        
        <button slot="hotspot-3" class="hotspot radius hide"
            data-position="-0.05610063827609485m 0.05683598255416794m 0.05518452882441566m"
            data-normal="-0.612569729403988m -0.5367251674984365m 0.5802451388781299m">
            <div class="annotation">
                <h3 class="titulo">El Dios de los Cultivos</h3>
                <audio controls style="max-width: 200px;">
                    <source src="DiosCultivos.mp3" type="audio/mpeg">
                    <source src="DiosCultivos.ogg" type="audio/ogg">
                </audio>
                <img class="imagen" src="DiosCultivos.jpg" alt="El Dios de los Cultivos">
            </div>
        </button>

        
        <button slot="hotspot-4" class="hotspot radius hide"
            data-position="0.07026784614015591m 0.047108326333810194m -0.00527357657543363m"
            data-normal="0.6970975686126154m -0.7147890628794069m -0.05596048089821367m">
            <div class="annotation">
                <h3 class="titulo">El Personaje de los Cuatro Rostros</h3>
                <audio controls style="max-width: 200px;">
                    <source src="Personaje4Rostros.mp3" type="audio/mpeg">
                    <source src="Personaje4Rostros.ogg" type="audio/ogg">
                </audio>
                <img class="imagen" src="Personaje4Rostros.jpg" alt="El Personaje de los Cuatro Rostros">
            </div>
        </button>

        
        <button slot="hotspot-5" class="hotspot radius hide"
            data-position="-0.02537735087705653m 0.010026686031035861m -0.008044960417762662m"
            data-normal="-0.8556850976985638m 0.4362630579566064m -0.27834790791193353m">
            <div class="annotation">
                <h3 class="titulo">La Copa Lambayeque</h3>
                <p>¿Quieres colorear esta escena mitológica de la Cultura Lambayeque? <a href="Museo Larco_Copa Lambayeque para colorear.pdf"> Dale click a descargar
                    <img class="imagen" src="Museo-Larco-Copa-Lambayeque.jpg" alt="Copa Lambayeque"></a>
                </p>
                
            </div>
        </button>

    </model-viewer>

**Comment by elalish** [comment]
I don't see any hotspots in your link; is it up to date? Also, do you have two questions or one? It might be helpful if you could include screenshots to show exactly what you mean.

**Comment by AndresMercado** [comment]
Sorry just was updating the page, now it has the hotspots. Thank you so mucho for your helpt

**Comment by AndresMercado** [comment]
![image](https://user-images.githubusercontent.com/20938161/95116163-37acb700-070c-11eb-97e9-44cf73eb83c9.png)

**Comment by elalish** [comment]
Thank you for the clarification, this is in fact a bug. It looks like hotspots are not being hidden when they are initially facing away from the camera. I'll get this fixed for v1.3.

**Comment by AndresMercado** [comment]
Thaaaankkk you so much Elalish, it is amazing to get answers right away from the development team. Next time I am in the area I will bring treats from Peru. Cheers!
