### ISSUE TITLE
3D view instead of AR

### ISSUE THREAD

**Issue by Geometrified** [google/model-viewer#1606]
Until yesterday every time I pressed AR button after loading models (embedded on my website) on my phone (Android) it started the camera and AR function. 

Today when I press AR button, it loads me to 3D view of my model with possibility to "Open" a site, after pressing "Open" it loads me to Glitch where I can press AR button again that finally loads the camera and AR function. Did I messed up my code? I really don't know why it started to do so. Everything works fine with AR button on iOS.
**I just want it to be like before - after loading embedded model AR button starts the camera, without this additional clicks and websites.**  **What should I do?**

**Comment by Geometrified** [comment]
**I've just checked it on my friend's phone and AR loads camera as it should. I'm really confused why it stopped working properly on my device.**

**Comment by elalish** [comment]
@Geometrified We've noticed some bugs around AR on Android 11; is there a chance your phone has upgraded and your friend's has not? Also, you may want to experiment with `ar-modes`: we default to webxr, but fall back to scene-viewer, unless you specify just one or the other. If you can get back to me with some more specifics of the different behaviors you're seeing, I'll be able to give a more complete answer.
