### ISSUE TITLE
Depth API prevents use of content with floor-level features/detail

### ISSUE THREAD

**Issue by 60days** [google/model-viewer#1618]
### Description

This is a Scene Viewer bug, but I cant find another bug reporting area for that specific project.

When viewing content that rests on the floor on devices with Depth API support, the objects will phase & flicker through the floor plane due to inaccuracies in depth estimation.

![IMG_20201009_104021](https://user-images.githubusercontent.com/2927295/95529562-f1669900-0a26-11eb-9fee-7fa608bb007e.jpg)
![IMG_20201001_154629](https://user-images.githubusercontent.com/2927295/95529572-f4fa2000-0a26-11eb-853c-37dbe572ffb6.jpg)

#### Live Demo

https://glitch.com/edit/#!/join/686693d2-b5f1-468c-8dbb-8fd595e3496c

### Version

- model-viewer: vX.X.X (all)

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by 60days** [comment]
As far as solutions - I feel like replacing tracked planes' depth information with definite values would be possible, but massively complex once you start introducing more than the floor (lowest tracked plane).

A quick fix would be to have the option to disabled depth API occlusion at start (since the user can do the same via the UI, it shouldn't introduce too many side-effects specific to the toggle).

**Comment by elalish** [comment]
Indeed, the depth is not particularly accurate, which is why Scene-viewer fades out with depth. Have you tried webXR mode? It doesn't do depth occlusion. I'd also be interested in knowing what makes you choose one mode over the other. @tpsiaki regarding the depth feedback for scene-viewer.

**Comment by 60days** [comment]
Hi elalish - in my particular use-case I can't use model-viewer's WebXR mode as I'm generating an intent:// link via an API that needs to drop directly into the AR mode without an intermediate webpage or showing any url to the user (as its for a commercial product where the brands do not want users to see the underlying service, or to add webpages to their site). This will be reached via non-website routes like QR codes, email newsletter links etc.

In terms of preferring scene viewer in other cases:

I have tested a WebXR implementation for other use-cases when launching AR on Android from a webpage, but we've received some feedback around the rotation behaviour that's stopped us from proceeding so far - in most of our user-testing users try to use two fingers to rotate, and a single finger to drag. Since models' bounds generally fill the frame they never discover the single-finger rotation.

We've also had a case where a model file's roughness looked very different visually between scene viewer and model viewer, but that may just be a poorly prepared gltf. Unfortunately we didn't chase down the issue to confirm as we had already received the rotation feedback and decided not to proceed. I can dig up the model if it would be of use.

I suspect I'll end up on model-viewer's WebXR implementation eventually (as the end goal is a universal UX & feature-set for iOS/Android AR quicklooks, and model-viewer is extensible in a way that works for that) but we're a very new startup with a considerable roadmap between here and there!

**Comment by sercanov** [comment]
Hi all, we're also having hard times with Depth API. I wish there were a parameter to disable Depth API in Scene Viewer. In my experience, Scene Viewer were more stable than WebXR so we choose to use it.

**Comment by elalish** [comment]
@60days Thank you for the detailed feedback! I'll make sure to get two-finger rotation into webXR shortly. There is a known issue in scene-viewer where shiny objects appear too rough due to the way ARCore calculates AR lighting.

**Comment by 60days** [comment]
I'm closing this as I believe the flag ```disable_occlusion=true``` should prevent the issue

**Comment by PavelKhabusov** [comment]
You can use Depth API's Occlusion Depth Bias from demo scene SceneAPIPlacement
![image](https://github.com/google/model-viewer/assets/38973220/b90e0604-a816-4bb5-b466-d76e4377fd7f)
