### ISSUE TITLE
Javascript API to create textures

### ISSUE THREAD

**Issue by civa86** [google/model-viewer#1621]
**Description**
I load a gltf model into the viewer with a material that has only a `baseColorFactor` defined inside its `pbrMetallicRoughness` properties

**Problem**
I want to change material properties in order to load a `baseColorTexture`.
According with the [examples](https://modelviewer.dev/examples/scene-graph.html) there is an API to handle this:

```javascript
material.pbrMetallicRoughness.baseColorTexture.texture.source.setURI
```
However, In my scenario, `baseColorTexture` is null so I'll get an error if I try to manipulate its source. 
Is it possibile to create textures with javascript code? Is there some API that I'm missing?

**Comment by elalish** [comment]
This API is pretty new and is definitely missing some key features. I believe we expose the constructors so that you can call `material.pbrMetallicRoughness.baseColorTexture = new modelviewer.Texture();`, though I won't claim it's well-tested. You might also try doing this in our [editor](https://modelviewer.dev/editor/) which makes use of this API. Keep in mind that you won't be able to apply a texture unless you already have UV coordinates, which is beyond our ability to generate.

**Comment by civa86** [comment]
I can't see the Texture constructor exposed inside the modelViewer instance that I can retrieve with the `document.querySelector`.
I will investigate the editor more and I will try to figure out how the example manages this part.
No problem for the UV, I know they must be in place in the gltf model and it's not part of the viewer taking care of them.

**Comment by adamcal** [comment]
@civa86 did you get this API working? We're having the same issue. Thanks!

**Comment by civa86** [comment]
@adamcal Not yet! 
I have to say that I was just making some test on this new component while we are using other realtime viewers for our real projects right now.

I didn't found the constructor I need anywhere, did you look for the Texture constructor too? It doesn't seem to be exposed.

Eventually I didn't have some time to investigate on the [editor](https://modelviewer.dev/editor/) example to try to figure out how they managed the same scenarios. Did you take a look on that?

**Comment by adamcal** [comment]
@civa86 

I did indeed look at the editor. It can swap out the textures perfectly on the models we're using but I'm honestly not skilled enough in JS to figure out how it works. 

I'll try to dig into it more but please let me know if you ever find anything.

Thanks!

**Comment by JamesBotterill** [comment]
I'm looking for the same thing, was hoping there'd be more about it in the documentation update but sadly not.

**Comment by niwasmala** [comment]
@elalish when I try to set texture like

`material.pbrMetallicRoughness.baseColorTexture = new modelviewer.Texture();`

I get an error in console 

`TypeError: Cannot set property baseColorTexture of #<PBRMetallicRoughness> which has only a getter`

Is there any update on this?

**Comment by elalish** [comment]
My apologies; after looking through this part of the code in more detail we are in fact missing the ability to create a texture from scratch; we can only `setURI()` on existing textures. I'm working on adding this functionality.

**Comment by ermincelikovic** [comment]
Any updates on this?

**Comment by elalish** [comment]
@timmmeh added this recently; see his example: https://modelviewer.dev/examples/scenegraph/#createTexturesExample

**Comment by elalish** [comment]
out now in v1.8
