### ISSUE TITLE
Unlit Astronaut in Safari (on first load)

### ISSUE THREAD

**Issue by chrismgeorge** [google/model-viewer#1622]
### Description
Safari -> Develop -> Empty Caches -> modelviewer.dev -> Unlit astronaut
To reproduce again, Close Safari -> Develop -> Empty Caches -> Quit Safari -> Relaunch safari -> modelviewer.dev -> Unlit astronaut

### Version
modelviewer.dev

### Browser Affected
- [ ] Chrome
- [ ] Edge (untested)
- [ ] Firefox
- [ ] IE (untested)
- [x] Safari

### OS
- [ ] Android (untested)
- [ ] iOS (untested)
- [ ] Linux (untested)
- [x] MacOS
- [ ] Windows (untested)

**Comment by jrwm** [comment]
It happens to me as well. Not only on the first load, but randomly when reloading.

**Comment by elalish** [comment]
@chrismgeorge Does this still repro for you? I cannot seem to repro.

**Comment by elalish** [comment]
I believe this is the same issue as #1955, so I'm going to close in favor of that one (which has more discussion).
