### ISSUE TITLE
Not sure how to use a blob instead of a URL and open it in AR using scene-viewer or model-viewer?

### ISSUE THREAD

**Issue by vasium** [google/model-viewer#1625]
I am trying to generate a glTF file from a custom 3D glTF configurator I am building. The file is being generated and I can download it without a problem if I use link.href = URL.createObjectURL( blob ); and link.download = filename; in the save(blob) function. However, what I am trying to do is to first generate the glTF file and then open it in AR using scene-viewer or model-viewer. Unfortunately when I am calling the exportGLTF() function the browser crashes! Any ideas of what I am doing wrong?

```
 var link = document.createElement('a');
  link.style.display = 'none';

  function exportGLTF() {
    var gltfExporter = new GLTFExporter();

    gltfExporter.parse(
      scene,
      function (result) {
        var output = JSON.stringify(result, null, 2);
        saveString(output, 'scene.gltf');
      },
      options
    );
  }

  function saveString(text, filename) {
    save(new Blob([text], { type: 'application/json' }), filename);
  }

  function save(blob) {
    link.href =
      'intent://arvr.google.com/scene-viewer/1.1?file=' +
      URL.createObjectURL(blob) +
      '&mode=ar_only#Intent;scheme=https;package=com.google.ar.core;action=android.intent.action.VIEW;end';
    link.click();
  }
```

**Comment by elalish** [comment]
I don't believe it's possible to open scene-viewer using a blob; @tpsiaki for confirmation. model-viewer also does not currently support this.

**Comment by vasium** [comment]
@elalish Any idea how can I accomplish this with scene-viewer without using a blob?

**Comment by elalish** [comment]
@vasium If your configurator could be powered by model-viewer's scene-graph API, then it would work in webXR as well. Not sure there's much hope for scene-viewer unless you do something server-side. If you're interested in collaborating on expanding our scene-graph API, help would be most appreciated!
