### ISSUE TITLE
How to track the AR button in google analytics?

### ISSUE THREAD

**Issue by elmau** [google/model-viewer#1635]
Is there a way to track the clicks on that button, since it can't be seen in the desktop view or the source code?

**Comment by elalish** [comment]
Have you tried a custom AR button using the `ar-button` slot? I think you can add an event listener that way.

**Comment by elmau** [comment]
I'll try doing that, thank you!

**Comment by TarzanBrennt** [comment]
@elmau: Did that work for you? If so, could you provide some insight in how you set up your tracking?

**Comment by adamolivegren** [comment]
@elmau I'm curious as well. Did it work for you with the custom `ar-button` ?
