### ISSUE TITLE
Is it possible to make hotspot move along with the model ?

### ISSUE THREAD

**Issue by likhita-biyyala** [google/model-viewer#1637]
Hi,
  I have given some hotspots on the model, when model is Idle the hotspot position is fine.
  But when the model have animation like running/Jump the hotspot are static, not moving along with the model.
  Is there any way that we can give hotspot as child of particular part of the model ?

  Example: If  want to give hotspot as a child of hand for this model, so that the hotspot move along with the hand when the 
  animations are performed.
 [Glitch](https://glitch.com/edit/#!/chill-tidal-echinacea?path=index.html%3A46%3A3) .

**Comment by elalish** [comment]
Yes, this has been near the top of the feature list for awhile. I need to do some work on the scene-graph API to enable it.

**Comment by likhita-biyyala** [comment]
ok ,thanks.
