### ISSUE TITLE
Ar is not working on Android Firefox, ar button is redirecting user to previous page

### ISSUE THREAD

**Issue by matios13** [google/model-viewer#1640]
### Description

AR is not working on Android Firefox and what weirder rather just not opening ar it goes back to the previous page

#### Live Demo
It works the same on my demo:
[my demo](https://hrgo-conference.s3.eu-west-2.amazonaws.com/demo/folder/Problem.html)
or model-viewer glitch
[glitch](https://model-viewer.glitch.me/)

### Version
- model-viewer: v1.2.1

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by matios13** [comment]
@elalish  I have investigated it a little bit and its seems that there are two problems 
1. self.history.back(); in ar.ts , on firefox it seems like after S.browser_fallback_url is triggered it wont add it to history. but it might be connected with nr 2. 
2. firefox issue with S.browser_fallback_url i have oppened an issue for that https://github.com/mozilla-mobile/fenix/issues/15952

**Comment by elalish** [comment]
@matios13 Thanks, I was just looking at this as well. It seems Firefox still doesn't support app intents, and they fail in a strange way. I'm just going to screen Firefox out for AR until it supports these things.
