### ISSUE TITLE
How to hide AR button for non supported devices?

### ISSUE THREAD

**Issue by Geometrified** [google/model-viewer#1654]
I can see AR button for my models on every single device even though they don't support AR Core. Is there any simple way to hide it?

I'm not a programmer so it is kinda difficult for me to find a solution. I've read that AR button should disappear after clicking when it failed to launch AR, but it doesn't work in my case. Checked it on 3 different Android devises (not supported) and AR button is still shown after clicking multiple times.

**Comment by elalish** [comment]
Well, the simplest way to not show the AR button is to not include the `ar` attribute. However, what you're describing still sounds like a bug. Can you fill in the rest of the issue template so I know exactly what devices, OS versions, and browsers you're using? Also, do you get different results when you add `ar-modes="webxr"`?

**Comment by bieldiaz** [comment]
Hello @elalish , it doesn't works for me if i add the `ar-modes="webxr"`. There is any solution catching the event of model-viewer?

**Comment by elalish** [comment]
I'm not actually sure if you're even having the same problem as above. Try opening a new issue and filling out the entire template so we can repro.
