### ISSUE TITLE
Access and Change Point Light Properties from Model Viewer Scene Graph

### ISSUE THREAD

**Issue by gnansai** [google/model-viewer#1656]
Is there any way to access the lights from ModelViewer Scene Graph and Hide/Unhide or Change Intensity of Lights as in the following ExampleGIF?

The GLB model with Point Light was used in the ExampleGIF.
THREE.Js was used to Load the glb model and changing light intensity to 0 and 3.

Is some thing similar possible with Model Viewer? Are the Lights exposed in the model viewer Scene Graph API as the materials?

![ExampleGIF](https://user-images.githubusercontent.com/25223402/96590184-51045480-1303-11eb-9d39-e774395d4d65.gif)

**Comment by elalish** [comment]
No, we don't have this functionality yet.

**Comment by elalish** [comment]
I think this is beyond model-viewer's scope.
