### ISSUE TITLE
3d models turn gray

### ISSUE THREAD

**Issue by denisTrubicin93** [google/model-viewer#1657]
### Description

good afternoon
On the Xiaomi Note 9 Pro device, some 3D models lose colors (become more gray). What could it be? thanks

### Version
- model-viewer: v1.2.1

### Browser Affected
- [x] Chrome

### OS
Normal view on windows
![pizza](https://user-images.githubusercontent.com/20687576/96620123-afcfcb00-130f-11eb-99b9-03db9866f62a.png)
Error on android
![pizza_bag](https://user-images.githubusercontent.com/20687576/96620829-9b400280-1310-11eb-93c2-5270b0cca769.jpg)

- [x] Android

**Comment by elalish** [comment]
Interesting. You compare windows to Android AR; what about Android 3D? Also, are you using webxr or scene-viewer for AR? You can choose just one using the `ar-modes` attribute. Generally webxr will give more consistent results. You might try changing the `exposure` attribute to a value larger than 1.

**Comment by denisTrubicin93** [comment]
Thanks for the answer.
I am using webxr. This error only on Xiaomi devices. On Samsung everything is displayed correctly.
View Android 3d
![pizza-3d](https://user-images.githubusercontent.com/20687576/96685319-9cf7dd80-1385-11eb-8017-40dfcf9c0b04.jpg)

**Comment by elalish** [comment]
Thanks for the additional detail! I would guess this is a GPU driver bug relating to the lighting. I'll need to get my hands on a device I can repro with to have any chance of fixing it. Can you give me a specific phone model that repros this? Preferably one new enough that I can buy it.

**Comment by denisTrubicin93** [comment]
Xiaomi Note 9 Pro 128/6
Also I tried on Browserstack, all devices except Samsung give the same error.
Maybe a bug in the 3d model? I have 5 3d models and 3 are displayed correctly

**Comment by elalish** [comment]
Thanks, that's quite interesting. If you can narrow down what about the glTF is making this happen, I'd love to know. I have a Pixel 3 I can test on if you can post a link with these different models.

**Comment by denisTrubicin93** [comment]
https://coloring3d.aestar.com.ua/food/ham/
https://coloring3d.aestar.com.ua/food/pizza/                  <--here bug-->
https://coloring3d.aestar.com.ua/food/cheesecake/
https://coloring3d.aestar.com.ua/food/steak/
https://coloring3d.aestar.com.ua/food/sushi/          <--here bug-->

**Comment by elalish** [comment]
I believe this is fixed by #1657. You can test on https://modelviewer.dev/editor/ until the next release goes out.
