### ISSUE TITLE
using model-viewer for first time with react??

### ISSUE THREAD

**Issue by sharafabacery** [google/model-viewer#1659]
### Description

this is my simple component
`import React from 'react'
import "@google/model-viewer";
const Demo22=()=> {
    
    return (
        <model-viewer src="../../AnyConv.com__Untitled.glb" alt="A 3D model of a Toy Train" camera-controls>
        
      </model-viewer>
    );
}

export default Demo22`
 it doesnt shown!!!!!!!!!!

react file:F:\Web\REACT_DEMO\client\src\components
3d object :F:\Web\REACT_DEMO\client

**Comment by elalish** [comment]
Does this example help? #1437

**Comment by ben-tinc** [comment]
I am a bit confused by the path of your model file. Did you use create-react-app? If so, did you place the model inside `public/`? The `src` is supposed to be a URL, not a JS import path. So let's say your model file is located at `./public/model/AnyConv.com__Untitled.glb`. Then `src` should be `"model/AnyConv.com__Untitled.glb"`.

**Comment by nestorchura2019** [comment]
same problem
only show the poster, not the 3d model
https://codesandbox.io/s/gifted-edison-m60h2?file=/src/App.js

**Comment by nestorchura2019** [comment]
> I am a bit confused by the path of your model file. Did you use create-react-app? If so, did you place the model inside `public/`? The `src` is supposed to be a URL, not a JS import path. So let's say your model file is located at `./public/model/AnyConv.com__Untitled.glb`. Then `src` should be `"model/AnyConv.com__Untitled.glb"`.

you have the solution?
