### ISSUE TITLE
Alpha blend

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1661]
A quick question on how to access alpha blend modes as executed in https://modelviewer.dev/editor/

In the materials - > other section. 

Also alpha cutoff in mask mode and double-sided properties. 

Thanks

**Comment by elalish** [comment]
That's hacked in at the moment. The plan is to expose this properly in our scene-graph API so we can remove this hack.

**Comment by dhruvadhia1** [comment]
Ok thanks, looking forward to that.
