### ISSUE TITLE
Android scene viewer animation speed slower

### ISSUE THREAD

**Issue by ryancrunchi** [google/model-viewer#1662]
### Description

When accessing a model from Android Scene Viewer, the animation seems twice slower than on other platforms (iOS quicklook usdz, desktop chrome etc...).
It was working some days ago, no animation speed problem. I suspect a bug in chrome 86 ?

#### Live Demo
https://prod.easytopia.app/experiences/thrillersuite
click "let's try" button

### Version
- model-viewer: v1.0.0
- chrome: 86.0.4240.99
- android: 10

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
If it works in the 3D mode but not in SceneViewer AR, then it sounds like a SceneViewer bug rather than a Chrome bug: @tpsiaki. Can you check if `ar-mode="webxr"` works (you may also want to upgrade your model-viewer version)? That is the all Chrome path.

**Comment by ryancrunchi** [comment]
Was a SceneViewer issue. It is now fixed.
