### ISSUE TITLE
Modifying camera interpolation speed

### ISSUE THREAD

**Issue by ben-tinc** [google/model-viewer#1663]
When going to a new camera position, is it possible to modify the speed at which the automatic interpolation works?

Alternatively, do you have any ideas how one would implement this kind of tracking shot manually? Is there a simpler way than calculating all the intermediate camera positions by hand (like in https://github.com/google/model-viewer/issues/1241#issuecomment-645430702)?

**Comment by elalish** [comment]
We don't yet expose that parameter in our API, but we could. It would be in the form of a time constant, which is currently 50ms. That controls how the motion damps out, but it'll still tend to start fast and end slow. If you're looking for constant-speed motion, you're better off with the method you linked to.

**Comment by jamessqr** [comment]
I would really love to see this exposed from the API. We make use of model viewer quite a bit and often have different creation direction for the camera interpolation speed.

**Comment by elalish** [comment]
@timmmeh FYI

**Comment by methot-ilya-3ds** [comment]
I am also interested in this feature.

**Comment by elalish** [comment]
Fixed by #2286
