### ISSUE TITLE
Spatial audio

### ISSUE THREAD

**Issue by ThomasRutzer** [google/model-viewer#1675]
### Description
Hi, 

I have use case where I want to use `<model-viewer>`in AR mode. A feature would be to adjust the volume of an audio source depending on the distance between camera position and model.
Maybe someone can point me into a direction how to achieve that?

### Version
https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js

**Comment by elalish** [comment]
Our API doesn't currently expose the information you need. It would be possible using our default WebXR AR mode, but QuickLook and SceneViewer are distinct apps, so you can't really customize them from your website. I'm a little hesitant to expose such a low-level API in model-viewer. Of course you could certainly fork us to accomplish this (you'd want to hook in with the `$updateCamera` method in ARRenderer.ts).

**Comment by ThomasRutzer** [comment]
Hi @elalish, thanks for your quick response. I understand your concerns about exposing such low-level information. I am gonna close this issue for noww.
