### ISSUE TITLE
Material SetURI Bug

### ISSUE THREAD

**Issue by FelipeR2U** [google/model-viewer#1678]
### Description

Having two <model-viewer /> with the same `src` and trying to "setURI" in one of them changes the same material/texture on the other.

#### Live Demo
Accessing [Staging and Cameras Page](https://modelviewer.dev/examples/stagingandcameras/) and running the following code on devTools console:
`document.getElementsByTagName('model-viewer')[0].model.materials[0].pbrMetallicRoughness.baseColorTexture.texture.source.setURI('https://picsum.photos/20')`

(Works with other models as well and other URLs as well)

### Version

- model-viewer: v1.3.0

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
Thanks for the clear repro steps! Setting the factors does not have this behavior, so at least it's not totally broken. Probably three's texture cache keeps these from being duplicated and then we replace the only copy. Should be fixable.
