### ISSUE TITLE
Track start of AR session with GTM/Analytics

### ISSUE THREAD

**Issue by TarzanBrennt** [google/model-viewer#1680]
Has anyone managed to track when a user presses the ar button?

I tried the following methods in GTM with no luck: 

1. Trigger when user clicks on "text in ar button" -> no events tracked
2. Trigger when user clicks on element "ar-button" -> no events tracked
3. Trigger when event "ar-status" fires -> event tracked every time event "ar-status" fires which is every time a page loads

Ideas?

**Comment by elalish** [comment]
I'm not quite sure how you tried those methods, but perhaps #1635 will help?
