### ISSUE TITLE
Hotspot not visible in AR mode

### ISSUE THREAD

**Issue by Kite54** [google/model-viewer#1681]
hi i´m pretty new to model-viewer.

on the desktop iOS 14.1 and on my android phone i can see the hotspots.. but not in AR mode?
If seen it on the twitter video thats it is possible. ANY IDEA?

This is my complete code:

<model-viewer
        src="https://ksih.design/clickandbuilds/WordPress/MyBlog/Downloads/GLB_Vorlage.glb"
        ios-src="https://ksih.design/clickandbuilds/WordPress/MyBlog/Downloads/helmstedt.usdz"
        poster="https://ksih.design/clickandbuilds/WordPress/MyBlog/Downloads/helmstedt.png"
        camera-orbit="-213.1deg 71.85deg 439.9m" field-of-view="45deg"    shadow-intensity="1"
        camera-controls
        auto-rotate
        ar>
     <button class="Hotspot" slot="hotspot-1" data-position="-0.49654181987603524m 0.6210276482746568m -0.5074702813990144m" data-normal="-0.15143375359059907m 0m -0.9884674088069175m" data-visibility-attribute="visible">
        <div class="HotspotAnnotation">Reststoffsilos</div>
    </button><button class="Hotspot" slot="hotspot-2" data-position="0.6181664494660295m 0.3624795748919165m -0.39498404785990715m" data-normal="0m 0m -1m" data-visibility-attribute="visible">
        <div class="HotspotAnnotation">Eintragshalle</div>
    </button><button class="Hotspot" slot="hotspot-3" data-position="0.7148748766405031m 0.6560578103644441m -0.022374415770173073m" data-normal="0m 0m -1m" data-visibility-attribute="visible">
        <div class="HotspotAnnotation">Bunker</div>
    </button><button class="Hotspot" slot="hotspot-4" data-position="-0.8845171481370926m 0.6233778757512571m -0.023338942112801186m" data-normal="-1m 0m 0m" data-visibility-attribute="visible">
        <div class="HotspotAnnotation">Kesselhaus</div>
    </button>
</model-viewer>
<style>
.Hotspot {
    background: #fff;
    border-radius: 32px;
    border: 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25);
    box-sizing: border-box;
    cursor: pointer;
    height: 24px;
    padding: 8px;
    position: relative;
    transition: opacity 0.3s;
    width: 24px;
}

.Hotspot:not([data-visible]) {
    background: transparent;
    border: 4px solid #fff;
    box-shadow: none;
    height: 32px;
    pointer-events: none;
    width: 32px;
}

.Hotspot:focus {
    border: 4px solid rgb(0, 128, 200);
    height: 32px;
    outline: none;
    width: 32px;
}

.Hotspot>* {
    opacity: 1;
    transform: translateY(-50%);
}

.HotspotAnnotation {
    background: #fff;
    border-radius: 4px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25);
    color: rgba(0, 0, 0, 0.8);
    display: block;
    font-family: Futura, Helvetica Neue, sans-serif;
    font-size: 18px;
    font-weight: 700;
    left: calc(100% + 1em);
    max-width: 128px;
    padding: 0.5em 1em;
    position: absolute;
    top: 50%;
    width: max-content;
}

.Hotspot:not([data-visible])>* {
    opacity: 0;
    pointer-events: none;
    transform: translateY(calc(-50% + 4px));
    transition: transform 0.3s, opacity 0.3s;
}
</style>

THANKS A LOT!

### Description

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

- model-viewer: vX.X.X

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Can you post a link to your site so I can repro? There are three AR modes; our default is WebXR and should work. SceneViewer on Android and QuickLook on iOS are separate apps and none of your web customization will apply. Since iOS doesn't support WebXR yet, there is no way to get AR hotspots on Apple devices yet.

**Comment by Kite54** [comment]
Hi elalish… thanks for your support!

https://ksih.design/clickandbuilds/WordPress/MyBlog/Downloads/app4.3/

I know about the iOS maybe i can find a way in the usdz model…

**Comment by elalish** [comment]
Your link is showing hotspots in AR for me just fine on my Pixel 3 with Android 11 and Chrome 86 (stable). If you are seeing a picture-taking button, then you're in scene-viewer instead, which doesn't support customization like hotspots. Can you post details on the device/browser you're using and maybe a screenshot?

**Comment by Kite54** [comment]
Hi elalish,

you are right and im sorry… now it works fine after the Chrome update. Sorry for wasting your time! Thanks!

**Comment by souradeepAsh** [comment]
Hi i am also facing some same issue, i am using redmi note 9 pro with android version 11 too but Hotspot is not working
