### ISSUE TITLE
Blank render of a gltf model in VueJs 

### ISSUE THREAD

**Issue by nshutijean** [google/model-viewer#1684]
### Description

I have a gltf model which is in src/assets/busThree.gltf but i cant get it to render. I'm using the npm version of model-viewer locally on a VueJs server. 

### Version
- model-viewer: v1.2.0

### Browser Affected
- [x] Brave: 1.8.96 | Chromium: 81.0.4044.138
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Screenshots

![vue-model-viewer](https://user-images.githubusercontent.com/28356145/97739507-989b9500-1ae8-11eb-94bc-a4e3a536e707.png)
![result](https://user-images.githubusercontent.com/28356145/97739545-a3562a00-1ae8-11eb-9660-33dd56d6387a.png)

**Comment by elalish** [comment]
Can you post a link where I can repro? Are you getting any console errors?

**Comment by leonzuendel** [comment]
exact same problem here in nuxt.js, also using the module added with yarn

**Comment by nshutijean** [comment]
After having a discussion in the "Discussions" side of the repo, the problem rose because of a placing gltf/glb models in the wrong path. They should be placed into the "public" folder instead of the "src" folder. 

For a more detailed answer: [https://github.com/google/model-viewer/discussions/1835](https://github.com/google/model-viewer/discussions/1835)
