### ISSUE TITLE
How to know when textures are completely loaded/applied in scene graph?

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1685]
Hi,

How to know when textures are completely loaded/applied in scene graph? I see there is a load event for src parameter, but that does not take into account the textures being changed in future through scene graph.

**Comment by elalish** [comment]
The `setSource()` method is async, so if you await it, it should be ready at that point. If that's not the case, it's a bug.

**Comment by dhruvadhia1** [comment]
I tried loggin this line 

```
let  applyPBRTexture =  (channel) => {
  	        //console.log(event.target.value);
  	        material.pbrMetallicRoughness[channel].texture.source.setURI(baseColor);
			
  	        //removeLoader();
  	      }

  	      let applyPBRNormalTexture =  (channel) => {
  	        //console.log(event.target.dataset.normalmap);
  	        material[channel].texture.source.setURI(normalMap);
  	        //removeLoader();
  	      }

  	      let applyOcclusionPBRTexture =  (channel) => {
  	        //console.log(event.target.dataset.occlusion);
  	        material.pbrMetallicRoughness[channel].texture.source.setURI(occlusionMap);
			//console.log(material.pbrMetallicRoughness[channel].texture.source.setURI(occlusionMap));
			
				  
  	      }
		  
		 
	
		  async function loadTextures()
		  {
		   
			 
      	   await applyPBRTexture('baseColorTexture');
      	   await applyPBRNormalTexture('normalTexture');
      	   await applyOcclusionPBRTexture('metallicRoughnessTexture');
			   
		   console.log(await applyOcclusionPBRTexture('metallicRoughnessTexture'));

		     // 
		  }
	       
		  loadTextures();
		  
```

that's how I have setup the code. I am actually trying to creating loading spinner and then the model is completely loaded including the textures I want to it to disappear. All the css part is there, its jut that when I put it after the console line, It does not appear at all as if it is not waiting for the function to finish. And when I log this line 

		   console.log(await applyOcclusionPBRTexture('metallicRoughnessTexture'));


I do get promise status as fulfilled.

**Comment by elalish** [comment]
I think you may want to read up a bit more on async JS first. You're trying to await functions you've written as non-async, which doesn't do anything.

**Comment by dhruvadhia1** [comment]
Got it. Thank you.
