### ISSUE TITLE
Cannot access editor URL of model-viewer when deploy on local Linux

### ISSUE THREAD

**Issue by nguyenbs** [google/model-viewer#1698]
### Description
I cloned this git repo in an instance of WSL2 Linux, and tried to deploy following instructions in README.md.
After running this command:

```
git clone --depth=1 git@github.com:google/model-viewer.git
cd model-viewer
npm install
npm run bootstrap
```
the homepage of modelviewer is successfully displayed under URL: http://127.0.0.1:8080/packages/modelviewer.dev/
But the URL http://127.0.0.1:8080/packages/modelviewer.dev/editor is not work, the error log is:

```
[Mon Nov 09 2020 07:54:24 GMT+0700 (Indochina Time)]  "GET /packages/modelviewer.dev/editor" Error (404): "Not found"
```
See the screen shot:
![image](https://user-images.githubusercontent.com/4568193/98489561-200fa380-2261-11eb-8457-4fe99ba96444.png)

### Version
- model-viewer: v1.3.0

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Did you see my reply? https://github.com/google/model-viewer/issues/1485#issuecomment-721241244

**Comment by nguyenbs** [comment]
Thank you, I'll close this issue
