### ISSUE TITLE
Not able to get render-fidelity-tools run on Ubuntu

### ISSUE THREAD

**Issue by UX3D-haertl** [google/model-viewer#1701]
### Description
We tried to get the render-fidelity-tools running on Ubuntu and WSL. 
The model-viewer works as intended, but when we try to run `npm run test` in render-fidelity-tools the following error appears:
```
(node:3749) ExperimentalWarning: The ESM module loader is experimental.
.../model-viewer/packages/render-fidelity-tools/lib/workflows/test-fidelity.js:15
import HTTPServer from 'http-server';
       ^^^^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createDynamicModule (internal/modules/esm/translators.js:73:15)
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:40:9)
    at file:///.../model-viewer/packages/render-fidelity-tools/lib/workflows/test-fidelity.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @Google Drive/model-viewer-render-fidelity-tools@0.0.1 test: `node --experimental-modules ./lib/workflows/test-fidelity.js ./test/config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @Google Drive/model-viewer-render-fidelity-tools@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2020-11-12T14_45_12_966Z-debug.log
```
If we run `npm run update-screenshots` the following error appears:
```
.../model-viewer/packages/render-fidelity-tools/lib/workflows/update-screenshots.js:15
import { spawn } from 'child_process';
       ^
SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at createDynamicModule (internal/modules/esm/translators.js:73:15)
    at Object.meta.done (internal/modules/esm/create_dynamic_module.js:40:9)
    at file:///.../model-viewer/packages/render-fidelity-tools/lib/workflows/update-screenshots.js:9:13
    at ModuleJob.run (internal/modules/esm/module_job.js:95:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @google/model-viewer-render-fidelity-tools@0.0.1 update-screenshots: `node --experimental-modules ./lib/workflows/update-screenshots.js ./test/config.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @google/model-viewer-render-fidelity-tools@0.0.1 update-screenshots script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2020-11-12T14_47_47_450Z-debug.log
```
Are there any dependencies despite `imagemagick`?
Do we need to use a particular node.js or npm version?
It seems like some dependencies are not resolved correctly, but `npm install` and `npm run bootstrap` seem to work.

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
When you say Ubuntu on WSL, you mean you're actually on a Windows machine? I can confirm this all works as intended on actual Ubuntu, but we've had scattered reports of difficulties on Windows (including WSL). Unfortunately I have no access to a Windows machine to debug. I would really like to get our repro running more easily on Windows for contributors like yourself. 

I'll do my best to provide support, but I'm unfamiliar with WSL. I know @bsdorra had some success getting things running under WSL. I'm on npm version 6.14.8 (the latest). If you find how to get this working properly, please push a PR to update our README accordingly.

**Comment by UX3D-haertl** [comment]
We tried it on 2 machines with normal Ubuntu 20 running and on one Windows machine with WSL.
We also tried it on Windows, but as you described, there are some issues currently.

**Comment by elalish** [comment]
Ugh. Well I haven't tried it on Ubuntu 20 specifically. What version of npm does it have? You followed all the steps on our README? It looks like it's having trouble with ES6 module imports. We build legacy versions with rollup that target ES5 for old browsers like IE11, but I can't imagine why you'd be having trouble there. If you're successfully running the model-viewer tests, those are already using ES6 imports so it's strange that only these other modules would have trouble.

**Comment by UX3D-haertl** [comment]
Apparently,  `sudo apt-get install nodejs` installs version 10 by default. After updating node.js to version 15 [(as described here)](https://github.com/nodesource/distributions/blob/master/README.md) it works.
