### ISSUE TITLE
View it in your space not shown

### ISSUE THREAD

**Issue by adrianposteuca** [google/model-viewer#1707]
Hi guys,

I have this situation I have added this code on my website. it worked for several weeks but stopped working out of the blue!
It works only to see the 3d model in a viewer but not as augmented reality?
I do not know why?
What is wrong?

```
<div id="Apollo"> 
    <model-viewer src="https://conceptfactory.ro/wp-content/uploads/2020/05/GLB-apollo.glb"
                  ios-src="https://conceptfactory.ro/wp-content/uploads/2020/05/usdz-Apollo_Belvedere.usdz"
                  alt="Golden Fish"
                  ar-modes="webxr scene-viewer quick-look fallback" 
                  ar-scale="auto" 
                  quick-look-browsers="safari chrome" 
                  shadow-intensity="1"
                  camera-controls autoplay
                  interaction-prompt="auto"
                  auto-rotate ar magic-leap>
    </model-viewer>
<h4>Apollo </h4>
</div>   
```

this is how it looks like but not a "view it in AR"
![image](https://user-images.githubusercontent.com/17274973/99256808-a195a180-281e-11eb-8f93-9c9b5ce05c5e.png)

**Comment by elalish** [comment]
Please fill out the issue template so I can help. Especially your device, OS, and browser versions, along with a link I can use to repro. Do you see any errors in the console? (through chrome://inspect)
