### ISSUE TITLE
3D models appear pixelated on Shopify stores when viewed on Windows Chrome

### ISSUE THREAD

**Issue by cgoodine** [google/model-viewer#1715]
### Description
I've noticed that models rendered using google model viewer on shopify stores appear pixelated when viewed on windows chrome. I'm not sure why, but some other websites that use google model viewer don't seem to have this issue. See below for details.

Below is a screenshot of a photogrammetry model [uploaded to a Shopify store](https://switch3d.co/collections/scan-shop/products/adidas-yeezy-boost-380-mist) and viewed on windows chrome:
<img width="938" alt="chrome_2whgibax79" src="https://user-images.githubusercontent.com/5186933/99835212-44596300-2b32-11eb-9f58-440bc2ce324a.png">

I took the same model URL and dropped in into another site that uses google model viewer (https://spase.io/). This is what it looks like, even though I'm using the same machine and browser:
<img width="938" alt="chrome_3q4uPjv9xP" src="https://user-images.githubusercontent.com/5186933/99835354-7bc80f80-2b32-11eb-8bba-682425812a42.png">

Notice the significant difference in resolution. The model appears blurry or pixelated when viewed on the Shopify store. 

I took the above screenshots when the model was not moving. @elalish mentioned that you intentionally "pixelate" renders to keep the frame rate up when the model is moving, but in this case, I see the pixeled effect when the model stops moving as well.

It's worth noting that I only notice this issue when I view the model on the desktop version of the site. When I view on the mobile site, it looks crisp. See below:
![Photogrammetry model on mobile site](https://user-images.githubusercontent.com/5186933/99836258-d1e98280-2b33-11eb-9987-bf6d50fba322.jpg)

This is the model I'm using to test: https://model3d.shopifycdn.com/models/o/31f14f245b24624b/1021_380MistHighRes.glb

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

I don't know the exact version number, but I can say that this issue appears for me on all Shopify stores. I also tried pasting the import scripts found in the Quick Start guide on https://modelviewer.dev/ into a website editor and found the same issue. Given this, I believe I am using the most up-to-date version, but I could be wrong.

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
It sounds like you made a minimal repro case; can you link that? Even better if you can remix our Glitch demo to repro. It's hard to debug a full Shopify website.

**Comment by cgoodine** [comment]
No problem at all. I was able to reproduce the issue immediately after remixing your Glitch demo. After remixing, I simply dropped in my model URL and changed the copy. Everything else was loaded from the template.

Here is my Glitch project: **https://glitch.com/edit/#!/join/ab6f3608-08f7-4f43-84e4-3db2f8314be6**

Below is a screenshot, which shows how pixeled the model is even in this environment:
![Screenshot 2020-11-20 142805](https://user-images.githubusercontent.com/5186933/99841846-d1091e80-2b3c-11eb-9ef0-7758fe36ea54.png)

**Comment by elalish** [comment]
Thanks! Quick question; have you tried different browser zoom levels? We've had reports of Windows having weird resolution behavior at certain zoom settings. Your demo is still looking great here on macOS. Also, have you tried different browsers? Any kind of matrix you can give us of what does and doesn't work properly would be very helpful.

**Comment by cgoodine** [comment]
I tried my Glitch demo on Edge and Firefox and the issue remains. I see no difference between these browsers and Chrome.

This is the demo on Edge:
<img width="722" alt="msedge_xwOgzPv92t" src="https://user-images.githubusercontent.com/5186933/99846063-aec6cf00-2b43-11eb-8978-0e3d155bf3e5.png">

This is the demo on Firefox:
<img width="689" alt="firefox_Qlowp4g4Un" src="https://user-images.githubusercontent.com/5186933/99846078-b4bcb000-2b43-11eb-90c2-bf9c1eba93b0.png">


Below is a link to a screen recording where I tested the model at different zoom settings. The resolution was incorrect for every zoom setting, however once I made it to 400% zoom it started to look good. It almost seems like the model is stuck at a specific resolution that only looks good when the model is significantly enlarged.

https://drive.google.com/file/d/1nN_NE9__qc2yBGWyWaYzOOle57CRXEMr/view?usp=sharing

I know I mentioned this above, but the only way I am able to make the model resolution look good on my machine (without going to 400% zoom) is to view it on Spase.io's implementation of google model viewer. Below is a screen recording which shows the difference:

https://drive.google.com/file/d/1a4F8aZp3dUclBfsxRTOwG-mJfQTkOXAZ/view?usp=sharing

I hope this helps. Please let me know if you need any more details or if you want me to run through any more tests. I'm happy to do whatever it takes to help you get to the bottom of this.

**Comment by cgoodine** [comment]
@elalish I really appreciate the work you did in #1747 however after running a few tests on my machine I can confirm that the issue still exists. Sorry it took me this long to respond, I know that a test sooner would have been more ideal.

Please let me know if there's anything else I can do to help with this issue. I'd love to see a crisp model on my machine, but more importantly, I'd love to make sure others don't experience this issue as well. Given the growing adoption of model viewer (knowing that it's natively supported on Shopify), I suspect there are many more people who are affected by this issue.

**Comment by elalish** [comment]
@cgoodine Are you still testing the released version? You'd need to test master to see this change, which you can do by building and deploying yourself or by using our modelviewer.dev pages (which run off master instead of the last release). You might try reproing on our [editor](https://modelviewer.dev/editor/) or our lighthouse [page](https://modelviewer.dev/examples/lighthouse.html).

**Comment by cgoodine** [comment]
@elalish thank you for calling this out. I was in fact testing on the released version and not master. 

As you recommended, I performed a test on your modelviewer.dev editor and lighthouse pages. Unfortunately, I am still seeing the issue. Below are screenshots:

<img width="573" alt="chrome_7uD4BBgErg" src="https://user-images.githubusercontent.com/5186933/101943311-dcd68680-3bb8-11eb-81ba-ec070b41c74c.png">
<img width="486" alt="chrome_HTk3LlxR80" src="https://user-images.githubusercontent.com/5186933/101943318-df38e080-3bb8-11eb-9d96-fc37f695860c.png">
<img width="812" alt="chrome_POWtVpV96n" src="https://user-images.githubusercontent.com/5186933/101943325-e06a0d80-3bb8-11eb-8213-1519262e45ea.png">

As you can see, the models continue to appear blurry on my machine. 

Just to make sure I wasn't crazy, I tested the models on a mac today and confirmed that they look sharp and beautiful on a mac. As mentioned above, they look great on iOS as well. As far as I can tell, the issue only comes up on Windows.

**Comment by elalish** [comment]
@cgoodine Thanks for the detailed tests! I finally broke down and ordered a cheap windows machine, so we'll see if I can repro and debug on that. What OS, browser version(s), and GPU do you have?

**Comment by cgoodine** [comment]
@elalish I hope all is well. I wanted to follow up with you on this issue. I found a really simple way to reproduce the issue on my machine. 

If I take a GLB and view it on Spase's playground (https://spase.io/playground) it comes out sharp. See below:
![Screenshot 2021-03-24 163623](https://user-images.githubusercontent.com/5186933/112379965-2c9c1200-8cbf-11eb-9ec6-ce4e8f92d685.png)

If I take the same GLB and view it on https://modelviewer.dev/editor/ it comes out blurry. See below:
![Screenshot 2021-03-24 163653](https://user-images.githubusercontent.com/5186933/112380111-5d7c4700-8cbf-11eb-9c1c-bb17c7f013f9.png)

I find this surprising because Spase is using model-viewer to create their playground. What is different about their implementation?

Thank you so much for take the time to review this. I really appreciate your help.

**Comment by elalish** [comment]
It looks like the render rescaling we do automatically to keep framerate up when the GPU is not powerful enough. However, it should revert to full res while the model is static. Are you seeing this constantly even when it's not moving? Can you scroll the sidebar smoothly?

**Comment by elalish** [comment]
This is very strange; plus you have a very powerful GPU, so really it should never get pixelated in the first place. Can you resize your window and try in other browsers as such? I'm curious if there's anything that affects this behavior. You see this on all models, 100% of the time?

**Comment by peteshand** [comment]
Could we get an option added to model-viewer to disable the `automatically rescaling to keep framerate`. While it's a good call to have this feature as the default, content creators should have some control over this behaviour.

**Comment by peteshand** [comment]
Hmmm still no dice after moving the script before the `model-viewer.min.js`

```
<head>
  <script>
    self.ModelViewerElement = self.ModelViewerElement || {};
    self.ModelViewerElement.minimumRenderScale = 1;
  </script>
  <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
</head>

<model-viewer id="viewer" src="model.gltf" ar ar-modes="webxr scene-viewer quick-look" camera-controls environment-image="neutral">
<div class="controls">
    <div>Variant: <select id="variant"></select></div>
  </div>
</model-viewer>
```

However what did work for me was as you suggested adding to the constructor post load.

```
<model-viewer id="viewer" src="model.gltf" ar ar-modes="webxr scene-viewer quick-look" camera-controls environment-image="neutral">
<div class="controls">
    <div>Variant: <select id="variant"></select></div>
  </div>
</model-viewer>

<script>
const modelViewerVariants = document.querySelector("model-viewer#viewer");

modelViewerVariants.addEventListener('load', () => {
  const ModelViewerElement = customElements.get('model-viewer');
  ModelViewerElement.minimumRenderScale = 1;

  ...
});
```

Thanks for your help @elalish
