### ISSUE TITLE
ar-scale="fixed" not working on iOS Chrome

### ISSUE THREAD

**Issue by TarzanBrennt** [google/model-viewer#1719]
DESCRIPTION:
I use `ar-scale="fixed"` to prevent users from pinching and zooming in in AR. This always worked perfectly so when users pinched, the model always automatically snapped back to 100%. That doesn't work anymore as the model stays in the smaller/bigger size after pinching in/out. 

VERSION:
model-viewer v1.3.0

BROWSER AFFECTED
- only AR View is affected

OS

- [x] Android 11
- [x] iOS 14.1

**Comment by elalish** [comment]
I don't quite understand; "fixed" should mean pinch does nothing at all. What AR mode/modes are you referring to (webxr, scene-viewer, or quick-look)? If you can grab screen recordings of the behavior you're seeing (and maybe how it was before) that would be helpful.

**Comment by TarzanBrennt** [comment]
After further testing we had the issue on an Android 11 Device (Pixel 3) in scene-viewer and on iOS (Tested with iPhone XS Max, iOS 14.1) in quick-look. It did however work as inteded (no movement on pinch) on a OnePlus 7T (Android 10) in scene-viewer. 

Link to the site: https://ar-webshop.com/demo-pflanze-ii/ 

Link to Video where the wrong behavior can be seen (File is too big to share here): https://youtu.be/GTJOIihSziY

**Comment by elalish** [comment]
Thanks for the demo! On iOS 14 I'm able to scale the model temporarily but it snaps back to 100%. On Android 11 Pixel 3 with Scene Viewer, I can scale strangely from about 96% to 103%, so sort of fixed. Everything is working just fine on WebXR. So, I think I'm seeing expected behavior and you're seeing something else? Are you fully updated?

**Comment by TarzanBrennt** [comment]
> Thanks for the demo! On iOS 14 I'm able to scale the model temporarily but it snaps back to 100%. On Android 11 Pixel 3 with Scene Viewer, I can scale strangely from about 96% to 103%, so sort of fixed. Everything is working just fine on WebXR. So, I think I'm seeing expected behavior and you're seeing something else? Are you fully updated?

Yes, I am fully updated on iOS (14.2). 
What  I learned ist the following: The beavior is as you desgribed (snapping back to 100%) when opened from Safari (which is perfectly OK) but is still scalable when started from Chrome - looks like the issue is browser related.
(to be clear: this is on iOS which means the AR experience is in quick-look)

**Comment by matios13** [comment]
@elalish  @TarzanBrennt  I had same issue and its Chrome bug, i have oppened an issue and they said it will be fixed
https://bugs.chromium.org/p/chromium/issues/detail?id=1163852#c4
