### ISSUE TITLE
Rotate model on X axis

### ISSUE THREAD

**Issue by tskaiste** [google/model-viewer#1724]
### Description

Is there an option to rotate the model on an X axis? Here's an example:
![image](https://user-images.githubusercontent.com/36891590/100056744-e036e780-2e2e-11eb-986f-d5c3e5fe00b8.png)
If not, it'd be nice to have this feature implemented.

#### Live Demo
I've found the example model viewer here -> https://www.creators3d.com/online-viewer

**Comment by elalish** [comment]
Yes, this is related to #1118 and I'd like to get this feature in shortly. It is worth noting though that glTF does specify that +Y is up and +Z is front, though I think this is still important since some models don't have a clear up/front direction.
