### ISSUE TITLE
Astronout has no texture in Firefox/Safari

### ISSUE THREAD

**Issue by tided** [google/model-viewer#1731]
### Description

At modelviewer.dev the Astronaut.glb is loaded without the texture.
Had the same problem with my own glb-file in modelviewer.dev/editor. The same file worked in my development environment with the latest release of modelviewer (v1.3.0) with no problems.

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [x] Firefox 83.0
- [ ] IE
- [x] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [x] Windows

**Comment by AndreasKl** [comment]
This also affects Firefox 83.0 on Fedora 33 and Microsoft Edge 44.17763.1.0.

**Comment by elalish** [comment]
Thank you! I have a repro, will look into this shortly.

**Comment by jrwm** [comment]
Still happens randomly.

**Comment by hlinvest** [comment]
Anyone have solution for it? It still happens.

**Comment by elalish** [comment]
I don't think it's really the same problem; may different things can look similar. Feel free to open a new issue if you can give detail on exactly what problem you're running into.

**Comment by hlinvest** [comment]
The same iframe that contains a 3d object,  when you view in Safari, some time the texture is not appear, all the object is black, if you refresh the browser the object might appear with the texture, might not.  
<img width="455" alt="Screenshot 2021-09-21 at 20 13 25 chrome" src="https://user-images.githubusercontent.com/4975938/134226167-88b42ffa-eae8-4ea8-8726-305e614fe9df.png">
<img width="490" alt="Screenshot 2021-09-21 at 20 13 38 safari" src="https://user-images.githubusercontent.com/4975938/134226200-8ccd33e5-adcd-4bee-be03-6779007c601a.png">
