### ISSUE TITLE
Setting 'ar-scale' to 'fixed' overwrites QuickLook-specific URL parameters defined as part of the USDZ file path

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#1732]
### Description

It is possible to pass in additional iOS-specific URL parameters to QuickLook by appending specific values to the end of the USDZ file path after a hash. For example, adding a custom HTML banner path:

`path-to-model.usdz#custom=path-to-banner.html`

These currently are respected by ModelViewer, except...

When also setting the ModelViewer `ar-scale` property to `fixed` the existing QuickLook URL parameters stop working. 

This is perhaps due to this point in the code:

https://github.com/google/model-viewer/blob/fa3420c0eec7fc37f9666509a4d8b0b5b19d0442/packages/model-viewer/src/features/ar.ts#L35

Where it looks as though the `ar-scale` parameter is replacing the entirety of the the USDZ URL hash, but should maybe append to it instead?

#### Live Demo

https://model-viewer-playground.glitch.me/custom-banner-mv.html
(view on iOS device)

### Version

- model-viewer: v1.3.0

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Good call, thanks. Any interest in making a PR, since you seem to have already identified the source of the problem?

**Comment by milesgreen** [comment]
Heh. I would if I could!
Well... let me see. This would take a bit of ramp up time. But I'd love to be more helpful if I can...
