### ISSUE TITLE
How to disable blending with scene viewer? 

### ISSUE THREAD

**Issue by creativehims** [google/model-viewer#1733]
By default, object blending is enabled in scene-viewer. Is there a way we can have it disabled as default?

**Comment by elalish** [comment]
@tpsiaki Is there an intent parameter for this?

**Comment by antekj** [comment]
Thanks @elalish for investigating, I am also interested in a possible solution.

**Comment by ronpadz** [comment]
Blending is a cool feature but so often yields undesirable results that I agree it should be off by default.

**Comment by Saicopate** [comment]
Fully agree on that. In most cases "off" setting is better.

**Comment by ctrlventure** [comment]
I would also like to know how to disable this. Is there any parameter that we can use?

**Comment by tpsiaki** [comment]
@elalish Yes there's an intent parameter for this.  You can pass `disable_occlusion=true` on the intent and that will turn off blending.
