### ISSUE TITLE
Accessing the duration of an animation

### ISSUE THREAD

**Issue by rhystmills** [google/model-viewer#1736]
`model-viewer` includes some very useful animation properties and methods including:
- play()
- pause()
- currentTime

A notable absence seems to be `animationDuration` - i.e. the total time taken by an animation.

I am working on a 'player' interface where a user can scrub to a particular moment in the animation, but will need to use a hard coded value for the duration of the animation, rather than reading it from the interface. I suspect the animation duration would be used somewhere internally - it would be very useful if it were made available via a property on the model-viewer in the same way that `currentTime` is.

**Comment by elalish** [comment]
True, and that should be pretty easy to expose. Any interest in submitting a PR?

**Comment by rhystmills** [comment]
Absolutely, I will have a go.

**Comment by dhruvadhia-cela** [comment]
There is a way to access Threejs library from Model Viewer. 

`<script>

        let mixer;
        let scene, model;

        const mv = document.querySelector("model-viewer");
        const clock = new THREE.Clock();
       
       mv.addEventListener('load', (event) => {

        //mv.onload = function () {
            let sceneObj = Object.getOwnPropertySymbols(mv).find(
                x => x.description === "scene"
            );
            scene = mv[sceneObj];
            model = scene.model.children.find(x => x.name === "ModelContainer");

            mixer = new THREE.AnimationMixer(model);
            
            // this will give you the duration of any given clip in the model. 
            console.log(scene.model.animations[1].duration);

            event.stopPropagation();
        }, true);

</script>
`

Its a hacky way though, I like your proposal on adding those functionalities in core Model Viewer itself.

**Comment by rhystmills** [comment]
PR now available here: https://github.com/google/model-viewer/pull/1742

**Comment by elalish** [comment]
Thanks for adding this!
