### ISSUE TITLE
Scene Viewer - imported content privacy policy

### ISSUE THREAD

**Issue by parrajacob** [google/model-viewer#1757]
### Description

Not a bug, more of a question. When using the Model Viewer Editor (https://modelviewer.dev/editor/) at the bottom right I see the message of `This <model-viewer> editor does not send any imported content to servers: Privacy` but I do not see a similar message when using the Scene Viewer (https://arvr.google.com/scene-viewer-preview). Can I expect the same privacy policy for the Scene Viewer app when importing content?

Thanks

#### Live Demo
N/A

### Version
- model-viewer: v1.3.0

### Browser Affected

- [X] Chrome
- [X] Edge
- [X] Firefox
- [X] IE
- [X] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [X] Windows

**Comment by elalish** [comment]
I believe that's true (there's no reason to involve the complexity of a server). You can always double check by looking at the network tab in dev tools. @tpsiaki who would have the official answer.

**Comment by tpsiaki** [comment]
That is correct.  None of the content is uploaded when using the Scene Viewer previewer - it is only processed and rendered locally in the browser.

**Comment by parrajacob** [comment]
Thank you for your prompt responses.
