### ISSUE TITLE
How to add custom button in AR mode ( webXR)?

### ISSUE THREAD

**Issue by Dovatech** [google/model-viewer#1758]
Hello everyone, 
I want to add info button in AR mode (webXr) and I need help😥. Button should be visible only in AR, not in 3D view. Is it possible to add buttons in ar?

### Browser Affected

- [ ✔] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ✔] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Yes! All you need to do is scope the CSS using our `ar-status` [attribute](https://modelviewer.dev/docs/#entrydocs-augmentedreality-css-arStatus)

```
  model-viewer[ar-status="not-presenting"] > #ar-button {
    display: none;
  }
```

**Comment by Dovatech** [comment]
@elalish , Thank you!!!
