### ISSUE TITLE
Hide .glb or .gltf file on source codes

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#1768]
Hello all! 

Is it possible to hide 3d file on source codes. If you check my demo link below when you right click on page and open source code panel you can easily download my glb file from html based assets. Any idea or suggestions to hide it from users/visitors would be great. Thanks..

ps: I deployed my html, css, js based static webpage via Netlify. 

Demo Link
https://confident-lamport-09f645.netlify.app/m6.html

The paart I want to hide is **src line**
    
  class="a"
  src="/Assets/m6/m6.glb"
  alt="3D Koltuk by BaseBros"

`

### Browser Affected

- [x ] Chrome
- [x ] Edge
- [ x] Firefox
- [ x] IE
- [x ] Safari

**Comment by elalish** [comment]
Not that I'm aware of. You can look at the network tab to see what files are downloaded even if they aren't clear from your code. It's exactly like an image; you can protect it by only making a low-res version downloadable for free, or by watermarking it, or by bringing legal action against people who use it without permission. There's no equivalent to video DRM in the 3D space.
