### ISSUE TITLE
please add support for "KHR_materials_clearcoat", "KHR_materials_transmission", "KHR_materials_sheen"

### ISSUE THREAD

**Issue by rawwerks** [google/model-viewer#1778]
### Description

There are three new PBR extensions that Khronos recently released that dramatically improve the ability to create photo-realistic GLTF files.  https://gfxspeak.com/2020/12/03/physically-rendering-extensions/

Given that model-viewer supports GLTF, and that these 3 extensions are official extensions for GLTF 2.0, it would seem within the scope of this application to include the functionality to correctly display these new extensions: "KHR_materials_clearcoat", "KHR_materials_transmission", "KHR_materials_sheen"

https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos

#### Comparison 

Comparison between Model Viewer (Left, extensions not supported) and Babylon (Right, extensions supported) 

![image](https://user-images.githubusercontent.com/19483938/102738155-25e7b280-42fe-11eb-8447-83048e0bdf92.png)

See example file at:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/ToyCar

### Version

Whatever version is live at https://modelviewer.dev/editor/

### Browser Affected

This is not a browser-specific issue.

### OS
This is not an OS-specific issue.

**Comment by rawwerks** [comment]
@bsdorra @elalish - any implementation tips on [KHR_materials_transmission](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_transmission) since these extensions are hot off the press?

**Comment by elalish** [comment]
Yes, you've already linked to the right place in three.js. Support in model-viewer will come via support in three. I believe clearcoat is already working, and sheen is partially there, but not hooked up to GLTFLoader. We definitely intend to support these extensions.

**Comment by donmccurdy** [comment]
2/3 of these (clearcoat, transmission) have been in three.js for a bit now and I assume are working in model-viewer already? Although I'd add Volume and IOR to the list now. 😉

**Comment by elalish** [comment]
They should in the next release when we update three.js versions. You can test the current state of development with our [editor](https://modelviewer.dev/editor/). We're also working on getting some tests going for these extensions before we go trumpeting support.

**Comment by elalish** [comment]
I'm going to call this fixed, as we have not just these extensions now with r131, but also ior, specular, and volume. I think sheen may not be totally supported yet and there could easily be some bugs in the others, but I'd rather track those as individual issues.
