### ISSUE TITLE
Panning Example not working well with auto-rotate

### ISSUE THREAD

**Issue by MisterX2000** [google/model-viewer#1782]
### Description

The panning example listed here:
https://modelviewer.dev/examples/stagingandcameras/#panning
isn't quite working well with the auto-rotate option enabled.
It looks like the rotation from the auto-rotate option isn't transferred over to the panning script.
It also doesn't pause the auto-rotate animation while you're panning.

#### Live Demo

https://pinnate-marbled-vegetable.glitch.me

### Version

- model-viewer: v1.3.0

### Browser Affected

- [x] Chrome: 87.0.4280.88
- [x] Edge: 87.0.664.66 
- [ ] Firefox ?
- [ ] IE ?
- [x] Safari: iOS 14.3

### OS

- [ ] Android ?
- [x] iOS: 14.3
- [ ] Linux ?
- [ ] MacOS ?
- [x] Windows: 20H2

_? - Not Tested_

**Comment by elalish** [comment]
Thanks for the clear repro!
