### ISSUE TITLE
Is getCameraOrbit() has toString() method?

### ISSUE THREAD

**Issue by sm-ffx** [google/model-viewer#1795]
According to docs `getCameraOrbit()` method alogn with theta, phi, and radius, should return `toString()` method. But in fact it doesn't have this method http://prntscr.com/wh0x6e

**Comment by elalish** [comment]
Sorry, I just added this; it'll be in the next release, which should be soon.

**Comment by sm-ffx** [comment]
got it. thank you for the quick response.
