### ISSUE TITLE
iOS-Chrome .USDZ File Opens as Unicode Text

### ISSUE THREAD

**Issue by CanerErdogan** [google/model-viewer#1796]
### Description

I have the following error after tapping View in AR button specifically in Chrome browser on iOS.
iOS+Safari works fine as well as Android, so I believe the model should be fine too.
![image](https://user-images.githubusercontent.com/8267609/103764360-5d5b9c00-502c-11eb-9130-05ee3a45259c.png)

I replaced the ios-src parameter with the following model which is Google's astronaut and it works fine.
https://cdn.glitch.com/36cb8393-65c6-408d-a538-055ada20431b/Astronaut.usdz?v=1569545377878

The model works on other platform/OS combinations, also on Chrome+iOS as redirection to the .usdz file link. I was able to reproduce the same error with several export methods, results in little change in the "text", but still no view.

I have been going through similar issues here and elsewhere on the web, but could not solve it yet. Can anyone help or at least tell me what might be the cause? Thanks a lot!

### Version
- model-viewer: v0.9.0 and some newer

### Browser Affected

- [ ]  Chrome 87.0.4280.77
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS 14.3
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by CanerErdogan** [comment]
Figured it out. I was using Google Firebase **and that was the problem!** It somehow meddles with the .usdz files. @firebase

**Comment by pbmonster** [comment]
This is a content mime-type issue, Chrome and Firefox on iOS require the server to specify correct content type. On Firebase hosting you can correct by adjusting your firebase.json file:

```
{
  "hosting": {
    ...
    "headers": [
      {
        "source": "**/*.@(usdz)",
        "headers": [
          {
            "key": "Content-Type",
            "value": "model/vnd.usdz+zip"
          }
        ]
      }
    ]
  }
} 
```
