### ISSUE TITLE
iOS Quick Look - make sure that it works as expected, and that the caveats outlined here are documented in the README

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#18]
Meta bug, can break out if not handled here. Taken from current readme:

- [ ] There is currently no way to tell whether an iOS device has AR Quick Look support. Possibly check for other features added in Safari iOS 12 (like CSS font-display): https://css-tricks.com/font-display-masses/ Are there any better ways?

- [ ] Since there are no USDZ three.js loaders (and seems that it'd be difficult to do), Safari iOS users would either need to load a poster image, or if they load the 3D model content before entering AR, they'd download both glTF and USDZ formats, which are already generally rather large. Not sure if this is solvable at the moment, so we may need to just document the caveats.

- [ ] With native AR Quick Look, the entire image triggers an intent to the AR Quick Look. Currently in this component implementation, the user must click the AR button. Unclear if we want to change this, as interacting and moving the model could cause an AR Quick Look trigger. Do we want this to appear as native as possible?

- [ ] The size of the AR Quick Look native button scales to some extent based off of the wrapper. We could attempt to mimic this, or leverage the native rendering possibly with a transparent base64 image. I've played around with this, but someone with an OSX/iOS device should figure out the rules for the AR button size. I did some prelim tests here: https://ar-quick-look.glitch.me/

**Comment by mikkoh** [comment]
You can check whether AR Quicklook is supported in the browser by doing:
```javascript
const anchor = document.createElement('a');
const supportsAR = anchor.relList.supports('ar');
```

We're running this in production at Shopify.
