### ISSUE TITLE
why model-viewer dont work in React   - [codesandbox example]

### ISSUE THREAD

**Issue by nestorchura2019** [google/model-viewer#1801]
**im trying to do work model viewer wih react.js**

the 3D model does not appear only the poster is shown
https://codesandbox.io/s/gifted-edison-m60h2?file=/src/App.js
-

![image](https://user-images.githubusercontent.com/56547770/103931702-19819900-50f7-11eb-9be1-fd840616dc19.png)

**Comment by ajmhyd** [comment]
I cloned this repo and it works just fine locally. So I created a clean `create-react-app` project that works with `model-viewer` and uploaded it to CodeSandbox., but for some reason, it doesn't work in CodeSandbox. I get two warnings in the console:

> Problems consuming cache 

> Error: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.

Therefore I believe it is a CodeSandbox issue

**Comment by ajmhyd** [comment]
I was able to get a CodeSandbox example using `NextJS` working.
[CodeSandbox Example](https://codesandbox.io/s/github/ajmhyd/google-model-viewer-nextjs)

**Comment by nestorchura2019** [comment]
> I was able to get a CodeSandbox example using `NextJS` working.
> [CodeSandbox Example](https://codesandbox.io/s/github/ajmhyd/google-model-viewer-nextjs)

I will try locally and with clean project

**Comment by ajmhyd** [comment]
@nestorchura2019 [HERE](https://github.com/ajmhyd/google-model-viewer-react) this is a working `create-react-app` example repo I made that you can clone.

**Comment by nestorchura2019** [comment]
thanks, work in local

**Comment by motifdev** [comment]
> I was able to get a CodeSandbox example using `NextJS` working. [CodeSandbox Example](https://codesandbox.io/s/github/ajmhyd/google-model-viewer-nextjs)

thank you!!!!!!!!!!

**Comment by NasirKhalid24** [comment]
enable-pan does not work in react like in the sandbox above - any ideas?
