### ISSUE TITLE
Autoplay attribute updating on mobile device

### ISSUE THREAD

**Issue by chrismgeorge** [google/model-viewer#1814]
On a mobile device, if you initially start with "autoplay" and then remove the "autoplay" attribute (making it default to false), the animation still continues. 

Expected: When you remove the "autoplay" attribute, the model pauses.

### Version
- model-viewer: v1.3

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
hmm, maybe? I think of autoplay as telling it to play when starting model-viewer. We already have `play()` and `pause()` methods, which I think are the right way to play and pause during a session.

**Comment by chrismgeorge** [comment]
yeah, I see what you're saying, i guess it's not a super common case anyway.
