### ISSUE TITLE
camera-control is not working with Vue component

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [google/model-viewer#1816]
Hello, 
I'm using the model viewer with Vue and the camera-controls not working, which means that the model loads inside the viewer correctly, but when I try drag the model and move it around it doesn't, even it doesn't change the mouse cursor to `drag`. I used the same model with regular html page and it's working fine. 

Here is my vue process: 
```
npm install @google/model-viewer --save

import  viewer  from '@google/model-viewer'

export default {
  components: {
    viewer
...

<model-viewer style="width: 400px;height: 300px"
          src="/test.glb" auto-rotate camera-control ></model-viewer>

```

any ideas or suggestions will be highly appreciaited.

**Comment by elalish** [comment]
I think it's just a typo: the attribute should be `camera-controls`; looks like you're missing the `s`.

**Comment by ahmed-adly-khalil** [comment]
the reason is DNC (deep night coding) :) 
sorry for that
