### ISSUE TITLE
Cloning fail

### ISSUE THREAD

**Issue by devhims** [google/model-viewer#1822]
I'm getting the permission denied error when trying to clone the repo. Any clues to fix this? 

```
git clone --depth=1 git@github.com:google/model-viewer.git
cd model-viewer
Cloning into 'model-viewer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
cd: no such file or directory: model-viewer
```

**Comment by Mystickal** [comment]
You need to add an SSH Key to your github account.

See this link for more information:
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by devhims** [comment]
Thanks for the suggestion @Mystickal! It's all working now.
