### ISSUE TITLE
A few examples have a small black dot at the center of the sun and bottom of sphere.

### ISSUE THREAD

**Issue by dbbrooks-lgtm** [google/model-viewer#1828]
### Description
Devices with repro: Samsung S8+,  Pixel 4 XL

Go to https://modelviewer.dev/examples/lightingandenv/
A black spot appears at the center of the Sun in the experiments, render exposure and skybox and environment.
 
It also occurs on https://modelviewer.dev/examples/loading/#gltfModel A black dot can be seen on the bottom of the sphere. And also it can appear on both poles of the sphere. 

Note that the black dot is bigger on the S8+ then the Pixel 4 XL. It's very small, almost unnoticeable on the Pixel 4 XL.

It does not repro on Chrome on Windows.

Screenshots:
![Black_Speck_gITF_Model_Floor_Pole](https://user-images.githubusercontent.com/77503048/104785963-a2748200-5740-11eb-8b6e-e80d0b03aa2c.jpg)
![Black_Speck_gITF_Model_Ceiling_Pole](https://user-images.githubusercontent.com/77503048/104785974-a99b9000-5740-11eb-80ea-f7675e291f1a.jpg)
![Black_Spot_Center_Of_Sun](https://user-images.githubusercontent.com/77503048/104785982-ad2f1700-5740-11eb-9d9e-f96ba098218d.jpg)

### Version
- model-viewer: v1.4

### Browser Affected

- [x] Chrome, version 87.0.4280.141
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari
### OS

- [x] Android P (9), Android S (12)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
I'd guess the dot in the sun is due to a half-float overflow. The top and bottom dots look more like a divide by zero.

**Comment by elalish** [comment]
Haven't been able to repro this on modern Pixels or anything else, so I'm going to assume it was either fixed upstream in three.js or was a GPU driver bug that has aged out.
