### ISSUE TITLE
The examples page frequently glitches/ jumps position a bit while scrolling.

### ISSUE THREAD

**Issue by dbbrooks-lgtm** [google/model-viewer#1830]
### Description
Devices with repro:  Samsung S8+ , Pixel 4 XL

Go to https://modelviewer.dev/examples/loading/ and scroll the page. While scrolling from one example to the next, I noticed the whole page frequently glitches / jumps position a bit, when the next example was close to the top of the screen and the bottom of the previous example is still partly visible.

Screen recording:

https://user-images.githubusercontent.com/77503048/104786804-d6e93d80-5742-11eb-9d1c-7958ddfeaddf.mp4

### Version
- model-viewer: v1.4

### Browser Affected

- [x] Chrome, version 87.0.4280.141
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari
### OS

- [x] Android P (9),  Android S (12)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
I really enjoy the music! We need music in more bug reports...
