### ISSUE TITLE
Model-viewer is being blocked by CORS policy

### ISSUE THREAD

**Issue by Jozzhell** [google/model-viewer#1839]
**Description**

Model-viewer is being blocked by CORS policy 'No 'Access-Control-Allow-Origin' header is present on the requested resource'.

I understand others have had this problem in the past, #1598 had the same issue but put the 'asset through a proxy' - any tips on how to do this?

The website is using Cloudflare as a CDN which changes the source to website.b-cdn.net instead of website.com - could this be causing this? The model is hosted on the website.

I've tried changing the .htaccess file as suggested by my host to:

`<IfModule mod_headers.c>`
`<FilesMatch "\.(glb|ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">`
`Header set Access-Control-Allow-Origin "*"`
`</FilesMatch>`
`</IfModule>`

But this had no noticeable affect.

Any help greatly appreciated!

**Comment by elalish** [comment]
You're on the right track, I'm a little surprised `Header set Access-Control-Allow-Origin "*"` didn't fix it; that's indeed the CORS header that needs to be set on any server that's serving a GLB. I'd imagine there's just an error somewhere in how it's supposed to configure Cloudflare.

**Comment by Jozzhell** [comment]
Thanks for your help, got it working.

Changing the htaccess did work, I had to force update Cloudflare by simply re-uploading the file to the server.
