### ISSUE TITLE
I've got an animated model that is in the wrong scale

### ISSUE THREAD

**Issue by filahf** [google/model-viewer#1959]
As the title says, the scale is wrong. I've tried to edit the file in blender but the animation will glitch out.

Is there anyway to reach down to the scale functionality of three.js while in web-xr mode?

Thanks in advance

**Comment by filahf** [comment]
I managed to solve it temporarily by modifying goalScale

**Comment by elalish** [comment]
You might want to try the `scale` attribute that was just added in v1.4: https://modelviewer.dev/docs/index.html#entrydocs-scenegraph-attributes-scale
