### ISSUE TITLE
glb model floating – possible bug in bounds?

### ISSUE THREAD

**Issue by veronicamontezuma** [google/model-viewer#1974]
### Description

GLB model is showing up hovering above the floor, like so:

![105767631-031e6e80-5f3a-11eb-9561-b9f1aa75cd9a-2](https://user-images.githubusercontent.com/11477166/105852168-e11cfe80-5fc2-11eb-8078-618ee52549d4.jpg)

The model appears to be correct (usdz works fine), so I asked about this on discussions and @elalish pointed me to a possible bug in bounds="tight" and suggested I open up this issue.

#### Live Demo

glitch page:  https://distinct-jelly-substance.glitch.me

### Version

- model-viewer: v1.4.1

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Oh wait, you neglected to mention you were using SceneViewer! This appears to be their bug (likely closely related to the reason I created `bounds="tight"`). I was testing incorrectly before; `bounds="tight"` does solve the issue, which you can see by setting `shadow-intensity="1"`, and solves it for WebXR mode as well. I have no control over SceneViewer, though I'll forward the bug to them. 

Out of curiosity, why did you choose SceneViewer over WebXR? We're constantly working to improve WebXR, so it's helpful to know where the perceived gaps are.

**Comment by elalish** [comment]
@tpsiaki It looks like SceneViewer has the same bug as I just fixed in model-viewer: it appears to use a bounding box created from node bounding box corners, which is too large in the case of rotated nodes. The model floats above its shadow because its vertical bounding box is too large (or at last that's my educated guess).

**Comment by veronicamontezuma** [comment]
@elalish ah, sorry about that! I did completely forgot to mention it was SceneViewer. 
But setting the shadow-intensity changes nothing for me, unfortunately ):  did it work for you on SceneViewer as well?

We chose SceneViewer for the camera settings already built in, honestly. With WebXR not working yet on iOS, it sounded simpler to just use the native ones for now (but might actually change this if webXR has better support with model-viewer)

**Comment by elalish** [comment]
Yes, shadow-intensity simply demonstrates the problem outside of AR mode, it has no effect on SceneViewer. In fact we have little ability to customize SceneViewer at all (being a native app), which is part of why we made WebXR our default. It's also faster, as it doesn't need to re-download the model. Please give WebXR a shot and start a discussion with any deficiencies you find. Thanks!
