### ISSUE TITLE
Add configuration for shadow bias

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#198]

**Comment by elalish** [comment]
@cdata What is this?

**Comment by cdata** [comment]
This was filed in haste during a f2f triage session with @jsantell . My understanding of shadow bias is that it is meant to be a circumstantially useful correction technique to avoid certain types of artifacts associated with casting shadows (e.g., https://docs.unity3d.com/Manual/ShadowOverview.html#LightBias).

I don't think this is super high priority for us right now, but perhaps it might be if we add some kind of ground plane feature in the future.

**Comment by elalish** [comment]
This is not a parameter in our current shadow algorithm.
