### ISSUE TITLE
Android lights too bright

### ISSUE THREAD

**Issue by Aubi0ne** [google/model-viewer#1991]
### Description

Hello, I have a model that looks good on ios and pc but the android version has much too bright lights. Do you know how I could fix this?

### Version

- model-viewer: v1.4.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

# IOS
![ios](https://user-images.githubusercontent.com/60987844/106368953-e2955080-634d-11eb-9a91-7b36ebe7caa7.png)
# PC
![pc](https://user-images.githubusercontent.com/60987844/106368983-25efbf00-634e-11eb-86f1-581cfff2dcd5.png)
# Android
![android](https://user-images.githubusercontent.com/60987844/106368989-30aa5400-634e-11eb-855d-be1de451a11d.jpg)

**Comment by elalish** [comment]
Can you please include your OS and browser versions as well as the device you're testing on? It's possible this is related to a recently fixed bug, either #1763 or #1657.

**Comment by Aubi0ne** [comment]
Sure, I am testing on a oneplus 6t with Android 10 and chrome 88

**Comment by elalish** [comment]
Try that model on our [editor](https://modelviewer.dev/editor/); you can use this to deploy it to your mobile device for testing. The editor is based on master, so it's ahead of the current release. Does that fix it?

**Comment by Aubi0ne** [comment]
Yes it works on the editor ! Do you know when the next release is expected ?

**Comment by elalish** [comment]
Looks like it's your lucky day: https://github.com/google/model-viewer/releases
