### ISSUE TITLE
Textures are pixelated in google scene viewer

### ISSUE THREAD

**Issue by AksAman** [google/model-viewer#1994]
### Description

Hi, i've been using model-viewer to display models in google scene viewer ar, but sometimes, some textures are pixelated in thr ar view but looks fine in the online scene viewers (like https://arvr.google.com/scene-viewer-preview). 

#### Live Demo
https://dybo-io.github.io/webar_customizer/?id=GITHUB_ISSUE

### Version
https://unpkg.com/@google/model-viewer@1.4.1/dist/model-viewer.min.js

### Pictures
This is the pixelation in arview
![WhatsApp Image 2021-02-01 at 22 37 47](https://user-images.githubusercontent.com/28787976/106493726-89f5bd00-64df-11eb-8d84-d2de2366e13c.jpeg)
In Online scene viewer, there is no pixelation
![no_pixelation](https://user-images.githubusercontent.com/28787976/106493740-8feb9e00-64df-11eb-89e2-98fec55bc7a0.png)

### Browser Affected

- [x] Chrome (v 88.0.4324.93)
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android (Nokia 6.1 Plus, Android 10)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Those look equally pixelated to me, just one is more zoomed-in. Any model will look pixelated if you get close enough to it.
