### ISSUE TITLE
Ghost geometries on animated model

### ISSUE THREAD

**Issue by FelipeR2U** [google/model-viewer#1996]
### Description

When using an animated model, some geometries keep persisted after the first frame. As shown:

- **Expected**

![image](https://user-images.githubusercontent.com/49691924/106520685-e9da6c80-64bb-11eb-8412-56c480ba90ac.png)
- Tested on:
  - [gltf-viewer](https://gltf-viewer.donmccurdy.com/)
  - [VSCode extension - gltf tools](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode)
    - Filament and three.js 

- **model-viewer**
![image](https://user-images.githubusercontent.com/49691924/106520752-01b1f080-64bc-11eb-8349-7e6796d14efd.png)

https://user-images.githubusercontent.com/49691924/106521765-805b5d80-64bd-11eb-8de7-2baeca4e20cd.mp4

[Link to the model](https://integrations.r2u.io/viewer/products/geladeira-anima-sketch-06.glb)

I wish I could give more information about what is happening, but I haven't found the source of the issue.

#### Live Demo

https://honey-bittersweet-mink.glitch.me
https://glitch.com/edit/#!/honey-bittersweet-mink

### Version

- model-viewer: v1.4.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows 10

**Comment by elalish** [comment]
I bet I know exactly the source of this bug, and I bet it's closely related to this comment: https://github.com/google/model-viewer/pull/1979#discussion_r566484397

I bet it only repros for transparent, double-sided materials, right?

**Comment by FelipeR2U** [comment]
> 
> 
> I bet I know exactly the source of this bug, and I bet it's closely related to this comment: [#1979 (comment)](https://github.com/google/model-viewer/pull/1979#discussion_r566484397)
> 
> I bet it only repros for transparent, double-sided materials, right?

According to the designer: "Yes, and adding **backface culling** on the material solved the issue"

**Comment by elalish** [comment]
Glad you have a workaround! I still need to get this fixed...
