### ISSUE TITLE
Model Editor outputs too small, wrong aspect Image

### ISSUE THREAD

**Issue by LennartArendt** [google/model-viewer#1997]
### Description

When I generate a poster in the Model Editor the poster comes out as a way too small and almost quadratic.
Using that in our project doesnt line up at all. Excuse me if I'm missing something but I thought that is probably not intended behaviour and should be reported.

### Version

- model-viewer: v1.4.1

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows 10

**Comment by elalish** [comment]
It's working fine for me; can you put your specific repro steps and a link to your demo of the poster not lining up?

**Comment by LennartArendt** [comment]
Ok, one of the problems was my fault. Windows Remote Desktop was the cause of the image being too small ( like 400px * 500px). Probably because it reduces the pixels being rendered or something.
Tried it on my personal machine and the picture now is 1173px * 1227px. 
I will try the bigger picture in our project tomorrow and make a video for you.
I'm currently not at work since I live in germany.

the repro steps are basically:
- load glb into the model editor
- generate poster and download
- add it to the model viewer tags in the html and the proper path

Since the poster had such a small resolution that might've caused the problems. I'll report back tomorrow.

**Comment by LennartArendt** [comment]
Sorry I havent reported back! It works now. The problem really was the image being too small because of Windows Remote Desktop. The proper resolution poster scales perfectly.
