### ISSUE TITLE
Is 'modelCacheSize' being respected?

### ISSUE THREAD

**Issue by HarkSolDev** [google/model-viewer#2000]
Hi, 

I have been working with model viewer for a couple of weeks now and liking the functionality. I have recently discovered the model cache (which I previously mistook as a memory leak ) and wished to set it to zero for no caching due to the size of the models I am rendering ( 1 would also be fine ).

I have implemented what I thought would work but the memory usage continues to rise on the load of each new model.

Is the model-viewer respecting the set cached value or have I approached this incorrectly. 

Hopefully this will eventually end up in an angular project but have stripped it back to html + js for simplicity

Any help is greatly appreciated.

#### Live Demo

I have built a plunker which should demo the problem. 

When the code first loads it sets the cache size before a model viewer is added to the screen (as per docs).
I also log the previous value and it is reporting the default which made me feel good, I was looking the correct thing. 

Toggling the asset visibility adds a new model viewer to the page with a freshly loaded GLB. 

Once loaded, toggling the asset visibility removes the element from the screen. 

On a subsequent load a new model viewer is added to the page with a fresh GLB asset is loaded in the viewer ( all the same asset just named  corset0 corset1 corset2 etc )

I have been using the chrome dev tool and taking heap shots between each asset load and unload using the garbage collect button between loads and memory usage only climbs.

https://plnkr.co/edit/gp9GeEjpWO1yxaTy?open=index.html

### Version

- model-viewer: v1.4.1

### Browser Affected

Only tried it on

- [ x] Chrome
- [x ] Firefox

### OS

- [x ] Windows

**Comment by elalish** [comment]
Yes, I wouldn't be surprised to find a memory leak here. Any sleuthing you can do toward finding its source would be much appreciated! Last time I searched I didn't come up with anything conclusive, but it's probably time to try again.

**Comment by HarkSolDev** [comment]
Ahh ok fair enough, unfortunetly I don't really have the time to investigate the root issue. I am currently work arround by rendering within an iframe.

**Comment by ukito-pl** [comment]
Hi, I have the same problem with memory leak. Memory usage keeps rising after each adding/removing of model viewer component to the DOM. I digged a little bit into the source code and found out that in dispose() method of GLTFInstance class
  https://github.com/google/model-viewer/blob/eea64b56b1ade54025c894531146dd526d8123ac/packages/model-viewer/src/three-components/GLTFInstance.ts#L129-L144
 you do not dispose texture maps. I added following line in materials.forEach loop to dispose the base map if it exists:
 `(material as MeshStandardMaterial).map?.dispose();`
and in my case problem seems to dissapear. Could you guys check it out and see if it is in fact the reason of memory leak? I am not familiar with modelviewer code and I didn't test it on many models so I can't be sure if it is a correct solution.

**Comment by elalish** [comment]
I believe this was fixed in v1.6. Please let me know if you're still seeing problems like this.

**Comment by ukito-pl** [comment]
Hi, unfortunately memory leak still occurs. Here is demo: https://plnkr.co/edit/PGOfoqXN8iXuhAzk 
Toogling the view on and off for many times will eventually lead to overflow. In my case after around 70 refreshes memory starts to rise up rapidly and after 120 views opengl crashes. It can vary based on user's machine. When using model-viewer on Single Page Application memory overflow can happen very quickly (imagine online shop where each item has its own model view).

On the positive note, modelCacheSize seems to be working ok. After setting it to 0 the model is being downloaded again.

**Comment by elalish** [comment]
Thanks, can you go ahead and file a new issue for the memory leak? Looks like there's still more work to do here.
