### ISSUE TITLE
Generate an environment map in AR

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#201]

**Comment by jsantell** [comment]
Dumping some links on this topic

https://github.com/johnsietsma/ARCameraLighting
https://medium.com/@ivannesterenko/realistic-reflections-and-environment-textures-in-arkit-2-0-d8d0f1332eed
https://ieeexplore.ieee.org/document/4156036
http://old.cescg.org/CESCG-2006/papers/Hagenberg-Supan-Peter/index.html

**Comment by jsantell** [comment]
https://arxiv.org/abs/1809.08134

**Comment by elalish** [comment]
Seems to be necessary as part of #167, or alternatively, to get an estimated one from ARCore.

**Comment by elalish** [comment]
ARCore will be generating the environment map, and once that ability lands in WebXR we can make an issue for hooking it up.
