### ISSUE TITLE
RTL direction seems not supported

### ISSUE THREAD

**Issue by RouaaAlzoubi** [google/model-viewer#2021]
When the page direction is set to RTL the viewer is not working properly and the hotspot points are not appearing, is there a way to fix that  ?

**Comment by elalish** [comment]
Excellent question; I'll admit I haven't tried this. Can you post a link to an example so I can debug? Ideally fill out the whole issue template.

**Comment by elalish** [comment]
Closing as we don't have enough info to debug.

**Comment by carl2049** [comment]
`<model-viewer id="your_id" dir="ltr">`
Works for me. Hotspots back in positions. Also I'm using custom icon with bootstrap modal for popup which has also no layout issues.
