### ISSUE TITLE
Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by sunwrobert** [google/model-viewer#2034]
### Description

There's not much in terms of repro steps. We get this error when importing the latest 1.5.0 release of model-viewer. 

```
RoughnessMipmapper.js:34 Uncaught TypeError: Cannot read property 'compile' of undefined
    at new RoughnessMipmapper (model-viewer.js:53061)
    at new Renderer (model-viewer.js:56415)
    at model-viewer.js:56691
```

#### Live Demo

I believe you can just go to https://opensea.io/ and look at the console to see the error. We are importing it like so:

```
<script src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js" type="module"></script>
```

### Version

- model-viewer: v1.5.0

### Browser Affected

- [x] Chrome Version 88.0.4324.182 (Official Build) (64-bit)
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
I'm not seeing any console error, nor any obvious use of model-viewer. Is that still a good repro link?

**Comment by sunwrobert** [comment]
seems to be working now, not sure what changed 🤷🏼 . Thanks though @elalish
