### ISSUE TITLE
How to convert cameraOrbit.radius back to percentage?

### ISSUE THREAD

**Issue by ctrlventure** [google/model-viewer#2044]
i have an input where the user types in a percentage for the camera-orbit radius, for example 105% like it is by default, but that input gets updated when they use the controls on the model doing `modelViewer.getCameraOrbit()`, but the radius returned by the function is in metres, how can i convert it back to percentage?

**Comment by shamsail** [comment]
Hi, you can use this code to solve your problem.

```
function getCameraState(viewer) {
      const orbitRad = viewer.getCameraOrbit();
      return {
        orbit: {
          thetaDeg: radToDeg(orbitRad.theta),
          phiDeg: radToDeg(orbitRad.phi),
          radius: orbitRad.radius,
        },
        target: viewer.getCameraTarget(),
        fieldOfViewDeg: viewer.getFieldOfView(),
      };
    }
```
    
    ```
function radToDeg(radians) {
      return (radians * 180.0) / Math.PI;
    }
```
Hope, it will resolve your issue :)

**Comment by ctrlventure** [comment]
Hi @shamsail , thanks for the quick answer, but that's basically what i had already, the radius is still in metres, not converted back to percentage, i think i didn't explain what i was looking for correctly, basically imagine the following:

`camera-orbit="0deg 75deg 105%"`

ignoring the `theta` and `phi` (which i'm already converting back correctly) the `viewer.getCameraOrbit();` will return for example a `radius` of `6.314696804229617` which seems to be metres, how can i convert those `6.314696804229617` metres back to `105%`? 

It seems that the percentage is calculated using the bounding box of the model, not sure really how the percentage works...

**Comment by elalish** [comment]
Probably we should have a `getMaximumCameraOrbit()` function like `getMaximumFieldOfView()` to make this easy. Still, you can use `getCameraOrbit()` before the user interacts to get the initial radius (divide by 1.05 if you're using `auto` to get the actual limit). Then you can get the percent by using the ratio of current radius to this one.

**Comment by ctrlventure** [comment]
> Probably we should have a `getMaximumCameraOrbit()` function like `getMaximumFieldOfView()` to make this easy. Still, you can use `getCameraOrbit()` before the user interacts to get the initial radius (divide by 1.05 if you're using `auto` to get the actual limit). Then you can get the percent by using the ratio of current radius to this one.

That did the trick, thanks!
