### ISSUE TITLE
GLB Model with Animations Doesn't Load in Model Viewer, But Works in Babylon Viewer? 

### ISSUE THREAD

**Issue by samdelara** [google/model-viewer#2045]
### Description

I am having issues loading a GLB model with animations into the model viewer. When loading the model, it is just a white screen with nothing on it. 
![Screen Shot 2021-02-24 at 5 40 17 PM](https://user-images.githubusercontent.com/32585478/109076297-5e25bb80-76c8-11eb-969b-9825f11f9b43.png)

The warning error that was shown here does mention that there is a node with a skinned mesh that is not root, but that shouldn't be causing this type of issue in the model viewer. 
![Screen Shot 2021-02-24 at 5 39 32 PM](https://user-images.githubusercontent.com/32585478/109076426-8a413c80-76c8-11eb-8c42-b910305186b7.png)

When I take that same exported GLB into another model viewer, like Babylon, then the model appears as expected with the animation playing properly. 
![Screen Shot 2021-02-24 at 5 40 02 PM](https://user-images.githubusercontent.com/32585478/109076572-cd031480-76c8-11eb-9dad-9ecc0a96c2bf.png)

For reference, here are the components of the model within Blender:
<img width="436" alt="Screen Shot 2021-02-24 at 5 51 57 PM" src="https://user-images.githubusercontent.com/32585478/109076857-41d64e80-76c9-11eb-8888-41bdaf82e6c8.png">

When I place the model in another Google product like Google Poly, then the viewer is also initially blank, but when zoomed out, we start to see a large version of the model that is then clipped by the camera.
![poly](https://user-images.githubusercontent.com/32585478/109076941-6d593900-76c9-11eb-95e0-4e01e6360e65.png)

When launched in AR, this model similarly looks huge in comparison to what it should be in a normal viewer.
![Screenshot_20210224-180152](https://user-images.githubusercontent.com/32585478/109078291-15233680-76cb-11eb-81e0-a1d76ca5cb52.png)

This is very strange that a viewer like Babylon was able to interpret the GLB correctly, but the model viewer here looks like it is either picking up a lingering default pose of the model, or just breaking a connection within the rig, which then breaks the model.

### Browser Affected

- [ X ] Chrome

### OS

- [ X ] Android

**Comment by elalish** [comment]
Interesting. I would take those validator warnings pretty seriously. Can you update the model to fix that? Also, recall that glTF specifies that units are meters, so you've probably exported this in mm or something, which is why it looks huge. Also, we set our camera based on the resting pose of the model, so make sure you animation isn't applying some crazy scale or translation.
