### ISSUE TITLE
The position and direction of the directional light can be changed

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#205]
If the directional light is pointing straight down, OR if we are not auto-rotating, use "fake" pre-rendered shadow. Otherwise use realtime.

Depends on #207

**Comment by elalish** [comment]
@cdata I'm hoping to close this in favor of removing it entirely in #396.

**Comment by cdata** [comment]
I think I'm generally in favor of that, but we should make sure we have a well-lit path for folks who want to do this kind of thing first.

One thing I have had in mind is that a drag/drop editor could help users to position and bake directional lights into an environment map they already have (or one from a selection we offer).
