### ISSUE TITLE
Model is broken in AR Mode

### ISSUE THREAD

**Issue by Qiweih** [google/model-viewer#2060]
### Description

Hi ,

I encounter a problem using the viewer. The problem is the 3d model become broken very often in AR mode.  You can refer to the pictures attached. 
I would like to ask if it's a problem of the 3d model itself (like format) or a possible bug of the viewer? (The Model is also attached) If it's about the model itself, could you give me some tips to solve the problem?  

![Working Image](https://user-images.githubusercontent.com/27771851/109390915-65aac600-794f-11eb-8c39-db0153637ab6.jpg)
![Not Working Image](https://user-images.githubusercontent.com/27771851/109390919-6b081080-794f-11eb-9a6b-9e997b57095f.jpg)

[chair.glb.zip](https://github.com/google/model-viewer/files/6054696/chair.glb.zip)

### Version
- model-viewer: v1.5.0

### Browser Affected

- [ 87.0.4280.141] Chrome

### OS

- [ 10] Android 

Thanks in advance.

**Comment by devhims** [comment]
Hi @Qiweih, I loaded you model in https://arvr.google.com/scene-viewer-preview.
As per the error, Scene Viewer doesn't support  KHR_draco_mesh_compression in GLTF format. I suggest you retest the non-compressed version of the model on the above link, and check if the error is gone.  

<img width="1439" alt="Screenshot 2021-03-01 at 7 57 34 PM" src="https://user-images.githubusercontent.com/17825870/109511238-d9bca980-7ac8-11eb-8a20-3c543653718e.png">

**Comment by elalish** [comment]
Judging by your custom UI, I'm guessing this is using WebXR mode instead of SceneViewer? This looks like a Chrome bug we've been investigating that pops up occasionally on different devices. Is this bad render consistent, or does it flash back and forth between good and bad? FYI @klausw.

**Comment by elalish** [comment]
May be the same as #2071.

**Comment by Qiweih** [comment]
Thanks, i will try the non compressed versio @devhims . 
It's not bad render consistent, it flash back and forth between good and bad @elalish, and yes the bug only appear in ar mode.

**Comment by Qiweih** [comment]
@devhims I tried the non compressed version, it's the same result.

**Comment by klausw** [comment]
Thank you for the detailed report. I think I may have identified the underlying issue (an apparent driver bug affecting Chrome) and am working on a workaround, see https://bugs.chromium.org/p/chromium/issues/detail?id=1184085 for the technical details. Sorry about the inconvenience!

**Comment by Qiweih** [comment]
@klausw  Thanks, i test the workaround on my device, it works perfectly!
