### ISSUE TITLE
Model Does Not Appear As Expected in Google Model Viewer Compared to Other Viewers

### ISSUE THREAD

**Issue by samdelara** [google/model-viewer#2067]
I am having issues loading a GLB model with animations into the model viewer. When loading the model, it is just a white screen with nothing on it.
![Screen Shot 2021-02-24 at 5 40 17 PM](https://user-images.githubusercontent.com/32585478/109565772-f3ea8d80-7ab0-11eb-8c90-09b99ddf00fe.png)

The warning error that was shown here does mention that there is a node with a skinned mesh that is not root, but that shouldn't be causing this type of issue in the model viewer.
![Screen Shot 2021-02-24 at 5 39 32 PM](https://user-images.githubusercontent.com/32585478/109565805-fcdb5f00-7ab0-11eb-9171-7f1551bf1746.png)

When I take that same exported GLB into another model viewer, like Babylon, then the model appears as expected with the animation playing properly.
![Screen Shot 2021-02-24 at 5 40 02 PM](https://user-images.githubusercontent.com/32585478/109565829-05339a00-7ab1-11eb-9f1f-4d636da8a152.png)

For reference, here are the components of the model within Blender:
<img width="436" alt="Screen Shot 2021-02-24 at 5 51 57 PM" src="https://user-images.githubusercontent.com/32585478/109565858-0ebd0200-7ab1-11eb-9591-b5a368cbc61a.png">

When I place the model in another Google product like Google Poly, then the viewer is also initially blank, but when zoomed out, we start to see a large version of the model that is then clipped by the camera.
![poly](https://user-images.githubusercontent.com/32585478/109565915-21373b80-7ab1-11eb-93ad-a412aa36b1cb.png)

When launched in AR, this model similarly looks huge in comparison to what it should be in a normal viewer.
![Screenshot_20210224-180152](https://user-images.githubusercontent.com/32585478/109565948-2c8a6700-7ab1-11eb-988f-12e1dd8f8be5.png)

This is very strange that a viewer like Babylon was able to interpret the GLB correctly, but the model viewer here looks like it is either picking up a lingering default pose of the model, or just breaking a connection within the rig, which then breaks the model.

Browser Affected
[ X ] Chrome
OS
[ X ] Android

I can confirm that this model was created in meters and that there shouldn't be anything upscaling it to the degree that it is. In other viewers, the model looks exactly as expected and doesn't get blown up. 
<img width="695" alt="Screen Shot 2021-03-01 at 4 52 37 PM" src="https://user-images.githubusercontent.com/32585478/109564164-acfb9880-7aae-11eb-85c8-d562b87cae5e.png">

I cleared other earlier errors by exporting out only joints that were being used by the mesh. This outstanding error I have pictured was considered a semantic issue in the documentation and leads to only a warning flag vs an error flag. The warning itself also mentions that the parent transforms would not affect the skin mesh, which leads me to believe that it would cause something in my rig to not move vs. move at all, which is not the issue I've been encountering. 
![Screen Shot 2021-03-01 at 4 54 21 PM](https://user-images.githubusercontent.com/32585478/109564366-f6e47e80-7aae-11eb-94d4-c9d2ade229d5.png)

I'm happy to help clear that error, but the Blender file that the model is in is clean, so it's confusing where this issue is coming from since Google model viewer is where I'm having issues with it. 
![Screen Shot 2021-03-01 at 4 59 57 PM](https://user-images.githubusercontent.com/32585478/109564926-bdf8d980-7aaf-11eb-9c8e-65b6cff813e1.png)

Here are my current export settings as well:
<img width="444" alt="Screen Shot 2021-03-01 at 5 06 38 PM" src="https://user-images.githubusercontent.com/32585478/109565496-8cccd900-7ab0-11eb-82f0-82910ee4222f.png">

Any additional help would be appreciated!

_Originally posted by @samdelara in https://github.com/google/model-viewer/discussions/2051#discussioncomment-419822_

**Comment by elalish** [comment]
Please don't cross-post, it makes discussions much more difficult to follow. We pay just as much attention to discussions as to issues.

**Comment by samdelara** [comment]
> Please don't cross-post, it makes discussions much more difficult to follow. We pay just as much attention to discussions as to issues.

So sorry! I wasn't sure if discussions were also looked at like issues were. Won't happen again!

**Comment by delaurean** [comment]
hello there!
did you solve it? having the same issue .. and don't know if is it a export settings problem or how to fix it..
