### ISSUE TITLE
WebXR API issues while rendering 3d models.

### ISSUE THREAD

**Issue by Esteban26** [google/model-viewer#2071]
When I open the model-viewer examples from the official documentation, the viewer is slow and the models are not rendered properly. Please see the below screenshots.

https://modelviewer.dev/examples/augmentedreality/index.html#demo-container-2

### Browser Affected
- [ X] Chrome 88.0.4324.181
### OS
- [X ] Android 10.0.0.247

My device is a Huawei mate 20 lite 

![Screenshot_20210228_205258_com android chrome](https://user-images.githubusercontent.com/1881501/109574925-6a3dbe80-7ab6-11eb-86de-7ca1b36281a9.jpg)
![Screenshot_20210228_205246_com android chrome](https://user-images.githubusercontent.com/1881501/109574928-6b6eeb80-7ab6-11eb-89e5-fc69c44b34b7.jpg)
![Screenshot_20210228_205317_com android chrome](https://user-images.githubusercontent.com/1881501/109574930-6c078200-7ab6-11eb-9fd1-757239e69834.jpg)

**Comment by elalish** [comment]
@klausw Looks like someone has a very consistent repro of this Chrome bug.

**Comment by Esteban26** [comment]
@klausw just to complete the information, I'm not able to reproduce the error on Scene Viewer

**Comment by klausw** [comment]
Thank you for the detailed report. I think I may have identified the underlying issue (an apparent driver bug affecting Chrome) and am working on a workaround, see https://bugs.chromium.org/p/chromium/issues/detail?id=1184085 for the technical details. Sorry about the inconvenience!

**Comment by alew3** [comment]
On IOS 14.4 it is very slow and crashes Safari.

**Comment by klausw** [comment]
> On IOS 14.4 it is very slow and crashes Safari.

alew3@, do you want to file this as a separate issue? This one is about the WebXR mode used by Chrome on Android, and that doesn't apply to iOS.

**Comment by alew3** [comment]
@klausw will do!
