### ISSUE TITLE
AR button appearing on browser that does not support getUserMedia

### ISSUE THREAD

**Issue by cmac2992** [google/model-viewer#2097]
### Description

The AR button is appearing on a browsers that doesn't support getUserMedia. It's my understanding the AR button is only supposed to appear if it is supported by the device and browser. I'm specifically using the metamask browser on a oneplus 7pro.  
This issue is replicable on the examples. https://modelviewer.dev/examples/augmentedreality/index.html#customButton 

Sorry for no screenshots of console, not sure how to access that on metamask browser.  

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/index.html#customButton

### Version
https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js

### Browser Affected
- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari
- [ x] Metamask, version: x1.0.11 (46)

### OS

- [x] Android Oxygen OS 10.3.8.GM21AA
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

I presume this happens on iOS as well but do not have a device to confrim

### AR
- [ x] WebXR
- [x ] SceneViewer
- [ x] QuickLook

**Comment by elalish** [comment]
I think this issue would be better filed on Metamask.
