### ISSUE TITLE
Add css property touch-action: none; to <model-viewer> element.

### ISSUE THREAD

**Issue by Ubachukwu-Ibeh** [google/model-viewer#2100]
### Description

In the website demo ( https://modelviewer.dev/ ) scrolling around to view the model (astronaut) isn't smooth on mobile plus I can accidentally reload the page when scrolling downwards. The touch-action: none css property added to the <model-viewer> element of the document prevents accidental page reloads from scrolling and provides smoother scrolling.

#### Live Demo
https://drive.google.com/file/d/10VJWJNCc3g8uRA0iPaJ1-jIz4taabP5t/view?usp=drivesdk

### Version
- model-viewer: v1.5.0

### Browser Affected
- [ * ] Chrome, version: 89.0.4389.72
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ * ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
We have this as an attribute (because the CSS version of touch-action seems to be quite buggy on iOS): https://modelviewer.dev/docs/#entrydocs-stagingandcameras-attributes-touch-action

Have you tested to find that the behavior is smoother with CSS touch-action: none? That would surprise me, since it looks like you're seeing low frame rate due to GPU rendering performance.

**Comment by Ubachukwu-Ibeh** [comment]
It usually seems as if its GPU performance but touch-action: none enhances speed greatly.

**Comment by elalish** [comment]
Can you post side-by-side links so we can see the speed difference you're talking about?

**Comment by Ubachukwu-Ibeh** [comment]
> We have this as an attribute (because the CSS version of touch-action seems to be quite buggy on iOS): https://modelviewer.dev/docs/#entrydocs-stagingandcameras-attributes-touch-action
> 
> Have you tested to find that the behavior is smoother with CSS touch-action: none? That would surprise me, since it looks like you're seeing low frame rate due to GPU rendering performance.

It seems it is actually just GPU rendering performance since touch-action: pan-y has been added already. However, I noticed that with the touch-action property set to anything other than 'none' even though giving a smoother experience lags only when scrolling the page and model simultaneously but apart from that everything is fine.
