### ISSUE TITLE
AR Finger Controls on Scene Viewer

### ISSUE THREAD

**Issue by canberka** [google/model-viewer#2101]
Hello everyone!

We are comparing AR views on Android and Ios. (Scene Viewer and QuickLook)...
As we know, AR placement works on ground and wall very well. But not on ceiling.

On **QuickLook**(IOS), we can move up the object with _**2 fingers**_. So, 3D objects which are lambs, chandeliers etc. can be shown on ceilings as any other objects.

[The video on IOS](https://user-images.githubusercontent.com/36857390/110222823-2ef02500-7ee6-11eb-959a-0051e2e0e1f2.mp4)

On **Scene Viewer**(Android), we can not move it up.

Are we missing something? Or is this can be feature?

Have a healthy days...

**Comment by sercandemirtas** [comment]
You are right @canberka. On ios devices it is possible to move it up. Maybe you are right. Controls of Scene Viewer could be different. I mean not with two fingers but I also dont know how to move it up on Sceve Viewer.

**Comment by elalish** [comment]
@tpsiaki more UX feature requests.

**Comment by ouhsiu1993** [comment]
Hi :
I want to ask will model-viwer close with google poly?
