### ISSUE TITLE
Add Ambient Occlusion post-processing effect

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#211]
There is an opportunity to "bake" the AO, maybe this is good to do in the composer:
https://github.com/wwwtyro/geo-ambient-occlusion/blob/master/index.js
https://github.com/wwwtyro/geo-ambient-occlusion/issues/3

We need to weigh the value of this against the foot-gun-y-ness of having folks do this in realtime.

Depends on #213

**Comment by jsantell** [comment]
We could also look into AO baking: https://github.com/wwwtyro/geo-ambient-occlusion/issues/3
