### ISSUE TITLE
How can I disable blending(occlusion) effect in scene-viewer again?

### ISSUE THREAD

**Issue by pops-vito** [google/model-viewer#2117]
### Description

#1784
SceneViewer's "disable_occlusion=false" option has not worked since the latest Google App update.

In the "ar-placement=wall" option, "disable blending" was available.

I want Disable scene-viewer occlusion again.

### Version

- model-viewer: v1.5.0 / v1.6.0
- Google(app): v12.6.13.23.arm64 
- Google Play AR Service: v1.23.210260603

### Browser Affected

- [x] Chrome, version: 89.0.4389.86
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
If you want to disable occlusion, you'd rather have `disable_occlusion=true`, not `false`, right? We actually disable occlusion by default, so I believe you're reenabling it by setting `disable_occlusion=false`. Does that fix your problem?

**Comment by pops-vito** [comment]
This feature will not be used after this Google app update.

I used it with example link(intent://arvr.google.com/scene-viewer/1.0?mode=ar_only&**disable_occlusion=true**&file=https%3A%2F%2Fmodelviewer.dev%2Fshared-assets%2Fmodels%2FAstronaut.glb#Intent;scheme=https;package=com.google.ar.core;action=android.intent.action.VIEW;S.browser_fallback_url=https%3A%2F%2Fmodelviewer.dev%2Fexamples%2Faugmentedreality%2F%23model-viewer-no-ar-fallback;end),
 and it is an issue that occurred.

**Comment by elalish** [comment]
I don't quite understand; are you reporting an issue with Scene Viewer or `<model-viewer>`? Can you provide a link to an example website with a `<model-viewer>` element and describe what it's doing and what the expected behavior is?

**Comment by pops-vito** [comment]
[sample video link](https://drive.google.com/file/d/1_uQYfduSxIhL3Gmken7ZY2gx80ab_7MR/view?usp=sharing)

give an example on **_modeviewer.dev_**'s website.
As shown in this video, the blending(occlusion) option in the upper right is not disabled.

By the way,
I installed it because a new update came out today. - Google(app): v12.8.6.23.arm64
And the error was corrected.
Thank you.
