### ISSUE TITLE
QuickLook fails to load model displaying "Object requires a newer version of iOS." 

### ISSUE THREAD

**Issue by dbbrooks-lgtm** [google/model-viewer#2119]
### Description
QuickLook launches, but fails to load model, and displays the following message: "Object requires a newer version of iOS." 
Devices with repro: iPhone
This must be intermittent because I encountered it a few weeks ago, but it stopped reproducing before I logged a bug. 
Device: iPhone 12 pro
iOS version: 14.4.1 (latest updates installed)

Open Safari and go to https://modelviewer.dev/examples/augmentedreality/#customButton
Click on custom button ("👋 Activate AR") to launch QuickLook

Screenshot:
![Scene-viewer-custom-button-example-issue](https://user-images.githubusercontent.com/77503048/110715963-18ceb700-81bb-11eb-874c-b16484a0b340.jpg)
### Version

- model-viewer: v1.6

### Browser Affected

- [ ] Chrome, version <>
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari
### OS

- [ ] Android <>
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Interesting, but that's not SceneViewer, it's QuickLook (since it's iOS). I'm guessing there must be some kind of Safari problem happening here. Does it repro consistently?

**Comment by dbbrooks-lgtm** [comment]
Oops, I spaced on the name.
It's intermittency is a difficult question to answer. Both times I've encountered it, (a week or two apart) it reprod consistently. But in-between that time, on the same config that I tested the first time I encountered it, it did not repro.

**Comment by russkiimike** [comment]
I found that if the models weren't properly formatted or it's too big quick look won't work. Always try with the default Astronaut model and if it works then it's an issue with your model (most likely)
