### ISSUE TITLE
Memory leak after repeated adding and removing model-viewer component to the DOM

### ISSUE THREAD

**Issue by ukito-pl** [google/model-viewer#2139]
### Description

Repeated adding and removing of model-viewer component to the DOM will eventually lead to memory overflow and loss of GL Context. Use live demo to test this behaviour. In my case, after around 70 refreshes, memory starts to rise up rapidly and after 120 views opengl crashes. It can vary based on user's machine. When using model-viewer on Single Page Application memory overflow can happen very quickly (imagine online shop where each item has its own model view).

#### Live Demo
https://plnkr.co/edit/PGOfoqXN8iXuhAzk

### Version

- model-viewer: v1.6.0

### Browser Affected

- [x] Chrome, version: 89.0.4389.90
- [ ] Edge
- [x] Firefox, version 86.0
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows 10

**Comment by elalish** [comment]
@timmmeh FYI here's that memory leak.

**Comment by vrboobies** [comment]
Confirmed issue on android. Crashes the chrome browser after about 10 load/unloads.

**Comment by fgillmann** [comment]
Also confirmed for Edge (Chromium) with the plunker in the first post.
Can also confirm it for our own usage of model-viewer.

We have model-viewer running in a React website with files up to 400MB which work fine within desktop browsers and even with mobile browsers its ok for our use case, if the device is not too old.

Once you click on an image representing the object, one instance of model-viewer is created within a fullscreen modal/overlay and once the user closes the overlay, everything is discarded. 

Doing so multiple times, with the same or different objects, regardless of modelCacheSize set to 0, considerably increases the memory consumption.

Also regarding the plunker: 
I had it run 24 times in Edge, finished with model-viewer not visible any more and then just went away for 20min, and coming back, the memory usage was dropped from 1600MB down to 180MB
