### ISSUE TITLE
Wall placement experience changed in scene viewer

### ISSUE THREAD

**Issue by GabrielArakaki** [google/model-viewer#2154]
### Description

Hi guys, we've noticed that the experience of the scene viewer wall placement has changed recently in the last weeks.
As soon as the feature was implemented in model-viewer, the placement of the object was actually on the floor, but it allowed the movement in a vertical plane.
Even though it is not ideal to place a wall object on the floor, the experience itself went smoothly than the current, in which you put the object directly on the wall. We've encountered many issues moving the object around the wall, when the object meets a painting or a balcony, in which it loses the context of the wall or vertical placement, and starts moving in a horizontal plane. 

We would like to know if you know about any intent params that we could use to have the old experience again, with both the floor and the wall marker to move the object around.

Before (positioning with floor and wall markers):
https://drive.google.com/file/d/1XwW38nKsc6RSCmcGsi9kwAU-_MPjEJuX/view?usp=sharing

After (positioning directly on the wall, and the resizing is locked, so apparently it finds a horizontal plane):
https://drive.google.com/file/d/19TuPl0KZ4abKJmPRQ6VZg2lIXVRgA8Y-/view?usp=sharing

#### Live Demo

https://demos.r2u.io/react-ar-components/2021/03/24/08/34/index.html

### Version

- model-viewer: latest

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by dthery** [comment]
I saw that there were changes in the scene viewer. Is there a link to follow the releases?

**Comment by canberka** [comment]
wall placement not works well old experience seems good..

**Comment by GabrielArakaki** [comment]
Just giving a quick update of recent changes, I understand that the old experience with two markers is being brought back. But most of the time, the scene viewer silently crashes or gives the message "Couldn't load object."

Reproduced on Google App 12.14.7.23.arm64
Galaxy S10e

Best,

<img src="https://user-images.githubusercontent.com/7118128/115306759-a698ad00-a13e-11eb-8377-a503f2ca5fe7.png" width="30%">

**Comment by FelipeR2U** [comment]
> 
> 
> Just giving a quick update of recent changes, I understand that the old experience with two markers is being brought back. But most of the time, the scene viewer silently crashes or gives the message "Couldn't load object."
> 
> Reproduced on Google App 12.14.7.23.arm64
> Galaxy S10e
> 
> Best,
> 
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/7118128/115306759-a698ad00-a13e-11eb-8377-a503f2ca5fe7.png">

Related to this, I created a [new issue](https://github.com/google/model-viewer/issues/2303), since this one is about UI.

**Comment by ThorstenBux** [comment]
Does anyone know if this should be resolved? I can load the wall placement object but the UI asks me to place it on the floor even though the placement is set to 'wall'

**Comment by elalish** [comment]
I think was resolved...
