### ISSUE TITLE
Add N-context "naive" rendering mode

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#216]
This change will introduce the first additional rendering mode. The scope of this change is somewhat large because it includes implementing the ability to intelligently switch between rendering modes depending on the result os some heuristic.

Use this mode for some low threshold of model viewers on the page. Possibly the threshold should be different on mobile compared to not-mobile.

**Comment by pushmatrix** [comment]
How is progress going with this?

**Comment by cdata** [comment]
The rendering modes work is going to rear its head soon, but I'm not sure how soon. @pushmatrix Would you characterize your interest due to this issue's relevance to #268 ?

**Comment by pushmatrix** [comment]
100%

**Comment by DavidPeicho** [comment]
Right now one scene canno't be viewed in two different viewers, but if that changes in the future, having **N** WebGL contexts will be a memory killer.

Having one scene shared by two viewers isn't something stupid, for instance you could want to just have two viewers, one with a camera pointing down, and one with a camera pointing up. If the library starts at some point to implement this possibility, having N-viewer will make all the GPU duplicated **N** times unfortunately.

**Comment by elalish** [comment]
I think we're going with the approach in #995 instead, which does this for n=1.
