### ISSUE TITLE
UX Request - Two finger rotation to align with Scene Viewer controls

### ISSUE THREAD

**Issue by 60days** [google/model-viewer#2180]
I noticed this request come up in a few other multi-part issues, and I thought it might be good to have a standalone issue to track. Let me know if not though, or if it has already been decided not to make this change, and I can close/delete. 

For context, in my product this is the main item preventing the decision to use model-viewer over scene-viewer. We've given it to a few clients to test, but most have complained they cannot rotate, because they never find the single-finger method. This is especially acute with large, screen-filling objects like couches/rugs.

**Comment by elalish** [comment]
Agreed, thank you for bumping this.

**Comment by canberka** [comment]
and can we please add vertical drag movement with fingers like quicklook on ios.
