### ISSUE TITLE
ios Chrome AR Problem

### ISSUE THREAD

**Issue by sercandemirtas** [google/model-viewer#2263]
Hello all!

On my project;  When you tap ar-button on iOS Google Chrome, Quick Look is not running. As you see in the video below blue progress bar is loading when I tap ar-button. After 15-20 second or sometimes 10 second Quick Look is running but sometimes it never opens and I need to tap ar-button multiple times to open Quick Look (iPhone 7 / ios 14.4.2)

What is problem here ?

Thanks...
  
<model-viewer 

    class="a"
    id="koltuk"
    src="sari_son.glb"
    alt="3D-AR by BASE"
    reveal="manuel"
    ios-src="sarifinalios.usdz"
    ar
    >
    <input slot="ar-button" class="ar-button" value="submit" type="image" 
    src="images/ariconsiyah3.png" >

</model-viewer>

#### Live Demo
www.basebros.com/dogaltas.html

https://user-images.githubusercontent.com/68244546/113864072-20ca4880-97b3-11eb-9e9e-d86703d74255.MP4

### Version

- model-viewer: 1.6.0.

### iOS

- [ x] Chrome

### AR

 -->
- [ ] WebXR
- [ ] SceneViewer
- [x ] QuickLook

**Comment by elalish** [comment]
Good question. This sounds to be likely a quicklook or Chrome iOS bug. How big is your GLB? Does it still repro with a small one (~1 Mb)?

**Comment by canberka** [comment]
> Good question. This sounds to be likely a quicklook or Chrome iOS bug. How big is your GLB? Does it still repro with a small one (~1 Mb)?

i tried this is 2.6 mb.. it is a carpet.. Only 6 polygon with diffuse and normal texture... Safari opens but chrome is not stable. sometimes opens quickly sometimes never..

**Comment by elalish** [comment]
I filed a bug on iOS Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=1197345

If you can add any detail there, I'm sure they'll appreciate it (version numbers and such).

**Comment by sercandemirtas** [comment]
@elalish Thank you for posting my bug. I added version number on post.

**Comment by elalish** [comment]
Closing this and reopening #2449, since the repro link here doesn't exist anymore.
