### ISSUE TITLE
Model viewer not working

### ISSUE THREAD

**Issue by lilyntalmers** [google/model-viewer#2281]
My model-viewer project suddenly stopped working on one of my phone. But it does work on my other phone. It was working fine about a week ago. Since then I haven't changed anything in the code. But suddenly it's not working. I have also checked the demo projects using that phone and the demo projects are also not working.

My hypothesis is: Someone changed something in a package which caused it to break.

**Comment by elalish** [comment]
I'm going to close this unless you fill out the issue template. I have no idea what you mean by "not working". I need all of the template info in order to debug.
