### ISSUE TITLE
model-viewer not loading on iOS

### ISSUE THREAD

**Issue by antekj** [google/model-viewer#2282]
Hello,
All of my model-viewer - based experiences have stopped working on iOS recently. 
The problem can be reproduced on https://unicef-ar.org/high-performance-tent/ with the following user agent: 
Mozilla/5.0 (Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.20.25 (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27

On Android it keeps working well.

Anybody with a similar problem maybe?
I'd appreciate any suggestions, thanks!

**Comment by antekj** [comment]
I have just realised that the problem seems to have been introduced globally, even here for example: https://modelviewer.dev/examples/augmentedreality/

**Comment by antekj** [comment]
A little update, only one of my models still work on iPhones: https://unicef-ar.org/nanosatellite-test
No idea what is the difference, I used the same workflow for preparing that .glb model as all the other models that don't work (3ds max -> FBX -> convert to GLB).

**Comment by antekj** [comment]
One more thing to specify: it's only about the .glb model, not even the .usdz. In that example I linked to in previous post, whenever I swap the .glb to anything else, boom and it stops working on iPhones.

**Comment by antekj** [comment]
Ok, I must've been stuck with an outdated model-viewer.js. 
This link works: https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js !

**Comment by elalish** [comment]
Great! Let us know if there's anything to fix.
