### ISSUE TITLE
Model Viewer not working in my iphone's  chrome 

### ISSUE THREAD

**Issue by pragneshmali99** [google/model-viewer#2288]
Model Viewer not working in my iphone's  chrome

**Comment by antekj** [comment]
Probably the same problem I've mentioned a few hours ago.
Interestingly, one of my models still works on iPhones: https://unicef-ar.org/nanosatellite-test/
I am still trying to figure out what aspect of this model is different from all of the ones that don't work.

**Comment by antekj** [comment]
@pragneshmali99 Are you linking to this version of the package? https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js
This is what I needed to change to make my model viewer work on iPhones again :)

**Comment by elalish** [comment]
Based on the comments, I'm going to assume this has already been fixed.
