### ISSUE TITLE
Distorted Models in some browsers

### ISSUE THREAD

**Issue by sprengerst** [google/model-viewer#2292]
Hi,

we have a problem with one of our models.

![image](https://user-images.githubusercontent.com/6854862/114876771-f30e8080-9dfe-11eb-83ca-2c98d8af9783.png)

It seems that on some browsers it is distorted.

https://mazing-ar.com/pro/heiku/chicago/

Are you aware of this issue? Or do you maybe know what could be the cause?

Best,
Stefan

**Comment by elalish** [comment]
Please fill out the issue template instead of deleting it! It looks fine to me, but I'm not sure which browsers have the problem, nor what the problem looks like (is your image one that's good or bad?). A comparison would be great.

**Comment by elalish** [comment]
No repro.
