### ISSUE TITLE
WebXR - the previous shadow remains in view while the new 3d model is loading 

### ISSUE THREAD

**Issue by Esteban26** [google/model-viewer#2321]
I'm playing around with the webxr example and I noticed few issues when changing the 3d model at runtime,

I initialize model viewer with this model:
![image](https://user-images.githubusercontent.com/1881501/115940945-f93cd680-a468-11eb-91b1-0fbd5173affa.png)

Then I change it with the below 3d model by changing the src property.
![image](https://user-images.githubusercontent.com/1881501/115940965-0954b600-a469-11eb-95e7-2b70bc477c91.png)

While the new 3d model is loading, the first model is removed but the shadow is still there. Please see the below image.

![image](https://user-images.githubusercontent.com/1881501/115941012-37d29100-a469-11eb-8c0e-e1a68ca443ac.png)

**Comment by canberka** [comment]
you should change the variant of model not the 3d model, if they are same model but different color... so this leads to very fast change and more usefull for users. 

But this is not answer of your question.

**Comment by elalish** [comment]
@Esteban26 Can you please fill out the issue template? At the very least I need a link and steps to repro.

**Comment by Esteban26** [comment]
Hi @elalish , sorry for the delay I'm still able to reproduce the issue, I'll share an example with you at the beginning of the next week,

**Comment by Esteban26** [comment]
Hi @elalish this is the demo page:  https://demo.cylindo.com/viewer/examples/webxr/test/V11-webxr-outside-viewer.html

Chrome 90
Huawei mate 20 lite
Model viewer source: https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js

To launch AR you need to press the View in AR button first, it opens model viewer, webxr is set as default when you change the source for example modelViewerInstance.src = 'new_glb_path_file.glb' the previous shadow remains until the new model is loaded.

**Comment by elalish** [comment]
Thank you, I can repro. I just did some significant changes to the WebXR UX that haven't been released yet. Can you check if it repros with the master version? https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js

I would think I'd have noticed this on https://modelviewer.dev/examples/augmentedreality/#webXR; are you doing anything special?

**Comment by Esteban26** [comment]
Hi @elalish, no, I'm just changing the source at runtime.

**Comment by elalish** [comment]
This no longer repros, so I think it was fixed as part of v1.7

**Comment by Esteban26** [comment]
Hi @elalish, yes, you're right this is not failing with the new fixes you releasde, sorry for the delay on my response.
