### ISSUE TITLE
[Model viewer testing] Asset getting launched in AR mode even after denying the camera permission 

### ISSUE THREAD

**Issue by DoniaBinu** [google/model-viewer#2343]
### Description
Asset getting launched in AR mode even after denying the camera permission 
Steps:
1. Take the link https://modelviewer.dev/examples/loading/ in the browser
2. Go to Scene Viewer link
3. Launch the model in AR mode
4. Deny the camera permission when message appeared

#### Live Demo
Screenshot attached
![screen](https://user-images.githubusercontent.com/83030762/116611587-64642e00-a8eb-11eb-9a23-22d32728b9e1.png)

### Version
Hardware: Pixel 4a, Samsung S9
- model-viewer: vX.X.X

### Browser Affected

- [ *] Chrome, version: 90
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [* ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
@tpsiaki @AdrianAtGoogle What is the expected behavior when the scene viewer permission is denied?

**Comment by DoniaBinu** [comment]
Video of the issue Uploaded :https://drive.google.com/file/d/18_XVOc7RH6asKyxUDQ1ZhmI_HMB5tLYY/view?usp=sharing&resourcekey=0-Z17pkHR0Bu7YoFqLcLrmiw

**Comment by FelipeR2U** [comment]
There is also a problem with this prompt in `ar-only` mode, in which an alert fires with "Couldn't load object" and closes the app.

**Comment by lucasmatheustesta** [comment]
I have the same problem, @FelipeR2U . A "solution" is to open the "Google" application type in "Zebra" plot the 3D (that uses SceneViewer also) and then the camera permission is set again.

This is causing me a lot of problems, since when opening a 3D from ModelViewer, the user could not give the permission, only a message "Couldn't load object" and closes the app

**Comment by elalish** [comment]
We just made a workaround for this; try v1.7.1

**Comment by bhouston** [comment]
We (Threekit) are seeing really weird behaviour across a lot of devices that appears to have started fairly recently - maybe in the last week -- it seem very related to this bug report:

https://twitter.com/BenHouston3D/status/1395457929248186368

Basically sometimes permissions are not asked and then AR fails to load if started from a SceneViewer intent.  Others are seeing it as well.

**Comment by bhouston** [comment]
@elalish where should I file the bug report on SceneViewer, which is the underlying cause?  Or is this already filed somewhere?  I know from Twitter it is also affecting Flipcart's AR work.

**Comment by bhouston** [comment]
Ah, just change the intent URL from "mode=ar_only" to "mode=ar_preferred" and that works around the issue.

**Comment by elalish** [comment]
Yeah, Scene Viewer already has a fix, but it'll take a week or two to roll out, so this work around is recommended.

**Comment by bhouston** [comment]
The work around doesn't actually seem to work.  I think it only appears to work because it is a non-deterministic bug.  Thanks for confirming a fix will get rolled out soon.

**Comment by elalish** [comment]
This was worked-around in v1.7.1 and a Scene Viewer fix is also forthcoming.

**Comment by lucasmatheustesta** [comment]
Thank you @elalish
