### ISSUE TITLE
[Model viewer testing][Samsung S9] Not able to see Annotations in AR mode

### ISSUE THREAD

**Issue by DoniaBinu** [google/model-viewer#2344]
### Description

I am not able to see Annotations like hotspot and dimentions in AR mode on Samsung S9 device. 
But its appeared in 3D when transitions to 3D mode

#### Live Demo
Video : https://drive.google.com/file/d/1PQ66zKvOitJSR1owE5h6LqJ2Od5byWTa/view?usp=sharing&resourcekey=0-hQmcWvdtZ1d3Xs7k5gGRmA
### Version
Hardware :Samsung S9
Browser : Chrome 90
-->
- model-viewer: vX.X.X

### Browser Affected

- [ *] Chrome, version: 90
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by sercandemirtas** [comment]
Can not access your link. Please make it public.

**Comment by elalish** [comment]
I believe this is fixed by #2342.
