### ISSUE TITLE
[SceneViewer] AR not working on new installations/after new update.

### ISSUE THREAD

**Issue by ukito-pl** [google/model-viewer#2381]
### Description

Hi,
after update of Google App from 14th May 2021 (v. 12.18.11.23.arm) SceneViewer stopped working in "ar_only" mode which is used in model-viewer.

### To reproduce
1. Uninstall updates of [Google App](https://play.google.com/store/apps/details?id=com.google.android.googlequicksearchbox)
2. Install them again
3. Go to https://modelviewer.dev/examples/augmentedreality/#sceneViewer and try to place model in AR.
It results in error such as "File could not be loaded". It seems it happens because SceneViewer doesn't have permissions to camera etc. and app fails and exits before user can grant those permissions. If I run SceneViewer app in "3d_preferred" mode which is used in Google AR examples (like duck or other animals) and then switch to ar mode, I can grant those permissions and model loads in AR. After I grant those permissions opening any model in "ar_only" mode (via model-viewer) also works correctly.

It is really a **major** bug that just breaks usage of SceneViewer.

### OS
- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by Adolar13** [comment]
Entering AR-Mode from none "ar_only" has the same problem.

**Comment by Adolar13** [comment]
Not just new installations. All devices which have the update installed have this problem. Even if permissions were previously granted and appear in app settings. Uninstalling the update aka switching to preinstalled Google App version is working.

**Comment by julienbfabre** [comment]
We have the same problem, scene viewer doesn't open any of the objects on android 10, but seems to work fine on Android 11.

**Comment by SGECZ** [comment]
After whining for weeks about the previous bug, I am now in the funny situation that it works on my phone. I am on Samsung Note10+ with Android 11, the Google version is the one from May 14th

**Comment by Gaffen** [comment]
I am also experiencing the issue on android 11

**Comment by wearept** [comment]
All our android devices at the office are experiening the same issue.

"It is really a major bug that just breaks usage of SceneViewer."

Yes it is!

Any ideia how to escalate this issue to the google UI team?

**Comment by SGECZ** [comment]
> 
> 
> All our android devices at the office are experiening the same issue.
> 
> "It is really a major bug that just breaks usage of SceneViewer."
> 
> Yes it is!
> 
> Any ideia how to escalate this issue to the google UI team?

by adding @AdrianAtGoogle and @tpsiaki - I think

**Comment by elalish** [comment]
While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

**Comment by SGECZ** [comment]
> 
> 
> While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

My biggest issue is cross-platform compatibility. We run https://cldxr.com - the goal is that our clients upload one file once - and then it works no matter if the end users are on iOS or Android. And it needs to be possible to standardize things.
Scene viewer is easy to handle, the USDZ for iOS we auto-generate. 
If you can offer better solutions we can integrate and works on Android and iOS out of the box - perfect.

**Comment by elalish** [comment]
We put WebXR as our default AR mode precisely because it's available on all the devices Scene Viewer is, and doesn't require an extra download of either file or app (Scene Viewer is part of the Google App, which not everyone has). It also stays in the browser, which gives you much more control of the experience and analytics. Give it a try and let us know if you find anything lacking. The console will now report errors in our latest version and explain why a particular AR mode was chosen.

**Comment by SGECZ** [comment]
Well - was excited to see a Google update, thought you guys are quick, but it was the update that now also killed it on my phone... <sigh>

**Comment by FelipeR2U** [comment]
> 
> 
> While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

@elalish, last time we tested WebXR (2020Q3) the experience seemed very slower than Scene-Viewer. Meaning that in the same device the FPS was higher in Scene-Viewer AR Mode. I really prefer the ability to make interactive models and UIs on WebXR, but the overall flow of the experience is what made me choose not to change. Since the new updates involves a lot of WebXR features, I'm about to test the new version and see if we can suggest anything. Maybe there should be a space for feedback? 🤔

**Comment by FelipeR2U** [comment]
About the issue, I recorded the current problem:


https://user-images.githubusercontent.com/49691924/118556832-ba81ff80-b73a-11eb-8c46-ba61d600e172.mp4

**Comment by elalish** [comment]
@FelipeR2U Feel free to open a discussion about WebXR! Feedback would be much appreciated.

**Comment by timmmeh** [comment]
Submitted a SceneViewer fix for this issue - should be out in the next release

**Comment by 60days** [comment]
For people experiencing this issue who have control over their intent URLs, switching to 'mode=ar_preferred' allows the camera permission popup to be accepted and the AR session started without the "couldn't load object" popover, although the user has a flash of the non-AR 3D UI. 

We're lucky enough to generate all our intent URLs on-the-fly (even for QRs, which was a worry!) so we're switching to this until the update resolves the issue.

**Comment by ukito-pl** [comment]
> While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

WebXR mode is very cool, gives a lot of extra features and possibilities. Generally it would be my "go to" technology regarding AR, but it is currently supported only on chrome and samsung browsers and doesn't work on IOS devices at all. Having extra features that are only available on specific devices/browsers is not a good idea and limiting a solution only to Android and Chrome is also not a good idea. Until Safari and other browsers implement WebXR I don't think I will use it in my cross-platform projects.

Regarding WebXR implementation:
- there is no user guidance, model just shows up in front of user and places on the floor when it finds it. But there is no prompt or anything saying that user should point the camera on the ground and move a phone from side to side to find a floor.
- no scale information when scaling model

**Comment by ideathingdev** [comment]
> While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

WebXR is great, the only missing feature stopping me from using it is the possibility for the user to capture photos and videos as this is highly requested (and expected, unfortunately) by clients.

**Comment by maciekglowka** [comment]
> 
> 
> While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.

I use WebXR as a default, BUT if a user opens link in an app (which is a lot of cases) than it uses Android WebView instead of Chrome - and then SceneViewer is the only option and a nice fallback. Otherwise my page would be broken.

**Comment by SGECZ** [comment]
> 
> 
> > While the Scene Viewer issue is being worked on, this seems like a good time to ask about your thoughts on WebXR. What are the reasons you prefer Scene Viewer to WebXR mode? We just [improved](https://github.com/google/model-viewer/releases/tag/v1.7.0) the object placement flow in WebXR and added two-finger rotation. I'm curious what our next priorities should be, since WebXR mode is the only way to enable hotspots and variants and such.
> 
> WebXR mode is very cool, gives a lot of extra features and possibilities. Generally it would be my "go to" technology regarding AR, but it is currently supported only on chrome and samsung browsers and doesn't work on IOS devices at all. Having extra features that are only available on specific devices/browsers is not a good idea and limiting a solution only to Android and Chrome is also not a good idea. Until Safari and other browsers implement WebXR I don't think I will use it in my cross-platform projects.
> 

I honestly don't mind too much telling a mobile user to use Chrome if they are on Android and as far as the iOS issue is concerned, I understand that this is covered (mostly) with the latest 1.7 model viewer update?


> Regarding WebXR implementation:
> 
>     * there is no user guidance, model just shows up in front of user and places on the floor when it finds it. But there is no prompt or anything saying that user should point the camera on the ground and move a phone from side to side to find a floor.
> 
>     * no scale information when scaling model

Those are very good points - plus the fact that scene viewer easily allows to capture photos and videos.

**Comment by AndresSalomon1990** [comment]
Same error is happening to me when using scene-viewer. WIth webxr works fine. Hoping you can fix it.

**Comment by SGECZ** [comment]
> 
> 
> For people experiencing this issue who have control over their intent URLs, switching to 'mode=ar_preferred' allows the camera permission popup to be accepted and the AR session started without the "couldn't load object" popover, although the user has a flash of the non-AR 3D UI.
> 
> We're lucky enough to generate all our intent URLs on-the-fly (even for QRs, which was a worry!) so we're switching to this until the update resolves the issue.

that was a good tip, thanks!

**Comment by maciekglowka** [comment]
Could you perhaps elaborate on the intent URL modification? Should I intercept model-viewer event to modify it?

**Comment by MicDesign1** [comment]
There is also something strange going on with the iOS side. After viewing the USDz file in AR for about a minute its lists the file name and size with a 'done' prompt...? It's never done this before.

**Comment by elalish** [comment]
@MicDesign1 That sounds worthy of it's own issue, given it's unrelated to this Scene Viewer thread (we can't launch Scene Viewer on iOS, only Quick Look). Can you fill out the issue template so we can repro? A screen recording would be great too.
