### ISSUE TITLE
Transparency broken after recent update

### ISSUE THREAD

**Issue by Kibetho** [google/model-viewer#2387]
Description
I've been publishing some 3D models to IPFS using model-viewer called externally to display them

![image](https://user-images.githubusercontent.com/37402533/118537953-79dbb380-b745-11eb-874d-5e0c002479e4.png)

Up until about a couple of hours back the model was visible as in the above image, but if I go to it now via Mobile or desktop it is distorted, zoomed out and seems to contain an additional transparent artefact

![image](https://user-images.githubusercontent.com/37402533/118537922-70eae200-b745-11eb-8939-e2691b990b0b.png)

With IPFS there should not have been any change to my file from when it was working until when it wasn't - so I'm wondering if something might have changed in a recent update.

Live Demo
https://bafybeibcu6a7vj47jfpjnv763wue2vdkrkpylrggknmwkssj2uumjc77gm.ipfs.infura-ipfs.io/

Version
- model-viewer: v1.7.0

Browser
- [x ] Chrome, version: xx.x.xxxx.xx
- [x ] Edge
- [x ] Firefox
- [ ] IE
- [ x] Safari

OS
- [ x] Android
- [ x] iOS
- [ ] Linux
- [ ] MacOS
- [ x] Windows

**Comment by elalish** [comment]
Please don't cross-post.
