### ISSUE TITLE
the model viewer is failing.

### ISSUE THREAD

**Issue by Ax-Zis** [google/model-viewer#2389]
### Description

I want to enter from my mobile to see the objects from my camera and I get a popup saying "The object cannot be loaded, it seems that an error occurred with this object".

What can it be or does someone have the solution?
Greetings...

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Please fill out the whole issue template! At the very least I need a link to reproduce your problem. And screenshot or video would also be very helpful.

**Comment by Yehoyakim** [comment]
maybe the same problem in #2381?

**Comment by Ax-Zis** [comment]
Here is a video of what happens to me.
https://drive.google.com/file/d/1xiMqbik2cFHforBcVPUM6EijUC3g10Os/view?usp=sharing

**Comment by AndresSalomon1990** [comment]
Same is happening to me. Is when using the scene-viewer ar-mode. With webxr works fine.

**Comment by elalish** [comment]
I'm closing this as a dupe of #2381 so we can keep all the discussion in one place.
