### ISSUE TITLE
Model renders black after reload (missing textures)

### ISSUE THREAD

**Issue by maciekglowka** [google/model-viewer#2396]
### Description

After updating to 1.7 I have a model swap issue in Firefox. I change models by setting different 'src' attributes.
When model is first loaded it shows ok. But then when I swap it to another and than swap back it renders without textures (eg. black).
When the page is reloaded (browser refresh) it is working again.
Does not happen on Chrome or Edge.
[I was playing a bit with iOS Safari as well and I think it also happened - but don't have access now to confirm 100%.]

#### Live Demo
https://pikle.eu/product_detail?pk=24
When you enter the page it will show the oak sideboard, press '2' below the 3d view to swap the model to pink one, and then '1' again to go back to the oak one - which will loose it textures and show black.

### Version

- model-viewer: v1.7.0

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

![Przechwytywanie](https://user-images.githubusercontent.com/25125159/118658604-d645de00-b7ec-11eb-8ced-6cca43ddd7e7.PNG)

**Comment by elalish** [comment]
Thank you, we already had this reported in Safari, but it'll be easier to debug in Firefox. I have a repro.

**Comment by maciekglowka** [comment]
If it helps - it happens very ocassionaly before 1.7 (and perhaps rather on exiting AR mode). Now after the update it is 100% consistent for me.

**Comment by elalish** [comment]
Interesting; I've been tracking a bug for awhile that has been quite hard to repro, but in that case the model was completely black (no reflection at all). This is the first I'm seeing just black textures. Which version were seeing occasionally before, if you remember?

**Comment by maciekglowka** [comment]
I think the previous black bug was a while ago, so maybe like 1.5? But I am guessing a bit.
But indeed it was completely black.
Now it is definitely only textures dropping.

If you look at this example:
https://pikle.eu/product_detail?pk=37

Here I dont have color textures, it is just pure material color. So on swapping everything is fine. However I have a roughness texture (small flaky patter)n - so if you swap back and forth you end up with highly reflective smooth model (black roughness i believe).

Sorry that the page is Polish only at the moment - but you can swap models with arrows or digits below the 3d view :)
