### ISSUE TITLE
empty USDZ when entering AR before load.

### ISSUE THREAD

**Issue by colordrop** [google/model-viewer#2397]
### Description

Using the newest version of model-viewer (1.7.0) with auto-generated USDZ files I'm unable to run AR on some Apple devices.  I've tested iPhones: 6, 8, X, XR, 11, 12, 12PRO and iPads: Pro, 6th gen. It happens only with models that have swappable textures but I don't see any pattern - for example, AR works on 2 out of 3 iPhones 12 I've tested (iOS and browsers are up to date). 
After AR button is tapped progress bar on the top shows again but nothing else happens - quicklook is not launched. Model-viewer without swappable textures works fine on every device I tried. 
It happens on Safari and Chrome but on some devices AR work only on Safari. 

#### Live Demo
https://colordrop.pl/ar-iker/

### Version

- model-viewer: v1.7.0

### Browser Affected

- [ ] Chrome, version: 90.0.4430.78
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [X] QuickLook

**Comment by elalish** [comment]
Can you be a little more specific about what doesn't work? Do you get an error message? A screen recording would be helpful. Your site is working on my iPhone SE. There's already a known issue that Chrome on iOS does not handle auto-generated USDZ.

**Comment by FelipeR2U** [comment]
If I understood correctly, I'm facing a similar issue. My application uses `exportScene` to get a GLB and we convert it to USDZ in a backend service. But since the new USDZ auto-generation update we tried opening AR directly from model-viewer with the following result:

https://user-images.githubusercontent.com/49691924/119195605-53768a80-ba5b-11eb-8e66-c13c7a44f624.mp4

It's way faster, but there seems to be some missing textures...

**Comment by elalish** [comment]
I believe what it's actually missing is baseColorFactor multiplication. Hopefully fixed soon: https://github.com/mrdoob/three.js/pull/21872

**Comment by colordrop** [comment]
Here you can see the AR button disappear after tapping on it.
https://user-images.githubusercontent.com/16795504/119459781-4b119e80-bd3e-11eb-95a1-1288c930354e.mp4

And here Quick Look starts but the model won't load 
https://user-images.githubusercontent.com/16795504/119459868-611f5f00-bd3e-11eb-9329-0313b38c29f4.mp4

**Comment by elalish** [comment]
> edit: With reveal attribute set to "interaction" tapping the AR button before loading the 3d model generates empty usdz

This is definitely a bug! You seem to be talking about several things; are there other issues as well? If so, I need details of device, browser, and repro link to go along with each video/issue.

**Comment by elalish** [comment]
In fact, better to have separate issues for different problems. Please open a new issue if any of your other problems persist.
