### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by zmnv** [google/model-viewer#2419]
Hello there. General Kenobi.

I created a PNG  Thumbnails Batch Renderer with your awesome project and sometimes it stops just because source model file has something like 'problems with materials' i think.. BUT. I can see the model.. 
Idk how to organize try catch with model-viewer just with vanilla js... sorry))

Can you handle this case without type error please? 

```
model-viewer.js:56233 Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined
    at new Sm (model-viewer.js:56233)
    at HTMLElement.[onModelLoad] (model-viewer.js:56342)
    at vc.<anonymous> (model-viewer.js:48752)
    at vc.dispatchEvent (model-viewer.js:1689)
    at vc.setupScene (model-viewer.js:44589)
    at vc.setSource (model-viewer.js:44577)
    at async HTMLElement.[updateSource] (model-viewer.js:49041)
    at async HTMLElement.[updateSource] (model-viewer.js:53334)
```

Screens:

![image](https://user-images.githubusercontent.com/25253501/119393144-3e0e9400-bcd9-11eb-9b46-3bd98bf4c166.png)

![image](https://user-images.githubusercontent.com/25253501/119392672-ba54a780-bcd8-11eb-815b-ed6639347aae.png)

From:

```
class Model {
    constructor(correlatedSceneGraph, onUpdate = () => { }) {
        this[_a] = [];
        const { gltf, gltfElementMap } = correlatedSceneGraph;
        gltf.materials.forEach(material => {
            this[$materials].push(new Material(onUpdate, gltf, material, gltfElementMap.get(material)));
        });
    }
```

source glb (14mb) (not mine)
https://cloudflare-ipfs.com/ipfs/QmeqKjz7KLigLis1AJGbuu22uXdgGdNaVneFF1MiDkoaPJ

from object 6137 at hic et nunc gallery.

I've checked source file and don't see any "materials" property.

**Comment by elalish** [comment]
This looks like a regression; we have code specifically to handle this case where the glTF only has the default material.

**Comment by zmnv** [comment]
@elalish Sorry for the question. Is any way to update `onerror` event to provide error handle in this situation:

> connect google model viewer as <script> html
> work with model viewer as `const viewer =  document.getElementById("viewer");`
> viewer.onerror 

or `onerror` event ONLY for http requests?

Now sometimes I get:
```
Uncaught (in promise) Error: Unable to retrieve canvas blob
    at model-viewer.min.js:48965
```
![image](https://user-images.githubusercontent.com/25253501/119404950-3525be80-bce9-11eb-81f8-dac24db7f245.png)

Now it's handled by module developer but I can't catch this...

And I have not access to catch this. Im not so smart in js and if it's real for now -- I will google more...

User story: 'as user or developer I want to see/set error poster to indicate bad situation not from a console'

**Comment by elalish** [comment]
Since `toBlob()` returns a promise, I believe you can catch errors this way: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch

**Comment by zmnv** [comment]
@elalish aaaaAAaaa that toBlob... yes.. I use this in MY script file as 'viewer.toBlob' sorry I forgot.

I just recorded the video of my case: youtube.com/watch?v=eqLrYNmI2xw. 
It's sounds like 'I want to see RED <ERROR> letters in png thumbnails of files'. 

thank you!

**Comment by elalish** [comment]
Okay, looks like this wasn't a regression after all. Just a case I had tried and apparently failed to fix.
