### ISSUE TITLE
SceneViewer .glb model loading fails with latest Google app installed

### ISSUE THREAD

**Issue by DerrickBarra** [google/model-viewer#2432]
Hi devs,

Our team is experiencing an error when launching SceneViewer AR via an intent string on the web as shown in the documentation.

![image](https://user-images.githubusercontent.com/20777145/119699417-27268980-be20-11eb-82de-0f5987ea7045.png)

The [glb we're testing](https://bxrtest.s3.amazonaws.com/BrandXR_Cube.glb) is here.

The error we're seeing is...

![image](https://user-images.githubusercontent.com/20777145/119699666-6523ad80-be20-11eb-90eb-f414a93afa5c.png)

This error happens on Android phones with the latest Google app installed (May 24, 2021) [12.19.11.23.arm64].

Bug experienced across multiple phones...

Samsung Galaxy M31
Redmi Note 9 
One Plus 8T
Xaomi A3
Redmi Note 8 Pro
Samsung Galaxy S8
Samsung Galaxy S9
Samsung Galaxy S10 Plus
Samsung Galaxy S20 Plus

If you have older versions of the Google app, the bug does not occur (we haven't figured out exactly what version number the bug started in)

**Comment by canberka** [comment]
Hi we are facing with same issue.. this issue comes from permission access, if you managed to press give access button this issue will never appear again. I think this code let the error remove 
<script>
  document.querySelector("#model-viewer").addEventListener('ar-status', (event) => {
    if(event.detail.status === 'failed'){
      const error = document.querySelector("#error");
      error.classList.remove('hide');
      error.addEventListener('transitionend',(event) => {
        error.classList.add('hide');
      });
    }
  });
</script>
<style>
  #error {
    background-color: #ffffffdd;
    border-radius: 16px;
    padding: 16px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate3d(-50%, -50%, 0);
    transition: opacity 0.3s;
  }
  #error.hide {
    opacity: 0;
    visibility: hidden;
    transition: visibility 2s, opacity 1s 1s;
  }
</style>


Can you try? This code from 
![Screenshot_20210531-150621_Chrome](https://user-images.githubusercontent.com/36857390/120190836-ccc36980-c221-11eb-986e-245697c26738.jpg)

**Comment by mrVers** [comment]
I had the same problem. Realised I was running version `1.4.1` and upgrading to `1.7.1` fixed the issue for me.
Now it pops up the same screen, but without the "Couldn't load the object" error.
After giving it access, it works as it should.

**Comment by DerrickBarra** [comment]
@elalish : FYI this proposed workaround does not help us, as we are loading SceneViewer via an intent string via button press on our website. We do not intend to integrate Model Viewer, and based on the documentation this shouldn't be a problem to load directly into SceneViewer and skip Model Viewer.

**Comment by elalish** [comment]
@DerrickBarra I believe you can work around this by using ar_preferred instead of ar_only. Scene Viewer is rolling out a fix currently for the ar_only bug.

**Comment by DerrickBarra** [comment]
@elalish Thanks, you're a life saver!
