### ISSUE TITLE
AR doesn't workion chrome for iOS

### ISSUE THREAD

**Issue by romanexceed** [google/model-viewer#2449]
### Description

The title says it all, AR doesn't work as it should on chrome for iOS.  For android, all is as usual. And in Safari AR works for iOS too, but not on chrome, quick-look is started after a few minutes if it is started all.

On Firefox, quick-look is opening quite slow too.

#### Live Demo
link of the webpage: https://viewarly.com/arplacement?slug=beckholmen-briefcase-2

### Version
- model-viewer: v1.7.2

### Browser Affected
- [x] Chrome, version: 90.0.4430.216
- [ ] Edge
- [x] Firefox version: 33.1 (4629)
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS  14.5.1
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by sercandemirtas** [comment]
@romanexceed we are having same problem too and also when we try on modelviewer.dev nothing happen after tapping ar-button. It just reload model-viewer.  

Chrome version 90.0.4430.216

model-viewer 1.7.2

**Comment by romanexceed** [comment]
Closing the issue as it has already been reported here: https://github.com/google/model-viewer/issues/2263

**Comment by elalish** [comment]
Reopening since #2263 doesn't have a functional repro link anymore.

**Comment by CanerErdogan** [comment]
Any updates on this? (with much shyness)

**Comment by elalish** [comment]
I filed a bug on iOS Chrome a while back: https://bugs.chromium.org/p/chromium/issues/detail?id=1197345

Please ping them there to help get it prioritized.

**Comment by pikilipita** [comment]
Has the Chrome iOS bug been resolved since July?

**Comment by themightyatom** [comment]
This is still a serious bug. After recommending users to use Chrome on iOS for best experience, I'm now having to send them to Safari again. It's seems to be a Chrome issue, but one best fixed with collaboration with the model-viewer team.

**Comment by DariaYakovleva** [comment]
Same problem. Any update with chrome ios?
Thanks!

**Comment by nobleach** [comment]
We have noticed that we are able to enter an AR experience on Chrome on iOS, but upon returning to the browser, all scrolling is broken - even after a hard refresh. The only thing that works is opening a new tab.

**Comment by elalish** [comment]
@nobleach Hmm, that sounds like a new and different iOS Chrome problem. Would you mind filing a Chromium bug and linking it here?

**Comment by nobleach** [comment]
@elalish I certainly can. Thank you.

**Comment by elalish** [comment]
I think this has been fixed by the Chrome team now.
