### ISSUE TITLE
Unsupported mime type 

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#2468]
### Description

One of the compressed model using following command 

gltfpack -i samplemodel.glb -o compressedmodel.glb -tc now gives this error 

on and one of my own examples 
https://modelviewer.dev/editor/

unsupported mime type for image data: image/ktx2

This error only started from yesterday June 10, not sure if the latest version of this script was updated 

<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>

With the same code, the same compressed model had no issues. 

#### Live Demo
Available on model viewer with one of my compressed glb files. 

### Version

- model-viewer:latest

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

**Comment by elalish** [comment]
Yes, this is a known issue with the editor that I'm currently working on. It has not yet been updated to support KTX2 textures like model-viewer has.

**Comment by dhruvadhia1** [comment]
I am currently facing the problem with model viewer as well. 

Demo here

https://thecela.com/configurator/b0praVlKRWhMRjBqWnQ9PQ%3D%3D/QVF0PQ%3D%3D/cDJBdW90PT0%3D/0

I tried uploading un compressed model and it worked. However, we are trying to keep the file size as small as possible. This model was working day before yesterday. Wondering if there was a release through unpkg link.

**Comment by elalish** [comment]
Hmm, when I drop your file into the editor it seems to load just fine (a tennis shoe). It prints the ugly warning, but that's the bug I was talking about earlier and can be ignored. Therefore, it seems there is a problem in your site. Can you repro with a simpler usage of model-viewer? And yes, there was a release recently, though it should not be a breaking change: https://github.com/google/model-viewer/releases

You can test different versions using e.g. https://www.unpkg.com/browse/@google/model-viewer@1.7.2/dist/model-viewer.min.js

**Comment by dhruvadhia1** [comment]
Yes you are right, did a simple test and it worked. However, when I upload un compressed files through our backend it works, only problem with compressed files. But again it does work with simple model viewer tag. Will look into the code and test out different versions of versions as well. Thanks

**Comment by dhruvadhia1** [comment]
OK I found the issue, it was using the different link which started with modelviewer.dev/....

with that link the result was simply blank. I sometimes use that as it has all the latest updates from issues and features being released.

**Comment by elalish** [comment]
Strange; it's working in my local master version. Maybe some cache is out of sync. Anyway, glad to know it's functional for you again!

**Comment by elalish** [comment]
This has been fixed now with the editor refactor.
