### ISSUE TITLE
Transparent background doesn't work in ar in iphone and ipad

### ISSUE THREAD

**Issue by lmomimi** [google/model-viewer#2476]
### Description
Transparent background doesn't work in ar in iphone and ipad,

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/#transparentBackground

open in iphone or ipad click ar button, all transparent part are black

if you upload a glb model contain transparent material to https://spase.io/playground
 convert to usdz model,then use html code 
`       <a href="./your.usdz" rel="ar">
            <img src="your.png" alt="" width="250" height="250">
        </a>`
ar transparent will work fine in iphone

### Version

- model-viewer: v1.7.2

### Browser Affected

- [ ] Safari

### OS

- [ ] iOS 14.6

### AR

- [ ] WebXR

**Comment by milesgreen** [comment]
Ah... Are you talking abut the actual model itself, which contains transparent materials? And when you go into AR on iOS (which looks to be auto generating a USDZ) those transparent materials are no longer transparent?

I guess this is more of a question of USDZ export from three.js - and whether USDZ even supports the same kind of transparent material definitions. 

Viewed on iOS QuickLook:
![IMG_9631](https://user-images.githubusercontent.com/53870482/122089510-bced7d00-cdfe-11eb-82b2-141bd8332341.JPG)

**Comment by elalish** [comment]
@mrdoob Is there a three.js issue on USDZ transparency yet?

**Comment by lmomimi** [comment]
scene view
![Screenshot from 2021-06-16 14-35-29](https://user-images.githubusercontent.com/48657926/122171166-ff23c680-ceb1-11eb-81c1-c839e4ed7d11.png)

ios AR view
![IMG_0112](https://user-images.githubusercontent.com/48657926/122171249-1662b400-ceb2-11eb-98d3-1a2419373362.jpg)

3d model

[cube.zip](https://github.com/google/model-viewer/files/6660808/cube.zip)

**Comment by milesgreen** [comment]
I thought there was a related fix in r129 https://github.com/mrdoob/three.js/pull/21747

**Comment by milesgreen** [comment]
Looks like r129 works for some (PBR?) transparent materials:

![IMG_9633](https://user-images.githubusercontent.com/53870482/122282622-86d5f900-cee3-11eb-90d6-b3bdc0fcc1fe.JPG)

**Comment by sercandemirtas** [comment]
@lmomimi Transparent materials works on USDZ too (alpha blend) but png images does not work. On png images transparents parts looks black. I think iOS developers are working on it and on september (after new release of ios) we hope they will fix it.

**Comment by mrdoob** [comment]
I've tried changing the jpg that the `USDZExporter` produces with the original png:

<img width="813" alt="Screen Shot 2021-06-18 at 8 41 20 PM" src="https://user-images.githubusercontent.com/97088/122604000-2bd00d80-d06d-11eb-888c-4ca5d719a962.png">

 And this is what I get:

<img width="918" alt="Screen Shot 2021-06-18 at 8 39 39 PM" src="https://user-images.githubusercontent.com/97088/122603892-06db9a80-d06d-11eb-9871-19bbaebf808b.png">

<img width="918" alt="Screen Shot 2021-06-18 at 8 40 57 PM" src="https://user-images.githubusercontent.com/97088/122604060-41ddce00-d06d-11eb-8a0a-c0ff3c509946.png">

**Comment by elalish** [comment]
Did you check in iOS too? I've seen different bugs in that version of QuickLook compared to the MacOS one.

**Comment by mrdoob** [comment]
Hmm, actually... That was the internal model.usda.

The usdz looks like this:

<img width="918" alt="Screen Shot 2021-06-18 at 8 56 46 PM" src="https://user-images.githubusercontent.com/97088/122605419-53c07080-d06f-11eb-86fe-d33fc24313f4.png">

**Comment by mrdoob** [comment]
Do we know if usdz support alpha/opacity maps?

**Comment by base-krchome** [comment]
> Do we know if usdz support alpha/opacity maps?

yes we know, it supports

**Comment by mrdoob** [comment]
@base-krchome can you share a usdz file that uses them?

**Comment by Karpulza** [comment]
Hi, I've been watching this thread just to see what develops. It seems to me that in terms of using the PNG as-is, we're just waiting for iOS to fix the display issue?

Has anyone tried a different way of using the images as materials? I wonder if there's a way to run the PNG files through some sort of node-based filter right in Blender to actually remove the blank areas in the image from the plane's geometry? 

I did try using a PSD file instead of PNG but had the same result.

**Comment by sercandemirtas** [comment]
@mrdoob @Karpulza I hope this will help!

Live link--
https://www.basebros.com/usdz-test.html

Usdz file link---
https://www.basebros.com/assets/test.usdz

Glb file link---
https://www.basebros.com/assets/test.glb

I created this cube via Blender and converted glb to usdz with macos terminal. You can download glb or usdz file and review shading parts for it.

**Comment by mrdoob** [comment]
@sercandemirtas That file doesn't seem to be transparent in MacOS 🤔

<img width="922" alt="Screenshot 2021-07-27 at 16 46 28" src="https://user-images.githubusercontent.com/97088/127185234-d539bf55-8446-4a07-8ecc-b6693520e925.png">

**Comment by JanSob** [comment]
> @base-krchome can you share a usdz file that uses them?

So I have the same issue. Oddly enough, it seem that the usdz-model works great on MacOS, it's only on IpadOS and IOS where 

a. the transparency is black instead of cut-out/transparent and
b. it seems there is some issues with lightning (the models are are considerably darker on IOS than MacOs).

The biggest issue is definitely a.

I have attached both the USDZ and the GLTF and a screenshot of the USDZ on MacOs (trans. working) and IpadOS (transp. not working).

Any kind of help is greatly appreciated, as this has become kind of a roadblock to my project 😓

MacOs
<img width="1279" alt="MACOS Screenshot USDZ Transparency" src="https://user-images.githubusercontent.com/8226322/127774264-bfbe1691-7edc-40e9-aef7-c3e96a4e31c5.png">

IOS
![IOS No transparency on IOS](https://user-images.githubusercontent.com/8226322/127774298-f2978c00-602c-4004-a992-497fe87e331d.jpg)

[gltf and usdz.zip](https://github.com/google/model-viewer/files/6912810/gltf.and.usdz.zip)

**Comment by elalish** [comment]
@JanSob How were these USDZ/glTF created? Do you get different results when the USDZ is auto-generated for quick look?

**Comment by JanSob** [comment]
> @JanSob How were these USDZ/glTF created? Do you get different results when the USDZ is auto-generated for quick look?

These were created with the threejs GLTFexporter/USDZexporter, but the result is absolutely identical (black instead of transparent) in model-viewer if I don't use the [IOS-Source] and let model-viewer auto-generate.

**Comment by elalish** [comment]
@JanSob Got it, that makes sense since auto-generation also uses USDZExporter.

**Comment by sercandemirtas** [comment]
To summarize; when we use model-viewer auto-generate to usdz, png images cannot be fully converted. Transparent parts appear black. But when we convert glb to usdz via macos terminal and use ios-src on model-viewer there is so problem. Any planned update on this issue? @elalish

**Comment by sercandemirtas** [comment]
> To summarize; when we use model-viewer auto-generate to usdz, png images cannot be fully converted. Transparent parts appear black. But when we convert glb to usdz via macos terminal and use ios-src on model-viewer there is so problem. Any planned update on this issue? @elalish

@elalish Hey! any news on this situation ?

**Comment by elalish** [comment]
You'll probably find better updates on the three.js github for this. USDZ is a strange beast, so there will always be some gaps. Hopefully this can be fixed.

**Comment by elalish** [comment]
Looks like this was fixed.
