### ISSUE TITLE
AR Environment Estimation Map

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#2479]
### Description

Follow up on #167.
This has landed 🎉 in Chrome so it would be great to get support for choosing if WebXR should use the pre-set env map or the estimated user environment.

Demo / Feature:
https://www.chromestatus.com/feature/5704707957850112

Applies to WebXR only

**Comment by takahirox** [comment]
I think this PR will resolve it? #2471

**Comment by hybridherbst** [comment]
Good timing! So when that is merged happy to close here :)
