### ISSUE TITLE
Render bleeds to other canvases on first paint

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#248]
View the [background-image](https://googlewebcomponents.github.io/model-viewer/examples/background-image.html) example. This only happens sometimes, and I've seen this consistently in the #237 branch, and have seen it previously with the update to r98 and changes to accomodate that (#219, #227), but first time I've seen it on master.

It goes away on second paint, e.g. triggering the mouse controls.

I've seen this bleed and also render the full other objects in the mentioned PRs, looks like this might just be depth?

![screenshot from 2018-11-30 14-40-05](https://user-images.githubusercontent.com/641267/49318702-73421e80-f4ae-11e8-829e-e12694281e67.png)

This might be the same thing as #239, as it doesn't appear to be related to the shape of other models on page.

![screenshot from 2018-11-30 14-39-32](https://user-images.githubusercontent.com/641267/49318761-a84e7100-f4ae-11e8-9eb4-8eda5c1405f1.png)

**Comment by mrdoob** [comment]
Have you seen this in multiple machines?

**Comment by mrdoob** [comment]
I wonder if it's a weird driver issue.

**Comment by elalish** [comment]
I've never seen this in a year of working on this project, so closing.
