### ISSUE TITLE
Error auto-generating USDZ model with variants

### ISSUE THREAD

**Issue by jangarita** [google/model-viewer#2481]
### Description
When I clone the variants example in my own environment and test it on QuickLook, I see the auto-generated model without colors.

It works well in the Model Viewer example page, but in my own environment doesn't work. I tested it in localhost, in my own hosting, in CodePen, with and without SSL, but the result is the same.

#### Live Demo
![Model Viewer examples page](https://labs.jangarita.com/svbug/modelviewer.jpg)
https://modelviewer.dev/examples/scenegraph/#variants

![My own server](https://labs.jangarita.com/svbug/ownserver.jpg)
https://codepen.io/jangarita/pen/LYWMdGE

### Version
- model-viewer: v1.7.2

### Browser Affected
- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS
- [ ] Android
- [X] iOS v14.5.1
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [ ] SceneViewer
- [X] QuickLook

**Comment by elalish** [comment]
This is a recently fixed bug in Three.js, which I just pulled in. The docs are served off master, while you are using the last release. This fix will go out as part of v1.8.
