### ISSUE TITLE
"Memory access out of bounds" error on Chrome Mobile

### ISSUE THREAD

**Issue by fcor** [google/model-viewer#2496]
### Description

Hi!

Since last week we have been experimenting some errors on different projects that were working fine before. This is only happening on chrome mobile. All other browsers I have tested are working fine. Here's the error msg I am getting in the console:

![imagen](https://user-images.githubusercontent.com/21111451/122771239-899b6a00-d2a6-11eb-906b-317543797b52.png)

I am not sure this is is strictly from model viewer or from Chrome - WASM while trying to decompress Draco.

#### Live Demo

Here are some example links of pages that were working and now are experimenting this error:
Live:
 - https://molecularweb.epfl.ch/modules/atomic-structures/protein-interactions/
 - https://molecularweb.epfl.ch/modules/biological-assemblies/ribosome/ribosome.html
 -  https://1gd2.glitch.me/

Code:
- https://github.com/fcor/molecular-mirror-app/blob/master/modules/biological-assemblies/ribosome/ribosome3d.html
- https://glitch.com/edit/#!/1gd2

### Version

- model-viewer: v1.7.2

### Browser Affected

- [x] Chrome, version: 91.0.4472.101
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
They all seem to be working for me (as best I can tell) on my Pixel 3. Do you have a bunch of tabs open that are eating memory maybe? If you can put some more detailed device info and repro steps, I can look more closely.

**Comment by gjcope** [comment]
We have been seeing this same issue on multiple devices, also just cropping up recently with pages that formerly worked fine on the same devices and only on Android Chrome.

I can confirm that I get the error on the Glitch link above and also on our Corals pages like (https://3d.si.edu/corals/shape-structure). Currently testing on a stock Galaxy s10e with no additional apps or tabs open. It seems to happen with the second model load on a page. FWIW the same thing is happening with our Voyager component.

**Comment by elalish** [comment]
Can I get confirmation that this only seems to occur with models that are DRACO encoded? I still haven't gotten a repro, but I don't have a Galaxy. @fcor Can you specify any devices you can repro with? And what Android version?

**Comment by gjcope** [comment]
@elalish Yes, I've only seen it on Draco compressed models. If it's helpful to have other device specs, I can gather those as well - it happens for everyone on my team with an Android device.

**Comment by gjcope** [comment]
We were able to reproduce it on a Pixel 4a, Android 11, Build/RQ3A.210605.005

**Comment by elalish** [comment]
Thanks, I have a repro now too, Pixel 4 Android 11, Chrome 91. Chrome 90 seems fine. We're looking into it with the Chrome team now.

**Comment by FrankGalligan** [comment]
Hi @fcor I'm from the Draco team and we are trying to look into your issue. So we can reproduce this on some devices sporadically using Chrome version 91.0.4472.134. But we cannot get a debug message like you have. Anytime we hook up any kind of debugging it works 100% of the time.

Can you post how you got your debug message? Thanks.

**Comment by gjcope** [comment]
@FrankGalligan In my situation I get the same message by reproducing the error on my device and then connecting to the desktop  debug console. I can confirm that it doesn't happen while actively connected. I assumed it was a difference in memory management.

**Comment by FrankGalligan** [comment]
@gjcope Thanks I can reproduce error messages that way.
 
This one is tough because it works fine in 91.0.4472.120, not in 91.0.4472.134 and then works fine again in 92+.

**Comment by gjcope** [comment]
@FrankGalligan I get the issue on my Galaxy s10e in 91.0.4472.120.

**Comment by fcor** [comment]
Hi @FrankGalligan I am seeing the issue on the following devices, both with Chrome 91.0.4472.120

Android 11 Pixel 2XL 
Android 10 Motorola One Action 

I get the message like @gjcope described.

**Comment by FrankGalligan** [comment]
OK thanks I'm guessing you are more unlucky than we were. But I also created a smaller test case as well, then your site.

But it is good to know that you can reproduce with .120. 

Anyway while trying a lot to fix it or find a work around, which we haven't been able to, I reached out to a lot of other people for help. Someone on the WASM team said they think this is the issue. https://bugs.chromium.org/p/v8/issues/detail?id=11863

I'm pretty sure that is it.

**Comment by gjcope** [comment]
Thanks @FrankGalligan that does sound like the issue. Hopefully there is movement. I guess pre-allocating memory isn't really an option in this case...

**Comment by fcor** [comment]
Thanks for digging into it @FrankGalligan, looks like this is the issue.

**Comment by FrankGalligan** [comment]
Hi @gjcope and @fcor We uploaded version 1.4.2 of our draco decoders here:
https://www.gstatic.com/draco/versioned/decoders/1.4.2/

Basically this is 1.4.1 but we set INITIAL_MEMORY to 64mb, which worked with one of your models. So this is only a workaround, because if a specific models needs > 64MB memory to decode then we will hit the issue again.

Can you try setting model-viewer to point to 1.4.2? E.g.
ModelViewerElement.dracoDecoderLocation = 'https://www.gstatic.com/draco/versioned/decoders/1.4.2/';

**Comment by elalish** [comment]
And it's a static property, so don't forget this line: 'ModelViewerElement = self.ModelViewerElement || {};' https://modelviewer.dev/examples/loading/#dracoSupport

**Comment by gjcope** [comment]
Thanks @FrankGalligan this is definitely an improvement on our end but still running into a few issues with the Three.js glTF loader then not being able to allocate a texture. I'm assuming it's still tied into the memory allocation bug, so hopefully there is some movement from the Chrome team. Thanks so much for your help!

**Comment by sercandemirtas** [comment]
> Hi @gjcope and @fcor We uploaded version 1.4.2 of our draco decoders here:
> https://www.gstatic.com/draco/versioned/decoders/1.4.2/
> 
> Basically this is 1.4.1 but we set INITIAL_MEMORY to 64mb, which worked with one of your models. So this is only a workaround, because if a specific models needs > 64MB memory to decode then we will hit the issue again.
> 
> Can you try setting model-viewer to point to 1.4.2? E.g.
> ModelViewerElement.dracoDecoderLocation = 'https://www.gstatic.com/draco/versioned/decoders/1.4.2/';



> And it's a static property, so don't forget this line: `ModelViewerElement = self.ModelViewerElement || {};` https://modelviewer.dev/examples/loading/#dracoSupport

Definetly works for now!

**Comment by fcor** [comment]
I still have some issues with some models but tried Chrome 92 (BETA) and works fine. It's expected to be a stable version next week. Thanks for your help @FrankGalligan @elalish
