### ISSUE TITLE
Can I set the material opacity?

### ISSUE THREAD

**Issue by Turtleted21** [google/model-viewer#2499]
Hello
Can I set the material opacity? I don't found a example,
 I look here https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/features/scene-graph/material.ts
I tried `material.opacity = 0.5;` with no sucess

With three.js we can set the material opacity with a glb model.

three js editor test with DamagedHelmet.glb :
![modelviewer_opacity](https://user-images.githubusercontent.com/46889785/122915272-de4cec80-d35b-11eb-9eab-caad23c9870c.jpg)

Thanks

**Comment by elalish** [comment]
Yes, simply follow this [example](https://modelviewer.dev/examples/scenegraph/#changeColor) and set the alpha channel of your base color to your desired opacity.
