### ISSUE TITLE
Bug: auto-conversion to USDZ fails and makes model-viewer result slightly brighter

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#2503]
### Description

I'm not sure if this is one, two or three bugs, but here we go:
- auto-conversion to USDZ does nothing (three bug? happy to open one there)
- the window gets slightly brighter during conversion (might be by design)
- the window stays slightly brighter after conversion (this seems to be a model-viewer bug)

#### Live Demo
https://tangible-nebulous-hide.glitch.me/

### Version

- model-viewer: v1.7.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [X] QuickLook - auto-conversion fail

**Comment by elalish** [comment]
Anything interesting in the console? Sounds like three.js choked on it (which isn't too surprising; there's lots of models that aren't supported yet for conversion). Also, how can you tell it is "after conversion" if the conversion does nothing? What queues are you looking at?

**Comment by hybridherbst** [comment]
Unfortunately there aren't any logs that I can see (with chrome://inspect). I don't have a Mac to test safari remote connection, is there a good way to get logs for Chrome/Safari on iOS into a Windows machine?

My assumption is that three doesn't support transcoding with either the ktx2 or draco extension which seem to be the only "arcane" things here (I understand that animation etc. aren't supported yet).

I added some more stuff to the test page:
1. auto-conversion from a ktx2+draco file → leads to lighter color, AR button disappears (no USDZ opens)
2. auto-conversion from a file without draco/ktx2 → lighter color is briefly visible but then goes back to normal, AR button re-appears (USDZ opens on Safari but not on Chrome)
3. manually converted USDZ (USDZ AR opens on both Safari and Chrome)

**Comment by elalish** [comment]
Note that #2 is a known issue in iOS Chrome: #2263/#2449

**Comment by hybridherbst** [comment]
Not sure if I understand #2449 correctly, maybe the title is overly broad – USDZ in general works fine on Chrome, just the auto-conversion seems to fail.

**Comment by Godelaune** [comment]
Hi, I have the same issue with files from Cinema4D:
GLB-files that were exported from Cinema4D won't work but if I load the same GLB-file into babaylon-sandbox and then export it again, then model-viewers USDZ-autoconvert works.
When the files come directly from Cinema4D I get the same brighter screen as described by @hybridherbst and then nothing happens.

**Comment by elalish** [comment]
@hybridherbst I'm going to close this bug as it's several different things, all of which I believe are external to our code base. I'd recommend filing the DRACO/KTX USDZ export one on three.js. Thanks!
