### ISSUE TITLE
Scene Viewer loading indicator gets stuck until object is placed in AR

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#2527]
### Description

When opening Scene Viewer directly to AR, with either `ar_preferred` or `ar_only`, often the loading progress indicator gets stuck displaying an arbitrary value less than 100% - even though the model appears to complete loading - and the frozen progress indicator only disappears once the model has actually been anchored in the AR scene. 

Expected behaviour: loading progress indicator should disappear once model has completed loading.

This is a Scene Viewer issue, not Model-Viewer. 

#### Live Demo

https://modelviewer-sceneviewer-arplacement.glitch.me/

Steps to reproduce: 
- Open one of the Scene Viewer Intent links labeled with either 'AR Preferred' or 'AR Only'. 
- Hold phone still, intentionally not scanning environment. 
- Observe loading indicator spinning and incrementing, then freezing at some value below 100%
- Now scan the environment, and observe the frozen loading indicator disappear when the model is anchored into the scene.

### Version

- model-viewer: N/A

### Browser Affected

- [x] Chrome, version: 91.0.4472.114
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

![Screenshot (Jun 30, 2021 12:41:33 PM)](https://user-images.githubusercontent.com/53870482/123963716-a4f32d00-d9aa-11eb-9e6a-7f66241bf733.jpg)

**Comment by elalish** [comment]
@tpsiaki

**Comment by RatkoJ** [comment]
I understand this is a scene-viewer issue, but does anyone know of any fixes for this?

**Comment by elalish** [comment]
No, your only fix is to use WebXR and make your own prompt with HTML like our example. A fix will roll out for Scene Viewer before too long as well.

**Comment by milesgreen** [comment]
This seems to be fixed now. The loading progress indicator now fades out when the sweeping phone graphic appears, prior to anchoring.
