### ISSUE TITLE
Add powerPreference option, and consider not defaulting to high-performance

### ISSUE THREAD

**Issue by kenrussell** [google/model-viewer#2541]
### Description

Visiting https://artsexperiments.withgoogle.com/periodic-table/ in Chrome on a dual-GPU MacBook Pro (have tested on a 15" 2017 model) currently causes a whole-system stutter because of the switch to the high-performance GPU. This is happening because model-viewer defaults to specifying powerPreference: 'high-performance' for its Three.js WebGLRenderer.

These models aren't complicated, and would run just fine on the integrated GPU on such systems. model-viewer should expose the option to the page to use the low-power GPU.

Additionally, it's unclear how many models being viewed by model-viewer really need to activate the discrete GPU. It should be considered to leave the default as-is; then the user agent will decide, and all of Chrome, Firefox and Safari will default to the low-power GPU on such systems. (On the other hand, we have collaboratively investigated rendering smoothness problems in Chrome with the PBR shaders on the integrated GPU, so perhaps that shouldn't be changed.)

#### Live Demo
https://artsexperiments.withgoogle.com/periodic-table/ 

### Version
- Not sure what version the periodic-table experiment is using
  
### Browser Affected
- [X] Chrome, version: 93.0.4562.0 (Official Build) canary (x86_64)

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Yeah, I don't want to make this a breaking change, so the default will stay as is. Before we explicitly chose "high performance" we had a lot of people with large screens and big gaming GPUs telling us the performance was terrible, and it turned out to be because it was choosing integrated graphics. Not sure how the browser decides, but it seems to basically always pick the integrated, especially on Windows.

**Comment by elalish** [comment]
Here is where the change was made and why: https://github.com/google/model-viewer/pull/1169

**Comment by elalish** [comment]
Fixed by #2656
