### ISSUE TITLE
Screen rendering issue when opening a new tab from a WebXR session

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#2542]
### Description

On Android Chrome, while in a WebXR session, opening a link to a new tab using `window.open`  causes a screen rendering problem, displaying a partial snapshot of the originating ModelViewer page rather than navigating to the destination page.

It appears that this partial snapshot is actually layered _over_ the destination page/tab. 

The issue is only observed when `window.open` is targeted to a new tab, using a `name` parameter of: `_blank`, a custom name, or omitted entirely.

The issue is **not** observed when using a `name` parameter of: `_parent`, `_self`, or `_top`.

Workarounds:
- Before using `window.open`, first dispatch a `click` to ModelViewer's default exit button slot, EG:
`modelViewer.shadowRoot.querySelector('#default-exit-webxr-ar-button').click();`

- Or, target `window.open` to the current tab using: `_parent`, `_self`, or `_top`.

#### Live Demo

https://modelviewer-webxr-exitlinks.glitch.me/

Steps to reproduce:
- Visit the demo link
- Enter a WebXR AR session
- Once in WebXR, click one of the buttons labeled: 'Open', 'Open _blank', or 'Open earth'.
- Observe what appears to be a broken ModelViewer page. Try to interact. You can't.
- Swipe screen to go back in browser history.
- The intended destination page will now be revealed.
- Observe that this is in a new tab, and the original ModelViewer page is in another tab.

### Version

- model-viewer: v1.7.2

### Browser Affected

- [x] Chrome, version: 91.0.4472.120
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android 11, Pixel 4 XL
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
@klausw WebXR bug? Sorry to bother you right before a long weekend...

**Comment by milesgreen** [comment]
In this capture, you can actually hear a video playing in the background on the destination page, hidden by the rendering glitch.

https://user-images.githubusercontent.com/53870482/124336030-60c38080-db94-11eb-8c77-0b36ffab5fe6.mp4

**Comment by bialpio** [comment]
Tracking internally as https://crbug.com/1234085.

**Comment by klausw** [comment]
Sorry about the late followup. I can't reproduce the issue in Chrome stable (92.0.4515.131) or Canary (95.0.4609.3). For me, the new tab opens as expected when using https://modelviewer-webxr-exitlinks.glitch.me/ with the `_blank` or `earth` buttons. When I return to the AR tab, the session has ended and the normal model-viewer view works as expected.

@milesgreen, is this still happening for you in current browser versions?

**Comment by milesgreen** [comment]
@klausw - Retesting in Chrome stable (92.0.4515.159) and the above issue is no longer seen. New tabs open as expected. Works great. Thanks for the fix!
