### ISSUE TITLE
Point cloud .glb doesn't load in AR

### ISSUE THREAD

**Issue by gexahedron** [google/model-viewer#2547]
Hi, I wanted to see point cloud .glb file in AR, but it is not shown in AR (although I get some response from the phone as if the object is placed). No UVs, no textures, only points.
Example of point cloud - https://sketchfab.com/3d-models/azalea-point-cloud-ed186481a6ab494b84701546a8060e61 - you can download it in gltf; I converted it to glb with gltfpack.
https://model-viewer-tester.glitch.me shows the cloud as is, as expected, without problems.

**Comment by elalish** [comment]
Can you please fill out the issue template you deleted? I need to know which AR mode(s) and devices this is happening with and a repro link.
