### ISSUE TITLE
iOS quick look do not work on example doc 

### ISSUE THREAD

**Issue by GianiNavette** [google/model-viewer#2551]
### Description
On the fly conversion glb to usdz doesn't work in example provided by model viewer.
Where a model viewer element has multiple model to choose from.

#### Live Demo
Go on iOS and go on this page and click on "view in your space"
https://modelviewer.dev/examples/augmentedreality/

### Version
Last Version
- model-viewer: v1.7.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ X] Safari

### OS

- [ ] Android
- [ X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ works] WebXR
- [ works] SceneViewer
- [doesn't work] QuickLook

**Comment by elalish** [comment]
It's working for me. Quick Look does have a strange delay before opening, but I can't control that. Can you be more specific with your device versions and maybe include a screen recording?

**Comment by GianiNavette** [comment]
@elalish 
I retried on my own iPhone on iOS 15 Public Beta 2 and it works, i think i was fooled by the strange delay last time.
However it doesn't work on my friend phone.

iPhone X.
iOS version 13.5.1.

https://user-images.githubusercontent.com/71259828/124933086-e5365900-e003-11eb-8606-02f4dd413ba4.mp4

Thank you for your time !

**Comment by elalish** [comment]
I would guess this feature of Quick Look isn't supported in iOS 13; that's pretty old for iOS at this point. If you can repro on any devices with iOS 14 or later, comment here and I'll reopen this.
