### ISSUE TITLE
User-configurable render-scale that overrides devicePixelRatio for individual model-viewers

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#261]
Relevant discussion: https://github.com/GoogleWebComponents/model-viewer/pull/258#pullrequestreview-181403843

> I imagine for future customization cases, there may be a render-scale value such that devs could specify 1 for 3D content with the rest of their content using DPR/viewport meta values for performance. This is similar to WebXR's frameBufferScaleFactor. In WebXR, I think, no scale (1) is high-end, and generally scale down (~0.5) for perf. This related issue, IIRC, some vendors have defaults to 0.75, and as a dev, it's unclear if setting scale 1 is reducing or increasing the scale. General food for thought!

**Comment by elalish** [comment]
Personally, I would rather skip the added API and instead detect low frame rate and adjust scale automatically. This is probably the single biggest thing we can do for performance.
