### ISSUE TITLE
Model modifications are not presented in AR

### ISSUE THREAD

**Issue by CanerErdogan** [google/model-viewer#2631]
### Description

Using the same code provided in https://modelviewer.dev/examples/scenegraph/#changeColor , I have tried to observe changes in AR, however the model views in default material settings. 

#### Live Demo
https://jsfiddle.net/rocjw0hg/

### Version
- model-viewer: V1.7.2

### Browser Affected
- [x] Chrome, version: 92.0.4515.115
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS
- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [x] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
SceneViewer cannot support this, as it does not take a Blob as input, so you'll need WebXR for this kind of feature on Android. Quick Look should work, but we need a three.js fix, which has been merged in master but not released yet. It will be shortly.

**Comment by CanerErdogan** [comment]
What I don't understand is, for both iOS and Android devices, the code given in the example works from modelviewer.dev but doesn't work from JSFiddle or my local project. The code includes 'scene-viewer' in ar-modes, removing that just makes AR button disappear in Android. But now I observed that the modelviewer.dev example somehow launches a WebXR session.

It makes me think there must be something else getting one working and not the other. Or maybe the code running for the example is actually different (or from another branch) than the code presented.

I would appreciate if I would learn how to get the fiddle working just like the example.

Thanks!

**Comment by elalish** [comment]
modelviewer.dev uses a prerelease version: `modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js` which you can use for testing as well, but it's not stable enough for production. As for why WebXR doesn't work, that may deserve a discussion of its own. Have you checked the console log for messages? If you ever denied the WebXR permission, then it will fail until you clear permissions on that site.

**Comment by CanerErdogan** [comment]
Thank you very much @elalish
