### ISSUE TITLE
editor metal/rough texture upload only affects metalness

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#2654]
### Discussed in https://github.com/google/model-viewer/discussions/2653

<div type='discussions-op-text'>

<sup>Originally posted by **Musante** August  5, 2021</sup>
For some days, in the model-editor uploading and setting the metalness/roughness texture only affects the metalness. 
The model retains the roughness map (or lack of) it had when imported.

Any suggestions?</div>

**Comment by elalish** [comment]
@Musante I can repro; good eye noticing this. We've just done a major refactor of the editor, so this is a regression we'll get fixed shortly.

**Comment by Musante** [comment]
Great, thank you!

**Comment by Pedergnana** [comment]
@elalish I had the same experience and yap metalness/roughness texture only affects the metalness. I would like to underline also that the ambient occlusion if I use a map RGP where R channel is the AO is not work properly anymore like before the last update.

**Comment by elalish** [comment]
@Pedergnana Can you please open a separate issue for this with detailed repro steps? Note that there is a separate section in the editor for the occlusion map, so you need to set the same texture there as well (they are not always combined, though it is common).

**Comment by Pedergnana** [comment]
Sure! Thank you!
________________________________
