### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#2658]
### Description

Having different backgrounds for the model viewer css property for devices 
Samsung Note 20
Samsung s20 FE

For the above two devices the background is white which is not intended 
![unnamed](https://user-images.githubusercontent.com/70779749/128435651-928619d4-338f-4f81-b135-40a7bc329017.jpg)

for all the other devices the background is correct which is like Grey radial gradient color as you can see in the image below

![unnamed (1)](https://user-images.githubusercontent.com/70779749/128435768-65e39a33-9c19-40f9-8e52-d9513766795c.jpg)
 

#### Live Demo

https://thecela.com/configurator/b0praVlKQWlvVDkxcHYxM0xLeGdxVEltcU49PQ%3D%3D/QVF0PQ%3D%3D/cDJBdW90PT0%3D/0/QXdWMw%3D%3D

### Version
Latest

### Browser Affected

- [ x] Chrome, version: xx.x.xxxx.xx
- [x ] Edge
- [x ] Firefox
- [x ] IE
- [x ] Safari

### OS

- [x ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Your screenshots appear to be from completely different sites; can you show two that are more comparable? This seems unlikely to be a model-viewer issue, so I'm moving this to a discussion.
