### ISSUE TITLE
Button View in Your space

### ISSUE THREAD

**Issue by Ax-Zis** [google/model-viewer#2680]
Good morning, I have a problem, when I want to open the 3d model for AR the view in your space button does not appear.
Does anyone know what happened?

### Browser Affected

- [ x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
I think you forgot to fill out the rest of the issue template. I have absolutely no idea what you mean, and no way to reproduce the behavior. Can you give details please?

**Comment by elalish** [comment]
Closing as no repro.
