### ISSUE TITLE
Attach camera-controls pointermove event listeners to window instead of element

### ISSUE THREAD

**Issue by lucadalli** [google/model-viewer#2682]
### Discussed in https://github.com/google/model-viewer/discussions/2678

<div type='discussions-op-text'>

<sup>Originally posted by **lucadalli** August 10, 2021</sup>
When rotating a model with `camera-controls` enabled, I often find myself getting frustrated at the model's unresponsiveness when my pointer falls out of the element's bounds.

When I'm interacting with the model, after the initial pointerdown event, I become far less conscious of where my pointer is and more focused on the actual orientation of the model. I'd be rotating the model, until suddenly, my inputs are no longer recognized, only for me to realize that my pointer is outside the element. This breaks my "immersion" as I have to reset my pointer position back onto the model and resume the interaction.

I strongly believe this is an inferior user experience to the one offered by THREE's OrbitControls, which attaches move listeners to window and hence allows an initiated camera interaction to continue anywhere on the page until the pointer is released.

https://threejs.org/examples/#misc_controls_orbit

</div>

**Comment by elalish** [comment]
Is there a reason you posted this again rather than replying on the previous thread?

**Comment by lucadalli** [comment]
While investigating this issue further I noticed that the behavior exhibited is dependent on browser and device.

On Win10 Chrome, the `mousemove` events are confined to the element's bounding box. 
Surprisingly, Win10 Firefox does not behave in the same way and `mousemove` events preceded by a `mousedown`  keep firing even outside the element's bounds.

On Android Chrome and in the emulated mobile environments of Win10 Chrome and Firefox, `touchmove` following a `touchstart` event which happened within element bounds keep firing even outside the element bounds. This means that all mobile environments I was able to test behave unanimously, in the way we prefer.

If iOS Chrome and Safari behave in the same way as Android Chrome, I think this can be leveraged in our implementation to keep the complexity low and avoid wastefully attaching and detaching listeners.

**Comment by lucadalli** [comment]
> Is there a reason you posted this again rather than replying on the previous thread?
I intend to work on this so I thought it would be better to have an issue for it. We can close and resume discussion on the original thread if its preferred.

**Comment by elalish** [comment]
Ah, sure thing. I would have just converted that discussion to an issue anyway, so this is fine. Thank you for taking this on!

**Comment by lucadalli** [comment]
My pleasure :) Are you able to test the current behavior on iOS Chrome and Safari, by any chance?

**Comment by elalish** [comment]
Yes, I have those devices locally; let me get back here with results.

**Comment by elalish** [comment]
As you work on this, please keep this [example](https://modelviewer.dev/examples/stagingandcameras/#panning) in mind, as we want to make sure it is still easy for users to customize their UX by intercepting events before they get to us. We need to be mindful of anything that may be a breaking change.

**Comment by lucadalli** [comment]
Great, I have also tested Android Edge and it behaves like the rest. Given that all modern mobile browser are consistent, the way we handle touch events can remain as is. I will address mouse events, which should be a trivial change.

> As you work on this, please keep this [example](https://modelviewer.dev/examples/stagingandcameras/#panning) in mind, as we want to make sure it is still easy for users to customize their UX by intercepting events before they get to us. We need to be mindful of anything that may be a breaking change.

Noted. I'll verify that changes are backwards compatible.
