### ISSUE TITLE
Dead code in Panning example

### ISSUE THREAD

**Issue by lucadalli** [google/model-viewer#2683]
### Description

The `onPointerUp` function in the [panning ](https://modelviewer.dev/examples/stagingandcameras/#panning) example seems to be dead code. It's not invoked anywhere.

#### Live Demo
https://modelviewer.dev/examples/stagingandcameras/#panning

### Version

- model-viewer: v1.8.0

### Browser Affected
N/A

### OS

N/A

### AR

N/A

**Comment by lucadalli** [comment]
If the function can be simply removed I can address this as part of #2682

**Comment by elalish** [comment]
ha, good catch. This is what I get for not having these examples compiled from TS... Yeah, sounds good.
