### ISSUE TITLE
Leaking event listeners

### ISSUE THREAD

**Issue by lucadalli** [google/model-viewer#2684]
### Description

SmoothControls attaches various event listeners to the `Window` object. When a model-viewer is removed from the DOM, it does not take care of cleaning up those event listeners.

#### Live Demo
https://modelviewer.dev/
1. Open Dev Tools
2. Select the `model-viewer` element
3. Observe `mouseup` listener on `Window` (Ancestors must be enabled)
4. Remove `model-viewer` element (`$0.remove` in console or `DEL` key)
5. Observe persistent `mouseup` listener on Window

### Version

- model-viewer: v1.8.0

**Comment by elalish** [comment]
I vaguely remember fixing this once long ago; maybe it never got merged... Anyway, yes, let's fix this.

**Comment by lucadalli** [comment]
Fixed in #2730
