### ISSUE TITLE
Mutiple animation on single click

### ISSUE THREAD

**Issue by Arumugamsix** [google/model-viewer#2698]
I have a Car Model. for that I need to open all the doors with a single button click.

But only one door animation is working. The remaining does not work.

Animations are
 modelViewer.animationName = ['Boot_Door_Ani','Front_Door_LeftAction','Back_Door_Left_AniAction','Back_Door_Right_Ani','Front_Door_Right_AniAction'];

kindly give a solution

**Comment by elalish** [comment]
Add an animation to the file called "All_Doors" that combines those existing animations. Then select that name and play it.
