### ISSUE TITLE
"Enter AR" button should only appear once the model is loaded

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#272]
We measure the model size/bounding box once it's loaded, and manipulate the size of the environment and model based off of these sizes. Entering (WebXR) AR while the model is loading will currently (mostly?) work since we set the model to it's natural scale and don't do anything in AR that requires the size (e.g. reticle with measurements), but this seems against the logic elsewhere in code.

* ModelScene currently will resize the scene and model once loaded, even if in AR
* No benefit of displaying loading indicators that (will?) exist in the 2D view, since users will be waiting for the model to load while viewing the AR camera mode.
* "Placing" the model before it's loaded should "work", but it's an empty model. I think once the model is loaded, it'll be in the correct spot however.

While we could make this work if it's intended, it seems to be going down a tricky user experience.

**Comment by cdata** [comment]
Two reactions to this:

 1. Seems like this should actually be subsumed by a loading-indicator state while the model is still loading
 2. This doesn't apply to iOS Quick Look scenarios (AR can be safely invoked before the model is loaded)
