### ISSUE TITLE
Including a Build Without Bundling Dependencies

### ISSUE THREAD

**Issue by AmitMY** [google/model-viewer#2747]
### Description

The package `@google/model-viewer` has an entry point at `dist/model-viewer.min.js`.
This file includes all the code required to run `model-viewer`, including (an estimate) of `1MB` for the `three` package, and a few `kb`s for the actual package code.

I would like you to include an additional build in the distribution, that does not bundle all of the dependecies, but instead, statically imports from `three` without a resolution.

This will decrease my bundle size drastically, as right now I am using `three` for one thing, and `model-viewer` for another, instead of both just referring to the same `three` reference.

(This is how most packages are packaged in NPM, and probably just a small modification to your build system)

----

Ideally, as the web moves to using javascript `module`s, if you would also include a build that imports `three` dynamically, that would be great, as this entire huge dependency can be lazy-loaded if needed. (however, I believe this would require major changes)

### Version
- model-viewer: v1.8.0

### Browser Affected
- [x] Chrome, version: all
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

**Comment by elalish** [comment]
Indeed, we've been talking about this a bit in a related issue: https://github.com/google/model-viewer/issues/1502

We do in fact also publish our unbundled library on npm (in the `lib` folder next to `dist`). However, I think there are some problems with our `package.json` for this use case. We're trying to find the best practice to support the various toolchains out there. If you can give any pointers as to what fields in `package.json` your tooling makes use of, that would be helpful. They all seem to do things a little differently. FYI @timmmeh.

As for lazy-loading three, yes that would be nice to do  at  some point.

**Comment by AmitMY** [comment]
I tried importing `@google/model-viewer/lib/model-viewer` but typescript errors ensued.

My build system is the default Angular build system which uses Webpack with the following main files priorities:
```js
mainFields: ['browser', 'es2015', 'module', 'jsnext:main', 'main'],
```

**Comment by elalish** [comment]
Pretty sure that is the right way; perhaps you can open a new issue with the specific typescript errors and we can help.

**Comment by AmitMY** [comment]
Hi @elalish 
I think this issue is still relevant.
There are no typescript issues, just that if I import both `model-viewer` and `three` in my app, `three` is bundled twice, and the console says 
> WARNING: Multiple instances of Three.js being imported.

In the `build:rollup` script, the `three` package is being included directly in the `dist`, which is less than ideal.
I suggest [here](https://github.com/google/model-viewer/blob/master/packages/model-viewer/rollup.config.js#L50) to make sure to "skip" three, and make it an external dependency.

You can see it in [the dist file](https://unpkg.com/@google/model-viewer@1.12.0/dist/model-viewer-umd.js) that indeed `three` is packaged in, which allows `model-viewer` to be used standalone, but does not allow bigger apps to reuse three

**Comment by AmitMY** [comment]
Here is my import:
```ts
import(/* webpackChunkName: "@google/model-viewer" */ '@google/model-viewer/lib/model-viewer');
```
And here are the chunks:
<img width="468" alt="image" src="https://user-images.githubusercontent.com/5757359/218077744-4814dea2-e859-45bf-a03f-d62d499c4b64.png">

And the reason is a bit technical!

You use `three` version `^0.146.0`
I have installed `0.149.0`

If this was `^1.146.0` and `1.149.0` that would work, since the `^` symbol "include everything that does not increment the first non-zero portion of semver"

But because it has a leading 0, it does not work. 
The correct way to do this seems to be `>=0.146.0 <= 1`
