### ISSUE TITLE
Separate texture SRC attribute

### ISSUE THREAD

**Issue by Lemovision** [google/model-viewer#2750]
Hi

For my application (custom user designs) I'm using a single model stored on my server
And I need multiple viewer pages referring to this model, each with a different texture file
Now by default the viewer looks for the texture in the same directory as the model
Can we have a separate attribute for the source path of the texture please?

Here is an example of same model with separate texture reference with 3dviewer.net (folder 01 and folder 02)

https://3dviewer.net/embed.html#model=https://lemovision.com/elephant/assets/Elephant.glb,https://lemovision.com/elephant/assets/01/cbimage.png
https://3dviewer.net/embed.html#model=https://lemovision.com/elephant/assets/Elephant.glb,https://lemovision.com/elephant/assets/02/cbimage.png

(I saw you have a function to "swap textures" on the fly, but then I would have to load the texture twice so I suppose it would be slower than referring to the right texture in the first place)

**Comment by elalish** [comment]
No, because we also have `createTexture()`, so the best way is to make a version of your model without the texture, then load the one you  want on the fly: https://modelviewer.dev/examples/scenegraph/#createTexturesExample
