### ISSUE TITLE
WebXR session crashes Android Chrome when served from iFrame

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#2780]
While working on a Shopify site, I noticed an issue with embedding ModelViewer in an iFrame: 

On Android 11 / Chrome 93, trying to enter a WebXR session is causing Chrome to crash. But, in a very specific scenario, it seems...

I created a demo Shopify site and WebXR testing page to help decipher what may be going wrong. See the demo link below.

On this page, there are 4 iFrames for testing WebXR behaviours. 

The first iFrame embeds the WebXR example from modelviewer.dev. On Android 11 / Chrome 93, tapping 'View in your space' should open a WebXR session, but **causes Chrome to crash** out to the Android home screen. ❌

To confirm, the iFrame code uses `allow="xr-spatial-tracking; fullscreen;"` and `allowfullscreen` to ensure sufficient permission to open a WebXR session. 

The second iFrame embeds the compatibility report page from the Immersive Web site. On Android 11 / Chrome 93, this page **confirms sufficient capabilities and permissions** to run a WebXR session. ✅

The third iFrame embeds a basic `immersive-ar` XRSession demo from the Immersive Web site. On Android 11 / Chrome 93, when tapping 'START AR' a fullscreen **WebXR session does start**, I see the camera feed and the 3D AR objects, as intended. ✅

The fourth iFrame embeds a different Immersive Web demo. On Android 11 / Chrome 93, when tapping 'START AR' **Chrome crashes** out to the home screen, similar to the ModelViewer demo. ❌

As far as I can see, one possible key difference between these 3 examples is how the XRSession is being created.

In the Immersive Web example that works, the code calls `requestSession('immersive-ar')` without any additional options:

https://github.com/immersive-web/webxr-samples/blob/1f1a73a281027dae5c42276a0c07c91322f15219/immersive-ar-session.html#L108-L113

Compare this to ModelViewer (that fails)...

https://github.com/google/model-viewer/blob/0c2f12b4d83a9cbf36e19245359579df5fb50ca6/packages/model-viewer/src/three-components/ARRenderer.ts#L150-L155

...and the other Immersive Web example (that also fails)...

https://github.com/immersive-web/webxr-samples/blob/2d144c75ca537d2cb95625c31f46c2830a0e7850/ar-barebones.html#L93-L96
 
...these both call `requestSession('immersive-ar')` with an `optionalFeatures` parameter of `'dom-overlay'` to, obviously, overlay DOM elements. 

This seems it might be the / a common factor that causes it to crash the WebXR session. 

However, to make matters more complicated, when the exact same iFrame code was tested on another site (the Glitch listed below) then **ALL** of the examples **DO** work. 

The Shopify site is password protected. The Glitch page isn't. So I don't know if this issue is peculiar to Shopify, or the way Shopify handles authentication, or password protected sites in general, or possibly some other aspect of iFrame permissions policy that I need to account for?

Given all of the above information, I'd say this is probably "_not model-viewer_" and either something I'm not accounting for, or a Chrome issue for team Google?
 

#### Live Demo
Shopify test page:
https://webxr-test.myshopify.com
password: demo
Click on "View WebXR Test"

Glitch test page:
https://modelviewer-iframe-test.glitch.me/

### Version

- model-viewer: v1.8.0

### Browser Affected

- [x] Chrome, version: 93.0.4577.62
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android 11
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Thank you for the details! Agreed this is probably outside my purview; @klausw can you comment?

**Comment by alcooper91** [comment]
Can you go to chrome://crashes and report if there are any crash id's that line up with the time of these crashes you're seeing?

**Comment by milesgreen** [comment]
@alcooper91 Yes. I just replicated the crash a few times and have uploaded the crash reports with IDs of:

a415bc051c1474f6
eed34afd11f2c5a3
2590152ca5097a56
00f0a3b45ec6419f
358466c62246ef3b

**Comment by klausw** [comment]
This should be fixed as of Chrome Canary  97.0.4685.0 or newer, I confirmed in 97.0.4688.0.

**Comment by elalish** [comment]
Thanks @klausw!

**Comment by klausw** [comment]
FYI, I have merged the fixes to the Chrome 96 branch, so they should be included in upcoming 96 betas and its later stable release. (It's possible that they could get reverted and not be included there after all, but that's unlikely.)

**Comment by milesgreen** [comment]
@klausw - Awesome! I can confirm that the problematic behaviour I reported is no longer observed in Chrome Canary (tested v 97.0.4689.3).

That's an obscure but massive roadblock removed for us. Thanks for persevering and follow through on that one. Much appreciated.

**Comment by klausw** [comment]
FYI, I confirmed that the fix is included in Chrome Beta 96.0.4664.35, so it is on track to being included in the upcoming stable 96 release.
