### ISSUE TITLE
Clarify our roadmap

### ISSUE THREAD

**Issue by smalls** [google/model-viewer#280]
We have some long-term plans, but they're not currently reflected in the project. Let's make this transparent.

In a discussion today, we looked at using GitHub features like milestones or projects for these goals, but we thought that might not be the best fit. Instead, we may look at something simple like documenting some use cases (in `.md` files somewhere), and adding a high-level overview to the `README.md` (with appropriate links).

**Comment by elalish** [comment]
@cdata I think we just did this! You can take some pride by closing this. Also, isn't this part of our 1.0 milestone?

**Comment by cdata** [comment]
We definitely laid out our plans to get to 1.0. However, there is an argument to be made for laying out a longer term roadmap including our intentions for WebXR and also peripheral projects / tools.

Any thoughts on this @smalls ?
