### ISSUE TITLE
animations not playing on quicklook

### ISSUE THREAD

**Issue by veronicamontezuma** [google/model-viewer#2850]
### Description

Animations in AR stopped playing on quicklook (on iOS15 it appears).
tested the same model on ios14.8 (plays animations) and ios15.0/15.0.1 (does not play animations).
I did look around (google and apple dev forums) and found some similar issues but not much about them... perhaps they changed something about the url params?

(I know quicklook is it's own thing, but thought it was worth opening this issue so if it is something general it is documented, feel free to disagree and close this)

#### Live Demo
https://app.pixelar.studio/viewer/057f7002517ce05b7d7444da8b2679cc40603f24

### Version
- model-viewer: v1.7.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by asemanh** [comment]
Hi @veronicamontezuma , you may want to follow this bug. They said they weren't able to repro it.

https://bugs.webkit.org/show_bug.cgi?id=231904

**Comment by asemanh** [comment]
@veronicamontezuma yes, that sounds about right, just wanted to make sure you know where to reach out if the next release doesn't fix it. :)
