### ISSUE TITLE
SmoothControls should take devicePixelRatio into account

### ISSUE THREAD

**Issue by mrdoob** [google/model-viewer#290]
### Description

We should take `window.devicePixelRatio` into account when processing the user's input. Translation, rotation and zoom amounts will otherwise depend on the device pixel density and will be inconsistent between devices.

#### Live Demo
https://model-viewer.glitch.me/

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions

- model-viewer: v0.7.0

**Comment by elalish** [comment]
The natural thing to me would be to normalize based on width and height (so that dragging all the way across the canvas gave the same amount of motion). But I'm not totally sure that's right either. Is there some UX person we could ask who's studied this?

**Comment by mrdoob** [comment]
I don't think this is still an issue.
