### ISSUE TITLE
Some attributes are not active anymore

### ISSUE THREAD

**Issue by pikil** [google/model-viewer#2908]
### Description

That seems that attributes like `scale` and `orientation` do not work in v1.9.0 anymore.

#### Live Demo
https://glitch.com/edit/#!/shadowed-bristle-radar?path=index.html%3A21%3A92

### Version
- model-viewer: v1.9.0

### Browser Affected
- [x] Chrome (v95.0)
- [ ] Edge
- [x] Firefox (v93.0)
- [ ] IE
- [x] Safari (v15.0)

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Indeed, I just noticed this as well, and fixed  it today: https://github.com/google/model-viewer/pull/2904

I may need to put a point  release next week with this an a  couple of other things.

**Comment by abhilashca** [comment]
@elalish Is that issue still open? I am trying to read values of orientation and scale but it always gives `0,0,0` and `1,1,1`. I have opened a discussion on the same #4015 . It would be great if you could take a look at the same.

Thanks in advance.
