### ISSUE TITLE
v1.9.0 performance regression

### ISSUE THREAD

**Issue by lucadalli** [google/model-viewer#2915]
### Description

After upgrading to v1.9, I was able to observe a significant slowdown for the `setTexture` method. While I was creating a minimal reproduction demo for `setTexture`, I noticed that initial load performance also suffered a regression. I imagine this stems from the same issue.

#### Live Demo
https://codepen.io/citylights/pen/qBXRwvX

The Codepen above serves as a primitive way to measure load performance. Alternate between version 1.8.0 and 1.9.0 by changing the script tag at the top of the `template`. 
Top left of the view shows the visible model count followed by the duration taken to load those models.
On my machine I am consistently measuring ~1500ms for v1.8 and ~10,000ms for v1.9 for 10 models.

### Version

- model-viewer: v1.9.0

### Browser Affected

- [x] Chrome, Win 10 Version 94.0.4606.81 (Official Build) (64-bit)
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Reopening, since I  had to revert the fix since it was causing a bigger problem: #2949. A proper fix is  coming in three.js, but  it'll take our next release cycle to resolve.

**Comment by sprengerst** [comment]
Oh no :( 
When will the next release cycle happen? It makes whole pages unusable :-/

**Comment by elalish** [comment]
@sprengerst you're welcome to pin to either v1.8 or v1.9.1 until our next release comes, e.g. `<script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>`. It's the  holidays, so it'll probably be after the new year.

**Comment by sprengerst** [comment]
@elalish Thank you. Holidays? What country do you live in, I think I should join you. :D
