### ISSUE TITLE
Define/Implement WebXR compatibility plan

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#293]
Now that the post-TPAC/2019 changes to WebXR are making their way into Chrome M73, we have roughly 3 APIs to consider:

* WebXR 2018 - Used by [Chacmool](https://web-education-ar-demo.appspot.com), [WebXR+AR Codelab](https://codelabs.developers.google.com/codelabs/ar-with-webxr), [webxr-polyfill](https://github.com/immersive-web/webxr-polyfill/)
* WebXR 2019 - As defined by the [spec](https://immersive-web.github.io/webxr/), the latest and greatest (no XRDevice, session modes, etc.)
* Chromium implementation - Transitioning somewhere between 2018 and 2019 APIs - as of now there are no sources/docs for example using an XRDevice with the new APIs, like getViewerPose/makeXRCompatible.

Right now, the changes in latest Chromium are just function renames, so testing for existence of functions (https://github.com/GoogleWebComponents/model-viewer/pull/292) is sufficient for now to ensure that AR continues to work on Chrome M73 Canary and M73 Dev. This will become unwieldy once more structural changes land that are more complicated than renaming a function, like the removal of XRDevice (https://github.com/immersive-web/webxr/pull/405) and introduction of "modes" (https://github.com/immersive-web/webxr/pull/419, https://github.com/immersive-web/webxr/pull/432).

We may want to use [webxr-version-shim](https://github.com/immersive-web/webxr-samples/blob/spec-update/js/webxr-version-shim.js) being developed against the latest spec, or a smaller bespoke abstraction once things stabilize, or as a part of the webxr-polyfill, or while things are in flux, only target latest Canary, in which case we should change our AR candidate checks to check that the new/supported API is available, as to not give false positives on Chrome Dev, for example.

This may make #281 redundant.

**Comment by elalish** [comment]
Now that WebXR is shipping in Chrome 81, the plan is to support it.
