### ISSUE TITLE
Clean way for objects to know if they're being rendered via WebXR

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#294]
WebXR requires rendering with the XRSession's framebuffer. Three exposed a way to set this via `renderer.setFramebuffer`, although there are some issues with transparencies and objects that render to their own render target (still need to dig into it more, but: https://github.com/mrdoob/three.js/issues/15393).

Potentially, a `renderer.getFramebuffer` method could indicate that the renderer is using a supplied framebuffer for rendering, but that does not yet exist (and need to learn more how `setFramebuffer` works).

**Comment by elalish** [comment]
No longer applies.
