### ISSUE TITLE
3D Model appears completely black

### ISSUE THREAD

**Issue by ARportals** [google/model-viewer#2949]
The main Modelviewer page nows displays a 3D model of the astronaut that's completely black on my phone Samsung S7. This seems to be related to the new version 1.9.1 that just got out. The same model used to work fine.

Link where you can see the issue
https://modelviewer.dev/

- model-viewer: v1.9.1

### Browser Affected
- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [X] Samsung Internet
- [ ] IE
- [ ] Safari

### OS
- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

![Screenshot_20211101-172522_Chrome](https://user-images.githubusercontent.com/25235922/139744343-86c3f080-3a92-460f-8073-4c1dce4ccf1f.jpg)

**Comment by elalish** [comment]
hmm, actually modelviewer.dev is not  on 1.9.1; I had to do a cherry-pick because of a problem with  three.js r134, so  modelviewer.dev is  on  r134 and v1.9.1 is on r133. Can you  check if the  problem persists  on v1.9.1? Also, do you see any  errors or warnings in the JS console?

**Comment by ARportals** [comment]
Here's what appears in the console:
![image](https://user-images.githubusercontent.com/25235922/139750957-a7d1291a-be06-4875-9269-e697ec499064.png)

**Comment by ARportals** [comment]
I confirm I can see the issue in 1.9.1

**Comment by elalish** [comment]
ugh! Thanks  for the detail. Okay, so this device doesn't support OES_texture_half_float. Does it work on 1.9.0?  or 1.8? And what versions are the  OS/browser? Is it up  to  date?

**Comment by elalish** [comment]
We have at least  one  other Samsung S7 which is working fine  with these examples, so I'm going to  delay panicking until  we get a  little more version info.

**Comment by danbaechtold** [comment]
Same issue here, with 1.9.1
Specs: Android Honor 8X, Android10, Chrome 95.0.4638.50 (all up to date).

**Comment by BobbyBuening** [comment]
Same problem here since v 1.9.1. 1.9.0 and 1.8 work fine. 
Tested on multiple Android devices with multiple .glb models:
Samsung Galaxy S7, Android 8.0.0, Chrome 95.0.4638.50
Samsung Galaxy S10+, Android 11, Chrome 95.0.4638.50

**Comment by GabrielArakaki** [comment]
Same here:

https://modelviewer.dev/ showing blacked out 3D model.

Samsung Galaxy S10e, SM-G970F
Android 11
Chrome 95.0.4638.50

**Comment by elalish** [comment]
@BobbyBuening Okay, so v1.9.1 is working properly on your devices but modelviewer.dev is not? Did you test with the same model? 

@GabrielArakaki Can you check if v1.9.1 is working or not (which is different than modelviewer.dev)? 

@danbaechtold and everyone else: can you please check a few different models to see how widespread this is? And also please check your JS console to see if you're also seeing `OES_texture_half_float extension not supported` or something else. We may have multiple issues contributing here.

Oddly we a Samsung S7 here on  Android 7 with Chrome 95 and this is all working, so this is very confusing.

**Comment by tpsiaki** [comment]
I tried modelviewer.dev on a Samsung Galaxy S7 with Android 8.0 (also tried w/ Android 7.0 before updating) and Chrome 95 and the astronaut is displaying correctly.

**Comment by danbaechtold** [comment]
@elalish You can reproduce it easily with BrowserStack Live (they let you test on real devices!):

Choose the Huawei P30 and open modelviewer.dev. It looks good for a sec (probably the poster image), then goes black.
And yes, it is the `OES_texture_half_float` issue (visible in their developer console).

**Comment by Josegranformato** [comment]
I am having all models show completly black, my other 2 projects at model viewer also look black online and live AR , the projects were fine but today, my Huawei P30 pro its showing all the models black, even the official modelviewer.dev astronaut looks black, the usdz looks fine, no problem on iphone.

**Comment by elalish** [comment]
Okay, so I've been told that apparently many Samsung phones have different GPUs in different countries, and their extension  support varies. I'd guess the reason we're not seeing consistent results is that we're testing devices with different GPUs. 

The strangest part is that this appears  to  be because of the switch back to WebGL1 (to avoid the performance regression). So apparently a given GPU supports half float  textures in  WebGL2, but not in  WebLG1. How much you want to bet  it's an  Adreno chip? 🙄

I'm stuck a bit between a rock and a hard place here. This seems to be a bigger problem than even the performance regression was, so I think I'll  have to put out a v1.9.2 that  reverts #2936. Then we'll do some work in three.js and get a proper fix out for the next  release cycle.

**Comment by Josegranformato** [comment]
Ok, I have no idea how to revert it, I have the Huawei p30 pro, processor Huawei Kirin 980, android 11, I have not done any update

**Comment by elalish** [comment]
I verified the fix (thanks @danbaechtold for the tip on Huawei P30  on BrowserStack) and pushed a v1.9.2  to npm, so your  sites  should start  working  again shortly as that  rolls out. I'm in the process of adding that  to our automated tests to keep this kind of  regression from happening in  the future. Thanks all for the details in helping to resolve this.

**Comment by Josegranformato** [comment]
great!! thanks so much, I am checking soon on it
