### ISSUE TITLE
Extremely slow performance with specific test file

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#2958]
### Description

The entire browser locks up when loading the comparatively small attached file.
This seems to be a threejs issue as it also happens in threejs editor and not only in model-viewer, tracked here for awareness.

See https://github.com/mrdoob/three.js/issues/22785 for full description and test file.

Might be related to the recent slowdowns mentioned in https://github.com/google/model-viewer/issues/2915 regarding shader compilation - the attached file will probably cause a number of different shaders to compile.

**Comment by timmmeh** [comment]
This sounds like the threejs slowdown issue currently tracked by 2915. 

Which browser are you testing on?

As a workaround you can pin v1.8 until our next release comes, e.g. <script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>

**Comment by hybridherbst** [comment]
It's Chrome on Windows, in the threejs issue a couple of related problems are linked - seems my poor little test file runs into multiple bugs in Chrome and threejs that together make it load forever.

**Comment by timmmeh** [comment]
Yes Windows is one of the main offenders, Chrome on OSX seems to be ok. Our only solution/workaround at the moment is to pin an older version model-viewer (which uses previous threejs) while this gets cleared up.
