### ISSUE TITLE
[Feature Request] Support for meshopt in modelviewer.dev/editor

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#2959]
### Description

model-viewer supports meshopt now 🎉 
However, seems the editor doesn't yet.

#### Live Demo

1. download [MultiRange2.etc1s+meshopt.zip](https://github.com/google/model-viewer/files/7479092/MultiRange2.etc1s%2Bmeshopt.zip)
2. open https://modelviewer.dev/editor
3. import the file

Expected: displays the file
Actual: loading bar, no console warning or error, but also no file

**Comment by timmmeh** [comment]
If it's working in model-viewer but not the editor than this is probably a bug

**Comment by hybridherbst** [comment]
For other meshopt-compressed files that don't use etc1s, there's actually an error logged:
```
Uncaught (in promise) Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files
    at GLTFMeshoptCompression.loadBufferView (space-opera.js:76401)
```
