### ISSUE TITLE
AR Quick View's AR Quick View button cannot be pressed on some iOS devices.

### ISSUE THREAD

**Issue by tokufxug** [google/model-viewer#2971]
### Description
AR Quick View's AR Quick View button cannot be pressed on some iOS devices.
As for the iPhone 12 Pro, the AR Quick View button cannot be pressed on iOS 15 when reading from the standard iOS QR code reader, but the AR Quick View button can be pressed on the iPhone 12 Pro with iOS 14.
On other devices, you can press the AR Quick View button when launching from Safari, but you cannot press the AR Quick View button when accessing from the standard QR code reader. Also, on some iOS devices, the AR Quick View button cannot be pressed.
The problem seems to be occurring outside of the Live Demo page as well.
Is there any way to avoid this AR Quick View button not being able to be pressed? It would be very helpful if I could get more information than just the solution to this problem.

iPhone7(iOS13):OK
iPhoneX(iOS15):OK
iPhoneX(iOS15):QR Code Reader:NG
iPhone11(iOS14):OK
iPhone12Pro(iOS14):OK
iPhone12Pro(iOS15):OK(QR Code Reader:NG)
iPhone12(iOS15.1):QR Code Reader:NG
iPad Air(iOS15):QR Code Reader:NG
iPhoneSE(iOS15):QR Code Reader:NG
Sometimes I can press the AR Quick View button on the same model, and sometimes I can't.

![image](https://user-images.githubusercontent.com/323081/140857972-7448281f-0f00-4471-a95a-17c6b1d3c668.png)

#### Live Demo

https://konabeer.jp/beach-diorama-ar/

### Version

- model-viewer: v1.9.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by tokufxug** [comment]
As a result of our own verification, the AR Quick Look button is deactivated on iOS 15 and when the QR code is imported from the Control Center. If you know of any known bugs or workarounds, or if there are any informative sites that have information on this issue, I would appreciate it.

**Comment by samaneh-kazemi** [comment]
Hi @tokufxug, can you try pinning version 1.8 and see if that works for you until iOS gets fixed?

**Comment by samaneh-kazemi** [comment]
e.g. 
```
<script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>
```

**Comment by tokufxug** [comment]
@samaneh-kazemi  I tried it with v1.8.0, but it did not improve the situation
![e455b9e0f879cac5e1aace55968159f7110521fc](https://user-images.githubusercontent.com/323081/141234302-0e9cc905-cb32-43a8-be13-612dddfb3a88.png)
.

**Comment by tokufxug** [comment]
![image](https://user-images.githubusercontent.com/323081/141234398-412b010d-eac2-4453-9c13-44a27b11509a.png)

**Comment by samaneh-kazemi** [comment]
Hi @timmmeh, any thoughts on this?

**Comment by samaneh-kazemi** [comment]
Hi @tokufxug, I actually was able to see the AR button and open the AR model. I'm using iOS 15.1
![photo4934209617244826094](https://user-images.githubusercontent.com/3915613/141528907-c29c375a-f3de-475a-9e52-6c9eb04aff79.jpg)
![photo4934209617244826095](https://user-images.githubusercontent.com/3915613/141528915-f8f8c2d5-468a-43fe-ac80-7bb344f42b23.jpg)

**Comment by minigorille** [comment]
I have same issue here, Iphone 12 PRO and ios 15.1 I can not place object in AR anymore, it will open the Apple object 3d loader but the AR button is greyed out.

**Comment by samaneh-kazemi** [comment]
Hi @minigorille , which version of model-viewer have you tried?

**Comment by minigorille** [comment]
@samaneh-kazemi I use the general one on my website : https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js

This is the website : https://streetartifacts.xyz
Best

**Comment by samaneh-kazemi** [comment]
@minigorille so as I shared earlier, try earlier version of model-viewer and see what happens
```
<script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>
```

Also, I tried your link in my iPhoneXR, iOS 15.1 and I was able to see both AR button and the model

**Comment by samaneh-kazemi** [comment]
![image](https://user-images.githubusercontent.com/3915613/141597622-2e517221-03be-4fbe-a621-2b974883177e.png)

**Comment by samaneh-kazemi** [comment]
![image](https://user-images.githubusercontent.com/3915613/141597637-2d180096-bfbf-4cdc-87d7-38379d8b7174.png)

**Comment by minigorille** [comment]
> @minigorille so as I shared earlier, try earlier version of model-viewer and see what happens
> 
> ```
> <script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>
> ```
> 
> Also, I tried your link in my iPhoneXR, iOS 15.1 and I was able to see both AR button and the model

Ok will try with older version, did you use google chrome or safari? I only have issue with Chrome and just realized also have issue with WebApp so App created from Safari.

**Comment by tokufxug** [comment]
@samaneh-kazemi 
>Hi @tokufxug, I actually was able to see the AR button and open the AR model. I'm using iOS 15.1

Did you access it with the QR Scanner in Control Center? This problem occurs with the QR Scanner in Control Center.

![image](https://user-images.githubusercontent.com/323081/141614517-63767232-6605-433e-81d2-6c9fe601b907.png)
![6e63bb2433fc2aad0c35b34d2da20e463a31a59b](https://user-images.githubusercontent.com/323081/141614533-50e2e955-40b5-4079-9bc2-4544a21c5cea.png)

https://www.iphonelife.com/content/how-to-add-qr-code-scanner-to-control-center-iphone

**Comment by timmmeh** [comment]
I can repro this issue too when using the QR code generated by the Editor, it works fine when viewing launching into AR from the example so I can only guess at this point that there is some missing configuration on the page hosted by the piping-server.

**Comment by elalish** [comment]
This definitely appears to be an iOS 15.1 bug (did not repro for me on 15.0). I can repro, in that Safari and Chrome both do AR fine (Chrome only  if ios-src is specified, since it has its own bug), but in-app browsers do  not. The QR Scanner is one example (the camera  QR  detector works fine because it opens actual Safari), and Twitter is another. If  you open https://twitter.com/hybridherbst/status/1465093146866556929 in the twitter app on iOS, AR doesn't work, while through the  web, it does. 

Considering that the model is properly shown, we have clearly  given Quick Look everything properly. They  have intentionally disabled  AR for app-based browsers and I'm not sure why (though I would guess some privacy/security issue). If someone would like to  file this on Apple,  I'd appreciate  it: https://bugs.webkit.org

**Comment by milesgreen** [comment]
This appears to be fixed in iOS 15.2
Tested in both the iOS Control Center QR Code Scanner and from iOS Twitter App with iPhone 12 Pro. Both now open Quick Look in AR, as expected.

**Comment by elalish** [comment]
Thanks @milesgreen! Good to hear the Safari bug count is finally going down instead of up.

**Comment by kk12837** [comment]
thanks!
