### ISSUE TITLE
game controller support?

### ISSUE THREAD

**Issue by Cicango** [google/model-viewer#3002]
### Description

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

- model-viewer: v8.891.0

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
 Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Please leave more detail than a heading so we know what you're asking  for.

**Comment by Cicango** [comment]
I have a Chinese generic xbox controller with usb connection to arch linux and I would like to connect the controller to model-viewer so I can control the 3d model with a game controller.

Is that possible?

**Comment by Cicango** [comment]
> Please leave more detail than a heading so we know what you're asking  for.

I have a Chinese generic xbox controller with usb connection to arch linux and I would like to connect the controller to model-viewer so I can control the 3d model with a game controller.

Is that possible?
