### ISSUE TITLE
Not work createThumbnail of glb

### ISSUE THREAD

**Issue by canberka** [google/model-viewer#3005]
I am trying to do create thumbnails of my glb like modelviewer/editor.  

some discussions talked about that but i failed somewhere.

```
  <img id="thumbnail" src={thumbUrl} />
  <script>
  
  
  const modelViewerTexture = document.querySelector("model-viewer#sphere");
  modelViewerTexture.addEventListener("load", (ev) => {
    let material = modelViewerTexture.model.materials[7];
    let thumbUrl =  material.baseColorTexture.texture.source.createThumbnail(128, 128);
  
  })
  
  </script>
```
![image](https://user-images.githubusercontent.com/36857390/144098634-717482d5-c96e-4c6c-aadd-3f26341c9897.png)

And also this not works too

```
  <img id="thumbnail" src={thumbUrl} />
  <script>
  
  
  const modelViewerTexture = document.querySelector("model-viewer#sphere");
  modelViewerTexture.addEventListener("load", (ev) => {
    let material = modelViewerTexture.model.materials[7];
    let thumbUrl =  await material.baseColorTexture.texture.source.createThumbnail(128, 128);
  
  })
  
  </script>
```
![image](https://user-images.githubusercontent.com/36857390/144098752-342c99c1-6dd7-4dcc-95bc-d0606320a5a7.png)

**Comment by elalish** [comment]
Let's keep this discussion centralized: https://github.com/google/model-viewer/discussions/2957#discussioncomment-1709578
