### ISSUE TITLE
Orbit distance change is too strong when min distance is small

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3013]
### Description

For detailled models, a small (~1-5% or smaller) orbit distance might be required to avoid cutting into surrounding geometry. It seems that the calculations for orbit distance react very strongly to the difference between min and max orbit (e.g. when setting to 1% and the default 105%, the camera moves far too much in the "small range"). 

#### Live Demo
https://glitch.com/edit/#!/thor-and-the-serpent?path=index.html%3A52%3A37
You can reproduce by double-clicking on any person to set the target and then zooming in with the mouse-wheel - a single "scroll step" will make a giant difference.

The orbit change seen here is a single mouse wheel step, but the same behaviour can be noticed on mobile where "zooming" feels wrong (resulting effect is much too strong):
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/2693840/144473543-a2dff57e-8431-4d28-a8f0-2d9952600603.gif)

The behaviour seems to depend heavily on the min-orbit-distance; adjusting that to 5% (which would be the max value I'd set for this scene) yields the same behaviour of scrolling being too uncontrollable at small distances.

A similar behaviour happens when controlling "perceived zoom" via field of view only; the issue is that in a scene like this one really wants to set the camera distance, otherwise the dragon is always in front of whatever you want to look at.

### Version
- model-viewer: v1.9.2

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [X] Windows

**Comment by elalish** [comment]
Here is  the code that controls the zooming behavior: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/three-components/SmoothControls.ts#L374-L391

As I recall, I used `log(fov)` to try to improve  exactly this  issue, since  changing fov in equal degree steps is even more insanely nonlinear. If you  can  find a better solution, I'd be  happy to see a PR.

**Comment by hybridherbst** [comment]
I think another (at least partial) solution would be to expose something like "zoom-sensitivity"; https://modelviewer.dev/docs/#entrydocs-stagingandcameras-attributes-orbitSensitivity seems to intentionally exclude zoom.

I agree that finding the right math would be better :)

**Comment by elalish** [comment]
Since we found a decent work-around for the example, I'm going to call this mostly fixed.
