### ISSUE TITLE
Lights contained in the GLTF file are transformed independently of the model

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3017]
### Description

Scenes that contain lights seem to behave strange in regards to where the lights are positioned. Somehow they seem to be outside the actual model hierarchy.

This affects both web mode and WebXR mode, with WebXR mode being even more problematic because the transformation is way off there.

#### Live Demo
https://prefrontalcortex.de/labs/model-viewer/upload/LightCones/

**Expected:**
![image](https://user-images.githubusercontent.com/2693840/144490278-7e6bf90f-a14f-4b8e-b8e3-42069a657162.png)

**Babylon:**
![image](https://user-images.githubusercontent.com/2693840/144490361-079aa89f-3d90-4cf3-b7ba-3f5450171cf1.png)

**SceneViewer:**
![image](https://user-images.githubusercontent.com/2693840/144490639-d7247b45-530c-4f18-bc20-177911a757fb.png)
(Related issue https://github.com/google/model-viewer/issues/2474 is still open regarding the light values not being scaled correctly when scaling the model, resulting in an unintended dependency between model scale and light intensity)

**model-viewer**:
![image](https://user-images.githubusercontent.com/2693840/144490724-cbdd1d61-ed54-4482-a56d-94274c70a045.png)

**model-viewer when panning:**
![uZ0bABX6U1](https://user-images.githubusercontent.com/2693840/144490798-1cd21759-03e3-45e7-871e-7b96190dff13.gif)

**WebXR**: (just a black square)

### Version
- model-viewer: v1.9.2

### OS Tested

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

### AR
- [X] Non-AR
- [X] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
I'd guess this is related to #2474 too. I *think*  this is a three.js thing, though it's entirely possible we're making a  bad assumption somewhere.

**Comment by hybridherbst** [comment]
Some more pictures, looks ok in the threejs.org/editor:
![image](https://user-images.githubusercontent.com/2693840/144502312-03b53134-4dea-4a61-8eab-5f80579fecd2.png)

modelviewer.dev/editor:
![image](https://user-images.githubusercontent.com/2693840/144502644-b6fc17f6-5d67-4bc8-803c-614431b54710.png)

And interestingly, gltf.report (I think this uses model-viewer, but maybe a modified version?)
![image](https://user-images.githubusercontent.com/2693840/144502709-f1ea7bd2-c98b-44dc-b84c-26900c2b776f.png)
