### ISSUE TITLE
WebXR API changes (XRViewerPose.views, XRView.viewMatrix)

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#302]
XRViewerPose has added `views` (replacing `frame.views`) and XRView has added `viewMatrix` (replacing `pose.getViewMatrix(view)`, which landed in Chrome m73 earlier this week [1](https://chromium.googlesource.com/chromium/src/+/d9eb23defc881813572049b8e5903f24241bf55a) [2](https://chromium.googlesource.com/chromium/src/+/d9eb23defc881813572049b8e5903f24241bf55a)

**Comment by elalish** [comment]
This has been fixed for awhile.
