### ISSUE TITLE
Safari on Monterey: transparency not rendering with etc1s textures

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3024]
### Description

Not sure where this issue belongs (three? Safari? model-viewer?, but wanted to track here first since it's affecting our model-viewer usecases on, well, the latest and greatest of devices that many people use.

Seems when etc1s-compressing textures, transparency information is lost _only_ on Safari 15 on Monterey.

#### Live Demo
https://glitch.com/edit/#!/sponge-lemon-vulture

**Safari 15 (not transparent)**
![image](https://user-images.githubusercontent.com/2693840/144622887-7335174e-d1a6-43cf-a780-39375291e120.png)

**Everywhere else I tested (transparent)**
![image](https://user-images.githubusercontent.com/2693840/144622958-cd816c19-795e-4d15-abd6-4984801ae4b1.png)

### Version
- model-viewer: v1.9.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows

### Reports on other platforms
Webkit Bug: https://bugs.webkit.org/show_bug.cgi?id=233817

**Comment by elalish** [comment]
Argh! Why is  Safari 15 such a disaster?? Thanks, and yes please file this on WebKit:  https://bugs.webkit.org

You might also want to file it on whatever software you use to generate etc1s textures, since I imagine they'll want to track this too.

**Comment by hybridherbst** [comment]
I filed a bug with Webkit, added the link to the original post, and opened an issue with gltf-transform 🙃

**Comment by donmccurdy** [comment]
Cross-referencing:

- https://github.com/KhronosGroup/3D-Formats-Guidelines/issues/17
- https://github.com/donmccurdy/glTF-Transform/issues/446
- https://github.com/mrdoob/three.js/issues/22899

https://bugs.webkit.org/show_bug.cgi?id=232357 is a different issue though – happening only with uncompressed images decoded with the `createImageBitmap` API.

**Comment by hybridherbst** [comment]
I fixed the link, the one I reported as new bug is https://bugs.webkit.org/show_bug.cgi?id=233817

**Comment by elalish** [comment]
This appears to be fixed.
