### ISSUE TITLE
Random parts of models go black on iOS 15

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3025]
### Description

On iOS 15, random parts of different models go black / have a black texture. Haven't found a pattern besides that it seems memory-related; even higher-end phones like iPhone XR exhibit the behaviour in like 2/3s of cases, while higher-end devices like recent iPads exhibit the behaviour only in 1/20 of cases or so.

(I don't think this is related to #2949)

#### Live Demo
https://glitch.com/edit/#!/zigzag-stellar-iguana

Screenshots of the same page after reloading a couple of times; the "full black" state happens less often:
![IMG_0178](https://user-images.githubusercontent.com/2693840/144628158-4705b65e-ce10-412b-b1ae-ecdcecc13730.PNG)
![IMG_0176](https://user-images.githubusercontent.com/2693840/144628166-4c88854c-6407-40b4-a10a-26d370c51bff.PNG)
![IMG_0177](https://user-images.githubusercontent.com/2693840/144628179-d4dff960-590c-476c-950a-a4bd0a571858.PNG)

Also happens on latest dev but slightly different, sometimes the top sphere (it's transparent) doesn't appear at all while it appears black in 1.9.2:
![Datei_000 (1)](https://user-images.githubusercontent.com/2693840/144630357-95537e8e-76f2-4e22-8e31-254a547fb8f1.png)

### Version
- model-viewer: v1.9.2

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android (tried to repro, didn't repro even on lower-end devices)
- [X] iOS (even on higher-end devices)
- [ ] Windows (tried to repro, didn't repro)

**Comment by elalish** [comment]
Yes, we've had a number of reports of this, but the best discussion is here: https://github.com/mrdoob/three.js/issues/22652

So the question is whether to wait for WebKit's bugfix to come down or try to work around it.

**Comment by sprengerst** [comment]
But didn't you fix this with 1.9.0 and introduce the "Windows performance bug" and "Android black bug" with it? There was a rollback to previous WebGL right?

**Comment by elalish** [comment]
Ha, if only that were the only issue 😭. This one is unique to Safari. Ah the joys of WebGL development...

**Comment by sprengerst** [comment]
Oh god :( Could you please tell me when you plan the next release? Maybe this issue is fixed with updated threeJS?

**Comment by sprengerst** [comment]
https://github.com/mrdoob/three.js/pull/22975

It looks really good that they will include a workaround.
