### ISSUE TITLE
[Documentation] the alt and id attributes on some examples are not up to date 

### ISSUE THREAD

**Issue by benmbark** [google/model-viewer#3033]
On some examples on scenegraph,  the `alt` and `id` attributes are not up to date with the corresponding models. 
https://modelviewer.dev/examples/scenegraph/
![mode-viewer](https://user-images.githubusercontent.com/8107923/144977943-8049c403-1f2a-4821-8941-54903f0fec3d.png)

**Comment by elalish** [comment]
PRs welcome 😁

**Comment by benmbark** [comment]
Done. my first PR here :  [3040](https://github.com/google/model-viewer/pull/3040)
