### ISSUE TITLE
Static site dashboard visualizing fidelity progress over time

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#306]
WIth the introduction of #305 we will have begun keeping records of the visual fidelity between `<model-viewer>` and various reference model viewers. This issue covers the work necessary to visualize progress towards greater consistency between all viewers over time, based on the records of our testing.

**Comment by elalish** [comment]
I think this is more trouble than it's worth, especially as we migrate the goldens out of our repo. FYI @sun765
