### ISSUE TITLE
Metalness on iOS not working in QuickLook

### ISSUE THREAD

**Issue by jozkr8** [google/model-viewer#3064]
### Description

Metalness edit says - 'Object requires a newer version of iOS'

### Version

iOS 14-15.

### Browser Affected
- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x ] Safari

### OS

- [ ] Android
- [x ] iOS
- [ ] Linux
- [ x] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
Can you please give a  more complete set of repro steps? I'm not sure what you're testing. Also, what device are you using?

**Comment by jozkr8** [comment]
https://modelviewer.dev/examples/scenegraph/#changeMaterial - this gets  'Object requires a newer version of iOS'

**Comment by elalish** [comment]
Safari 15.5 has fixed a lot of things; hopefully this is one.
