### ISSUE TITLE
.glb model crashes the webpage on iOS Safari

### ISSUE THREAD

**Issue by v-prgmr** [google/model-viewer#3067]
### Description

A glb model was first converted to gltf + 4k texture with draco compression using Blender. The 4k texture was then compressed and recombined with the gltf model as binary .glb file. This .glb model when loaded via modelviewer, works well on Chrome on Android but while loading the same page on Safari on iOS, the webpage crashes. The .glb file used was converted to usdz using USD_from_GLTF converter. Also sometimes the modelviewer shows the .glb model in gray in Safari without the textures in the 3D viewer.

#### Live Demo
Link to glb (https://drive.google.com/file/d/1i8qDC8bdBebfpnGHzR21PkCMy4sUSnN6/view?usp=sharing)
Link to usdz (https://drive.google.com/file/d/1ydR2Xhui6xhS-L_QsdPxG7OTRlPU2OcX/view?usp=sharing)
### Version

- model-viewer: v1.9.2

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari (iOS 15.0.1)

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [X] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Yeah, Safari 15.1 appears to have introduced some kind of major GPU memory  leak. I  believe #3025 and #3000 are the same issue. The good news is it looks like a workaround has been found upstream in three.js, so hopefully our next release will improve things. Meanwhile, please  ask WebKit to fix their implementation of `ImageBitmap`.

**Comment by v-prgmr** [comment]
@elalish  An update from the various tests I carried out. Newly generated models which are compressed using DRACO compression from Blender (tested 2 versions, 2.91 and 3.0) are causing the browser (Safari and Chrome) to crash on iOS. However, the browser does not seem to crash when I use an old .glb model which underwent the same compression routine using Blender 2.91 a long time ago.

Could this mean there is a problem with the .glb models instead?

**Comment by elalish** [comment]
Does this behavior repro even with extremely simple models? If so then there's probably a bug  in the DRACO decoder. If not, then it's probably just running  out of GPU memory, in which case lots of things could affect it. Chrome and Safari are both  WebKit on iOS, so it's likely still their bug. Thanks for the info!

**Comment by v-prgmr** [comment]
@elalish Found the issue! It was the **8K** texture that was causing the issue. I baked the same .glb models once again with **4K** textures and everything works like it used to. (Maybe I will reduce the resolution further and experiment with the quality).  Thank you so much :)
