### ISSUE TITLE
camera-target shouldn't work during webxr

### ISSUE THREAD

**Issue by futahei** [google/model-viewer#3068]
### Description
I used the Annotation feature to add a process to change `camera-taget` and `camera-orbit` when the button is clicked, and it works fine in 3D-view, but when I click the button in AR (webxr), the model moves.
`camera-orbit` seems to be ignored, but changing `camera-target` causes the model to move.

I think that `camera-target` shouldn't work during AR mode (webxr).

#### Live Demo
**Preview**
https://held-chestnut-gauge.glitch.me
**Code**
https://glitch.com/edit/#!/held-chestnut-gauge

### Version
- model-viewer: v1.9.1

### Browser Affected
- [x] Chrome, version: 96.0.4664.104
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [x] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Good point, I can't think  of any reason the 3D camera target should affect the AR scene.
