### ISSUE TITLE
Support multiple "live" references per fidelity test scenario

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#308]
As of #305 , fidelity tests take a screenshot of `<model-viewer>` at test-time, while reference viewers have their screenshots captured by hand in advance.

It should be straight-forward to expand our automation to support multiple test-time screenshots per test. This would allow us to include HTML documents corresponding to other web-based reference viewers (such as Khronos' viewer, Babylon etc.)

**Comment by elalish** [comment]
I'm fine with leaving other renderers as an offline process. I think it's best to bump their versions only occasionally, and take a hard look at the results when we do. FYI @sun765
