### ISSUE TITLE
JS error when switching material variants if not all model parts have variant definitions (intentionally)

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#3086]
### Description

I noticed that some models with particular material variants cause an uncaught JS error when changing `variantName`.

It appears that it is caused when there are multiple nodes in the GLB and some nodes have variant definitions and some parts don't. 

This is an intentional scenario where there might be a model with multiple variants for some parts, but other parts don't change between variants. EG. For a model of a car, the bodywork might change paint colour, but the wheels wouldn't.

See demo:

https://modelviewer-materialvariant-test.glitch.me/

View the demo. Select the 'Primitives XOX' model from the first dropdown (default). Then select the 'Green' material from the second dropdown. A JS error is thrown. Cone and Cube should turn green, Sphere should remain black. But only Cube turns green. Now select another material. Now select 'Green' again, and this time no error occurs, both Cone and Cube are updated, as expected. So it appears to only affect the first time that variant is applied and subsequent applications work fine. 

See the JS Console for the following error:

<img width="853" alt="Screenshot 2021-12-29 at 18 44 16" src="https://user-images.githubusercontent.com/53870482/147693734-ff1cb411-75a0-4b7c-bb3b-045c29428598.png">

All the other models in the demo link work, as they all define variants for every node. 

#### Live Demo

https://modelviewer-materialvariant-test.glitch.me/

### Version

- model-viewer: v1.9.1

### Browser Affected

- [x] Chrome, version: 96.0.4664.110
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari, 15.1

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by milesgreen** [comment]
I think I might have found a more definitive case. 

In the above demo, I have added one more model: 'Primitives XOX'. This also causes the JS error. 

I noticed in the original Faucet model that 2 of the 3 nodes had variants defined in the GLB, but the third had no variants, as it doesn't change material between variants. 

I created a new model, 'Primitives XOX', with 3 basic primitives. 2 of the primitives (cone and cube) have material variants defined, the sphere has no material variants defined.

This new model causes the same JS error.

**Comment by milesgreen** [comment]
Updated title to be more specific to what I now think the issue is caused by

**Comment by milesgreen** [comment]
Modified initial error description to be more specific to what I now think the issue is caused by.

**Comment by elalish** [comment]
@timmmeh I can repro this on master; would you  mind taking a look when you're around?

**Comment by timmmeh** [comment]
@milesgreen thanks for tracking this down

**Comment by timmmeh** [comment]
@milesgreen can you provide the Primitives XOX model, its blocked from download in the glitch sample

**Comment by timmmeh** [comment]
I setup a local test to reference the model and was able to patch this bug.

**Comment by milesgreen** [comment]
Sorry @timmmeh. Been AFK and only just seen your request for the GLB. But looks like you’ve already resolved it? Let me know if you still need the sample GLB.

**Comment by timmmeh** [comment]
No problem and it looks resolved so I shouldn't need that anymore, I can always reference it directly, just can't drop it into the editor but no biggie, thanks again for pointing this issue out.

**Comment by milesgreen** [comment]
Just in case:
[Primitives-XOX.glb.zip](https://github.com/google/model-viewer/files/7796186/Primitives-XOX.glb.zip)
Thanks for the prompt fix.

**Comment by milesgreen** [comment]
Can confirm that pulling from master after this commit has indeed fixed the issue I was seeing on the above demo page.
Thanks
