### ISSUE TITLE
Add discrete PBR cases to fidelity test suite

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#309]
@donmccurdy assembled very thorough, discrete PBR tests to compare Three.js and Khronos' WebGL renderer to a (as yet unidentified) ray tracer.

This issue covers work necessary to add similar, discrete comparisons to the `<model-viewer>` fidelity tests that will land as of #305 .

@jsantell is currently investigating the potential of using [Mitsuba](https://www.mitsuba-renderer.org/) as a reference ray tracer for producing screenshots for comparison.

**Comment by elalish** [comment]
@cdata If we're doing rendering work for 0.5, perhaps this should happen at the beginning of that to make sure we're on the right track?

**Comment by cdata** [comment]
Yeah, possibly. I don't think we have the time integrate Mitsuba renders ahead of 1.0, although that would be cool. But, we could definitely implement some basic test scenarios using different material spheres each testing some discrete PBR property.

**Comment by elalish** [comment]
I think the PBR test cases will come from the 3D Commerce group, once they make their samples available.

**Comment by elalish** [comment]
This is now working, mostly.
