### ISSUE TITLE
AR button is not working on IOS 15, safaricontroller

### ISSUE THREAD

**Issue by kk12837** [google/model-viewer#3095]
### Description

The AR button is not working on IOS 15, safaricontroller

#### Live Demo

[https://dev.hkep.com/test/keith/video/123.MP4](url)

### Version
- model-viewer: v1.8.0

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [x] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
This was a Safari 15.1 bug  that was reported fixed in 15.2: https://github.com/google/model-viewer/issues/2971#issuecomment-998330528
