### ISSUE TITLE
AR button and markers is disappearing randomly

### ISSUE THREAD

**Issue by bieldiaz** [google/model-viewer#3097]
### MY CODE
```
<model-viewer 
    environment-image="/assets/test/spruit_sunrise_1k_HDR.hdr"
    skybox-image="/assets/test/spruit_sunrise_1k_HDR.hdr"
    src="/assets/test/spheres/bolaPlana8.gltf"
    ar
    ar-modes="webxr scene-viewer quick-look" 
    camera-controls
  >
  <button #hotstop class="Hotspot" [ngClass]="{'hidde' : (showMarkers$ | async) == false}" slot="hotspot-2" data-position="-0.38768624421372744m 0.71344296341581m 0.43869763985752946m" data-normal="-0.6505763992356204m 0.16255461108780261m 0.7418398392993653m" data-visibility-attribute="visible">
    <div class="HotspotAnnotation">front of sphere here</div>
  </button>
  <button slot="ar-button" id="ar-button">
    View in your space
  </button>
  </model-viewer>

```
### Description
 I'm working with the model viewer with angular 13. And when I move the 3D object, the ar button and the markers disappear. I have just updated my iphone to version 15.2. The AR is working correctly but disappears randomly. Someone could help me? 

#### Live Demo
https://www.youtube.com/watch?v=W-XhWnKcNJw&ab_channel=BielDiaz

### Version
scripts: https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS
- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
That's strange. Can  you try to make a glitch or codepen that  reproduces  it? Or at least post a URL where we can repro? I  would guess that Angular is doing something weird, so it would be especially helpful if you can repro with some plain HTML.

**Comment by bieldiaz** [comment]
Hei @elalish, 
I am attaching a codepen, but it doesn't work since I can't hang the glb and gltf files. I have been using this set of files (.html, .css, and .ts) as a component of angular. I have done it this way and it has worked correctly, but the buttons keep disappearing randomly. I have a series of services that help me load the Model Viewer scripts.

codepen: https://codepen.io/bieldiaz/pen/OJxZeKa

Thanks :)
