### ISSUE TITLE
Model displayed in low-res (pixelated/blurry)

### ISSUE THREAD

**Issue by snowchii** [google/model-viewer#3107]
### Description

I just want to start by saying that I'm not a coder, I just followed the instruction from the official website and implemented some 3D objects on the homepage of my Shopify website. I've also seen this issue being reported a few times, most recent in #3044. To sum up the problem: models are blurred and with auto rotation enabled, they are a bit laggy (the other elements on the page are fine, only the model has this issues). I'm using the minified version of the model-viewer.

**Things I've noticed:**

- Zooming in/out does nothing
- Refreshing the page does nothing
- The model is displayed in full quality and after ~1 second, it gets blurred/low quality (see video below). Focus on the left side of the box and you will see how the quality goes from high-res to low-res

https://user-images.githubusercontent.com/97367250/148663385-57145b44-8b57-4eca-893d-6e4c7c16155d.mp4

The real quality of the object (imported in Model Viewer Editor)
![box-quality](https://user-images.githubusercontent.com/97367250/148663165-3d88506c-8391-46b2-a0e7-5894cf21eb80.jpg)

This is the code that I'm using:

```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>

<style>
model-viewer {
  width: 100%;
  height:  800px;
  float: left;
}

model-viewer#reveal {
    poster-color: transparent;
  }

.progress-bar {
  display: none;
  visibility: hidden;
}
</style>

<model-viewer bounds="tight" interaction-prompt="none" camera-controls disable-zoom auto-rotate-delay="0" src="LINK" ar ar-modes="webxr scene-viewer quick-look" environment-image="neutral" id="reveal" loading="eager" auto-rotate poster="LINK" shadow-intensity="1" camera-orbit="-108deg 76deg auto" camera-target="0m 0.13m 0m" min-camera-orbit="-14deg 76deg 0.5826m" max-camera-orbit="-14deg 76deg auto" min-field-of-view="45deg">
<div class="progress-bar" slot="progress-bar"></div>
</model-viewer>
```

I've updated to the latest version of Chrome (97.0.4692.71) on Windows 10 and that fixed the problem (before I was using 96.x.x). On Android (Huawei Android 9), the issue is still present in the Chrome browser (latest version). I haven't tested all the browsers on Android.

The issue was not present a few days ago, I've only noticed it today.

Please let me know if this issue could be fixed somehow or if I should just wait for the next version of the model-viewer.

Thank you!

#### Live Demo

I can't link the website because the Shopify theme is still a work in progress (not public). But, I've noticed the issue on other websites which are using model-viewer (I went in the 'Show and tell' section in the Discussion tab and checked out some websites).

### Version

- model-viewer: v1.9.2

### Browser Affected

- [x] Chrome, version: before 97.0.4692.71
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Interesting; so the issue is specific to Windows and Android, but only on Chrome <97? I  guess  that means it's a Chrome bug that's been fixed, but I'm still curious what's going on. The blurring is  just an indication that GPU performance is bad (we blur to keep the frame rate up). Can you make a simple repro by remixing the Glitch  from our issue template? Does it repro even with a simple 3D model?

**Comment by sepehrg** [comment]
I have the same problem. At first, it is high quality but after 1 second it gets blurred, it does the same even in https://modelviewer.dev/editor/. Any solution?
