### ISSUE TITLE
Change animation speed

### ISSUE THREAD

**Issue by futahei** [google/model-viewer#3125]
### Discussed in https://github.com/google/model-viewer/discussions/2795

<div type='discussions-op-text'>

<sup>Originally posted by **cw789** September 16, 2021</sup>
Hello everybody.

Is there a possibility to change the animation speed during the play?</div>

@elalish suggests using requestAnimationFrame, but there is `timeScale` in Three.js ( `AnimationAction` or `AnimationMixer`) that may allow you to change the animation speed.
Are there any plans to add `currentTimeScale` as property ?

**Comment by elalish** [comment]
It's not a high priority, but if you'd like to take it on, you're welcome to open a PR.

**Comment by futahei** [comment]
Okay, I'll work on it.
