### ISSUE TITLE
URL unfurl of modelviewer.dev/editor could be better

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3151]
### Description

Was just posting links to the modelviewer editor and babylon sandbox and noted that one looks nice and polished and the other could use some adjustments:
![image](https://user-images.githubusercontent.com/2693840/151030240-16559f2c-fd2c-41e3-8d3e-a953e7d3f5f6.png)

Better description / a little emoji / the <model-viewer> "wordmark" would be nice there :)

(good starter PR I guess!)

#### Live Demo
Paste the URL "https://modelviewer.dev/editor" into Discord, Slack, or Twitter, and look at the unfurl
Compare to "https://sandbox.babylonjs.com/"

**Comment by samaneh-kazemi** [comment]
Hi @hybridherbst thanks for reaching out. I added this to our backlog.
