### ISSUE TITLE
setAlphaMode("BLEND") doesn't work anymore to hide materials

### ISSUE THREAD

**Issue by dmkrtz** [google/model-viewer#3167]
Here I am again, with a transparency issue.
So, I have some buttons in my application to show/hide materials. First, I was the one who used a negative number for the alpha which made things go invisible pre 1.9.0. Then, after lots of troubleshooting we came to the conclusion that this was me abusing a bug, and a different approach would be to hide a material by setting the AlphaMode to `BLEND` and then setting the rgbA to 0, to revert just set rgbA to 1 and AlphaMode back to `OPAQUE`. Now I just updated to v1.10.1 and here I am again, with broken show/hide buttons using >v1.9 technique.

Sample code?
If button hide pressed -> 
```
modelViewer.model.materials[i].setAlphaMode("BLEND");
modelViewer.model.materials[i].pbrMetallicRoughness.setBaseColorFactor(color); (color in this case is a color string 0,0,0,0)
```
vice versa and with Opaque for show.

v1.9.2:
![dmkrtz3DViewerNET_T7mxhQMAhB](https://user-images.githubusercontent.com/89161020/151862010-ff77d1f0-9f7a-47d5-8784-d7264e639406.gif)

v1.10.1:
![dmkrtz3DViewerNET_4cSL3S315L](https://user-images.githubusercontent.com/89161020/151862027-423146d8-7724-4f93-88e6-d9c098e8c555.gif)

### Version
- model-viewer: v1.10.1

### Browser Affected
- [X] Chrome/WebView2 based application

**Comment by elalish** [comment]
Ugh, sorry about this. I don't suppose you'd be interested in contributing an example of this to our docs pages? We use those as manual regression tests, which will help keep us from breaking your use case, and I think others would be interested in the technique anyway. 

There were some changes upstream in three.js; I'd guess something there is the issue. I'll look into it.

**Comment by dmkrtz** [comment]
Thanks for the reply, and thanks for looking into it!

Sure, I could make an example with a model from the docs/example page. Just have to know how to contribute there :)

**Comment by elalish** [comment]
Thanks! You can submit a PR adding an html page here: https://github.com/google/model-viewer/tree/master/packages/modelviewer.dev/examples and we can link it from the index.html main page.

**Comment by vaggarath** [comment]
If this can help, i had the same issue and switched my function to MASK to hide parts and it does the tricks almost better than blend : with blend i had some kind of freeze and a little delay that i don't have anymore^^

**Comment by LazZiya** [comment]
I also do it as @vaggarath mantiond using "MASK", it is better for hiding objects. "BLEND" will keep the object visible even with lowest alpha value, so I use it for objects like glass. 

When using "MASK", make sure you are setting alpha value to a value below alpha cut off.

````js
var mat = modelViewer.model.materials[i];
mat.setAlphaCutoff(0.01);
mat.setAlphaMode("MASK");
mat.pbrMetallicRoughness.setBaseColorFactor([0, 0, 0, 0]);
````

**Comment by rexalix** [comment]
the same problem. Blend mode makes normals inverted. I have no idea how to fix it and I strongly need the blend mode working correctly becouse my object have a lot of glass
