### ISSUE TITLE
Feature Request: webxr camera functionallity 

### ISSUE THREAD

**Issue by sprengerst** [google/model-viewer#3172]
### Description

As you want to replace scene-viewer with webxr, it would be great to implement an optional "take a picture" function like it is possible in Quicklook and Scene-Viewer also in WebXR.

Especially in times where the adoption of AR is growing this would include an additional way of sharing ones AR experiences.

- [X ] WebXR
- [ X] SceneViewer
- [X ] QuickLook

Best,
Stefan

**Comment by samaneh-kazemi** [comment]
Hi @sprengerst, thanks for reaching out. This feature is on our list, see #1481. We're blocked by a WebXR API though.

**Comment by sprengerst** [comment]
@samaneh-kazemi this would be a crucial function to get rid of scene-viewer. Any update on this?

**Comment by dungnguyen234** [comment]
now is 2023 , have webXR support screenshot feature yet ?

**Comment by elalish** [comment]
Not yet, sadly. Any interest in making a PR?

**Comment by iiLearner** [comment]
is anyone already working on it? I'd be interested in developing this and opening a PR otherwise

**Comment by elalish** [comment]
@iiLearner A PR would be fantastic! No one is currently working on this.

**Comment by gabrielgaldinomagalhaes** [comment]
👀

**Comment by v-prgmr** [comment]
👀
