### ISSUE TITLE
AR icon is displayed in browsers without current support

### ISSUE THREAD

**Issue by smalls** [google/model-viewer#318]
On iOS, Quick Look is the currently supported AR method. However, Quick Look is only launchable from Safari, and not from other browsers (I tested Chrome and Firefox).

A potential fix would be to not show the icon except on a supported os/browser combination.

I tested this with the sample page - https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html

### Browser Affected

- [X] Chrome - iOS Stable, Dev, & Canary
- [ ] Edge
- [X] Firefox - iOS 14
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [X] iOS - 12.1.2
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by mikkoh** [comment]
Ugh I forgot about this issue. I believe the only way to handle this is to browser sniff and only show the badge for iOS Safari. This is how we handle it for Shopify AR.

Affected browsers is actually beyond that list. For instance Facebook, Instagram, etc all render their own browser chrome and under the hood don't use https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller

In which case you get a false positive for this feature working. Really Apple does need to handle this.

**Comment by elalish** [comment]
I think this was fixed.
