### ISSUE TITLE
Missing lit-element dependency for dev when using types

### ISSUE THREAD

**Issue by merlosy** [google/model-viewer#3188]
### Description

When installing the model-viewer with npm, it doesn't work right away in dev mode for my app as lit-element is missing.

In a vue2 - TypeScript app, I need to import the ModelViewerElement type which cause the error probably:
```ts
import { ModelViewerElement } from '@google/model-viewer/lib/model-viewer';
```

### Workaround

Run `npm i -S lit-element@2.5.1`

### Suggestion 

Set lit-element as a dependency of the model-viewer web-component package? (or at least peerDependency)

### Version

- model-viewer: v1.10.1

### Browser Affected

- [X] Chrome, version: 98.0.4758.81
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by justinfagnani** [comment]
I also came across the missing dependency when loading model-viewer from `lib/` rather than `dist/`. There are reasons why consumers might not want to use the pre-bundled module-viewer.

The simple fix is for lit-html and lit-element to be dependencies, not devDependencies.
