### ISSUE TITLE
Upgrade to Lit 2

### ISSUE THREAD

**Issue by justinfagnani** [google/model-viewer#3196]
### Description

The lit-html and lit-element dependencies are pretty out of date at this point. Upgrading to Lit 2 should be relatively easy for this project.

### Version
- model-viewer: current

**Comment by elalish** [comment]
I remember looking into this several months ago. The blocker I noticed at the time was our use of `spread` in our editor, which I recall didn't have an equivalent in Lit 2? Open to better ways.

**Comment by e111077** [comment]
Just uploaded a PR for review #3405
