### ISSUE TITLE
Add support for TEXCOORD_n and COLOR_n for morph targets.

### ISSUE THREAD

**Issue by AleksandarCebov** [google/model-viewer#3202]
### Description

In [gLTF 2.0.1 Specification](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html) it says that "_Client implementations MAY optionally support morphed TEXCOORD_n and/or COLOR_n attributes_".
I am aware that is optional, but it would be nice for model viewer to support them.

#### Live Demo
https://stream-separated-vanilla.glitch.me/

### Version

- model-viewer: v1.10.1

### Browser Affected

- [ X] Chrome, version: xx.x.xxxx.xx
- [ X] Edge
- [ X] Firefox
- [ X] IE
- [ X] Safari

### OS

- [X ] Android
- [ X] iOS
- [ X] Linux
- [ X] MacOS
- [ X] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Yes, but this requires three.js support. Please file the issue there (I'd bet there already is one).

**Comment by elalish** [comment]
Oh, interesting. I had assumed this was referring to supporting multiple UV channels rather than different kinds of morph targets; that makes sense now.

**Comment by AleksandarCebov** [comment]
Three.js v138 has been released including the support for COLOR_n for morph targets.

**Comment by elalish** [comment]
In that case I believe this is fixed by #3231. Please test master and reopen this if anything is still amiss. You may find `https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js` helping for testing pre-release.
