### ISSUE TITLE
Imported Spotlight is incorrect

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3215]
### Description

When importing a glTF file containing spotlights, those spotlights are incorrectly placed/rotated in model-viewer.
This seems to stem from an underlying threejs issue, where spotlights break when a scene is serialized and then deserialized again. Not sure why model-viewer does a full serialize/deserialize pass though even when just loading in a file (which I think is a bug).

#### Live Demo
- Download [LightRoundtrip.zip](https://github.com/google/model-viewer/files/8115003/LightRoundtrip.zip)
- Drop in modelviewer.dev/editor
- Drop in this black pixel as environment map to see the light better ![blackPixel](https://user-images.githubusercontent.com/2693840/155095501-353c0438-38e3-49a3-887a-61ff09801fc6.png)

**Result**
![image](https://user-images.githubusercontent.com/2693840/155095689-53000d85-250d-40a3-bd19-076572fecc4d.png)

**Three.js Editor (expected result)**
![image](https://user-images.githubusercontent.com/2693840/155095773-f869981e-e3a9-43f4-8152-796db5727d97.png)

**Unity Editor (expected result)**
![image](https://user-images.githubusercontent.com/2693840/155096035-58e9ff3d-383b-40f3-8bcd-189a6065a718.png)

**Three.js Editor (after page refresh which does a serialization/deserialization pass - known issue - matches model-viewer result)**
![image](https://user-images.githubusercontent.com/2693840/155095851-5bc3c172-f3db-4f9e-a86c-14512739625c.png)
This is a known issue in three: https://github.com/mrdoob/three.js/issues/9508 with an old-ish PR related to it: https://github.com/mrdoob/three.js/pull/14658#issuecomment-666051811

I think the problem here is that model-viewer does that serialize/deserialize pass, not sure why that's needed.

### Browser Affected

- [X] Chrome, version: xx.x.xxxx.xx
- [X] Edge
- [X] Firefox
- [X] IE
- [X] Safari

### OS

- [X] Android
- [X] iOS
- [X] Linux
- [X] MacOS
- [X] Windows

**Comment by elalish** [comment]
We don't serialize/deserialize, but we do make a copy of the scene. I guess that also somehow triggers this bug? It sounds like the light targets are not being hooked up properly.

**Comment by hybridherbst** [comment]
I think three in some places implements "copy" with interally literally converting to/from JSON, maybe we're hitting one of those here when doing the copy (is the copy then used for showing the scene instead of the original?)

**Comment by hybridherbst** [comment]
Just ran into this again so I thought I'd bump this issue :) 
[LightRig.zip](https://github.com/google/model-viewer/files/12526584/LightRig.zip)

Expected:
![image](https://github.com/google/model-viewer/assets/2693840/81dc99dc-bbbc-4583-a395-fa348f2dd88d)

Actual:
![image](https://github.com/google/model-viewer/assets/2693840/d7049d73-0bfa-4514-a01c-29f2dfd19677)

**Comment by elalish** [comment]
Yes, fair. I don't suppose you'd like to try a PR to fix it? I think you know more about three's directional lights than I do and as far as I can tell you're the only one using them... 🥲

**Comment by hybridherbst** [comment]
I think there would be two places: one is that three should remove the target properties from lights altogether (see https://github.com/mrdoob/three.js/issues/5079 and https://github.com/mrdoob/three.js/pull/14658), the other would be that model-viewer shouldn't serialize/deserialize the scene (which causes the targets to break).

**Comment by elalish** [comment]
That sounds reasonable. When those three.js issues get fixed, let's come back to this. We have a few workarounds to reassign lost info from the serialization process that we can probably add this to.
