### ISSUE TITLE
Selecting animation by name fails with animations that have identical names

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3224]
### Description

The glTF spec doesn't require animation names to be unique. Especially when combining multiple models into one file, they might share animation clip names (or not have an animation clip name at all). Currently, model-viewer only matches by name – so for these files animations can't be properly be chosen from.

In such cases, `availableAnimations` actually returns the correct array of animation names, they just happen to be all the same (or have duplicate entries, which is correct).

### Workarounds

Currently, this enforces files to have unique animation names. A good amount of other viewers have the same issue with that (but not all, and the spec doesn't require unique names).

A workaround I can imagine being useful here is that in addition to accepting a string as animation name. I started a PR for that.

#### Live Demo
This file has multiple animation clips that target different objects but have the same name (valid for glTF):
[MultipleInstancesSameClip.zip](https://github.com/google/model-viewer/files/8133643/MultipleInstancesSameClip.zip)

Calling `availableAnimations` on it will correctly return ["UpAndDown", "UpAndDown", "UpAndDown", "UpAndDown"], but the respective clips can't be played since it's only matched by name.

For comparison, here's the same file but with the workaround of having unique clip names:
[MultipleInstancesSameClip-uniqueNames.zip](https://github.com/google/model-viewer/files/8133659/MultipleInstancesSameClip-uniqueNames.zip)

### Notes

A number of other glTF viewers also struggle with this; I intend to report bugs for these as well 🕵️‍♀️.

**Comment by elalish** [comment]
Thanks for the report and the PR! Sounds good to me.
