### ISSUE TITLE
Documentation cannot be viewed in legacy browsers / crawlers

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#328]
1) We serve our standard bundles on our doc site
2) We host our doc site on Github Pages

Our site cannot be viewed by crawlers and legacy browsers due to number 1.
We cannot take advantage of UA-detection to perform differential serving due to number 2.

In order for our docs to be properly indexed by crawlers, and (arguably less important) viewable in legacy browsers, we need address the above constraints.

This work has been broken out from #327

**Comment by elalish** [comment]
I believe this is fixed as we serve the legacy version as well on our docs pages.
