### ISSUE TITLE
Feature Request: smooth zoom with mouse/keyboard

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3281]
### Description

Related to #3013

Zoom sensitivity is currently very hard to control on devices without touchscreens, especially for models with bigger ranges of possible useful views, e.g. architectural visualizations, landscape modelling, game levels, stage designs, ...

One workaround (until a better zoom calculation heuristic is found) would be to add something like "Alt + Right Mouse drag" for a smooth zoom, similar to how other viewers do that.

**Comment by hybridherbst** [comment]
Just for my understanding, would I use disable-zoom and then manually register a wheel handler (or a handler for Alt + RMB) that calls the zoom method?

Also that's maybe more a discussion item, but would you mind listing the "design goals" for the current zoom, if any? (e.g. "should only take 2 wheel ticks to zoom in really far") That would help if/when I get to try a PR for a better general zoom heuristic (I really think the current one isn't that great).

**Comment by hybridherbst** [comment]
Yes, right now it's 2-3 clicks to go from "fully zoomed out" to "fully zoomed in" for any scene that's larger than "one product" while the goal would be to be able to see both details and the big picture but also something inbetween :).
Of course one could change wheel sensitivity in the OS but that definitely defeats the purpose of reasonable defaults for a viewer (all other apps and scrolling everywhere else would then feel wrong).

Two examples with low `interpolation-decay` to show the "clicks":

![20220317-183622_chrome](https://user-images.githubusercontent.com/2693840/158861818-2182c767-cc44-419b-93bd-9b8639423d13.gif)

![20220317-183836_chrome](https://user-images.githubusercontent.com/2693840/158862061-0102dd35-23e9-4a98-b478-e6d37f390737.gif)

**Comment by elalish** [comment]
Well, most mouse wheels I've used recently don't have "clicks" at all, and neither does my trackpad (which emits wheel events). So it all feels smooth to me. How many clicks do you get for a "one product" (default camera) case?

**Comment by hybridherbst** [comment]
Any standard Logitech mouse has these "clicks"/"steps" :) I believe mostly only trackpads and Apple's mice have "smooth" control, but I'm not sure. Basically everyone I know who works on a Windows machine has such a mouse. I don't have hard data on that of course.



This one has five "clicks" and feels pretty good:
https://modelviewer.dev/examples/loading/#meshoptSupport

Maybe it's related to the wheel event modes? Seems there's some hardcoded multiplier that I'm not sure about: https://github.com/google/model-viewer/blob/566d4b1f06d65c6e677aa9a264ba71fff16892d2/packages/model-viewer/src/three-components/SmoothControls.ts#L676

But then again, looks like Chrome should always return pixels anyways: https://bugs.chromium.org/p/chromium/issues/detail?id=227454#c23



On your device, does it feel good to double-click and then zoom in to some desired distance here? https://thor-and-the-serpent.glitch.me/

Related: did you ever test that `zoom(1); zoom(1); zoom(1);` has a approximately similar output as `zoom(3);`, or might that be very different?

**Comment by elalish** [comment]
That multiplier is the ratio between touch drag and wheel clicks (since they both control zoom). I think I found the problem though: https://github.com/google/model-viewer/blob/566d4b1f06d65c6e677aa9a264ba71fff16892d2/packages/model-viewer/src/three-components/SmoothControls.ts#L388

The radius change is scaled based on the distance between the min and max, but the fov change is not. I think that means when the ratio between those stops changes, the effective sensitivity changes. I think that's fixable.
