### ISSUE TITLE
Blend Shapes broken on Windows with current three.js

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3303]
### Description

Bug has already been fixed upstream in threejs dev, I think it makes sense to track it here as well until the next threejs version (r139) rolls into model-viewer:
https://github.com/mrdoob/three.js/issues/23764

**EDIT:** fix shipped with r139 so once that's rolled in the bug should be gone 🎉 

### Browser Affected

- [X] Chrome
- [X] Edge
- [X] Firefox

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by hybridherbst** [comment]
@elalish do you have an approximate timeframe for when r139 (or later) might roll into model-viewer?

**Comment by elalish** [comment]
I might as well just do it now. I'm thinking I may need to do a point release tomorrow.
