### ISSUE TITLE
Model is doubled on iOS

### ISSUE THREAD

**Issue by LazZiya** [google/model-viewer#3327]
### Description
After the model is fully loaded in iOS, it is doubling with one static model and one interactive (can be rotated, zoomed, ..etc.). This problem seems related to latest iOS update because it is affecting previous model-viewer versions as well.

#### Live Demo
https://demo.ziyad.info/webar-models/fs90/range-cooker.html

![fs90](https://user-images.githubusercontent.com/22244584/160993024-cf35041a-135d-42d0-897d-292f65712665.jpg)

### Version
- model-viewer: v1.11.0
- model-viewer: v1.10.1

### Browser Affected

- [x] Chrome
- [x] Safari

### OS
- [x] iOS

**Comment by elalish** [comment]
I can repro on iOS, but only with your site. Can you try to make a simpler repro case? I can't tell what's unique about your usage.

**Comment by LazZiya** [comment]
Well I will work on a simpler model to check. However it was working fine in Feb. 2022 prior to the latest iOS updates.

**Comment by chaitanya-deep** [comment]
Happens to me too. But just for this model. The others seem to be working fine.
https://celestar-preview.euclidxr.com/bcc2654b-b1ec-4bd1-b483-ee69a02b9020


![IMG_3B893DD5D262-1](https://user-images.githubusercontent.com/5744488/162672230-93338cd5-e086-49f7-989f-3b4ea16d2a6d.jpeg)

**Comment by LazZiya** [comment]
@chaitanya-deep yes I can regenerate the issue with your model on my iPhone! 

I managed to re-make my model without duplication in below steps:
- reduce vertices, faces, edges as much as possible
- remove all unnecessary details that will not affect the experience quality
- remove all materials, keep the model with one material for all parts
- re add materials one-by-one while checking the model at each step
- if at any step the material causing a problem, try to change the material or use similar existing one
- reduce materials count is possible

I know this is a hard way solution, but this was the only way to solve it. 

The point is that the same model was running fine without problems in February, but now even with previous model-viewer version it is producing the same issue.

**Comment by elalish** [comment]
@LazZiya please file a bug on WebKit: https://bugs.webkit.org/ They've had a number of webgl regressions lately.

**Comment by chaitanya-deep** [comment]
I guess this issue can be closed. It seems to be out of the scope of model-viewer. And as stated in the above link, it was already fixed and I was able to verify that it's working as intended in Safari technology preview.

https://user-images.githubusercontent.com/5744488/163317622-744242d7-040d-430c-8be9-85ad597036d7.mov

**Comment by LazZiya** [comment]
@chaitanya-deep any idea when the new Safari version will be released?

**Comment by chaitanya-deep** [comment]
The past 4 revisions were in beta for under 50 days (http://www.thinkybits.com/blog/iOS-versions/).
So I'm guessing tentatively by the end of May

**Comment by elalish** [comment]
Thanks for following up @chaitanya-deep!

**Comment by LazZiya** [comment]
just installed iOS 15.5 and the bug is fixed :)
