### ISSUE TITLE
Regression: oncontextmenu can't be disabled anymore

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3331]
### Description

Not sure what has changed (enable-pan?), but right now context menu click can't be disabled anymore on the model-viewer element, which was working fine before.

**Edit:** seems `enable-pan` fixes that (disables the context menu), but then custom logic is "additive" to the built-in pan behavior.

#### Live Demo
https://glitch.com/edit/#!/toothsome-abyssinian-degree
Note `oncontextmenu="return false;"` in <model-viewer> to prevent a right-click menu from showing up.
You can switch to the 1.10.2 version at the bottom where this worked.

### Version
- model-viewer: v1.11.0

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
Oh, sure, I didn't think about that when I disabled it for `enable-pan`. Here's the problem: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/features/controls.ts#L492

I'm not quite sure what the right way to solve this is... Any thoughts?

**Comment by hybridherbst** [comment]
Guess one way would be (pseudo-code, not sure about the syntax for these things in JS)
```
if (this.enablePan) {
  const originalContextMenu = this.contextMenu;
  this.oncontextmenu = function() {
    if(originalContextMenu) originalContextMenu();
    return false;
  };
}
```

This way
- when pan is off nothing is changed
- when pan is on and there's an event it's still called but the original effects are preserved

**Comment by elalish** [comment]
Thanks, but I've got a better way. Also, I believe if you use the `addEventListener` way instead, that will also work even before this is fixed.
