### ISSUE TITLE
PMREM issue on Pixel phones

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#3336]
If you go here: https://modelviewer.dev/examples/scenegraph/#changeMaterial and set the roughness to ~0.2 on a Pixel phone (tested on 3, 4a, and 6), you get some seams in the environment light (I need to add a screenshot). I'm assuming it's a three.js bug in the PMREM generator, but since I contributed that code, I'm going to try to fix it too.

**Comment by elalish** [comment]
Okay, this issue is super weird. I think I'm getting close to if not a fix, at least a workaround for most of it. I've found multiple things that feel like Pixel driver bugs, but they're weirdly subtle and I have no idea what the root cause is. For instance, when I simplified the PMREM generator to introduce no blur, I get a strange line forming in all the lowest levels that does not appear in my mac: 
<img width="430" alt="image" src="https://user-images.githubusercontent.com/1649964/161637446-ba841859-9f41-4ed6-b1f8-0f8ef924efe8.png">

**Comment by mrdoob** [comment]
> I get a strange line forming in all the lowest levels that does not appear in my mac

Hmm, where is the line in the screenshot?

**Comment by elalish** [comment]
It's a little subtle: If you look at the top rows I'm doing no bluring, so they should be identical to each other as you scan from left to right (and that's how they look on my mac). Instead you see the smooth squares getting a horizontal line across the middle of each, and the top half seems to loose any vertical gradient. It's very strange. It gets more obvious when it's stretched across a large model.

**Comment by mrdoob** [comment]
Ah right, I see that now...

**Comment by elalish** [comment]
Fixed by https://github.com/mrdoob/three.js/pull/23841, which will be pulled in with r140.
