### ISSUE TITLE
model does not display correctly on iOS

### ISSUE THREAD

**Issue by saken14** [google/model-viewer#3342]
### Description

I am testing AR mode. I have .GLB and .USDZ model. With .GLB model in AR mode everything is OK. There is a problem with .USDZ model, when I try to test my .USDZ model on iOS the model is not displayed correctly (twisted in some places). (code: ar-modes="webxr scene-viewer quick-look") you can check it out by link below. Test on iOS AR mode.

#### Live Demo

https://layout.slonworks.ru/modelviewertest/

### Version

- model-viewer: v1.11.0

### Browser Affected

- [x] Chrome, version: 99.0.4844.84
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [x] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
Some screenshots would help a lot. You've selected Chrome and Android and WebXR, but describe only iOS. Might you adjust to the actual browser/platform where your problem occurs? From your description I'm guessing it's Safari and Quick Look. If it's iOS Chrome, there are some known issues. If it's Safari, then you should file the bug on WebKit, mentioning the Quick Look bug.

**Comment by saken14** [comment]
![photo1649238246](https://user-images.githubusercontent.com/67655468/161947303-66a0fbfc-49e6-4943-a66d-b38d4679f671.jpeg)
![photo1649238246 (1)](https://user-images.githubusercontent.com/67655468/161947308-a1a53c7d-ae40-41b1-affd-8478e0e313b5.jpeg)
![photo1649238246 (2)](https://user-images.githubusercontent.com/67655468/161947312-75914764-14e7-471e-a0d1-2c986c7954d7.jpeg)

As you noticed, left leg is wrong displayed. I tested on Safari. With android OS everything is ok))

**Comment by elalish** [comment]
It looks like your only problem in Quick Look (the built-in AR app on iOS), which is the only thing that uses your `ios-src` USDZ. So I would guess your USDZ converter has an error. Have you tried our USDZ auto-generation?

**Comment by saken14** [comment]
Ah yes, there was an issue with USDZ model initially. I fixed it, then it is OK, diplayed well. You can test yourself https://layout.slonworks.ru/modelviewertest/  Thank You @elalish !!
