### ISSUE TITLE
Twitter preview card AR button in Android Chrome: "This content is blocked"

### ISSUE THREAD

**Issue by wmurphyrd** [google/model-viewer#3362]
### Description

Using Chrome browser on an AR-cabable device, the enter AR button in a Twitter Web preview card leads to an error message "This content is blocked. Contact the site owner to fix the issue." If I click through to the site (leaving twitter), then the AR mode works. 

It looks like Twitter does not have the right permissions on the iframe for this to work - perhaps they removed them at some point.

#### Live Demo

https://twitter.com/modelviewer/status/1468282531329970176

https://user-images.githubusercontent.com/10034859/163040760-e7fdf0b3-805a-4a3e-bd45-ffaba0bcddc5.mp4

### Version

It's a modelviewer.dev link, so presumably current version

### Browser Affected

- [x] Chrome, version: 100.0.4896.79
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by samaneh-kazemi** [comment]
Hi, thanks for reaching out. My colleague just tried this example @diegoteran on android and it worked. So we're not able to repro this. Could it be something in your settings that doesn't allow twitter to open other apps?

**Comment by samaneh-kazemi** [comment]
@wmurphyrd ah my bad. Yeah it seems broken if we open the twitter link using Chrome instead of the app. Since this is only happening for Twitter on Chrome side, it could be either a twitter or chrome bug. Do you mind filing a bug for them? @elalish can provide more inputs next week.

**Comment by elalish** [comment]
Yeah, I actually filed this issue on Twitter, since it would be an easy fix on their side, but no word.

**Comment by wmurphyrd** [comment]
@elalish could model-viewer not handle the missing permission a little more gracefully? Twitter isn't the only site that implements these player cards (e.g. https://github.com/mastodon/mastodon also shows the player card without the webxr permission and also errors in the same way).

**Comment by elalish** [comment]
That's not MV's choice; that's the browser. It's a very easy fix for mastodon, twitter, etc: just add the `xr-spatial-tracking` permission to their iframe: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy/xr-spatial-tracking

Please file bugs on them. I also have to wonder if it isn't a Chrome bug that `xr` appears to be an available API in an iframe where it's not allowed: @klausw?

**Comment by wmurphyrd** [comment]
Oh this is interesting, the browser is correctly reporting that WebXR is unavailable
![image](https://user-images.githubusercontent.com/10034859/163864018-9775f30f-7c52-4635-8a69-486ee4d9b13a.png)

The actual error is a CSP error that occurs when trying to open Scene Viewer
![image](https://user-images.githubusercontent.com/10034859/163864654-953d66a1-ea1b-459a-9eef-cb56d51a6c04.png)

**Comment by elalish** [comment]
@eugenecys Do you know what rules there are around launching a SV intent from inside an iframe?
