### ISSUE TITLE
Feature Request: Get and Set texture transform info

### ISSUE THREAD

**Issue by fbenedetti06** [google/model-viewer#3368]
Following your kindly upgrade #3263

I am more than interested to be able to change location, scale, rotation of a texture by program!

Without this ability I will be forced to create several 3D model (each one with different texture parameters) and load one  depending of texture required... For sure It's not a satisfying way to do it.!

**Comment by elalish** [comment]
Would you like to submit a PR? Shouldn't be too hard. It's not a high priority at the moment.

**Comment by fbenedetti06** [comment]
>

**Comment by MrSounds** [comment]
@elalish Would it be realistic seeing this feature any time soon?:) I believe scaling textures on a model would be very useful, in for example having a "logo-area" where you could scale the texture (logo) up and down. Probably lots of other use-cases as well.

**Comment by elalish** [comment]
I'm taking vacation on and off through the holidays, so I don't have time to dedicate to this, but a PR is always welcome! I do think it would be a useful feature. However, what about your use case requires a JS API for this? You can always author your glTF this way, and even author variants with different texture settings you can switch between.

**Comment by portedison** [comment]
This would be useful - we need to edit Texture.repeat when switching Textures.

Possibly a callback after creating a texture?
https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/features/scene-graph.ts#L131

Are there any hacks in the mean time? Or can I access texture from the return? I see it wrapS / wrapT are in 'sampler'. Not sure how to utilise that.

**Comment by elalish** [comment]
I believe you can already change the repeat values using e.g. `mv.model.materials[0].pbrMetallicRoughness.baseColorTexture.texture.sampler.setWrapS(RepeatWrap);` That might only work if you're using our TS, so you might have to manually replace `RepeatWrap` with `10497` a la the glTF spec.

**Comment by portedison** [comment]
Thanks @elalish I'll have a tinker, I understood it to be three parts, wrapS wrapT and the repeat. Same  as they have here.
https://threejs.org/docs/index.html#api/en/textures/Texture.wrapS

It looks like you only allow the first two? 
https://github.com/google/model-viewer/blob/a4639b5de24cca1ba32938a8a3a9186c5527cb0f/packages/model-viewer/src/features/scene-graph/sampler.ts#L143

**Comment by elalish** [comment]
Three.js is very closely aligned here with both the WebGL spec and the glTF spec, as they're all designed to be compatible. I believe they even use all the same numerical enum values. We handle all three values: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts#L104

**Comment by MrSounds** [comment]
I have successfully scaled textures through programmatic access to texture samplers, but I am facing challenges when trying to rotate the texture around its own center point.

When I attempt to rotate the texture, it seems to rotate, but not around its own center. It appears as if the rotation is happening around the upper-left corner of the texture coordinate system instead.

Is there a way to set the rotation point to the center of the texture so that it rotates around its own center point?

Any suggestions or guidelines would be highly appreciated.

Thank you in advance!

**Comment by elalish** [comment]
That's correct, as that corner is the origin of the texture according to OpenGL. You'll need to do the matrix math to calculate the correct translation that's equivalent to rotating about a different center.
