### ISSUE TITLE
Enable Three.js to be lazy loaded

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#337]
_As a 3D content publisher,
when I deploy <model-viewer> on the web,
I want to defer loading Three.js until it is needed,
so that my users do not incur unnecessary latency_

It would be nice if we could lazy load Three.js until it is actually used by a `<model-viewer>` element. In a typical case, it might be lazy loaded almost immediately. However, if there is a `poster` configured, or if the element itself isn't visible right away, there might be an opportunity to heavily defer loading the bulk of the `<model-viewer>` JS payload.

It might be easiest to accomplish this with dynamic `import`, and defer any deployment details to the author's build pipeline. This will allow us to keep our distributed bundles simple, which enabling lazy loading for advanced production scenarios.

**Comment by elalish** [comment]
Easier to lazy load model-viewer instead, see Performance example.
