### ISSUE TITLE
[SceneViewer] AR not working after update.

### ISSUE THREAD

**Issue by GabrielNogueiraBR** [google/model-viewer#3372]
### Description
Hi,
After the last Google App update from April 12, 2022 (13.14.9.23.arm64), SceneViewer's augmented reality functionality stopped working. 

### Live Demo
- **Augmented reality in Search:** 

https://user-images.githubusercontent.com/30303558/163820414-dbfa64dd-b368-4045-8aef-b008c9f5853f.mp4

- **Model Viewer examples:**

https://user-images.githubusercontent.com/30303558/163823392-46dd7e65-f509-4a23-8576-1694371995e6.mp4

Link: https://modelviewer.dev/examples/augmentedreality/#sceneViewer

### Browser Affected (Mobile)
- [x] Chrome, version: 100.0.4896.88
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android (10 QKQ1.200114.002)
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Thanks for the quick report! It looks like was just starting to roll out and is now getting rolled back. Let us know if it doesn't resolve soon.

**Comment by albanlandry** [comment]
Is there any solution to it? We are facing the same issues with our AR gallery website. The AR does not work anymore on Android version 9.

**Comment by silverseazhuyin** [comment]
We have this similar issue for Web AR on Android device since yesterday. Is there any solution?

**Comment by karanganesan** [comment]
+1

**Comment by eugenecys** [comment]
Hi, sorry about this - I made a change that breaks AR for any Android devices before Android R in the latest release. I sent out a fix that's going out this week, so you should have the update by Monday

**Comment by pimentoformateUG** [comment]
Hi there, when can we expect this to be fixed for devices before Android  R ?
Man thanks for a reply.

> Hi, sorry about this - I made a change that breaks AR for any Android devices before Android R in the latest release. I sent out a fix that's going out this week, so you should have the update by Monday

**Comment by albanlandry** [comment]
Hi @eugenecys, I made some tries recently. The issue seems to be coming from the scene-viewer ar-mode. I used android 9 on Samsung galaxy s8. Webxr works fine. But whenever I set scene-viewer first in the priority list, the scene-viewer app crashes. That is really unfortunate because the webxr mode does not allow capturing a video of the AR scene or taking a picture, which is needed for our application. Do you have any suggestions?


> Hi, sorry about this - I made a change that breaks AR for any Android devices before Android R in the latest release. I sent out a fix that's going out this week, so you should have the update by Monday

**Comment by saken14** [comment]
yes, the scene-viewer app crashes... what we can do? I have the same problem with @GabrielNogueiraBR . When will it be fixed?

**Comment by eugenecys** [comment]
The fix is out by now - please update to the latest Google App v13.15 or higher. Apologies again for the crash!
