### ISSUE TITLE
iOS Chrome not launching AR anymore  instead moves to binary representation of USDZ

### ISSUE THREAD

**Issue by sprengerst** [google/model-viewer#3393]
### Description

Many of our contacts reported that AR stopped working for them on iOS with Chrome. Even the ModelViewer example page is not working, see the live demo: https://modelviewer.dev/examples/augmentedreality/index.html#ar

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/index.html#ar

https://user-images.githubusercontent.com/6854862/165531221-d212aea1-3003-4e2f-a3dc-00537c0d8be0.mp4

### Version

- model-viewer: vLATEST_STABLE

### Browser Affected

- [X] Chrome, version: 100.0.4896.85
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [X] iOS 15.4.1
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [X] QuickLook

**Comment by milesgreen** [comment]
Sounds like https://github.com/google/model-viewer/issues/3292

**Comment by sprengerst** [comment]
You are right @milesgreen
