### ISSUE TITLE
Add dashes in description of modelIsVisible in docs

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [google/model-viewer#3394]
https://github.com/google/model-viewer/blob/2a31f2fc7981fa880fe5d49737c38bee91b4fa4d/packages/modelviewer.dev/data/docs.json#L109-L110

In the docs, I couldn't tell that this was written as "model is visible." I thought it was misspelled like `modelVisible`. In the description, can we write out "pronounced model-is-visible"?

**Comment by elalish** [comment]
Sure, would you like to make a quick PR?
