### ISSUE TITLE
Some objects missing when model is displayed in model-viewer

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3398]
### Description

I ran into a strange issue: from one of my test models, some parts are missing only when displayed in model-viewer. Babylon, three.js editor, Gestaltor, ... are fine. The model has relatively many materials and textures.

#### Live Demo
- Download [TransparencyTest.zip](https://github.com/google/model-viewer/files/8578250/TransparencyTest.zip)
- Put into https://modelviewer.dev/editor

_Expected:_
![image](https://user-images.githubusercontent.com/2693840/165643890-c95bffb4-366e-485d-8186-2d46a330b3b5.png)

_Actual (right third missing):_
![image](https://user-images.githubusercontent.com/2693840/165643988-e126e5ab-fbba-4383-9d32-66a693f6a7c6.png)

### Version
- model-viewer latest editor

### Browser Affected

- [X] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
"relatively many"? It has 2,111 materials! Oh, I think I found the problem though - set shadow-intensity = 0 and they show up. I added a feature to detect and remove baked shadow planes when our shadows are enabled (and remove them from bounding box calculations). I detect them as axis-aligned planes with unlit, transparent materials. You successfully found my edge case. Perhaps I should check that they are at the edge of the bounding box of what's left too, though that wouldn't solve this model (not that I have a lot of desire to...). What do you think?

**Comment by hybridherbst** [comment]
For desktop-level graphics, that's not too many materials 😅

Interesting that this is related to the shadow plane removal. I thought that only applied to horizontal planes; do you have a test model where it's desirable to remove vertical planes at all?

**Comment by elalish** [comment]
Yeah, we see lots of products (wall-mounted lights, bathtub fixtures, etc) that are wall-mounted and therefore have vertical shadow-planes. 

Even on desktop, you'll get much better rendering performance if you combine the materials into a smaller number of draw calls.

**Comment by hybridherbst** [comment]
I see - still, aren't the shadow planes removed because of the ground shadow that model-viewer adds? How does removing the vertical shadow help? Or are they otherwise just floating in mid-air somewhere?
(side note, does that mean they're turned back on in AR where they actually contribute their intended effect?)

**Comment by elalish** [comment]
We support changing the position of our shadow via [`ar-placement`](https://modelviewer.dev/docs/#entrydocs-augmentedreality-attributes-arPlacement), which perhaps isn't the most intuitive, since it also affects non-AR shadows.

**Comment by hybridherbst** [comment]
I see. I'd still say it would be less confusing if only the planes in that direction are removed (basically, the shadow planes that might be replaced by a model-viewer shadow). I'd probably have to see some example cases to fully grasp the problem; usually hand-made or raytraced shadow planes are prettier than auto-generated realtime shadows, so I don't think I understand why removing them is desired at all...

**Comment by elalish** [comment]
The issue is just that generally you won't want both: if you want a consistent look using our shadow system, you don't want the ray-traced ones disturbing that. The bigger issue is regarding camera framing, since baked shadows are generally much wider than the model and cause the framing to be terrible.
