### ISSUE TITLE
Allow users to bring their own lights

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#34]
While some content publishers want full control over the scene, there are specifically perf costs for things like shadows and lights. Do we want something like `allow-model-lights` to import dynamic lights that are found in a glTF model? Would this enable shadows as well? Should this be disabled, even if set, on mobile?

**Comment by jsantell** [comment]
@donmccurdy is there envmap support in gltf now?

**Comment by donmccurdy** [comment]
No, only as a vendor extension: https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_lights_image_based. I think we would want to discuss further before implementing it at this stage.

**Comment by elalish** [comment]
Done ages ago
