### ISSUE TITLE
Android Artefact when AR webxr with piping server

### ISSUE THREAD

**Issue by GianiNavette** [google/model-viewer#3408]
### Description
I'm building a 3D configurator for one of my clients, 
I've created a three js project, that creates a glb model with some variable : 
The models are created through a process that takes SVG as an input and makes the model.
Then I use a CSG to create a model that gets cut at a certains width.
Then I export the gltf using {gltf exporter} from threejs and I take the blob of it and push the model on a piping server, 
finally I put the right link in the model viewer so i can watch it in AR.
At first it loads and you can watch it for a 30 secondes or so, then it lags out and shows you the browser with some artefacts.

#### Live Demo

can't provide it since it's for a client
but here is some images
![Screenshot_20220502-151700_Chrome](https://user-images.githubusercontent.com/71259828/166243384-e5ae2cc8-2ab9-4c4f-9f07-f045dceb53b5.jpg)
 and here is one of the models that can be created
https://nextcloud.logia.app/index.php/s/r2Dt34M2ZQz3SR6
(it's hosted on my website, since I can't put glb files in github issues)

### Version
<script type="module" src="https://unpkg.com/@google/model-viewer@1.11.1/dist/model-viewer.min.js"></script>

### Browser Affected

- [X] Chrome, version: xx.x.xxxx.xx

### OS

- [X ] Android

### AR
- [X] WebXR

Quick look doesn't seem to have a problem, I think its maybe too CPU/GPU intensive for android

## Solution
I think there is an issue when you put three js in the background, but i will wait for your advice

**Comment by elalish** [comment]
Hard to say without a repro link; I'd guess the GPU might be getting corrupted? Maybe out of GPU memory? Definitely worth checking for memory leaks and such.

**Comment by GianiNavette** [comment]
> Hard to say without a repro link; I'd guess the GPU might be getting corrupted? Maybe out of GPU memory? Definitely worth checking for memory leaks and such.

https://logia.app/prod/racken/objectExport/index.html
There you go it's still a rough prototype so you have to click on the button "subtract" and wait a bit !

**Comment by elalish** [comment]
I think this is more likely a Chrome bug.
