### ISSUE TITLE
Build or adapt tool for generating PMREM ahead of time

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#341]
As of #338 we will have the ability to apply PMREM at runtime. However, this has been demonstrated to incur a significant runtime performance penalty (see discussion in #338 for context).

It would be nice to be able to support generating these maps offline, ahead of time, to spare folks with tight performance budgets the cost of generating them at run time.

We can accomplish this either by building a tool, or attempting to adapt and leverage an existing tool like [cmgen](https://github.com/google/filament/tree/master/tools/cmgen).

**Comment by elalish** [comment]
We increased the performance of PMREM generation instead, so this is no longer necessary.
