### ISSUE TITLE
Models go black after selecting them again

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3414]
### Description

Seems to be a regression.
When going to [modelviewer.dev/examples](https://modelviewer.dev/examples/augmentedreality/index.html) and switching between models, when re-selecting a model that turns black. There's an error (probably unrelated) and a number of warnings related to textures in the console:
![image](https://user-images.githubusercontent.com/2693840/166424477-edbe8b02-8fc6-4140-9e51-1d9950e7c639.png)

Might be a caching-related problem, and the textures are discarded but shouldn't?
https://user-images.githubusercontent.com/2693840/166425578-ad204a07-20b3-4525-9f62-ae051b3f464f.mp4

#### Live Demo
https://modelviewer.dev/examples/augmentedreality/index.html
- Select Model 2
- Select Model 1 again -> black
- Select Model 3
- Select Model 2 again -> black
- Select Model 1 again -> black

### Version
- model-viewer: latest

### Browser Affected

- [X] Chrome
- [X] Edge
- [X] Firefox
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
oh, good call, I can repro. I bet I know what regressed that. Thanks! Some people think I'm crazy for serving our dev pages off the master branch, but this is exactly why I do!

**Comment by hybridherbst** [comment]
I think it's a great choice and certainly helps to expose the latest work to more testing :)
