### ISSUE TITLE
[Editor] Clicking "Edit Snippet" and then "Save" removes enable-pan

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3429]
### Description

My guess there's some attribute sanitization going on and enable-pan is still missing? Clicking "Edit Snippet" on modelviewer.dev/editor and then saving (without any changes) removes enable-pan.

#### Live Demo
modelviewer,dev/editor

**Comment by elalish** [comment]
oh yeah, I noticed this too; thanks for filing the issue.

**Comment by elalish** [comment]
I think this is outdated now that enable-pan is not an attribute anymore. If you notice this on any other attributes, please reopen.
