### ISSUE TITLE
auto generated USDZ transparency 

### ISSUE THREAD

**Issue by GianiNavette** [google/model-viewer#3436]
### Description

Hello I'm having trouble making an object fully transparent in AR.

My goal is to completely hide the object, so I don't want to see it a little bit transparent

#### Live Demo
Here is a link if you want to try
https://logia.app/prod/bocyclo/index.html
I use this to make it transparent
```
 parts[i].setAlphaMode('MASK');
                parts[i].setDoubleSided("false")
                parts[i].setAlphaCutoff(0.75);
                //parts[i].setOpacity(0);
                console.log(parts[i]);
                parts[i].pbrMetallicRoughness.setBaseColorFactor([1,1,1,0]);
```

![IMG_8050B2EF48CF-1](https://user-images.githubusercontent.com/71259828/167420034-f090b9d9-238c-405b-80a2-e158ea8011ea.jpeg)
![IMG_AB3CCD0F9BB4-1](https://user-images.githubusercontent.com/71259828/167420508-c7f23187-197a-48b2-869c-0e2b38101c5a.jpeg)

### Version
Last Version of model viewer

### Browser Affected

-  [X] Safari

### OS

-  [X] Android Tested and works
- [] iOS 15.0 tested not working
-  [] iOS 15.4.1 tested not working

### AR
Web XR has no problem but quick look is weird
- [X] QuickLook

**Comment by elalish** [comment]
I'm not too surprised this isn't working in Quick Look. The problem with their only accepting USDZ is that there's not a clear way to translate all the material properties from glTF or other formats. I'd recommend lobbying Apple to accept the glTF open standard and/or WebXR so we can have consistent rendering code (@grorg).
