### ISSUE TITLE
Cannot export Hotspots from the editor

### ISSUE THREAD

**Issue by Gamigre** [google/model-viewer#3455]
### Description

The hotspot feature doesn't works anymore for me. I have this issue since last week or so. I can place hotspots but the snippet will not update to show their position nor create a new < button> or < div> for them [see picture]. When using the export function, the scene created doesnt features any of the hotspots placed with editor. The index.html file is akin to the snippet and devoid of any hotspot mention. Hotspot placed manually/pasted from another scene works. 

### Version

- last online verion of the editor

### Browser Affected

- [X] Chrome, version: 101.0.4951.54
- [X] Edge
- [X] Firefox last version
- [X] Safari for iPad

### OS

- [X] Windows 10
- [x] Tested on safari for ipad with a default model for the same results
![image](https://user-images.githubusercontent.com/43046028/168174999-1db25762-e7c1-4be2-96b2-59de8bdce320.png)

**Comment by e111077** [comment]
addressed in https://github.com/google/model-viewer/pull/3462
