### ISSUE TITLE
Script error in scene generated from ModelViewer Editor

### ISSUE THREAD

**Issue by abhilashca** [google/model-viewer#3490]
Hello,

I was experimenting with Model Viewer for last few weeks. I generated the scene after selecting Astronaut model from Model Editor - [https://modelviewer.dev/editor/](https://modelviewer.dev/editor/). The generated script is having script error while loading the webpage - 'Uncaught TypeError: Cannot read properties of null (reading 'classList')' in `script.js`.

Below are few screenshots

![image](https://user-images.githubusercontent.com/12084395/170110077-597d85cc-4962-48a5-9d95-79160ca05b2d.png)
![image](https://user-images.githubusercontent.com/12084395/170110116-aa08f503-e5a5-43cf-9c6d-3e353e9dad0d.png)

Do I need to add anything after downloading the scene from Model Editor? Any help will be appreciated.

Thank you.

**Comment by elalish** [comment]
Can you put that into a [Glitch](https://glitch.com/) for us so we can take a look. Ideally it'll "just work", though you might need to tweak paths to match your serving layout.
