### ISSUE TITLE
Object Couldn't be opened - Issue in IOS

### ISSUE THREAD

**Issue by rksambari** [google/model-viewer#3501]
### Description

We are getting "Object couldn't be opened" issue in IOS based on defect number #1496 I ensure to use 1.2.1 version of model viewer in my code as below. (We also tried 1.9.0 but it didn't work).

`
    <model-viewer src="mymodel.glb"
              ios-src="mymodel.usdz"
              alt="My AR Project"
              ar
              auto-rotate
              camera-controls></model-viewer>
`

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

- model-viewer: v1.2.1

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by samaneh-kazemi** [comment]
Hi @rksambari, thanks for reaching out! Can you please share a glitch link with your changes?
Also, this is our latest release:
https://github.com/google/model-viewer/releases
And when you use the following script, it will pick up that release.
```
<script
      type="module"
      src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
  ```
  
You can also try this if you want to work with the github head.

```
<script
      type="module"
      src="https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js"></script>
 ```

**Comment by rksambari** [comment]
Thanks, this is working fine with usdz file in IOS.
