### ISSUE TITLE
Make JS camera changes cancel interaction prompts just like user interactions

### ISSUE THREAD

**Issue by valdrinkoshi** [google/model-viewer#3506]
With https://github.com/google/model-viewer/pull/3320, we have an API to run custom prompts. We'd like to have an API for interrupting/cancelling a currently running prompt, e.g. `modelViewer.cancelInteract()`, which can be used when events outside of the model-viewer are triggered like user scrolls.

**Comment by elalish** [comment]
I think simpler than adding an API for this, is just to fix the behavior. This change will apply to both the default prompt and to custom prompts. *Might* be considered a breaking change, but it's very minor and we're doing v2.0 now anyway.
