### ISSUE TITLE
AR buttons have empty href attributes

### ISSUE THREAD

**Issue by ksawery-brzeski** [google/model-viewer#3545]
### Description

Inside `model-viewer`  component there are anchor tags without `href` attribute. Example:
```
<a id="default-ar-button" part="default-ar-button" class="fab" tabindex="2" aria-label="View in your space">
``` 

This negatively affects SEO

#### Live Demo
A good example is the official website of the project: https://modelviewer.dev/
Example above comes from this website.

If you have troubles finding it you can generate lighthouse report and it is going to be listed in SEO section

### Browser Affected

- [x] Chrome, version: 102.0.5005.115 (Official Build) (x86_64)
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS
- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Good call, lighthouse has probably been updated since the last time we looked at this closely. Up for making a PR?
