### ISSUE TITLE
Augmented Reality does not work on iOS WKWebView

### ISSUE THREAD

**Issue by AmitMY** [google/model-viewer#3548]
### Description

On iOS when building the app natively using capacitor (or cordova), augmented reality does not work, however, the augmented reality button still shows. (note, that `navigator.xr` is not defined)

When clicking the button, nothing happens. The web console says:
> Attempting to present in AR with Quick Look...

While the Xcode console says:
> ⚡️  [log] - Attempting to present in AR with Quick Look...
2022-06-24 23:12:49.615350+0200 App[7504:646725] [Process] 0x10402d618 - [pageProxyID=7, webPageID=8, PID=7506] WebPageProxy::didFailProvisionalLoadForFrame: frameID=3, domain=WebKitErrorDomain, code=102, isMainFrame=1
⚡️  WebView failed provisional navigation
⚡️  Error: Frame load interrupted

(Which afaik means that the way the plugin is trying to access the file is "not secure", even though it is a local file)

Either the button should not show, or perhaps there is an error, and the error should show in the console or something so it can be addressed (perhaps a permissions issue?)

**Note!** this works when I go to the web version of the app (https://sign.mt) but not in a native build.

##### Things I tired:
In `Info.plist` I added a "Quick Look needs to be run in main thread" setting, which then results in the following console log

#### Live Demo
Can't show a live demo, as it requires building the app for iOS.
```bash
git clone https://github.com/sign/translate/
cd translate
npm install --legacy-peer-deps
npm run build
npx cap sync ios
npx cap run ios
```

### Version
- model-viewer: v1.12.0

### Browser Affected
Native iOS build in WKWebView

### OS

- [ ] Android
- [x] iOS

### AR
- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
Yeah, there's no WebXR on iOS yet, but this Quick Look bug with WKWebView is a known issue on Apple's side: https://github.com/google/model-viewer/discussions/3528. I'm going to close this to keep the discussion concentrated there.

**Comment by AmitMY** [comment]
> This issue was addressed by https://github.com/google/model-viewer/pull/3784

however, i still can't see quick look on iOS. Is it disabled in this library?

**Comment by elalish** [comment]
No, it's not disabled, but there are a bunch of reasons it may not work. Feel free to file an issue *if* you are willing to fill out the template completely so that we can understand what your issue is.
