### ISSUE TITLE
Model animation and position not working on IOS 15

### ISSUE THREAD

**Issue by rahulconsagous** [google/model-viewer#3580]
all content working properly on android and iOS version 14. but it is not working iOS 15
![WhatsApp Image 2022-07-11 at 8 02 06 PM](https://user-images.githubusercontent.com/84760088/178686204-7477febe-033e-48ef-9da0-e05aabcb1e72.jpeg)

**Comment by elalish** [comment]
Please post this again when you've filled in the issue template. You haven't provided nearly enough information for us to determine the problem. At minimum, reproduction steps and a comparison of what the difference in behavior is.
