### ISSUE TITLE
Material with transparency on plane geometry not rendered

### ISSUE THREAD

**Issue by th-ink** [google/model-viewer#3665]
### Description
When using a plane geometry with a transparent material, either MeshBasicMaterial or MeshStandardMaterial (transparent parameter of the material set to `true`), model-viewer does not render the object. If the same material is applied to a box geometry, it renders just fine. Also if another object is added to the scene with the transparent plane geometry, then everything is rendered corectly.

#### Live Demo
https://quixotic-amber-rotate.glitch.me/

GLTF model: https://data-store.xyz/transparent_m.gltf
### Version
- model-viewer: v1.12.0

### Browser Affected

- [x] Chrome, version: 103.0.5060.134
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
It seems to be working fine on our [editor](https://modelviewer.dev/editor/) (which is serving the latest master, rather than the last release). Perhaps this has been recently fixed?

**Comment by th-ink** [comment]
I've checked the editor and it does work as expected. For my project, I am pulling model-viewer like this: `<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>` By the looks of it, I get version 1.12.0.  So I am not sure which is the latest master version?

**Comment by elalish** [comment]
You can try `<script type="module" src="https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js"></script>` to test master, just don't use it in production.

**Comment by th-ink** [comment]
Thank you, I can confirm that this version is working as expected. Do you have an estimate on when this would be made available to use in production?

**Comment by elalish** [comment]
This month, ideally. You can also pin your version earlier for now in case this bug was recently introduced, e.g. `https://unpkg.com/@google/model-viewer@1.11.1/dist/model-viewer.min.js`
