### ISSUE TITLE
Switch default environment-image to neutral, renaming the current default as legacy.

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#3675]
Switch default [environment-image](https://modelviewer.dev/docs/index.html#entrydocs-lightingandenv-attributes-environmentImage) to neutral, renaming the current default as legacy.

See #3460

**Comment by DenisAzarkin** [comment]
Thanks for it! Can you fix it in the AR mode too?

**Comment by elalish** [comment]
Are you referring to #3415? That's been fixed as well.

**Comment by DenisAzarkin** [comment]
We make some tests with AR mode. Now we have another issue #3715. Hope you fix this one.
