### ISSUE TITLE
Load Local File

### ISSUE THREAD

**Issue by AdriFernan12** [google/model-viewer#3681]
### Discussed in https://github.com/google/model-viewer/discussions/3680

<div type='discussions-op-text'>

<sup>Originally posted by **AdriFernan12** August  5, 2022</sup>
Hi! I'm using Android Studio and i'm trying to render a 3d object on the modelviewer, when i put a web url it works fine, but what i want to do is a offline app and it doesn't work. I imported the 3d object to my assets folder but when it loads it shows an error:
Fetch API cannot load file:///android_asset/planetLowPoly.glb. URL scheme "file" is not supported.
Is there any way to load a local file? Thanks in advance</div>

**Comment by elalish** [comment]
Please don't cross-post.
