### ISSUE TITLE
THE DOCS ARE GONE ☹️

### ISSUE THREAD

**Issue by demarijm** [google/model-viewer#3694]
### Description

For some reason when visiting the page, https://modelviewer.dev/docs/index.html , (on Chrome and Safari). I'm met with an empty screen. I have attached some screenshots below of the screen and of the console.
 
<img width="447" alt="Screen Shot 2022-08-08 at 21 36 55" src="https://user-images.githubusercontent.com/28942035/183543919-a2d36125-1307-4a6d-8ae4-1d4727a4df2b.png">

<img width="1437" alt="Screen Shot 2022-08-08 at 21 32 20" src="https://user-images.githubusercontent.com/28942035/183543715-1b5e0079-88fa-47dc-9968-2a51c8ed5db7.png">

### Browser Affected

- [x ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ x] Safari

### OS

- [ ] Android
- [x ] iOS
- [ ] Linux
- [x ] MacOS
- [ ] Windows

**Comment by alanb-sony** [comment]
stray comma in the json file: https://github.com/google/model-viewer/commit/5d5ee8f4bb740379b7edbe7605786ce3b22a5733#r80703984
