### ISSUE TITLE
Add inputSensitivity property

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#3714]
This JS API will multiply the factor by which user inputs affect the camera, including mouse, touch, and keyboard. It may be useful to set this to a value larger than 1 when calling `interact`, then back down to 1 after in order to exaggerate the motion of the touch points.

**Comment by elalish** [comment]
@clochardM33 You'll be able to set this via modifier keys to get small-step motion. As a JS API instead of an attribute it'll also be synchronous, which should make it a bit easier to use.

**Comment by clochardM33** [comment]
> @clochardM33 You'll be able to set this via modifier keys to get small-step motion. As a JS API instead of an attribute it'll also be synchronous, which should make it a bit easier to use.

Will go and look at this. Expect questions!
