### ISSUE TITLE
'error' event not working as documented

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#3741]
### Discussed in https://github.com/google/model-viewer/discussions/3738

<div type='discussions-op-text'>

<sup>Originally posted by **btutal** August 25, 2022</sup>
Hi, I have seen [error event](https://modelviewer.dev/docs/index.html#loading-events) in the documentation and have been trying to use it but I am not able to get the `event.detail.type` as said there. I have prepared a demo glitch. 

You should see normal behavior if you open [this link ](https://broad-nimble-fan.glitch.me). But if you open [this one](https://broad-nimble-fan.glitch.me?model=NotExistingModel) it will try to place not existing model and will throw an error in the console. Thrown error object doesn't have `event.detail.type` as far as I have seen, it looks like this. 

```
TypeError: Cannot read properties of undefined (reading 'scene')
    at get scene [as scene] (model-viewer.js:53505:36)
    at [clone] (model-viewer.js:53564:34)
    at [clone] (model-viewer.js:53872:29)
    at Rd.clone (model-viewer.js:53524:33)
    at Jc.load (model-viewer.js:50020:34)
    at async n (model-viewer.js:51576:21)
```

Am I doing something wrong? Demo code is also [here](https://glitch.com/edit/#!/broad-nimble-fan)
</div>

**Comment by elalish** [comment]
@btutal You are in fact correct; 'loadfailure' doesn't even appear in our code base, except for that bit of documentation :/

Should be an easy fix; sorry about that.

**Comment by btutal** [comment]
It is at least good to hear that I was using it right:) Thanks for the quick feedback.
