### ISSUE TITLE
exportScene({ trs: true }) is not preserving the scaling info of the Model

### ISSUE THREAD

**Issue by subhankar-trisetra** [google/model-viewer#3765]
Example Code:
```javascript
async function exportGLB(){
    let modelViewer = document.getElementById("static-model");
    modelViewer.scale = '1 3 3';
    const glTF = await modelViewer.exportScene({ trs: true });
    var file = new File([glTF], "export.glb");
    var link = document.createElement("a");
    link.download =file.name;
    link.href = URL.createObjectURL(file);
    link.click();
  }
```
This is the image scene on the canvas: 
![image](https://user-images.githubusercontent.com/98544661/187949280-d7991874-6845-4e42-b733-21f664572251.png)

But this is the glb model when I view it in the viewer:
![image](https://user-images.githubusercontent.com/98544661/187949647-1d0ad763-29f7-4573-8994-404716af25a5.png)

**Comment by elalish** [comment]
Good catch! Does it work with `trs: false`, or does that have the same behavior? Feels like a three.js bug, but not sure.

**Comment by elalish** [comment]
Ah yes, it's universal, and it is our fault. We're exporting the model from below where this transform is applied. I should be able to fix it tomorrow.
