### ISSUE TITLE
Shouldn't render when model has not loaded yet

### ISSUE THREAD

**Issue by mrdoob** [google/model-viewer#378]
### Description

Currently we're rendering every frame even if the model hasn't loaded yet. In cases where we have many models in the page this can influence loading times.

#### Live Demo

https://googlewebcomponents.github.io/model-viewer/examples/multiple-elements.html

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [x] Helios
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### Versions

- model-viewer: v0.0.7

**Comment by cdata** [comment]
This is in the same general sphere of work as #37 and #216

**Comment by elalish** [comment]
I don't think this is true anymore.
