### ISSUE TITLE
overlapping models when changing src attibute

### ISSUE THREAD

**Issue by ivoperalta** [google/model-viewer#3780]
Does anyone know what's happening here?

[https://modelviewer.dev/examples/augmentedreality/](url)

when switching the glb file at least two model stay overlapped...

**Comment by adrianposteuca** [comment]
Following!

**Comment by aleexgtrz** [comment]
While they work it out, change the script src to [](https://cdn.jsdelivr.net/npm/@google/model-viewer@1.12.0/dist/model-viewer-umd.min.js)

**Comment by aleexgtrz** [comment]
While they work it out change the script src to 1.12.0 [https://cdn.jsdelivr.net/npm/@google/model-viewer@1.12.0/dist/model-viewer-umd.min.js](https://cdn.jsdelivr.net/npm/@google/model-viewer@1.12.0/dist/model-viewer-umd.min.js)

**Comment by elalish** [comment]
Ugh, sorry! Apparently npm likes to push prerelease versions to the 'latest' tag that unpkg uses. 🙃 I just published a v1.12.1 that's identical to v1.12.0 to replace the accidental `latest` on v2.0.0-rc1.

Additionally, there's clearly an ugly regression I need to fix before the real v2.0. Thanks!
