### ISSUE TITLE
Glass Material not rendered 

### ISSUE THREAD

**Issue by adrianposteuca** [google/model-viewer#3787]
### Description

Gass material is not displayed/ rendered right.
In the ModelViewer it looks ok with a workaround of setting the "shadow-intensity="0"
but in AR mode it does not render at all.

![Screenshot_20220906-155011_Chrome](https://user-images.githubusercontent.com/17274973/188642797-71a953a0-4880-4770-8052-d8e4976120cc.jpg)
![Screenshot_20220906-155044_Chrome](https://user-images.githubusercontent.com/17274973/188642820-50b534cb-862a-4e44-997f-6c94afa8dad6.jpg)

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version
 src="https://cdn.jsdelivr.net/npm/@google/model-viewer@1.12.0/dist/model-viewer-umd.min.js"

- model-viewer: vX.X.X

### Browser Affected

- [x ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ x] WebXR
- [x ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Yes, this has been fixed, just waiting for release.
