### ISSUE TITLE
allow three access

### ISSUE THREAD

**Issue by makc** [google/model-viewer#3796]
for the case when the page using model-viewer needs three to do some other job, since it is already bundled with model-viewer - it would be a shame to have to download three.js twice.

I see somebody have [thought about it before](https://github.com/google/model-viewer/commit/4f6bae88be94fffb722234713614036962ef819a#diff-fcd9619b063d76c34a55c5211623b5ad7490d00acf5a86cd40ad5c6836cd4111R28) but having official support for this would be nice.

**Comment by elalish** [comment]
Agreed! I just need to find the proper way to expose it and ensure the bundler doesn't tree-shake anything out. For this reason, I think we'll make a separate bundle for this, like `model-viewer-three.min.js`.

**Comment by elalish** [comment]
@makc Have you looked at #3948? The proposal is to distribute an additional mv package without three.js at all - then you would pull that in with an import map along with whatever other code you need it for. Does that look like a workable solution for you?

**Comment by makc** [comment]
@elalish that does sound reasonable, but then would you not have false bug reports in mv if the user imports incompatible three revision?

**Comment by elalish** [comment]
Yeah, but at least we aren't claiming to validate versions like with npm. I prefer no handrail to a handrail you can't trust. We'll just have to put it in the docs and remind people to post their versions in the issue template.

**Comment by elalish** [comment]
This happened as part of [v3.2](https://github.com/google/model-viewer/releases/tag/v3.2.0), try model-viewer-module.min.js, and follow the import map instructions at https://modelviewer.dev/examples/postprocessing/#setup
