### ISSUE TITLE
Default variant is displayed on load before switching to variant-name

### ISSUE THREAD

**Issue by chaitanya-deep** [google/model-viewer#3845]
### Description
For glb files with multiple variants, the default variant is displayed on load before switching to the variant-name.
The poster in this case matches the variant name. This used to occur earlier in v1 if seamless poster is enabled.

#### Live Demo
https://celestar-preview.euclidxr.com/product/8ecfee53-4fe9-4f0b-b398-4b2c9560261a?lang=en&variant=blue

The above viewer is part of a React application. I was also able to replicate it locally and on Codepen without React: https://codepen.io/cdeep/pen/KKRQEME

### Version
Latest (2.0.2)

### Browser and OS
Chrome 105.0.5195.125 on macOS

**Comment by elalish** [comment]
Thank you for the excellent repro!
