### ISSUE TITLE
[Error] Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files

### ISSUE THREAD

**Issue by lanxinger** [google/model-viewer#3854]
### Description

We are using a meshopt compressed glb (ktx2 textures). 

When we tried it in your model editor [https://modelviewer.dev/editor/](https://modelviewer.dev/editor/) it worked, however when trying to load the same file via our demo site it produces the following error:

**[Error] Error: THREE.GLTFLoader: setMeshoptDecoder must be called before loading compressed files
(anonymous function) (model-viewer.min.js:559:5350)
promiseReactionJob**

#### Live Demo
[https://plinth.it/demos](https://plinth.it/demos)

### Version
- model-viewer: v2.0.2

### Browser Affected

- [X] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [X] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [X] Windows

**Comment by cqx931** [comment]
I just came across the same issue with v4.0.0, I wonder what's the way to resolve this.

**Comment by OpenDEM** [comment]
Did you add meshopt support? https://modelviewer.dev/examples/loading/#meshoptSupport
