### ISSUE TITLE
Need screenposition of hotspot but queryHotspot function not defined

### ISSUE THREAD

**Issue by AlbrechtHartmann** [google/model-viewer#3865]
### Description

I am trying to create svg lines that connect parts of my model with a Hotspot text.
I know there is an example based on #3844 on the model viewer website but each time I am trying to get a similiar result I only get the error code:
"queryHotspot is not a function". On the website it says that this function is used to get the screenposition of any Hotspot (thats what I need) but somehow this function doesn't seem to be implemented. 

#### Live Demo
https://modelviewer.dev/examples/annotations/index.html the custom Overlays example.

### Version

- model-viewer: v2.0.2

### Browser Affected

- [X ] Chrome, version: xx.x.xxxx.xx
- [X] Edge
- [ ] Firefox
- [ ] IE
- [] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
Sorry, that function was just added, so it hasn't been released yet on npm. If you'd like to test, you can build locally or grab the latest here: https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js, but don't use it for production as it updates on each merge (you can always copy it and serve it yourself).

**Comment by AlbrechtHartmann** [comment]
Thank you for your help @elalish 😊. I should have checked that first (#3837 < #3844) 🤦‍♂️. Looking forward to the release of that function 👍
