### ISSUE TITLE
What is Alpha Factor?

### ISSUE THREAD

**Issue by pragavame** [google/model-viewer#3885]
What is Alpha Factor ?

![image](https://user-images.githubusercontent.com/99244643/195943275-f5dff7d8-62f8-442e-b62f-415151dcc2e5.png)

How i can change it?

**Comment by elalish** [comment]
Please respond to your earlier issue before you open new ones: https://github.com/google/model-viewer/discussions/3884 

You can look up alpha's definition in the glTF spec.
