### ISSUE TITLE
Models with KTX2 textures upon deployment to mobile and AR not loaded and shown in mobile (received blank screen)

### ISSUE THREAD

**Issue by destintaionrahul** [google/model-viewer#3911]
### Description

**Model Viewer editor - https://modelviewer.dev/editor/** - Model with KTX2 textures(**teektx2.glb**) deployment to mobile and AR not working, same model with JPEG/PNG(**tee.glb**) deployed to mobile and viewed in own space correctly. 

The model with KTX2 textures opens up correctly in model viewer but not deployed to mobile. The mobile deployment doesn't load the model in mobile.
**Model Files:**
[Glb model files -tee & teektx2.zip](https://github.com/google/model-viewer/files/9893169/Glb.model.files.-tee.teektx2.zip)

**Steps to reproduce**

Load the model with KTX2 textures in the model view editor, use deploy to mobile with "default to AR mode to screen viewer" unchecked for WebXR mode and checked for Screen viewer mode; both are not working. 
The model doesn't load in mobile. 

Also, check the model with Jpeg/PNG texture(**tee.glb**) loaded successfully to mobile and viewed in space correctly.

**Expected Behaviour**

The model with KTX2 textures should work exactly as the model with Jpeg/PNG textures and should be deployed and loaded in mobile and viewed in space correctly.

**teektx2.glb -Not being deployed to mobile, model not loaded** 

**_Model in Desktop browser_**
![image](https://user-images.githubusercontent.com/45796366/198817431-2fc02503-0dc0-4f40-98a0-77540f8466c8.png)
Deploy to mobile
![image](https://user-images.githubusercontent.com/45796366/198817491-2d7227b2-db8b-4ca9-b737-9543482bab6f.png)
Mobile doesn't load the model with KTX2 textures.
![image](https://user-images.githubusercontent.com/45796366/198817508-785e9d9c-938c-4886-9fba-13b162bc742e.png)

**tee.glb - Deployed correctly to mobile AR working**

**_Model in Desktop browser_**
![image](https://user-images.githubusercontent.com/45796366/198817622-75b90020-69e7-48bd-add3-0a7103ef1d38.png)

Deploy to mobile
![image](https://user-images.githubusercontent.com/45796366/198817707-89ab9415-13bb-47dc-8d2b-a34136e7b0d1.png)

**_Model loaded in mobile_**
![image](https://user-images.githubusercontent.com/45796366/198817963-c9871f50-2a47-4579-ba7b-dec790698199.png)

**Model in own space**

**_WebXR_**
![image](https://user-images.githubusercontent.com/45796366/198817987-0a4e839e-c1c6-43e9-b061-b6aadd4cc3ce.png)

**_ScreenViewer_**
![image](https://user-images.githubusercontent.com/45796366/198817996-4c7556fd-d18e-4a8e-a2eb-16429d640497.png)

### Version

- model-viewer: v2.0.2

### Browser Affected

- [x] Chrome,Version 106.0.5249.126
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android 11
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Ah yes, I can repro, thanks. So, the problem is the three.js GLTFExporter is failing because of a bug exporting KTX2 textures. The good news is they'll load everywhere, the bad news is it'll take a while to fix our deployment (and I would bet saving the scene from our editor is also broken for these files).

**Comment by jontojek** [comment]
I am seeing this behavior also, when my glb model has jpeg textures it loads and displays AR on iPhone through ModelViewer with no problem.  After using Gestaltor to convert my glb model to have ktx2 textures, it still displays nicely in ModelViewer, but the AR feature does not work, or give errors, or do anything on the mobile phone, just blank.

**Comment by elalish** [comment]
This was fixed some time ago by a three.js update we pulled in - I just verified it's working.
