### ISSUE TITLE
Incorrect handling of zero-filled accessors when morph animations are present

### ISSUE THREAD

**Issue by Aloalo** [google/model-viewer#3946]
### Description

The attached file is valid GLB with morph animations. It is modified version of the MorphStressTest glTF sample asset.

In the original sample asset, the scene contains only one mesh with 2 primitives. The "floor" primitive doesn't morph, which is achieved by accessors for all morph targets being zero explictly.

In the modified asset the same is true, but the targets don't state the NORMAL attribute and the POSITION attribute doesn't have a bufferView which means it should be read as all zeros. Both of these are allowed by the spec:
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#:~:text=Attributes%20present%20in,sets%20of%20attributes.
https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#:~:text=The%20index%20of%20the%20buffer%20view.%20When%20undefined%2C%20the%20accessor%20MUST%20be%20initialized%20with%20zeros

The attached asset has no validation issues and loads and plays animations correctly in Blender and Babylon.js.

[morphTest.zip](https://github.com/google/model-viewer/files/10042845/morphTest.zip)

### Version

- model-viewer: v2.1.0

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
Doesn't work on https://gltf-viewer.donmccurdy.com/ either; looks like a three.js bug. Would you mind filing it upstream?

**Comment by Aloalo** [comment]
Sure, here it is: https://github.com/mrdoob/three.js/issues/24999

**Comment by Mugen87** [comment]
Will be fixed with `r147`, see https://github.com/mrdoob/three.js/issues/24999#issuecomment-1322141987.

**Comment by elalish** [comment]
Fixed by three.js upgrade.
