### ISSUE TITLE
Cannot reuse/recycle <model-viewer> instance if it's performing interact() animation

### ISSUE THREAD

**Issue by valdrinkoshi** [google/model-viewer#3961]
### Description

If `<model-viewer>` is running the custom `interact()` animation and gets disconnected from the DOM, it cannot be reused later (e.g. reconfigure with different source and append to the DOM). By inspecting the Elements panel in the devtools, it looks like it gets stuck on updating the `<canvas>` elements (continuously "blinking"). Note that this issue doesn't happen for the default prompt animations (see demo page).

#### Live Demo

https://glitch.com/edit/#!/uncovered-thread-bead

### Version

- model-viewer: v2.1.0

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Good find, thanks Val!
