### ISSUE TITLE
<model-viewer> doesn't render after being detached then attached

### ISSUE THREAD

**Issue by valdrinkoshi** [google/model-viewer#3967]
### Description

If I detach the `<model-viewer>` from the DOM, and later on attach it again (same parent or different nodes), the `<model-viewer>` doesn't render anymore. It requires to force an update to `src`, and it's not enough to "fake" the update to that property using `requestUpdate` https://lit.dev/docs/components/lifecycle/#requestUpdate  e.g. (see demo page)

```
  // Faking an update to src doesn't work.
  await mv.requestUpdate('src', null);

  // Forcing an update of the actual property works.
  const src = mv.src;
  mv.src = null;
  await mv.updateComplete;
  mv.src = src;
```

#### Live Demo

https://glitch.com/edit/#!/north-cactus-begonia

### Version

- model-viewer: v2.1.1

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Yes, that's by design. When the element is detached from the DOM, the `src` is automatically set to `null`, which allows the model to be garbage collected if the cache is exceeded. I think `mv.src = url` should be adequate to reset.

**Comment by elalish** [comment]
Oh, I bet I know why; there's a 1000ms delay between removing it from the DOM and setting `src = null`. That's from way before my time; seems a bit long. Anyway, I wouldn't mind improving this, but it's not blocking anything, right?

**Comment by valdrinkoshi** [comment]
Correct this is not blocking, as we can reset src to null when disconnecting the element
