### ISSUE TITLE
Consider changing controls to be on by default

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#397]
During discussion, @yuinchien pointed out that the number of practical use cases where it is desirable for controls to be disabled is quite small. Let's document the potential consequences of enabling controls by default and consider changing this default so that controls are opt-out instead of opt-in!

**Comment by elalish** [comment]
@cdata I'd vote for putting this in before 1.0, what do you think?

**Comment by cdata** [comment]
TBH I don't know. We don't have a lot of data on the preferred use case, and the platform precedent for this feature (it was originally named after `<video controls>` attribute) is also opt-in (not opt-out) despite being an obviously useful thing to have turned on by default.

**Comment by yuinchien** [comment]
Might be worth looking at video embed. For Youtube and vimeo, the control is on without having an attribute. So far I can't recall seeing usage of model-viewer that's designed to not have control.

**Comment by cdata** [comment]
Your suggested examples actually prove out what I'm saying. `<video>` has built-in controls, and requires the `controls` attribute in order to activate those built-in controls. However, YouTube and Vimeo do not use the `controls` attribute. Here is the HTML where YouTube uses the `<video>` tag (formatted for readability):

```html
<video tabindex="-1"
  class="video-stream html5-main-video"
  controlslist="nodownload"
  style="width: 447px; height: 251px; left: 0px; top: 0px;" 
  src="blob:https://www.youtube.com/a11c89a2-6086-498d-990c-7c6eeaf2a5e6">
</video>
```

And here is the same one for Vimeo:

```html
<video preload
  loop
  style=""
  src="blob:https://vimeo.com/4940d27c-fa51-4715-8537-949cf2f45eb2">
</video>
```

The `<video>` tag deliberately asks that a content author _opts-in_ to interactive user controls. And both of these embeds implement heavily customized controls on top of the `<video>` tag rather than use the built-in controls.

**Comment by elalish** [comment]
I think the ship has sailed on this. I'm fine with the current behavior, and our users haven't complained.
