### ISSUE TITLE
GLB ar scale is diferent when opened in ios or android

### ISSUE THREAD

**Issue by Carlos19979** [google/model-viewer#3971]
### Description

GLB ar scale is diferent when opened in ios or android, same file with same scale, apears in android as 42% scale, while in ios does apear at 100%, when i enable ar scale to fixed in android it first apears at 42% then scales to 100%.

#### Live Demo
http://metaplainarhomes.s3-website-eu-west-1.amazonaws.com/dashboard/promotion/viviendas/real

### Version

- model-viewer: "version": "2.0.1",

### Browser Affected

- [ x] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [x ] WebXR
- [x ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
@AdrianAtGoogle What do you think, bug or expected behavior?

**Comment by NipunGoelFAI** [comment]
We are also facing the same issue, the 3D model opens properly in Android, but when it comes to iOS, the same 3D model opens up in the enlarged mode such that the 3D model goes outside the mobile screen and then when we try to reduce the size in mobile using two fingers, then after lot of tries its size come within the mobile screen.

**Comment by NipunGoelFAI** [comment]
https://github.com/google/model-viewer/assets/108470776/297ac145-a71f-4d07-b3e5-d630db1e5958

It happens this way in AR view in iPhone

**Comment by elalish** [comment]
I'm going with expected behavior - I think this is part of SceneViewer's (somewhat arbitrary) logic to shrink huge scenes so they don't confuse the user. WebXR mode doesn't do this, so you can always use that instead.
