### ISSUE TITLE
Scene viewer can't load object due to AR QuickLook parameters when auto generating USDZ blob

### ISSUE THREAD

**Issue by elizaII** [google/model-viewer#3992]
### Description
Scene Viewer will throw an error whenever I've appended AR quicklook parameters to `src` (per the [pull request #3434](https://github.com/google/model-viewer/pull/3434)) since I want to auto generate the USDZ file as well. The AR quicklook parameters work splendid on iOS' quicklook, but causes Scene Viewer to fail. I suspect it's because the `modelUrl` for Scene Viewer never checks if it contains a hash (with the quicklook parameters) ([line 308-336 in ar.ts](https://github.com/google/model-viewer/blob/72c1055acc377cc062f843ed3e75cc0a8f666a22/packages/model-viewer/src/features/ar.ts#L336)), so Scene Viewer can't find the object file. It will look for a file that looks like the following:`locationUrl/file.glb#quicklookParameters`, which doesn't exist.

You can reproduce it by appending a hash with any parameters after the file in `src`.
Removing the hash and subsequent parameters loads the object fine in Scene Viewer.

#### Live Demo
https://fixed-honeysuckle-nickel.glitch.me/

#### On iOS (the auto-generated version with the banner) ✅ 
<img src="https://user-images.githubusercontent.com/14200339/206672923-37ca1ae3-6056-4974-b803-affe22a8d791.png" width="300" />

#### On Android (launching Scene Viewer)
_Translation: Couldn't load object; Looks like there's something wrong with this object._
<img src="https://user-images.githubusercontent.com/14200339/206673040-c8c000ab-7101-4cb3-9db0-7b4cc33b4f5a.png" width="300" />

### Version

- model-viewer: v2.1.1

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [x] SceneViewer
- [ ] QuickLook

**Comment by milesgreen** [comment]
Can confirm I can reproduce. 

Not sure if this is SceneViewer becoming stricter. If I recall, the presence of extra # params used to be ignored by SceneViewer. 

In the mean time, curiously, it appears you can fix this by appending any arbitrary query parameter to your GLB source path. Like so:

locationUrl/file.glb?v=123#quicklookParameters

And that seems to work fine in both SceneViewer and iOS.

**Comment by elalish** [comment]
@milesgreen much obliged!

**Comment by milesgreen** [comment]
@elizaII, try with the latest build which now includes a fix for this. Does that work for you?
