### ISSUE TITLE
Mesh is missing primitive index association

### ISSUE THREAD

**Issue by Th3Gl0w** [google/model-viewer#4029]
### Discussed in https://github.com/google/model-viewer/discussions/4028

<div type='discussions-op-text'>

<sup>Originally posted by **Th3Gl0w** December 30, 2022</sup>
I recently start a project and face this issue : 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/22825877/210092290-8d2b1b37-72ae-4e9a-91ef-ab26bdff8a2f.png">

I replicated the situation here : https://codesandbox.io/s/practical-mountain-d6sitq?file=/src/App.js

Also when i try with the same 3D model in the model-viewer Editor i can change the color material

So if someone have face this problem before or have any idea to help me fix it , it would be great . Thanks  🙏 </div>

**Comment by elalish** [comment]
I found the source of this bug: https://github.com/mrdoob/three.js/issues/25252; It happens because your glTF has multiple scenes, which you aren't using. If you remove those it should work.

**Comment by Th3Gl0w** [comment]
Thanks , it solve the problem 😁
