### ISSUE TITLE
On first load ( incognito window ) div size issue on touch screen- div.userinput.show size too big, until user input- then it snaps to correct size

### ISSUE THREAD

**Issue by danhodgkins** [google/model-viewer#4082]
### Description

After loading a glb, the div.userinput element is much taller than it should be. When user touches screen, the element snaps to correct size

Before interaction:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/18121000/216048748-384e7fd2-cbc8-499f-8543-4528fc267c37.png">

After: 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/18121000/216048869-edf573be-9750-4430-a7fd-497d3456a88e.png">

Subsequent loads always work fine...

Please provide a detailed description of the bug, how to reproduce it, and the
expected behavior.  Always include a code snippet, screenshot, any errors
reported in the console, and the model to help us understand and fix the
problem.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

model-viewer@2.1.1

### Browser Affected

- [x ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by danhodgkins** [comment]
I can reproduce the issue using the exported scene directly from https://modelviewer.dev/editor/ 
Loading first time seems to work sometimes, but is consistent if open a new tab and reload page.

https://collectar.co.uk/mvtest/

**Comment by elalish** [comment]
I can't reproduce the issue with the link you provided. What device/browser? However looking at your console log, I'm seeing several errors in your JS.

**Comment by elalish** [comment]
Perhaps you could share a screen recording so we can see what you see?

**Comment by danhodgkins** [comment]
https://user-images.githubusercontent.com/18121000/216108511-2f40f775-038d-48af-94c1-39b8554b3556.mp4

Thanks for getting back to me. In the video I'm loading the demo at https://collectar.co.uk/mvtest/ which is a straight export from the model viewer editor. I can't account for the errors as they came with the export. 

You'll see as the page loads, the model is shifted to the bottom of the page and then as I tap the screen, it shifts to the correct position. I'm testing on a Motorola G50 but my colleague has seen the issue on other Android devices. In the video I try the rul in new tabs as this will recreate the issue, if it doesn't happen in the first tab.

**Comment by danhodgkins** [comment]
Before user interaction: 
<img width="510" alt="image" src="https://user-images.githubusercontent.com/18121000/216110749-a96e47c1-0b93-49c2-bb8f-c2acbcf36ae2.png">

After:
<img width="513" alt="image" src="https://user-images.githubusercontent.com/18121000/216110800-f78c2bec-4edf-4cfd-bee8-7853e0bf9fef.png">
