### ISSUE TITLE
model-viewer@v3 uses `lottie-web` as a dev dependency 

### ISSUE THREAD

**Issue by AmitMY** [google/model-viewer#4090]
### Description

- I installed v3.0.0
- I use model-viewer globally (`import(/* webpackChunkName: "@google/model-viewer" */ '@google/model-viewer');`)

The error I get is:
```
Error: node_modules/@google/model-viewer/lib/features/scene-graph/api.d.ts:1:31 - error TS2307: Cannot find module 'lottie-web' or its corresponding type declarations.

1 import { AnimationItem } from 'lottie-web';
```

### Version
- model-viewer: v3.0.0

### OS

- [x] MacOS

**Comment by elalish** [comment]
Yes, we have lottie-web listed as a dev dependency specifically so you get the required types. How are you installing us? Is there a reason the dev dependencies are not being pulled down?

**Comment by anders8** [comment]
Same error from the same issue. I use model-viewer in an Angular project, so it was previously (2.x.x) installed with just 

npm install @google/model-viewer

So are you saying that lottie-web needs to be added manually in dev dependencies? (I see it listed now in dev at https://www.npmjs.com/package/@google/model-viewer?activeTab=dependencies but I didn't look last night.)

**Comment by elalish** [comment]
Interesting; I don't use Angular so I'll need your help to figure out the right solution here. My understanding of npm dev-dependencies was exactly that when you are developing with the project and you `npm install` it will pull them down for exactly this reason, similar to our @types/three dev dependency. If that's not happening, I'd love to understand why and what the best practice is here to solve it at the library level.

**Comment by muuvmuuv** [comment]
Here is a repl: https://github.com/muuvmuuv/google-model-viewer-4090

1. pnpm install
2. pnpm start

**Comment by elalish** [comment]
@muuvmuuv Thank you - I notice that your pnpm-lock.yaml file has no entry for lottie-web (hence the error) and also that its model-viewer entry has `dev: false`, while others have `dev: true`, which I'm guessing tells it whether or not to include its dev-dependencies. I've never configured pnpm, so might you know of a way to indicate that the dev-dependencies are important?

**Comment by robertsLando** [comment]
I had this issue too but not using pnpm but npm and webpack shows that warning

**Comment by AmitMY** [comment]
v3.0.1:

> Error: node_modules/@google/model-viewer/lib/features/scene-graph/api.d.ts:1:36 - error TS2307: Cannot find module 'lottie-web' or its corresponding type declarations.
> 
> 1 import type { AnimationItem } from 'lottie-web';
