### ISSUE TITLE
Hotspots on several models

### ISSUE THREAD

**Issue by dzhakhangirov** [google/model-viewer#4095]
### Description

I'm trying to show Hotspots on several models. I change the Attribute "data-surface" along with the link to the model "src", but it doesn't work. It was all right with the old Attributes (data-position). Is it possible to solve this problem?

	const hotspots = document.getElementsByClassName("Hotspot");
	const surfaceAstro = ['0 0 3081 3082 3083 0.032 0.900 0.068', '0 0 3972 3973 3974 0.027 0.543 0.430', '0 0 1905 1906 1907 0.216 0.737 0.047'];
	const surfaceShish = ['0 7 321 322 323 0.438 0.229 0.333', '0 0 498 499 500 0.077 0.176 0.747', '0 8 16305 16306 16307 0.530 0.351 0.119'];
    const models = ['shishkebab.glb', 'Astronaut.glb'];
    const toggleModel = document.querySelector('#toggle-model');
    let j = 1;
    setInterval(() => {
		for (let i = 0; i < hotspots.length; i++) {		
		if (toggleModel.src == "./models/shishkebab.glb"){
		      hotspots[i].setAttribute('data-surface', surfaceAstro[i]);}
		else {hotspots[i].setAttribute('data-surface', surfaceShish[i]);}
              }	
	toggleModel.setAttribute('src', `./models/${models[j++ % 2]}`); },	2000);
#### Live Demo
https://arguv.com/ar_viewer/custom/0/bug/Archive/cycling/index4.html

### Version

- model-viewer: v5.0.2

### Browser Affected

- [ ] Chrome, version: 109.0.5414.120

### OS

- [ ] Windows
![kebab](https://user-images.githubusercontent.com/124194927/216610641-1ea613cd-b005-448e-8089-15589a12adc3.png)
![cosmo](https://user-images.githubusercontent.com/124194927/216610671-ca99697c-63f0-4c8d-a4e6-5a74dfb17f13.png)

**Comment by elalish** [comment]
Ugh, yep, I totally forgot to add that line. Should be an easy fix.
