### ISSUE TITLE
Animated textures demo does not work on Firefox

### ISSUE THREAD

**Issue by Frank3K** [google/model-viewer#4096]
### Description

On Firefox the new Animated textures demos do not work. This happens both on Firefox on macOS (version 109.0.1). On Android (Firefox 109.1.1) the same happens. On Chrome 109 on macOS the demos _do_ work.

![image](https://user-images.githubusercontent.com/8014077/216680708-8b819931-fec4-45f2-8ac0-25327fefcc2a.png)

Console messages:

![image](https://user-images.githubusercontent.com/8014077/216680782-c4c2020c-de90-4508-abdb-ba9a52bbb242.png)
#### Live Demo

https://modelviewer.dev/examples/scenegraph/#animatedTexturesExample

### Version

- model-viewer: v3.0.0

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [x] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### AR

- [x] WebXR
- [x] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
Thanks, I can repro. Looks like just an error in the example rather than in MV.

**Comment by elalish** [comment]
There also seems to be an issue on Safari just with Lottie - likely a problem with import maps.

**Comment by elalish** [comment]
Fixed by #4104
