### ISSUE TITLE
connecting animated textures

### ISSUE THREAD

**Issue by dzhakhangirov** [google/model-viewer#4102]
### Description

Hi everybody! Has anyone tried to connect animated textures? https://modelviewer.dev/examples/scenegraph/#animatedTexturesExample
Did it work for you? I can't figure out what I'm doing wrong. Help, please, or send an example of your connection.

#### Live Demo

https://arguv.com/ar_viewer/custom/0/bug/spere/

### OS

- [ ] Windows

**Comment by elalish** [comment]
Try waiting for `customElements.whenDefined('model-viewer')` as per the updated example.

**Comment by dzhakhangirov** [comment]
Thank you for your answers and patience. Updated the code following the example. But it still doesn't work. Something is missing.
https://arguv.com/ar_viewer/custom/0/bug/spherenew/

**Comment by elalish** [comment]
Did you look at your console log? It's full of errors, mostly about a cross-origin video.

**Comment by dzhakhangirov** [comment]
I changed the link from your video to my own. There are only 9 errors in the console, they do not relate to the video. But the result is the same ))
All your examples are run by my code, but for some reason this one is not. Sorry, but okay, I don't want to distract you from business.
![image](https://user-images.githubusercontent.com/124194927/217383756-0edece42-6613-4650-b6af-7fc386746661.png)

**Comment by elalish** [comment]
@dzhakhangirov Thanks, this is interesting. Everything appears to be working fine, but nothing is showing. I'm not sure how it could have changed from my example, but it looks like your sphere's UV coordinates are not going from 0 to 1. All of these three textures/videos have a lot of black/white around their edges, which I think is showing through correctly. Try a movie that has stuff to look at on its entire frame and I think you'll see what's happening.

**Comment by dzhakhangirov** [comment]
I changed the sphere to yours and it worked, thank you very much! 
Apparently something was wrong in my balls)) 
I'll figure out what's wrong with them.
