### ISSUE TITLE
NPM "Critical" Dependency Issue Warning

### ISSUE THREAD

**Issue by johnnyshankman** [google/model-viewer#4213]
### Description

When using the npm module in its current state I get the following compilation warning:

```
Warning  in ./node_modules/@google/model-viewer/lib/three-components/TextureUtils.js

Critical dependency: the request of a dependency is an expression
```

#### Live Demo
Set up a react or vue project. Install three and the model viewer as readme shows. 

Import the model viewer. Then run the compilation and you'll see this warning everytime.

### Version
- model-viewer: v3.0.2

### Browser Affected
N/a

### OS
N/a

### AR
N/a

**Comment by johnnyshankman** [comment]
This is usually due to an incorrectly referenced lazy loaded import in webpack from my knowledge. I'll pull down the repo and take a look today.

**Comment by johnnyshankman** [comment]
I would assume it's this lazy import as the culprit:
https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/three-components/TextureUtils.ts#L75

**Comment by johnnyshankman** [comment]
This has potential to solve the issue: https://stackoverflow.com/a/73359606/3078875

`this.lottieLoaderUrl` is a string but it could require re-ref'ing and explicit retyping in the manor seen above.

**Comment by elalish** [comment]
That sounds reasonable - please send a PR when you get it tested.

**Comment by annahassel** [comment]
> That sounds reasonable - please send a PR when you get it tested.

Is it possible to use this solution https://github.com/google/model-viewer/issues/4091#issuecomment-1445869112?

**Comment by elalish** [comment]
I don't really have a means to test it, which is why I'm relying on someone who can to make the PR. Yes, any solution is valid so long as it passes our tests and doesn't make maintenance harder. 👍

**Comment by johnnyshankman** [comment]
Thank you @annahassel !

**Comment by muuvmuuv** [comment]
Oh, great! Glad this made it, thanks @annahassel. Was about to create a PR as well but decided to wait for a reply by the authors ^^ anyway
