### ISSUE TITLE
User-configurable transform for model when placed in AR

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#426]
We scale and translate a model in order to frame it properly in inline scenarios. However, when the user goes to place the model in WebXR-based AR, the natural scale is used. And, the translation may not look right depending on geometry of the model in question.

This issue proposes that we enable authors to configure the relative scale, translation and rotation of the model for the purposes of presenting in AR.

**Comment by ronpadz** [comment]
> This issue proposes that we enable authors to configure the relative scale...
It feels like the ar-scale attribute should be extended beyond "fixed" and "auto" to include an integer representing the desired percent scaling of the model in AR. A common source of model acquisition is from asset stores and this would streamline their usage in model-viewer without having to first re-scale in modeling software.

**Comment by cdata** [comment]
> It feels like the ar-scale attribute should be extended beyond "fixed" and "auto" to include an integer representing the desired percent scaling of the model in AR.

@ronpadz I definitely agree with this; we might even get crazy and allow a float 😁

The `ar-scale` attribute itself currently exists as an intermediary to support cases where native viewers can be configured to allow or disallow resizing when placing objects in AR. It's possible that this name is a bit confusing.

The floor is open for suggestions for how best to accommodate the multi-dimensionality of this concept.

**Comment by ronpadz** [comment]
> This issue proposes that we enable authors to configure the relative scale, translation and rotation

I'd start by not trying to couple scale with translation and rotation as those properties may deserve their own attributes. 

I see the ar-scale attribute taking three values: "auto", percentage (float), or "fixed" whereby the latter uses the scale built into the model. If a percentage is stated then the model should be fixed at that percentage.
