### ISSUE TITLE
addHotspotOnClick wrong position

### ISSUE THREAD

**Issue by Roxcsas** [google/model-viewer#4281]
### Description
Im trying to make a function to add an hotspot on click and im using "positionAndNormalFromPoint(clientX, clientY)" for the coordinates but it works only if the model-viewer is in full screen.
I tried to put it in a div and add an height and a width to the model-viewer but the position i get is wrong.

### Version
- model-viewer: v3.1.1

### Browser Affected
- [x] Chrome, version: 113.0.5672.64
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by elalish** [comment]
Fixed by #4268, see https://github.com/google/model-viewer/pull/4268#discussion_r1187972870

I happened to just find and fix this last week. Until the next release you can work around by offsetting by the MV element x and y.
