### ISSUE TITLE
positionAndNormalFromPoint return null if css scale apply

### ISSUE THREAD

**Issue by ngocducdim** [google/model-viewer#4294]
### Description

Hi, I have a div that apply `transform: scale(1.1819444444444445);`, this div contain `<model-viewer>`, and when I use `positionAndNormalFromPoint` it return `null`, if I remove `transform: scale(1.1819444444444445);` it return correct position

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Version

- model-viewer: vX.X.X

### Browser Affected

- [ yes] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [yes ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
Pretty sure this was recently fixed by https://github.com/google/model-viewer/pull/4268#discussion_r1187972870

**Comment by ngocducdim** [comment]
I'm not sure if it fixed but haven't publish new version yet, I test on model editor (https://modelviewer.dev/editor/), apply the `transform: scale(1.1819444444444445);`, add the hotspot, the hotspot position not correct
![image](https://github.com/google/model-viewer/assets/97713182/004eadb6-5634-480b-8822-389fff6eeeb4)

**Comment by elalish** [comment]
yeah, that's right. You can test our latest pre-release here: https://modelviewer.dev/docs/faq.html#entrydocs-general-questions-api
