### ISSUE TITLE
`postinstall` script not found

### ISSUE THREAD

**Issue by subhankar-trisetra** [google/model-viewer#4362]
### Description

```bash
➤ YN0009: │ @google/model-viewer@npm:3.2.0 [58ced] couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-dcba39bc/build.log)
➤ YN0007: │ trisetra-decor@workspace:. must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 6s 348ms
➤ YN0000: Failed with errors in 19s 639ms
```
```bash
# This file contains the result of Yarn building a package (@google/model-viewer@virtual:58ced34e477cff2c62a5e26ca6c375fed90e1af1a4fcc875901614bfd6afa62fbc58ffae3a1f03b621a96e23ef501c7dc5c56da1d8c169f9ff70fe73a6e888d7#npm:3.2.0)
# Script name: postinstall

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/home/subhankar/workspace/trisetra-decor/node_modules/scripts/postinstall.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.16.0

```
This error pops up when I try to install `@google/model-viewer` with Yarn 2+. I works perfectly fine with ```"@google/model-viewer": "^3.1.1"```

### Version

- model-viewer: v3.2.0
- yarn: v3.6.1
- node: v18.16.0

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [x] Linux
- [x] MacOS
- [ ] Windows

**Comment by KaiSoellch** [comment]
same here

**Comment by btopro** [comment]
also confirming this happens with yarn 1.22.18. My `yarn install` has a postinstall which it appears that this project including the hook has it run as well. As I don't have that file in my setup it bombs

**Comment by annahassel** [comment]
same

**Comment by jgalindosl** [comment]
I was able to get it to work with the following workaround:

    npm install --ignore-scripts

although, this will ignore scripts for all packages.

**Comment by btopro** [comment]
I'd recommend cutting a release off this as it breaks all tooling to install 3.2.0 currently

**Comment by subho57** [comment]
> I'd recommend cutting a release off this as it breaks all tooling to install 3.2.0 currently
@elalish Can you cut a release as v3.2.1 as a hotfix for this issue?

**Comment by elalish** [comment]
working on it, but we need a better fix: #4368, which isn't quite ready yet. See you on Monday.

**Comment by cipas** [comment]
hey @elalish any news on this ? thanks

**Comment by asilliahmet** [comment]
same here as well, tried node 18.17 and 20.5's npms

**Comment by pReya** [comment]
While this is getting fixed, you can either use

`npm i @google/model-viewer --ignore-scripts` or you can install an older version:
`npm i @google/model-viewer@3.1.1`

**Comment by cocukadams** [comment]
Well, while it's working with `yarn add @google/model-viewer --ignore-scripts` locally, that can't be appropriate approach to push this code to remote repository, because CloudFlare is not going to download dependencies with the following script. That may cause problem.

**Comment by elalish** [comment]
Sorry, this turned into a bit of a perfect storm of difficult timing. My wife just gave birth, so I've been on parental leave. Working on this now, hopefully I'll have a release out this week, finally.

**Comment by muuvmuuv** [comment]
Congrats! No hurry, better leave that computer off and take your time. We wont retire because of that :D

**Comment by asilliahmet** [comment]
> While this is getting fixed, you can either use
> 
> `npm i @google/model-viewer --ignore-scripts` or you can install an older version: `npm i @google/model-viewer@3.1.1`

This did not work for me, however installing a specific three version along with it did. What i did was:
`npm i @google/model-viewer@3.1.1`
`npm i three@0.151.2`
