### ISSUE TITLE
[Feature request] Ground Projected Skybox

### ISSUE THREAD

**Issue by mj321** [google/model-viewer#4372]
I'd like to see support for the "ground projected skybox" from three.js in model-viewer

https://threejs.org/examples/webgl_materials_envmaps_groundprojected.html
https://github.com/mrdoob/three.js/blob/master/examples/webgl_materials_envmaps_groundprojected.html

It would open up new use cases.

**Comment by elalish** [comment]
Agreed, that could be cool. Interested in trying a PR? I'd be happy to review and help with any questions.

**Comment by phreak** [comment]
Thinking further: if that ground projection would also be able to show animated graphics (for example seamless WEBPs), that could open a whole. world to the model viewer.

**Comment by elalish** [comment]
Fixed by #4604
