### ISSUE TITLE
iOS color Change - in AR mode

### ISSUE THREAD

**Issue by Arumugamsix** [google/model-viewer#4398]
I have some issues with iOS.

In iOS - AR mode color change takes time to load

**Comment by elalish** [comment]
Please don't cross-post: #4397. Also, you'll need to give us a lot more detail for us to help you - deleting the issue template rather than filling it out is generally not a great idea.

**Comment by Arumugamsix** [comment]
Hi

Sorry for that

This is my site 
https://audi-india-ar.s3.ap-south-1.amazonaws.com/q8etron/index.html  

when I click on the color change button in Android it is working color change happens immediately 

but in iOS it's not happen. color is changing after double/multiple clicking the button
