### ISSUE TITLE
AR not launching on IOS 17

### ISSUE THREAD

**Issue by petarZinaic** [google/model-viewer#4414]
### Description

AR mode not launching at all on IOS 17. Is there a way or a possibly fix which will allow me to run AR mode on this IOS version?

### Version

- model-viewer: v3.2.1

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [X] QuickLook

**Comment by milesgreen** [comment]
Probably same issue as this: https://github.com/google/model-viewer/issues/4354

Good news is that it looks like a fix is in place and will be in the final iOS 17 public release.
