### ISSUE TITLE
sampler.setOffset doesn't move my texture

### ISSUE THREAD

**Issue by xeiaaa** [google/model-viewer#4428]
### Description
When i try to run sampler.setOffset, the texture doesn't move. setRotation and setScale does work correctly though. is there anything i missed?
![image](https://github.com/google/model-viewer/assets/23055744/fa58aeb1-a0d8-4316-8511-0007c9e97457)

Here's my code for the slider
```
<Slider
          aria-label="slider-ex-1"
          defaultValue={0}
          mt={4}
          onChange={(e) => {
            const offset = {
              x: -e * 20,
              y: -e * 20,
            };
            console.log(sampler.offset);
            sampler.setOffset(offset);
          }}
        >
          <SliderTrack>
            <SliderFilledTrack />
          </SliderTrack>
          <SliderThumb />
        </Slider>
```

**Comment by elalish** [comment]
Hmm, it seems to be working in our [example](https://modelviewer.dev/examples/scenegraph/#transformTexturesExample). Can you find the difference between that and your site, or perhaps show us a minimal repro? Also, what MV version are you using?

**Comment by diegoteran** [comment]
Hi @xeiaaa, is this still an issue for you? Can you share how to repro or any console logs that the behavior outputted?

**Comment by diegoteran** [comment]
There were some recent changes in #4473 , I'll assume this fixes it since can't repro the error.
Feel free to open an issue if it still doesn't work for you.
