### ISSUE TITLE
normalTextures acting oddly with KHR_materials_variants

### ISSUE THREAD

**Issue by echadwick-artist** [google/model-viewer#4443]
### Description
normalTextures are lighting oddly when materials are swapped using KHR_materials_variants.
![2023-09-03 17_14_34-EricChadwick com](https://github.com/google/model-viewer/assets/40177036/de322d00-5c1f-44c7-8100-8c0848fda89d)

This occurs with the attached model, both when embedded with 3.2.0 and when loading the model into the [<model-viewer> Editor](https://modelviewer.dev/editor/).

[StainedGlassLamp.zip](https://github.com/google/model-viewer/files/12507608/StainedGlassLamp.zip)

Error does not occur when loading the model in [BabylonJS Sandbox](https://sandbox.babylonjs.com/):
![2023-09-03 17_17_06-Babylon js - StainedGlassLamp glb](https://github.com/google/model-viewer/assets/40177036/7189c8e5-1f5d-48de-9833-086b0cbe1451)

[Threejs Editor](https://threejs.org/editor/) may have a clue. If the second number next to the normalTexture is changed to +1, the bump is inverted. Perhaps this value is being ignored (or forced to 1) with variants.
![image](https://github.com/google/model-viewer/assets/40177036/3d93284d-80f2-4fb5-ab5d-56f030d8476d)

#### Live Demo
[https://ericchadwick.com/gltf/index.html#StainedGlassLamp](https://ericchadwick.com/gltf/index.html#StainedGlassLamp)
1. Scroll to the StainedGlassLamp example (anchor should take you there).
2. Switch the variant to "Lamp Off" 
3. Notice how the lighting appears to invert on the dark bumpy metal around the stained glass, on the bumpy details in the base, etc.
4. Switch the variant back to "Lamp On", and notice the change in lighting on the bump maps.

### Version
- model-viewer: v3.2.0

### Browser Affected
- [x] Chrome, version: 116.0.5845.141 (Official Build) (64-bit)
- [ ] Edge
- [x] Firefox 117.0 (64-bit)
- [ ] IE
- [x] Safari

### OS
- [ ] Android
- [x] iOS 16.6
- [ ] Linux
- [ ] MacOS
- [x] Windows 11 Home 22H2

### AR
- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by echadwick-artist** [comment]
I have simplified the problem and made another example asset. This only has a single mesh, a baseColorFactor and a normalTexture. 

![bump-variants-simple](https://github.com/google/model-viewer/assets/40177036/9d21535b-f3af-4450-9efd-57ae6b858ead)

glTF file:
[bump-variants-simple.zip](https://github.com/google/model-viewer/files/12528080/bump-variants-simple.zip)

**Comment by elalish** [comment]
Thank you for the simplified example and the clue - I think you're right. I'll look into it.
