### ISSUE TITLE
Status content discoverable by mobile screen reader swipe gestures

### ISSUE THREAD

**Issue by svinkle** [google/model-viewer#445]
### Description

Mobile screen reader users will run into the `status` content when using swipe gestures. This may cause confusion as to the position or purpose of this seemingly duplicate content.

Adding `aria-hidden` to the container will avoid this issue as this cause screen readers to bypass the container altogether:

```ts
// status-announcer.ts:81
statusElement.setAttribute('aria-hidden', 'true');
```

![Screenshot_20190325-111102](https://user-images.githubusercontent.com/1392632/54931988-6d09ff00-4ef0-11e9-9841-3fcc79bb4af9.png)

#### Live Demo
1. Go to [`<model-viewer>`](https://googlewebcomponents.github.io/model-viewer/index.html) with Chrome for Android
2. Load up [TalkBack screen reader](https://support.google.com/accessibility/android/answer/6007100?hl=en)
3. Swipe right with one finger until the `status` content is found

### Browser Affected

- [x] Chrome
- [ ] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.1.1

**Comment by cdata** [comment]
@svinkle this is awesome, thanks for filing!

To clarify, is the issue you are describing that the status element is read two times (once when the text content changes, and once again as you cycle through elements while swiping)?

> Adding aria-hidden to the container will avoid this issue as this cause screen readers to bypass the container altogether

The intention of the status element in our case is two-fold:

 - Its content should be announced by screen readers as the text content changes.
 - Its content represents global status related to `<model-viewer>` (so, there should only be one status element across all `<model-viewer>` elements).

If we added `aria-hidden` to the element, would changes to its text content still be announced correctly?

If so, then I think we can make this change easily.

If not, maybe we should explore a different strategy for announcing global status (perhaps using `aria-live`, like we do with the camera controls).

**Comment by svinkle** [comment]
> the status element is read two times (once when the text content changes, and once again as you cycle through elements while swiping)?

Yes, exactly this.

> If we added `aria-hidden` to the element, would changes to its text content still be announced correctly?

Yes, announcements still occur as expected.

There would be no change other than the visually hidden text node is bypassed while using swipe navigation.

**Comment by cdata** [comment]
SGTM, we will make this change

**Comment by svinkle** [comment]
Apologies, @cdata, we'll need to close #455 – further testing this solution reveals applying `aria-hidden` to a live region **does not** announce updates as expected.

My original test bed featured a click event handler which would temporarily set `aria-hidden` to `false` and then `true` again in order to avoid screen reader users from finding the status element while navigating. Upon inspecting the DOM, I missed this toggle and only saw the `true` value being applied.

My recommendation is to close #455 for now. This is a minor issue compared to others we're facing so leaving as-is will not be a blocker.

---

That said, I've tested a notification or sorts to help with this dilemma of not being able to "hide" the content node in the DOM. Wrapping the `status` element with a parent element note attached works well to provide the user some context on what they're interacting with an why…

```html
<div role="region" aria-label="Live announcements">
  <div class="visuallyhidden" role="status"></div>
</div>
```

When navigated to in the DOM, this would be announced as, _"Live announcements, region"_, which would serve the purpose of providing context.

Just something to consider.

**Comment by elalish** [comment]
I think this was fixed as part of our other a11y work.
