### ISSUE TITLE
<model-viewer> shows neither content, nor styling on mobile Safari specifically on iPadOS 17.0

### ISSUE THREAD

**Issue by PixelPartner** [google/model-viewer#4468]
### Description

On iPads running iPadOS 17.0 (21A329) the canvas / shadowDOM of `<model-viewer>` stays empty, but properly sized.

#### Also reported to

Webkit: https://bugs.webkit.org/show_bug.cgi?id=261727
Apple: rdar://115722249
Apple: FB13187835

#### Live Demo
https://modelviewer.dev (your own project docs/samples)

### Version

- model-viewer: v3.1.1

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari iPadOS 17.0

### OS

- [ ] Android
- [x] iPadOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by PixelPartner** [comment]
Safari on iPhoneOS 17.0 works as expected.

**Comment by PixelPartner** [comment]
[Twitter user @LightfieldArt confirmed this](https://twitter.com/LightfieldArt/status/1704365471171047802)

**Comment by elalish** [comment]
Thanks for letting us know and for filing the bug on Apple. This doesn't look like something we can fix from our side, though if you happen to find a work-around, a PR is always welcome!

**Comment by PixelPartner** [comment]
Apple fixed that with iPadOS 17.0.1, so please all update soon.

**Comment by elalish** [comment]
Excellent, thank you!
