### ISSUE TITLE
Add iridescence & anisotropy models to the test suite

### ISSUE THREAD

**Issue by bhouston** [google/model-viewer#4486]
### Description

@echadwick-artist has created a series of new models for anisotropy and iridescence testing.  We should add them to the test suite.  He describes them here:

* https://github.com/KhronosGroup/glTF-Sample-Models/issues/392#issuecomment-1741303812
* https://github.com/KhronosGroup/glTF-Sample-Models/issues/393#issuecomment-1741293754

I would like to add all of the models he lists to the model-viewer test suite so that we have proper coverage in these undercovered areas.

#### Live Demo

None.

### Version

None.

### Browser Affected

None.

### OS

None.

### AR

None.

**Comment by bhouston** [comment]
I've created a pull request here: https://github.com/google/model-viewer/pull/4493 for the anisotropy models.

**Comment by elalish** [comment]
I believe you already added all of these, thanks!
