### ISSUE TITLE
Automatically generate Schema.org metadata related to model

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#451]
Schema.org is considering the addition of a 3DModel type (https://github.com/schemaorg/schemaorg/issues/2140).

We should add a user configuration for `<model-viewer>` that causes `<model-viewer>` to generate and maintain a JSON-LD script tag in the `<head>` of the document that corresponds with the given `<model-viewer>`'s configuration.

**Comment by ronpadz** [comment]
Adding this reference to the [pending schema spec](https://schema.org/3DModel):

> 3DModel
> This term is proposed for full integration into Schema.org, pending implementation feedback and adoption from applications and websites.

**Comment by elalish** [comment]
@tpsiaki This has been around for a long time, but I guess it is a possible approach?

**Comment by elalish** [comment]
@ronpadz Indeed, I just forgot to close it. Thanks!
