### ISSUE TITLE
Dark models are displayed in older devices (ar mode)

### ISSUE THREAD

**Issue by Hardin22** [google/model-viewer#4560]
Description
I am experiencing an issue where one of my 3D models renders much darker than expected when viewing the object in AR space on specific Android devices using model-viewer. This issue appears to be device-specific as it displays correctly in non-AR view and on other devices.

Version
model-viewer: latest (v3.3.0)
Browser Affected
✅ Chrome, version: [latest]
OS
✅ Android
🔲 iOS
🔲 Linux
🔲 MacOS
🔲 Windows
AR
✅ WebXR
🔲 SceneViewer
🔲 QuickLook
Additional Context
The model appears too dark in AR mode, lacking the standard lighting seen in non-AR mode or on other phones. Note that the model does not appear completely black (as seen in others issues sections), it just lacks of lighting. The issue is inconsistent across devices, mainly affecting older LG and Samsung models using Chrome. I do not have specific information on the devices used, only the brand; these devices are older. On most phones (about 95% in my case) everything works perfectly, and the lighting is applied correctly. Weirdest thing is that the same devices that render some models dark can view other models with correct lighting on the same web page, despite the models being processed and created in exactly the same way.

**Comment by elalish** [comment]
Please don't cross post: #4559.
