### ISSUE TITLE
iOS Edge Beta: no longer opening USDZ files in ARQL

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#4571]
### Description

In iOS Edge (beta) USDZ files and generated USDZ blobs are no longer opened in ARQL. Instead, Edge simply displays the filename. 

#### Live Demo

https://modelviewer.dev/

- Click on the AR icon on the astronaut. 
- Observe Edge open a window that displays the filename, rather than opening 3D model to ARQL. 

Also happens on non Model-Viewer content, such as: 
https://developer.apple.com/augmented-reality/quick-look/

Has been reported through the in-app feedback channel. But I do not have a way to escalate or follow up. 

iOS Edge is pretty small audience share. However, Model-Viewer compatibility checking currently assumes iOS Edge to be compatible. If Edge does not fix, may have to remove Edge from ARQL candidate list. 

### Version
- model-viewer: any

### Browser Affected

- [ ] Chrome, version: xx.x.xxxx.xx
- [x] Edge, 117.0.2045.12 beta
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [x] iOS, 17.2 beta 3 (21C5046c)
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

### Screenshots

After clicking on AR button:
![IMG_8576](https://github.com/google/model-viewer/assets/53870482/3c7f25ec-f474-45e5-b573-e785a1a68f1f)

**Comment by elalish** [comment]
Interesting, that sounds like an old iOS Chrome bug - I wonder if they updated to a bad (for us) version of Chromium.

**Comment by sugarfreejaz** [comment]
happening for me as well.

**Comment by milesgreen** [comment]
Retesting with:

- Edge 121.0.2277.70 beta
- iOS 17.4 beta (21E5195e)

Same issue still persists. 

Will try testing on some non-beta releases of Edge/iOS.

But might have to drop support for iOS Edge...

**Comment by elalish** [comment]
Fair enough - is it just me or is QL getting shakier and shakier? It seems to take longer than ever to load a model.

**Comment by milesgreen** [comment]
Also being discussed here:

https://github.com/google/model-viewer/discussions/4781

**Comment by milesgreen** [comment]
As discussed here: https://github.com/google/model-viewer/discussions/4781#discussioncomment-10049785 this now looks to be resolved and iOS Edge once again supports viewing models in AR quicklook.

Closing.
