### ISSUE TITLE
Calling createVideoTexture with cross origin video url cause CORS error

### ISSUE THREAD

**Issue by navidadelpour** [google/model-viewer#4634]
#### How To Reproduce
1. Run this [example](https://modelviewer.dev/examples/scenegraph/#animatedTexturesExample) on localhost or glitch.com.
1. Switch to video mode.
1. The below error is logged in the console.
```
THREE.WebGLState: DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The video element contains cross-origin data, and may not be loaded.
```

#### Live Demo

https://glitch.com/edit/#!/stellar-abstracted-verdict

#### Solution
As I searched about this issue, I come across this [issue](https://github.com/ml5js/ml5-library/issues/217) that addresses the same problem which solved with [this](https://github.com/ml5js/ml5-library/issues/217#issuecomment-424085565). And I submitted a PR that fixes this issue by letting us call the `createVideoTexture` like this:
```javascript
createVideoTexture(url, {crossOrigin: "anonymous"})
```
The detailed Implementation will be explained in the PR. I would be glad to know if there are anything else needed for this feature. or it can be solved via another solution.

### Version

- model-viewer: v3.3.0

### Browser Affected

I only checked the issue on the chrome. I guess the issue exists in all browsers.
- [X] Chrome, version: 120.0.6099.109
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by Saliiih** [comment]
I am facing the same issue.
