### ISSUE TITLE
Elastic min/max extents of camera orbit

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#465]
In AR QuickLook, there is a maximum and minimum to how much you can tilt the model (like model-viewer has). However if you keep dragging down, the model keeps tilting slightly with diminishing effect, allowing you to go beyond the limits.

![quicklook](https://user-images.githubusercontent.com/190692/55413657-be8d3c00-5537-11e9-91c6-a0aac8ce6600.gif)

Then when you release, it snaps back as though there is some elastic force on it.

I wonder what people feel about this and if it makes for a more polished UX that we should port to the viewer.

**Comment by cdata** [comment]
Nice! Personally, I think this looks really slick and I would like our controls to support this kind of interaction. Perhaps we can look into upgrading them to work this way as we implement #458 .

**Comment by elalish** [comment]
@cdata Can we give this a milestone?
