### ISSUE TITLE
WebAR on Samsung S24+ Exynos. Black Screen but AR works

### ISSUE THREAD

**Issue by LB31** [google/model-viewer#4661]
### Description

Same problem as with the issue #3495 but with the new Samsung S24.

When I start a WebAR session features like hit testing still work, but there is no camera view.

#### Live Demo
Screenshot: ![webXR_S24plus](https://github.com/google/model-viewer/assets/15799249/20ad1c2f-28a6-4bfd-a87b-607a318a0916)
Link: https://immersive-web.github.io/webxr-samples/hit-test.html

### Version
- model-viewer: v3.4.0

### Browser Affected
- [ ] Chrome, version: 120.0.6099.231
- [ ] Chrome Canary, version: 123.0.6263.0
- [ ] Samsung Internet, version: 24.0.0.47

### OS
- [ ] Android

### AR
- [ ] WebXR

**Comment by elalish** [comment]
Thanks, but does Samsung have someplace you can file bugs or feedback? There's nothing we can do about their browser bugs. Also, you're not even referencing anything to do with model-viewer. At least we can fall back to scene viewer.
