### ISSUE TITLE
Frames Rendering to Incorrect Canvas - Multiple Model-Viewers on Page

### ISSUE THREAD

**Issue by cpiggott** [google/model-viewer#4705]
### Description

When looking through the Model-Viewer examples page, I ran into an issue when there was more than one Model-Viewer rendered on the page at any time. As I scroll from one example to the next, you'll see in the attached video that the model/scene expected for one instance renders to the other and then bounces back and forth.

#### Live Demo

See the attached [video](https://github.com/google/model-viewer/assets/5440136/7469221a-3d12-4336-8cac-ccf3597cc59b). 

### Version

- model-viewer: Whatever is on the examples page: [Model-Viewer Example](https://modelviewer.dev/examples/augmentedreality/index.html)

### Browser Affected

- [X] Chrome, version: 122.0.6261.94 (Official Build) (x86_64) 
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS, version: macOS Version 13.6.1 (Build 22G313) MBP 16", 2019
- [ ] Windows

**Comment by cpiggott** [comment]
I haven't had issues until recently, but I don't know when it started. I might have some time later this week to try with a few older versions if I can repro with a local instance.

I'm not seeing the same issue on other browsers, but I am seeing artifacting now on Safari which I haven't seen before.

 
<img width="664" alt="Screenshot 2024-03-11 at 2 07 44 PM" src="https://github.com/google/model-viewer/assets/5440136/3323e35a-5d29-45d5-b533-b139253027d2">

**Comment by elalish** [comment]
This is starting to look like a GPU driver issue - is there anything you can update on your system? It should be easy to test older versions by changing the version string here: `https://ajax.googleapis.com/ajax/libs/model-viewer/3.4.0/model-viewer.min.js`

**Comment by cpiggott** [comment]
I'll see about updating to 14.4 tonight and report back.

**Comment by cpiggott** [comment]
Updates solved the issue. Sorry for the false alarm!
