### ISSUE TITLE
Ar button problem 

### ISSUE THREAD

**Issue by bysmoke** [google/model-viewer#4706]
[pufff.txt](https://github.com/google/model-viewer/files/14539718/pufff.txt)

There is no AR button in both web and android. What am I doing wrong?
![pufandroid](https://github.com/google/model-viewer/assets/162462298/eb9f6fe2-2490-4066-9dd6-f41fddbbae27)
![puffweb](https://github.com/google/model-viewer/assets/162462298/7e277e68-2abd-4cca-9714-d24286bb9023)

**Comment by elalish** [comment]
Let's keep this in your original, #4698. If you want issues to be answered, please fill in the issue template instead of deleting it.
