### ISSUE TITLE
Generated usdz has a random y rotation when the auto-rotate attribute is used

### ISSUE THREAD

**Issue by vincentfretin** [google/model-viewer#4732]
### Description

When not using ios-src, the generated usdz is correctly facing us when you don't have the auto-rotate attribute on the model-viewer tag.
When you have the auto-rotate attribute set, the generated usdz y rotation is different each time you click on the AR button.
I have currently no idea how this is correlated and where in the code the issue may be.
I found the issue while testing the placement "wall" for QuickLook, see my original comment https://github.com/google/model-viewer/pull/4030#issuecomment-2030234235

#### Live Demo
https://vfretin-wrong-usdz-y-rotation.glitch.me/
I removed the ios-src attribute and kept the auto-rotate attribute.

https://vfretin-ok-usdz-y-rotation.glitch.me/
I removed the ios-src and the auto-rotate attributes. This one is working correctly.

### Version
- model-viewer: v3.4.0

### Browser Affected
- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS
- [ ] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
Thank you for the very clear repro!

**Comment by vincentfretin** [comment]
I'm glad you found the issue and did the fix!
