### ISSUE TITLE
Upgrade to latest version of threejs (r164.1)

### ISSUE THREAD

**Issue by aardvarkk** [google/model-viewer#4786]
### Description

Upgrade to the latest version of ThreeJS

### Version

- model-viewer: v3.5.0

### Browser Affected

- [x] Chrome, version: xx.x.xxxx.xx
- [x] Edge
- [x] Firefox
- [x] IE
- [x] Safari

### OS

- [x] Android
- [x] iOS
- [x] Linux
- [x] MacOS
- [x] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
A little be of context on *why* this point release is important would be nice... 😄

**Comment by aardvarkk** [comment]
@elalish It adds support for the glTF extension `KHR_materials_dispersion`, so upgrading allows any models that use it to display properly in Google Model Viewer.

**Comment by elalish** [comment]
Excellent, thank you!
