### ISSUE TITLE
Model is rendered too pale/vague

### ISSUE THREAD

**Issue by bingo-soft** [google/model-viewer#4795]
### Discussed in https://github.com/google/model-viewer/discussions/4794

<div type='discussions-op-text'>

<sup>Originally posted by **bingo-soft** June  3, 2024</sup>
By default my model looks very pale or vague. Just like this:

![model-viewer1](https://github.com/google/model-viewer/assets/48438172/7b673fc6-13d9-4c55-8dd5-a00c71209436)

For example, compare that to xeokit viewer:

![xeokit](https://github.com/google/model-viewer/assets/48438172/33bc612f-5139-4457-b042-7649ef44548a)

I tried many different options, but none of them works. At the moment, I set it like so:

```
<model-viewer :src="src" ar camera-controls :shadow-intensity="1" min-camera-orbit="auto auto 0m" :zoom-sensitivity="0.1" class="model-component"></model-viewer>
```

How can I fix it?
</div>

**Comment by elalish** [comment]
Please don't cross-post
