### ISSUE TITLE
WebXR+AR experience design

### ISSUE THREAD

**Issue by jsantell** [google/model-viewer#48]
The current/previous WebXR+AR experience was the most crude thing imaginable: a circle appears on a surface when found and tapping places the model there. No other visuals or indications. Very MVP. Open questions surrounding this, and what we need or can do for an initial release:

## Stabilizing notification

In the [WebXR+AR codelab](https://github.com/googlecodelabs/ar-with-webxr/), a gif is displayed to users indicating they should "look around" with their device as a pose is found. This can take a few seconds in some environments on some phones.

We use this gif with the caveat that there's [some compositing jank with it](https://github.com/googlecodelabs/ar-with-webxr/issues/9).

<img src="https://github.com/googlecodelabs/ar-with-webxr/blob/master/assets/stabilization.gif?raw=true" height="200">

## Instructions

In the [Chacmool](https://web-education-ar-demo.appspot.com/) AR experience, instructions are rendered to describe how to interact.

<img src="https://user-images.githubusercontent.com/641267/47580559-0a421680-d904-11e8-9753-99b443493ae5.png" height="400">

## Footprint Reticle

In the [Chacmool](https://web-education-ar-demo.appspot.com/) AR experience, the reticle becomes the footprint of the model, and displays additional information regarding the dimensions (once placed, see the other Chacmool image here). 

<img src="https://user-images.githubusercontent.com/641267/47580559-0a421680-d904-11e8-9753-99b443493ae5.png" height="400">

## Interaction Controls

Apparently it's difficult to touch the screen and press two buttons to take a screenshot, but you can see some styled touch marks when interacting, and can slide (translate) and rotate the model (via two finger rotate). These interactions are/were non-trivial to get working, probably out of scope for MVP. I think the "pin" button halts the movements.

<img src="https://user-images.githubusercontent.com/641267/47580105-d74b5300-d902-11e8-9dba-a0d08e0a016c.png" height="400">

## Exit controls

This seems easy and something we should probably have. The "X" in the upper left in Chacmool example.

**Comment by jorgesilva** [comment]
@jsantell @cdata for exit, we also need a configurable call to action button that can point to a custom link. This would be essential for those looking to use AR to increase conversion rates (e.g., "Buy Now").

Currently, neither Scene Viewer, nor Quick Look have a way to achieve this, yet this feature is key to justify the use of AR from the economics of conversion mindset that paying clients would have to introduce AR to their web sites/apps.

Incidentally, the same applies for Google's search markup for listing AR in directly on search and/or shopping channels.

I am keen to help with this effort any way I can.

**Comment by elalish** [comment]
@jorgesilva I believe you'll get all the customization you want once DOM Overlay ships with WebXR in Chrome (which should be fairly soon). I'm less sure about the SceneViewer / QuickLook integration side. Contributions there would be very welcome!
