### ISSUE TITLE
[Tonemapping Page] Switching to another tonemapper than PBR Neutral and then back does not set the tonemapper back to PBR Neutral

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#4804]
### Description

When switching here the scene does not go back to PBR Neutral, it goes to Linear/Clamped:
https://modelviewer.dev/examples/tone-mapping

<img width="807" alt="image" src="https://github.com/google/model-viewer/assets/2693840/2ef7c6e7-0fb3-4d02-8768-6bf16401c49e">

At page reload it correctly displays PBR Neutral:
<img width="711" alt="image" src="https://github.com/google/model-viewer/assets/2693840/b151e348-6148-469e-a979-f47c33226473">

#### Live Demo
https://modelviewer.dev/examples/tone-mapping

**Comment by elalish** [comment]
I can't repro this - can you give more specific steps? Is it browser-dependent?

**Comment by hybridherbst** [comment]
Here's a video:
This happens on Chrome on both MacOS and Windows.

As far as I can tell, selecting the first option will always choose "None" (so no exposure and things clamp).

https://github.com/google/model-viewer/assets/2693840/9ff516d8-3d8e-44a2-b256-b0191b42d6b1

**Comment by hybridherbst** [comment]
Found it, was simply the wrong value in there (custom tonemapping -> doing nothing vs. actually using neutral tonemapping)
