### ISSUE TITLE
Support for hot-swapping of multiple models

### ISSUE THREAD

**Issue by ronpadz** [google/model-viewer#481]
Support for hot-swapping of multiple models in an experience without leaving the viewer is required. Consider the example of a product that has multiple configurations like an automobile. There could be a selector strip along the edge of the viewer window containing tiny thumbnails representing different models for the different available trim levels. Tapping a thumbnail replaces the current model with the selected model in the viewer allowing for easy and instant exploration and comparison. There would have to be a limit to the number of models bundled with the experience in order to limit the download transmission expense. One option would be to only download the default model and only download other selections if/when they are made but this would not be as performant as having all models downloaded and at the ready. Perhaps this is a decision the experience creator makes.

**Comment by smalls** [comment]
Would using multiple glTF scenes fulfill this? That would allow a single glTF to contain multiple configurations, and the developer or user could change between them without reloading the model.

Implementation aside, I agree - being able to change between multiple configurations would be great, and unlock use cases like the automobile configurator you mentioned.

(Somewhat related is generating models - see #186).

Thanks!

**Comment by elalish** [comment]
I would say this is already supported, as you can change the src URL of the model-viewer element at any time, as shown in the last example from this docs [page](https://modelviewer.dev/examples/model-formats.html). We even cache the models, so you can switch back and forth quickly, and you can control the cache with modelCacheSize.

**Comment by david-rhodes** [comment]
Sorry for the necro, but changing the `src` seems like an inefficient way to swap a sub-component of a model. This means mesh data is duplicated between source files and the client and host both pay the price.

Perhaps a glTF extension, similar to `KHR_materials_variants`, but for meshes is a better solution, but I'm not sure when or if that would be ratified. 

Besides, these type of scene graph API features could allow more interactive experiences to be built.

**Comment by elalish** [comment]
You should engage the WG on mesh variants; I believe there is interest and having someone driving for it will speed ratification.
