### ISSUE TITLE
Rendering Issues on Modelviewer Editor

### ISSUE THREAD

**Issue by sprengerst** [google/model-viewer#4815]
Some models stopped working if they are turned, it seems that the rendering engines has troubles showing the GLB. They disappear after some movements.

https://github.com/google/model-viewer/assets/6854862/d00b0e1d-056a-4d79-955f-69de4f66c6eb

#### Live Demo
https://modelviewer.dev/editor/

### Version
- model-viewer: v LATEST

### Browser Affected

- [x ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by sprengerst** [comment]
https://drive.google.com/file/d/1KXACTYyPKMsvw2EeI0NqDdVEmFWkcNGU/view?usp=sharing

Here is the GLB

**Comment by elalish** [comment]
Wow, that's crazy! I can repro, and weirder yet, it does not repro in the three.js editor, which should be using the same shaders. It sort of looks like z-fighting - you don't have coplanar triangles or anything weird like that, right? 

Is this a regression? Was there ever a time when this model worked properly in our editor?

**Comment by sprengerst** [comment]
Hi,
yes, this model worked before. There is nothing special to it, as you said it works with ThreeJS. Thanks for having a look. @elalish

**Comment by sprengerst** [comment]
I thought someone is crazy, after reading the first report :D

**Comment by elalish** [comment]
Would you mind checking different MV versions to let us know where the regression started? Just change the version string in `https://ajax.googleapis.com/ajax/libs/model-viewer/3.5.0/model-viewer.min.js`

**Comment by sprengerst** [comment]
Hi  @elalish 
I'm sorry we are using it "self built", it's not so easy to downgrade here.
We have another GLB where the issue occurs now. 

https://drive.google.com/file/d/1qJrURF1M7nGDtAfdV-lZEXd7LP6uKcY9/view?usp=sharing

**Comment by sprengerst** [comment]
@elalish  do you already now what is the problem here?

**Comment by elalish** [comment]
No, I haven't gotten a chance to look at this yet, and right now I'm prepping for a SIGGRAPH talk. You'll see when there's a PR. However, if you'd like to dig in and show what you find, that's always appreciated!

**Comment by Vinmossu** [comment]
> No, I haven't gotten a chance to look at this yet, and right now I'm prepping for a SIGGRAPH talk. You'll see when there's a PR. However, if you'd like to dig in and show what you find, that's always appreciated!

I have the same issue here, and the only thing I found is that the glitch seems to appear when using at least one alpha blend material with the double sided turned on

**Comment by elalish** [comment]
Possibly - thanks for the ping, I'll take another look.

**Comment by elalish** [comment]
Lucky us, you were right!

**Comment by sprengerst** [comment]
Perfect :) Thanks for the update.
