### ISSUE TITLE
Material and enviroment is not good in AR mode IOS

### ISSUE THREAD

**Issue by shahbaziparisa** [google/model-viewer#4817]
I use this code:

```
 <model-viewer  
                  src={model} 
                  ref={modelViewerRef}
                  shadow-intensity="1"
                  xr-environment
                    camera-controls 
                    environment-image="christmas_photo_studio_07_1k.hdr"
                    exposure="1"
                    scale="0.02 0.02 0.02" 
                    tone-mapping="neutral"
                    loading="eager"
                disable-tap 
                    onProgress={handleProgress()}
                    ar ar-modes=" scene-viewer quick-look  webxr"
                >
                    <button slot="ar-button" id="ar-button">
                    </button>
                </model-viewer>
```
But the result in ios is not good:
How Can I fix it?
![IMG_2034](https://github.com/google/model-viewer/assets/70272544/08987223-a721-4830-935b-51497221516e)
![IMG_2033](https://github.com/google/model-viewer/assets/70272544/5447868d-09c9-48c7-8038-c51510ae5775)

**Comment by elalish** [comment]
Let's keep the discussion centralized where I've already answered: https://github.com/google/model-viewer/discussions/4289#discussioncomment-9797604

Also, can you please be more specific than "not so good"? For all I know you could be complaining that your AR office building is sized for ants. 😄

**Comment by shahbaziparisa** [comment]
> Let's keep the discussion centralized where I've already answered: [#4289 (reply in thread)](https://github.com/google/model-viewer/discussions/4289#discussioncomment-9797604)
> 
> Also, can you please be more specific than "not so good"? For all I know you could be complaining that your AR office building is sized for ants. 😄

I mean the color and environment is not activated in Ar mode. It is clear that in 3Dview and ARmode they have different appearance.
About Scale it is ok I changed it manually for testing.
