### ISSUE TITLE
Thumbnail generation

### ISSUE THREAD

**Issue by ronpadz** [google/model-viewer#484]
When a url for a model-viewer experience is embedded in a web site, news article or social media post there needs to be an option available to the creator to have displayed a thumbnail representation of that experience which contains:
- An snapshot image of the model against a neutral background (ideally with a shadow to convey the volumetric nature of the model experience)
- A title for the experience
- A tagline for the experience
- The Model-Viewer badge as a signifier of the media type

This is akin to the behavior of a YouTube video link embedding.

**Comment by cdata** [comment]
We have definitely discussed making this a feature of #12 . I think that a composer / editor tool for exploring how `<model-viewer>` works would be ideal to exposure auxiliary helpers for things like thumbnail generation.

**Comment by elalish** [comment]
We now have a [tool](https://modelviewer.dev/examples/tester.html) for this, though we call thumbnails "posters".
