### ISSUE TITLE
Rendering artifacts on https://modelviewer.dev/

### ISSUE THREAD

**Issue by petrbroz** [google/model-viewer#4889]
### Description

I'm seeing strange rendering artifacts - noise - with the Neil Armstrong suit model on https://modelviewer.dev/. See the attached [video](https://github.com/user-attachments/assets/757b8dd8-3e08-4106-8ade-493282a8fa9d).

#### Live Demo

Directly on https://modelviewer.dev/.

### Version

- model-viewer: v3.5.0

### Browser Affected

- [x] Chrome, version: 127.0.6533.119
- [ ] Edge
- [ ] Firefox (no rendering artifacts there)
- [ ] IE
- [x] Safari, version: 17.6

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS: version 14.6.1
- [ ] Windows

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by petrbroz** [comment]
Also attaching my `chrome://gpu` info: [about-gpu-2024-09-17T08-25-00-145Z.txt](https://github.com/user-attachments/files/17025134/about-gpu-2024-09-17T08-25-00-145Z.txt)

**Comment by elalish** [comment]
This is a duplicate of https://github.com/google/model-viewer/issues/4773 - looks like Apple shipped a bad GPU driver for their old Intel-based Macs, since it's affecting both Chrome and Safari. Please help us rattle Apple's cage about this bug - there's not much we can do from here.

**Comment by elalish** [comment]
@AdaRosCanon FYI, in case you know a good way to escalate this regression.

**Comment by petrbroz** [comment]
Sorry about that @elalish. Let me close this ticket, and hopefully Apple addresses this soon.

**Comment by AdaRoseCannon** [comment]
Filing requests with Feedback Assistant is honestly the best way to escalate.
