### ISSUE TITLE
Ensure environment map adheres to lazy loading semantics

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#490]
As of #487 , we will have introduced progress bars, the notion of loading progress and the notion of new reveal semantics. However, we still need to ensure that environment maps are not aggressively loaded if the user has appropriately configured `<model-viewer>` to indicate that they would rather defer loading the environment map until the last possible moment.

**Comment by pushmatrix** [comment]
This is something we just bumped into this morning. For our shops that initially have model-viewer elements hidden, the environment map still gets generated and eats up 200-300ms of time even if not viewer is visible. 

IMO environment map generation should happen on viewer loading.

**Comment by richardmonette** [comment]
How detailed is the environment map that is being generated? If it doesn't contain high frequency details (think the "ambient" sort of light in Apple's QuickLook) then spherical harmonics / light probe could be an alternative to PMREM. Light probes are now supported in threejs https://github.com/mrdoob/three.js/pull/16223 An option could be to pre-compute the spherical harmonic coefficients offline and then store them in model viewer as the default. These coefficients comprise just a few vectors (think a few bytes at most) and easily embedded directly into the codebase.

**Comment by cdata** [comment]
@richardmonette 👋 I think you and @elalish could have an enriching (for the rest of us) discussion on this topic :)

@pushmatrix we can definitely defer generation of the environment map, we just don't right now. I scheduled it for v0.9.0, let's chat if you think it should land sooner!

**Comment by pushmatrix** [comment]
0.9 works :)

**Comment by richardmonette** [comment]
@elalish we could just load the spherical harmonics coefficients https://github.com/mrdoob/three.js/blob/dev/src/lights/LightProbe.js#L10 directly If you have an example of the env map we want to use as the default I've got some command line tools we can use to generate the sh coef.

**Comment by elalish** [comment]
@pushmatrix Agreed, but was that timing for 0.7 or master? Since #856 landed the generation time should also be quicker. If you have a chance to test it, I'd like to see what result you get.

**Comment by elalish** [comment]
@richardmonette Thanks, however SH has enough resolution only for the diffuse portion of the reflection, not the specular (even for a blurry env-map like our generated one). Additionally, I'm actually not happy with SH even for diffuse light when it comes to HDR environments. More on this later when I've finished my current set of rendering improvements.

**Comment by pushmatrix** [comment]
0.7, I'll test master

**Comment by richardmonette** [comment]
> Thanks, however SH has enough resolution only for the diffuse portion of the reflection, not the specular (even for a blurry env-map like our generated one).

Agreed, one last thought before I drop it, what if you used it as a progressive loading intermediate step, so the user would see the model sooner, with some lighting while PMREM finished in the background?

**Comment by elalish** [comment]
Possible, but I think there are simpler solutions. I'd like to spend some time improving our startup performance, and I think there may be more significant gains simply by organizing the threads to do more work in parallel with the networking and such.

**Comment by cdata** [comment]
Just to offer a compromise view, at the limit we will want to wring out every last drop of time we can to get our TTFI down. In that world, I can definitely imagine us relying on lower-fidelity intermediate lighting from SH while we generate something that looks nicer.

That said, the devil is in the details: what is the practical consequence for fidelity? I suspect folks are just as likely to be annoyed by a "flash of low-fidelity lighting" as they are by an extra second (possibly more) of load time. It's something that warrants experimentation.

It's also worth mentioning that we don't have a great tooling story to help folks generate SH for their own environment lighting (yet).

**Comment by pushmatrix** [comment]
@elalish Tested the speed difference between 0.7.2 and master in terms of env map rendering, and it seems like it shaves off 40ms.

**Comment by pushmatrix** [comment]
@elalish I don't do anything fancy with perf testing. I just use the performance monitor in Chrome.

Here's a glitch running master: https://sugary-bathroom.glitch.me/
<img width="648" alt="Screen Shot 2019-11-11 at 11 15 32 AM" src="https://user-images.githubusercontent.com/190692/68602635-b786be80-0474-11ea-990d-2c0cb9ae3b73.png">

And then I compare it with one running 0.7.2: https://spurious-ringer.glitch.me/
<img width="630" alt="Screen Shot 2019-11-11 at 11 17 41 AM" src="https://user-images.githubusercontent.com/190692/68602768-f3218880-0474-11ea-8bfd-6fee835c8002.png">

Probably lots of factors coming into play here, so the results do have a +/- 20ms to them.

**Comment by elalish** [comment]
Thanks, that’s helpful, because I see a very different trace. What device /
GPU are you testing on?

**Comment by pushmatrix** [comment]
<img width="273" alt="Screen Shot 2019-11-11 at 11 26 13 AM" src="https://user-images.githubusercontent.com/190692/68603334-17319980-0476-11ea-94a0-b691b2d55e40.png">

**Comment by elalish** [comment]
Pretty sure this is working these days.
