### ISSUE TITLE
can't place the 3d model into the right place

### ISSUE THREAD

**Issue by pengc02** [google/model-viewer#4902]
![Image](https://github.com/user-attachments/assets/0a82f580-b28b-447c-83c6-133ac3c1b850)

hi,guys! i'm building a page an use model-viewer to show a dynamic glb file, it seems that the viewer can't find the right bounding box and place the model at the wrong place, what can i do the adjust it.

'''
<model-viewer src="xxx.glb" poster="assets_dreamcraft3d/meshes/anya.jpg" align-model="center" style="width: 100%; height: 100%;" autoplay shadow-intensity="1" camera-controls touch-action="pan-y"></model-viewer>
'''

**Comment by danilokrulj** [comment]
I think there is not enough information to understand your problem, can you explain in more detail?
Is the model animated? Is it not on the ground? Is the problem in AR or while viewing the model before AR?

**Comment by pengc02** [comment]
> I think there is not enough information to understand your problem, can you explain in more detail? Is the model animated? Is it not on the ground? Is the problem in AR or while viewing the model before AR?

Thanks, i have solved the problem by adjusting camera-target and camera-orbit. Thank you very much!
