### ISSUE TITLE
Re-introduce Chrome as a legacy browser test target

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#496]
Before [we switched to recommending the `script type="module" / nomodule` strategy](https://github.com/GoogleWebComponents/model-viewer/commit/4adb9ef990acb625cd00470c97dc7710f77fde6a) for loading bundles, we included stable Chrome in our "legacy" browser target tests so that we could test the results of running the "legacy" bundle (which is meant to support IE11) against modern Chrome. We did this because there is a chance (however small) that someone will prefer to serve the IE11-intended bundle exclusively.

Unfortunately, as of the above-mentioned change, we accidentally stopped testing Chrome against that bundle. The Chrome target would run, but against the "modern" bundle.

So, that target has been removed from the legacy test targets. We should re-introduce it with its original intended purpose.

**Comment by elalish** [comment]
No more legacy bundle!
