### ISSUE TITLE
Meta Quest 3 v72 breaks AR

### ISSUE THREAD

**Issue by nolankucd** [google/model-viewer#4973]
I updated my Meta Quest 3 to v72 and it has caused problems for AR mode. The recently introduced (and much loved) hand tracking no longer works and the experience is generally not working as expected. Frequently AR mode fails to load or display the model unless the page is reloaded and the model falls through the set floor level. 

I suspect changes tot the hand tracking model in v72 is partly to blame.

**Comment by elalish** [comment]
Is this a known issue regarding WebXR, three.js, and the Quest browser @cabanier, @mrdoob?

**Comment by cabanier** [comment]
I don't believe there were any changes to hand tracking in v72.  I'm out of the office at the moment but will ask my team if they can investigate.

**Comment by nolankucd** [comment]
My understanding is that v72 comes with Hand Tracking 2.3.

**Comment by cabanier** [comment]
> My understanding is that v72 comes with Hand Tracking 2.3.

Do you have a guardian? What mode are you in?

**Comment by nolankucd** [comment]
Apologies, I did a factory reset of the Quest 3 and now it works as expected with model viewer.
