### ISSUE TITLE
Implement reveal="manual"

### ISSUE THREAD

**Issue by mikkoh** [google/model-viewer#502]
### Description

This is something we've been talking about at Shopify. If a user doesn't want to render in webgl but only handle fullscreen/ar experiences we could use an attribute `playsinline`. I think by default it would always "play inline" meaning render in webgl. However if a user passed `playsinline="false"` it would mean that it would not render in webgl but handles only fullscreen/ar experiences.

Documentation for `<video>` `playsinline`

> A Boolean attribute indicating that the video is to be played "inline", that is within the element's playback area. Note that the absence of this attribute does not imply that the video will always be played in fullscreen.

Thoughts? We might implement this even if it's not built into to `<model-viewer>` but it might be nice to have it in `<model-viewer>`

**Comment by cdata** [comment]
Yeah, that makes a lot of sense.

I think I would like to see this manifest as a specialization of the recently introduced `reveal` attribute. We have discussed having a `reveal="manual"` form where the only case where the model is revealed is when imperative `.dismissPoster()` API is invoked.

So, with this reveal behavior you would manually dismiss the poster when the model goes fullscreen. Does that sound similar to what you are going for @mikkoh ?
