### ISSUE TITLE
The AR button is not obvious / intuitive

### ISSUE THREAD

**Issue by jpmedley** [google/model-viewer#507]
Current, the only demo listed in the readme is for the [non-vr demo with the blue background](https://model-viewer.glitch.me/). It would be nice to have a vr equivalent.

**Comment by cdata** [comment]
AR or VR?

There is the demo in our online documentation: https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html

**Comment by jpmedley** [comment]
The button that activates it isn't really obvious. I didn't think to click it until you told me there was a demo.

**Comment by cdata** [comment]
Thanks for the feedback!
