### ISSUE TITLE
Fidelity golden screenshot update automation is not running

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#531]
Our GCP-based fidelity golden screenshot update automation is currently out of commission. Unfortunately, we haven't automated spinning up this infrastructure yet, so others won't be able to diagnose the issues for themselves without a lot of manual work.

Until this problem is addressed, we will have to manually update the fidelity test goldens using the appropriate `npm` scripts.

**Comment by elalish** [comment]
I'm okay with manual golden updates.
