### ISSUE TITLE
Simplify AR attributes

### ISSUE THREAD

**Issue by smalls** [google/model-viewer#541]
We now have several attributes that each individually control our AR experience:

* `ar` for Scene Viewer
* `ios-src` for Quick Look
* `magic-leap` for Magic Leap devices
* `unstable-webxr` for browsers that support the new WebXR API

Currently, a given platform/browser only supports a single AR experience - therefore, there's no overlap between these individual settings. Therefore we currently have the opportunity to simplify and consolidate on a single attribute (`ar`).

This means removing the other attributes (`ios-src`, `magic-leap`, and `unstable-webxr`), and gating those features by a mix of the `ar` attribute and other parameters like:
* included additional source (in the case of `magic-leap`) 
* other configuration (for `ios-src`, nested `source` or `src` as discussed in #429).

In the future a given platform may support several of these experiences, and a developer may want to express an opinion about which ones to prefer. However, as those become available we can assess if that's needed (or if there are always best options available).

This is a further refinement of the `ar` attribute, documented as part of #540. We'll want to do this after moving away from `ios-src` as part of #429.

**Comment by mikkoh** [comment]
I was just thinking about this. Does Magic Leap not use GLTF? If it doesn't now it will.

What if `ar` could be a boolean or a list of platforms?

eg.
`<model-viewer ar`
or
`<model-viewer ar="magic-leap,ios"`

I would probably just simplify to use `ar` as a boolean initially and then when someone complains implement the list.

**Comment by smalls** [comment]
Magic Leap can use GLB (not glTF iirc).

I agree with your proposal of starting with `ar` as a boolean and later (when more options exist/we have solid use cases) extending that to an ordered list.
