### ISSUE TITLE
Improvement: Add new events for AR behavior

### ISSUE THREAD

**Issue by Esteban26** [google/model-viewer#567]
This event could help us to know if the AR button has been created, if it has been clicked etc without access the shadow dom.

Related to the AR button

- AR button ready To be triggered in case it has been created and showed.
- AR button error: To be triggered in case AR button has been requested with the ar attribute/ unestablewebxr but device is not an AR candidate.
- AR button tapped (Same case i had to access to the shadow dom and if you change some the default-ar-button class my code would fail so would be better to have a way to subscribe users to these events).

Related to the AR behavior.

- AR success: To be triggered in case AR has been triggered successfully. Maybe it won't be possible due to the Intent implementation.

- AR error: To be triggered in case intent code has failed, in my case I made subscribed again to the sabe hash change event, so would be better to have an event coming from model-viewer instead or send a callback to be executed in case of this error happens.

**Comment by cdata** [comment]
Thanks for this great list.

So, to throw some ideas on the wall, it seems like we might need:

 - `ar-button-visibility` - Fires when the button becomes visible or hidden
 - `presentation-error` - Fires when there was an error presenting in AR. But, I think we can only safely fire this for WebXR cases? Maybe we also need....
 - `ar-fallback` - Fires when we launch a "fallback" AR mode like fullscreen
 - `ar-activate` - Fires when we are about to attempt activating an AR transition **or** launching WebXR-based AR. Note: you can already tell if the AR button is clicked (using `event.path`). This would be fired when the AR button is clicked, but also when AR is attempted from imperative API calls like `modelViewer.enterAR()`

"Success" is tricky. For Scene Viewer and Quick Look, success means leaving the browser, so it's kind of unclear what you should do when responding to a success event (or if the event will even fire when expected).

"Error" is also tricky. We don't know if there was a real error on the Quick Look / Scene Viewer side (like, if the model fails to load in Scene Viewer, the browser has no idea). Today we only know that Quick Look / Scene Viewer did not activate, not if there was an error, and failure to activate usually just means they aren't available.

**Comment by Esteban26** [comment]
Thanks, your list could help a lot, and yes, track events could be tricky, It happened to me while trying to track events of ARQuickLook btns, I was able to get the click event of the AR button when entering to the AR view but not when users exit from that view.

**Comment by Esteban26** [comment]
@cdata could you please also share some documentation about the method you mentioned **enterAR** I already checked the current documentation but that method is not documented.
