### ISSUE TITLE
Support Basis compressed texture loading

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#571]
As of https://github.com/mrdoob/three.js/pull/16522, Three.js has support for loading [Basis textures](https://www.khronos.org/blog/google-and-binomial-contribute-basis-universal-texture-format-to-khronos-gltf-3d-transmission-open-standard). We should take advantage of all of this amazing work and integrate support into `<model-viewer>`.

This work is in the same spirit as #72

**Comment by elalish** [comment]
Done!
