### ISSUE TITLE
Scene viewer bug with skinned mesh root transform. Model viewer works fine.

### ISSUE THREAD

**Issue by ephb** [google/model-viewer#572]
### Description

I have created an animated a gltf. The animation works fine in model viewer but is broken when opening it in scene viewer. It seems like the skeletal animation works in general but the root transform seems to not be applied.
 
Additionally the zoom to extents does not work.

Model was created with the babylon.js gltf exporter for 3dsmax 2019.

#### Live Demo

https://prong-month.glitch.me/

### Browser Affected

Does not apply. Works fine in browser.

### OS

- [x] Android 9 on Samsung Galaxy S8

**Comment by cdata** [comment]
Thanks for reporting this! I have relayed the issue to the Scene Viewer team and will update here when I learn more.

**Comment by cdata** [comment]
@ephb thanks again. This is a bug in Scene Viewer. I don't know when a fix will be released, but the problem has been confirmed, and hopefully an updated version in a future release will work as you expect.

Separately: that dancing unicorn is an amazing asset. Where did you get it from? Is it actually licensed CC-BY (as the repro case suggests)?

**Comment by ephb** [comment]
@cdata thanks for letting me know. Is there a place to report scene viewer issues directly? 

The asset is not CC-BY i forgot to change that form the astronaut sample.
I need to produce another model with the same properties that I can actually put under CC-BY to test future versions of scene viewer with.

**Comment by cdata** [comment]
@ephb unfortunately right now there is no direct way to give feedback on Scene Viewer. Eventually, I expect there will be an option to provide feedback from the three-dot drop-down menu.

Our team works closely with the Scene Viewer team, so in the mean time we are able to let them know about relevant bugs. That won't be sustainable for us over the long term, but for now we can forward any test cases you make :)
