### ISSUE TITLE
Make camera controls physics configurable

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#580]
In #288 we introduced a new camera control scheme that features many potentially configurable parameters.

In https://github.com/GoogleWebComponents/model-viewer/issues/498#issuecomment-486709830 we discussed making the physics of camera interpolation configurable. This includes qualities such as velocity and dampening. We should add sufficient configurability to `<model-viewer>` to ensure that camera interpolation looks and feels the way a user expects.

**Comment by elalish** [comment]
Dupe.
