### ISSUE TITLE
User configuration to customize URL shown in Scene Viewer

### ISSUE THREAD

**Issue by streamgao** [google/model-viewer#588]
### Description
The Scene Viewer demo shows a link at the bottom of 3D and AR modes. 
But there is no such attribute for this src value. 
Can we surface this attribute out?

### OS

Android

**Comment by cdata** [comment]
Currently we auto-populate this field with the current URL, because users probably don't expect to click through to a totally different page after launching Scene Viewer from the web. Could you lay out the use case for exposing this as a configurable attribute?

**Comment by streamgao** [comment]
Looking to implement this component for AR commerce use cases. 
It would be nice to have that attribute so we can link to the product sale website in AR.

**Comment by streamgao** [comment]
Current AR experience make user isolated in the AR mode solely without any context from the place they enter. 
It'll  be very helpful to offee more information for better user experience

**Comment by cdata** [comment]
@streamgao currently we set the hyperlink to be the page that the user came from, which is the page that hosts the 3D model. Can you confirm that you see a hyperlink back to the original page when launching Scene Viewer?

**Comment by streamgao** [comment]
@cdata  Yes!  
Sorry I didn't explain clear: 
We piloted some commerce content with AR quicklook solution recently. You can find some examples from [here](https://www.yahoo.com/lifestyle/worlds-best-litter-box-see-augmented-reality-152835094.html) and [here](https://www.yahoo.com/lifestyle/meet-plant-2019-see-home-augmented-reality-163945595.html). 

So: 
- Current iOS with usdz solution doesn't have this function of hyperlinking and doesn't provide a place to put extra information in AR mode.  
- We want to adopt the model-viewer with the control over the hyperlinks. The use case we are looking here is:  find the product inside of an article, click to go to AR/3D mode, click the hyperlink should lead to the merchant website rather than the original page. 

Thanks!

**Comment by elalish** [comment]
This is done; if you add SceneViewer query params to your URL, they are properly passed along and override our defaults.
