### ISSUE TITLE
Camera-orbit attribute ignored in certain cases

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#592]
### Description

I'm trying to implement a reset button that sets the camera-orbit parameter back to a default (eg: "0deg 90deg 1m")

So after the user spins a model around, they can press the button to reset the view. The problem is when you spin the model around, the camera-orbit param does not get updated to reflect the model's new position. I understand that's because we don't want to update the DOM every frame.

But that means that the camera does not move because the camera-orbit parameter has never changed from "0deg 90deg 1m", even though the model did visually rotate.

My workaround right now is to remove the camera-orbit attribute before setting it.

#### Live Demo
Follow repro instructions here:
https://dapper-blender.glitch.me

### Browser Affected
All browsers

### OS
All OS
### Versions

- model-viewer: v0.3.1
- three.js: r101

**Comment by cdata** [comment]
@pushmatrix we rely on `UpdatingElement` semantics for this (see the property configuration [here](https://github.com/GoogleWebComponents/model-viewer/blob/master/src/features/controls.ts#L89-L91)). So, in theory the value should always report as changed, even when you are setting it to the same value that it was set to previously.

Have you been setting it via `setAttribute`? Did you also try setting its property form (e.g., `modelViewer.cameraOrbit = '0deg 90deg 1m'`)? Do you get the same result from both?

**Comment by pushmatrix** [comment]
Yeah both setAttribute or jQuery's `attr` and no dice.

Setting it from `modelViewer.cameraOrbit = '0deg 90deg 1m'` does work as intended

**Comment by cdata** [comment]
I discussed this with the TLs of `LitElement`, and they agreed that this is something that `UpdatingElement` is undermining. I filed https://github.com/Polymer/lit-element/issues/699 to request a change.

In the mean time, you should be able to assign the property as a workaround.

**Comment by elalish** [comment]
I don't think we need to track this one.

**Comment by emreboyraz0** [comment]
`for (const attr in extraAttributes) {
            modelViewer.setAttribute(attr, extraAttributes[attr]);
        }
        modelViewer.jumpCameraToGoal();`
solved my issue
