### ISSUE TITLE
Option to reveal only when model-viewer element is visible on the page

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#594]
In some cases the model-viewer might not be visible on page load:

- Part of an image carousel (ex: it is on slide 4 of 5)
- Below the fold

It could be beneficial to have an option to only reveal the viewer if is actually visible on the page. So when you get to the viewer in the carousel, it reveals. Same with when you scroll down the page and see the viewer element.

If `preload` is set, then the reveal is simply dismissing the poster. If `preload` is not set, then the loading + revealing happens as soon as the viewer is visible.

Suggestion:
- `reveal="visible"`

**Comment by cdata** [comment]
Thanks for filing this! We discussed implementing a `loading` attribute in the spirit of [the same attribute being proposed for images and iframes](https://addyosmani.com/blog/lazy-loading/). The idea would be that you can write your HTML like this:

```html
<model-viewer loading="lazy" src="any.glb"></model-viewer>
```

With the above configuration, the default `reveal` mode (`"auto"`) would be in play, and the model would not load or reveal until it enters the viewport.

Do you think that would satisfy your use case?

**Comment by pushmatrix** [comment]
Oh boy, yes yes yes! I didn't know `loading` was an attribute being proposed. That makes a ton of sense to make the model-viewer act similarly. 👍 👍

**Comment by pushmatrix** [comment]
Need to double check if the intersection observer works for cases where you unhide an element that had `display: none` on it.

**Comment by pushmatrix** [comment]
Which milestone do you think this would fall under?

**Comment by cdata** [comment]
Good question! Let's stick it in v1.0.0 :)

**Comment by pushmatrix** [comment]
Can this be closed now that model-viewer lazy-loads models by default?

**Comment by pushmatrix** [comment]
Is this a todo? I thought it's already implemented.

**Comment by elalish** [comment]
I believe this is now the default behavior.
