### ISSUE TITLE
Discover if other browsers besides iOS Chrome and Safari support Quick Look

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#627]
As of #626 users will be able to opt-in or -out of Quick Look integration in iOS Chrome and Safari. However, there are other browsers on iOS and we don't know whether they support Quick Look integration or not. We should do some research to uncover the general level of support across these other browsers, and possibly implement support as needed.

**Comment by Enelar** [comment]
So, on AR supported device I should try as many browsers as possible. Alrighty then.

**Comment by Enelar** [comment]
Aug 2 2019, with screenshots:

Chrome 62.0.32.02.54+
Edge 42.0.0.2233+ (42.0.0.2059 isn working, but 2233+ is fine)
UC Browser Latest -
Opera 48.0.2331.132663+
Firefox Latest - (model-viewer 60+)

[Test AR Astro.tar.gz](https://github.com/GoogleWebComponents/model-viewer/files/3464974/Test.AR.Astro.tar.gz)

Tested on Honor 10. Should I test any other versions @cdata ?

**Comment by Enelar** [comment]
![photo_2019-08-20_13-17-20](https://user-images.githubusercontent.com/750396/63339080-cca7f180-c34c-11e9-8ad9-3432749a49de.jpg)
