### ISSUE TITLE
Make auto-rotate rate of rotation configurable

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#629]
When enabling `auto-rotate`, users may desire to:

 - Change the rate of rotation to some specific value
 - Reverse the direction of the rotation

We should add a configurable attribute to set the rate of rotation in order to support these use cases.

**Comment by mithru** [comment]
any news on when this might be available?

**Comment by elalish** [comment]
It's been on the back burner for quite some time, so thanks for pinging. Can you tell me about your use case?

**Comment by mithru** [comment]
Thanks!
Flipping the rotation direction is all we need at the moment. 
Some clients have their logo on one side of their product which is a great starting position. But the current rotation makes it then rotate to the back of the product from that position. 

Any quick way to flip the rotation direction?

**Comment by elalish** [comment]
There's not, but this should be a simple attribute to add. I'll try to get this in the next release.
