### ISSUE TITLE
jpg/png embedded in .glb file - Couldn't load object error

### ISSUE THREAD

**Issue by hellomarekmis** [google/model-viewer#635]
I'm trying to display a simple plane object with a texture - london tube map - in model-viewer. Object is valid and renders well in a browser, but when entering the AR mode, I receive a message:
"Couldn't load object - looks like there's something wrong with this object"
You can try it here:
https://london-tube-ar.netlify.com/

Error encountered on: Android, Chrome, Motorola 7G.

**Comment by cdata** [comment]
Thanks for reporting @hellomarekmis . This is a Scene Viewer issue, not a `<model-viewer>` issue. I have forwarded this bug report to the Scene Viewer team, and they are investigating. I'll let you know when I have some official word back from them.

In the mean time, it appears as though you are using a very large image as the texture for that plane. I suspect if you could break it up into several smaller, square images (say no larger than 4096 in any dimension), you might have success loading in Scene Viewer.
