### ISSUE TITLE
Support BabylonJS as an alternative rendering backend

### ISSUE THREAD

**Issue by vortice3D** [google/model-viewer#639]
### Description

It could be very fair to have a model-viewer component of BJS alongside ThreeJS.

Any tip on a starting point to accomplish this task?

Best regards.

**Comment by cdata** [comment]
Thanks for checking us out!

In the long run, I believe we will consider supporting alternative renderers. BabylonJS is an obvious candidate, and so is Filament.

The easiest way to do it today is (unfortunately) not so easy. You will basically have to replace every class in the `src/three-components` directory with API-compatible versions that wrap your renderer of choice. And even after you do that, I'm not 100% sure that our abstractions aren't leaking Three.js details, so there might be additional work to do at the margins.

We would be excited to hear if you make any progress in this task. Good luck!

**Comment by vortice3D** [comment]
Hi **Christopher**:

Thank you very much for your advice, we have now a possible project that could be made that way (**_model-viewer_** web component + **_BabylonJS_**).

It that work is finally carried-out, we'll have in touch with this forum in order to explain our progress.

Best regards.
