### ISSUE TITLE
It's possible for animated models to clip outside of skybox

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#656]
![butterlyclipsphere](https://user-images.githubusercontent.com/240083/60029921-e2ec4680-9656-11e9-839b-b13997604c8f.gif)

**Comment by mrdoob** [comment]
My guess is that is not the skybox but the `camera.far` not being far enough for this animation.

**Comment by cdata** [comment]
Good call

**Comment by elalish** [comment]
This isn't really fixable since animations can move arbitrarily far.
