### ISSUE TITLE
Demo - Model out the viewport on page load

### ISSUE THREAD

**Issue by ilmandone** [google/model-viewer#657]
### Description

Opening the demo page at https://model-viewer.glitch.me/ I found the model only partially visible (see screenshot below).

![GoogleWC-ModelViewer](https://user-images.githubusercontent.com/7240510/60076108-04b4fe80-9727-11e9-97d3-fdea2f98f38f.JPG)

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Browser Affected

- [x ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ x] Windows

### Versions
- model-viewer: vX.X.X
- three.js: 105

**Comment by cdata** [comment]
Thanks for reporting! Can you share any additional details about your device that might help reproduce the bug? Ex: GPU, assistive technology etc.

**Comment by ilmandone** [comment]
Hi Christopher

I found out the issue on a 
HP EliteBook Folio 1040 G3 - i7-6600 with no ssistive technology.
Chrome 75.0.3770.100

A further investigation show that a similar issue occur if you shrink the browser window to 632px (in this case the model disappear).

Hope that help you
Andrea

**Comment by cdata** [comment]
@ilmandone Thanks a lot. Your description of the model disappearing reminded me of another issue we are close to fixing: #618 

I think the problem will likely be fixed in #619 , which should land soon.

**Comment by ilmandone** [comment]
Great :)
I look forward to new features 😃

**Comment by elalish** [comment]
Fixed sometime long ago.
