### ISSUE TITLE
Present multiple models at the same time when viewing in AR

### ISSUE THREAD

**Issue by KingYapster** [google/model-viewer#675]
Is there a way, where I can pass 2 modelUrl? So, it would load 2 models in ARViewer!

const intent = `${modelUrl.toString()}?link=${link}&title=${title}#Intent;scheme=${scheme};package=com.google.ar.core;action=android.intent.action.VIEW;S.browser_fallback_url=${encodeURIComponent(locationUrl.toString())};end;`;

**Comment by cdata** [comment]
Unfortunately Scene Viewer does not support this capability at this time. When WebXR lands, we will definitely support this in `<model-viewer>`.

**Comment by cdata** [comment]
@KingYapster I'm going to change the title of the issue to reflect a desire to load multiple models into the same scene.

**Comment by Dmitrijsmok** [comment]
@cdata I think this issue is not actual anymore. 
I have been loaded two separate meshes into one AR scene: First the main object/mesh, the second used to offset the first object from the floor.
You need to place both meshes into one collection in Blender 2.8

**Comment by KingYapster** [comment]
> 
> 
> @cdata I think this issue is not actual anymore.
> I have been loaded two separate meshes into one AR scene: First the main object/mesh, the second used to offset the first object from the floor.
> You need to place both meshes into one collection in Blender 2.8

I want to load multiple glbs files through model viewer. Think of it as a website where you can customize a robot and finally augment a complete robot (During runtime, store and pass all the (robot parts) glbs which are added by the user during customization phase, so user can augment the robot)

**Comment by cdata** [comment]
@Dmitrijsmok that's definitely a way you can approximate what @KingYapster is looking for. However, it has downsides, mainly that if you have tens or hundreds of model combinations, it isn't practical to make a different model for every combination.

Confirming @KingYapster 's original use case has yet to be supported 👍 so keeping this issue open.

**Comment by elalish** [comment]
Dupe.
