### ISSUE TITLE
Ability to manipulate model rig imperatively

### ISSUE THREAD

**Issue by kavikode** [google/model-viewer#685]
Is there an example of model viewer with forward kinematics and inverse kinematics?
Can you please let me know if the following example can be converted to model viewer, link: (link: https://threejs.org/examples/?q=kinematics#webgl_loader_collada_kinematics) threejs.org/examples/?q=ki…?

**Comment by cdata** [comment]
`<model-viewer>` cannot load Collada files specifically. That said, glTF supports exporting models with skeletal rigs (and optional associated animations). A good example of this is the `RobotExpressive.glb` that we use for our [animation examples](https://googlewebcomponents.github.io/model-viewer/examples/animation.html).

**Comment by kavikode** [comment]
Thank you so much! Animation is great but would like more control over the skeletal rig. With keyboard controls, how do I dynamically control each part of the skeletal rig?

**Comment by cdata** [comment]
Thanks for clarifying the use case. We definitely want to enable this kind of control. We do not support it currently. With your permission, I will change this issue into a feature request to have direct access to the scene graph for the purposes of manipulating the model's rig. Does that sound good to you?

**Comment by kavikode** [comment]
yes please I appreciate it.

**Comment by elalish** [comment]
This is out of scope for MV; you can always hack down into the three.js layer for this, but it's not an API we plan to support publicly.
