### ISSUE TITLE
Build and maintain a stand-alone AR button that can be used separately from <model-viewer>

### ISSUE THREAD

**Issue by milesgreen** [google/model-viewer#697]
Feature Request:

Provide the ability to launch directly to SceneViewer as a link from any element, rather than embedding the entire Model Viewer on the page. (Similar to how iOS AR Quick Look works). 

For example, support the ability to have an HTML href element that can link straight into SceneViewer. 

Benefits:

- Model preview doesn't need to be loaded unless user really wants to view it, so less bandwidth consumed.
- Reduces amount of space required on page.
- Easier to integrate into existing pages that might not have the space or need for an embedded 3D model.

**Comment by cdata** [comment]
👍 thanks for the feature request!

I agree, I think there is room in this space for an `<model-button>` element of some kind that does this. To throw in my own two cents: I think it would be cool if such a button could also _load `<model-viewer>`_ as a fallback (if desired) in the case that Quick Look or Scene Viewer are not available.

It would be pretty easy to implement such a magic button (especially if you borrowed some of the code in our project). That said, I'm not sure that this behavior belongs in `<model-viewer>` in particular. I would almost want it to be a _separate_ web component that lives in parallel with `<model-viewer>`. 

Just some thoughts :) thanks again for the request!

**Comment by milesgreen** [comment]
Good food for thought. Thanks. I see what you mean about this could be a separate web component to `<model-viewer>`. Makes sense.

**Comment by soraryu** [comment]
Note that you can "hack" that right now already by having javascript auto-click the AR button after it's available.
If you click on this link on a supported mobile device it will bring you right into AR on iOS and Android:
https://infinitygames-kids-galicnik.glitch.me/

Or (and that's how we're actually using it) scan this QR Code:
![image](https://user-images.githubusercontent.com/2693840/66398678-841cc400-e9de-11e9-9fee-a9d4e002ec6f.png)

Downside of course is that a) it will still load the GLB file into browser memory b) on iOS you get the double hit with GLB + USDZ. Upside is the aforementioned fallback, unsupported devices will just display the model-viewer model.

**Comment by drewwiskus** [comment]
> Note that you can "hack" that right now already by having javascript auto-click the AR button after it's available.

I hacked it to dispatch a click event onto the "default-ar-button" but android crashed everytime about a fullscreen request. Could you explain how you got around that?

**Comment by cdata** [comment]
@drewwiskus to fix the error you need to include the Fullscreen API polyfill, see https://github.com/GoogleWebComponents/model-viewer/blob/master/POLYFILLS.md

But, I can also tell you that you are seeing that because Scene Viewer is failing to launch. A common reason for this is that models are required to be hosted on a secure https origin (and localhost does not work). Let me know if changing that helps!

**Comment by leoncvlt** [comment]
I needed this for one of my projects, and decided to quickly implement a component for this: https://leoncvlt.github.io/ar-button/

I would love to contribute to model-viewer and have this as part of the package but after looking at the source for a bit I sadly figured my typescript knowledge is not up to task yet 🙃Might have to dedicate a few weekends to that.

**Comment by elalish** [comment]
This is fairly easy now, and the multiple downloads is solved with WebXR.
