### ISSUE TITLE
Model references not loading

### ISSUE THREAD

**Issue by J97cp** [google/model-viewer#728]
### Description

Got a model for showing with <model-viewer> but src only works with this link of the Astronaut.glb "https://cdn.glitch.com/36cb8393-65c6-408d-a538-055ada20431b%2FAstronaut.glb?v=1542147958948".
I downloaded the model to use it locally but it doesnt load.
![image](https://user-images.githubusercontent.com/32024393/63878588-875c7300-c98f-11e9-91e1-44cfe644e116.png)

### Browser Affected

- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions

- model-viewer: v0.6.0
- three.js: rXX

**Comment by cdata** [comment]
Hey @J97cp thanks for the report. Can you reload the page with your developer tools open to the network tab and paste a screenshot of what you see there?
