### ISSUE TITLE
Models are paler in AR mode on Android Chrome

### ISSUE THREAD

**Issue by fselcukcan** [google/model-viewer#754]
Hello everyone,

I am using model-viewer scene viewer to view gltf files in AR mode on Android in Chrome, however, they are not showed as they are in AR mode. They are paler than in the non-AR 3D viewer. Screenshots below are not the only example, it happens with other models too, I haev posted only two for the sake of brevity.

[Scene viewer support and limitations table](https://developers.google.com/ar/develop/java/scene-viewer) mentions File format support as:

> glTF 2.0/glb, using these extensions:
> - KHR_materials_unlit
> - KHR_texture_transform

Does that mean the gltf/glb files must have these materials properties as explained in he following links to corresponding extensions docs? I have checked some of my files gltf files in a text editor and they do not have these material properties. According to these extension's pages there should be some extensions properties in the materials:
- [KHR_materials_unlit](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit)
- [KHR_texture_transform](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_texture_transform)

Screenshots (for the second screenshot the resultis same in view in you space mode as well):
![Screenshot_20190917-125732_Chrome](https://user-images.githubusercontent.com/5363259/65037322-15f05e80-d956-11e9-9fcf-966f038abcbb.jpg)
![Screenshot_20190917-125801_Google](https://user-images.githubusercontent.com/5363259/65037321-15f05e80-d956-11e9-806a-1bb15df02f01.jpg)

**Comment by elalish** [comment]
Could you post some images so we can see what you mean by "paler"? As for extensions, no those are supported but optional. With no material specified you should get the default PBR material with metal = 0 and roughness = 1.

**Comment by fselcukcan** [comment]
I have added screenshots to the original post above.

**Comment by cdata** [comment]
@fselcukcan just to make sure we're all on the same page: currently, the "AR in Chrome" that you are seeing is achieved on Android via an external app called Scene Viewer. The main reason why renders sometimes look different in cases like this is that Scene Viewer uses a different rendering backend.

That said, if there is a major difference between `<model-viewer>` and Scene Viewer we want to correct that. Just keep in mind that it may not have anything to do with `<model-viewer>`'s fundamental rendering capabilities.

**Comment by elalish** [comment]
@fselcukcan Can you tell us some specifics of your device? We can't repro here, so it probably has to do with your particular GPU. We'll be happy to pass the bug along to SceneViewer once we have enough info for them.
