### ISSUE TITLE
GLB Normal map is corrupted 

### ISSUE THREAD

**Issue by AytoMaximo** [google/model-viewer#796]
Hello! I've found out that some of GLB files open with broken normal map. However all the files were created together and converted with the same tool. 

Demo is [here](https://aytomaximo.ru/model-viewer/test.html).

If you look at network tab and check the loaded resources, you can find that normal map is corrupted. 

![ShooterScreenshot-54-04-10-19](https://user-images.githubusercontent.com/14392087/66167930-5b927400-e644-11e9-85ba-a6bfa26a0c12.png)

However, for example, [this model ](https://aytomaximo.ru/model-viewer/test2.html) loads without errors. 

Also, I can't see any problems with the normal map if I just download GLB file on my PC. 

I use Unity for composing and converting 3D models from DAE with textures with the help of:
1) https://github.com/ousttrue/UniGLTF
OR also tried
2) https://github.com/KhronosGroup/UnityGLTF

Any idea what's going on? :)

**Comment by cdata** [comment]
Hi @AytoMaximo , thanks for reporting this. My immediate reaction just looking at your screenshot is that the normal map is being corrupted, and no longer parses as a valid image file. Of course, it is possible that there is a bug in our parser. I tried dropping your model into https://sandbox.babylonjs.com/ and it appears to be parsing the texture correctly. So, that makes me think that perhaps we are parsing that particular image incorrectly.

@donmccurdy do you think it's possible that the `GLTFLoader` could have a bug related to extracting images? Or perhaps Babylon's equivalent is just more forgiving of corrupted images...

**Comment by donmccurdy** [comment]
@AytoMaximo are you able to see a difference in the rendering of the model itself? I am not, and when I inspect the texture data uploaded to the GPU with SpectorJS (https://spector.babylonjs.com/), the normal map appears to be uploaded fine:

![Screen Shot 2019-10-05 at 11 46 52 PM](https://user-images.githubusercontent.com/1848368/66265416-e309ef80-e7ca-11e9-9e04-06b11391b176.png)

So I'm inclined to say this is either (a) a bug in Chrome's network tab, or (b) something about handling Blob URLs causing issues with Chrome developer tools. For example, maybe the Blob URL was revoked by the loader before Chrome Dev Tools accessed that data.

**Comment by AytoMaximo** [comment]
> are you able to see a difference in the rendering of the model itself?

@donmccurdy , our customer's 3D modeller had asked why don't we use normal maps, so that's I've started to investigate the issue. As for me, the developer and not the artist, there are no differences too :)

I don't not what is the issue, but there is an opinion that the 3d object looks wrong. Maybe I need to put here a [B302.zip](https://github.com/GoogleWebComponents/model-viewer/files/3694073/B302.zip) with the original DAE+textures.

**Comment by donmccurdy** [comment]
We do use normal maps. I don't think the original DAE file will help, the artist will need to identify why they think the normal maps aren't working correctly, or what the model ought to look like. For example, does the model appear any more correct on one of these viewers?

- https://gltf-viewer.donmccurdy.com/
- https://sandbox.babylonjs.com/

If there's visible difference in the normals compared to `<model-viewer/>` we can look into that.

**Comment by elalish** [comment]
I'm going to close this since there doesn't seem to be a problem with model-viewer.
