### ISSUE TITLE
AR mode not working on Safari only

### ISSUE THREAD

**Issue by DavidKarasek** [google/model-viewer#799]
### Description

Suddenly, I am no longer able to get this to work on iOS/Safari only. This was working a couple of days ago, and nothing has changed on the client side. It works fine iOS/Chrome and Android/All. I have tried using using older version of model viewer as well as 0.6.2. Other examples work fine in the phones being tested. 

```
<model-viewer alt="Refridgerator" 
  src="assets/Fridge.glb"
  ios-src="assets/Fridge.usdz" 
  background-color="#fff"
  poster="assets/fridge.jpg"
  reveal="interaction"
  preload
  quick-look-browsers="safari chrome"
  ar>
</model-viewer>
``` 

Example of how it is implemented in the HTML, link provided below.

#### Live Demo
https://nmg-web-ar-demo.firebaseapp.com

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [+] Safari

### OS

- [ ] Android
- [+] iOS - 13.0 / 13.1.2
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.6.2 (have downgraded to v0.5.1 as well)
- three.js: rXX

**Comment by DavidKarasek** [comment]
It has randomly started working for me again on all devices, with nothing changed.

**Comment by cdata** [comment]
@DavidKarasek thanks for reporting. Can you give us an update? Does it randomly fail for you, or has it been stable for the last two days or so?
