### ISSUE TITLE
No HDR on low-end devices

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#804]
In v0.6.x we lost rendering on many low-end devices (#797). As of #750 we appear to be rendering again, but without HDR and with some weird looking artifacts on Nexus 5.

![image](https://user-images.githubusercontent.com/240083/66490464-10be9500-ea66-11e9-9091-9836c91da7fd.png)

**Comment by elalish** [comment]
@cdata is this still true? I'm surprised I don't remember this issue.
