### ISSUE TITLE
Interaction prompt appears after tab switch

### ISSUE THREAD

**Issue by maaslalani** [google/model-viewer#812]
### Description
![Screen Recording 2019-10-10 at 11 04 59 AM 2019-10-10 11_29_04](https://user-images.githubusercontent.com/42545625/66583558-923f2180-eb51-11e9-9294-0ccbbd5d31c5.gif)

If the user interacts with the model _before_ the interaction prompt is displayed it will not show up, however if the tab is switched the interaction prompt shows up immediately.

Since the `userPromptedOnce` should not be triggered in this case, this _may_ be intentional behaviour but it seems strange to trigger on tab switch and not either normally or not at all.

#### Live Demo

Reproduce-able on: 
https://googlewebcomponents.github.io/model-viewer/

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.6.2
- three.js: r0.108.0

**Comment by cdata** [comment]
Thanks for reporting @maaslalani . Should I assume the preferred result here is that when returning to a tab where interaction already happened, the prompt is not displayed?

**Comment by maaslalani** [comment]
I think so @cdata, with this interaction prompt its not too noticeable but #788 might make it a little more so if the user changes the model to a weird position and then the prompt pivots the model.

What are you thoughts?

https://translucent-lunch.glitch.me/
![2019-10-10 13-46-27 2019-10-10 13_50_38](https://user-images.githubusercontent.com/42545625/66593471-118a2080-eb65-11e9-9f6b-3f4c6e9fab6a.gif)

**Comment by cdata** [comment]
To be honest, I'm on the fence. The current behavior is good for someone who may have accidentally interacted but did not know what they did. OTOH most users will probably just find it redundant (or in the worst case cloying or mildly-annoying).

Let's change it so that it doesn't reactivate under any condition after interaction happens once.

**Comment by pushmatrix** [comment]
This is somewhat related to https://github.com/GoogleWebComponents/model-viewer/issues/792 in that there are definitely cases where we want to re-iterate that something is interactive. This might be one of those cases.

**Comment by cdata** [comment]
@pushmatrix good point, I think these two things are related. Perhaps we can address this one when we fix #792.

**Comment by elalish** [comment]
I can't repro, so I think this got fixed during one of the prompt refactors.
