### ISSUE TITLE
Quality Tests broken in Firefox

### ISSUE THREAD

**Issue by donmccurdy** [google/model-viewer#813]
In Firefox 69.0.2 on macOS, the Quality Tests page renders but renders cannot be selected. In the JS console I see one initial error:

> TypeError: this.shadowRoot.querySelector(...).transferControlToOffscreen is not a function

And subsequent errors each time I click a render:

> TypeError: event.path is undefined

**Comment by donmccurdy** [comment]
Similar result in Safari, actually.

**Comment by cdata** [comment]
Yah, we have done zero diligence in this regard. The second error is probably due to a missing polyfill. The first error is because the analysis view has a hard dependency on OffscreenCanvas.
