### ISSUE TITLE
Allow fixed environment-image for more dynamic lighting

### ISSUE THREAD

**Issue by 01010111** [google/model-viewer#821]
Allowing a fixed environment/background-image would make it feel like the user is rotating the object in place instead of orbiting it, which would be a more appropriate interaction in some cases.

**Comment by cdata** [comment]
@01010111 thanks for the feedback! We can definitely consider adding an option for this. Do you have any specific cases in mind?

**Comment by 01010111** [comment]
I'm working on a model viewing web app to showcase some models of different artifacts, this accomplishes just about everything I need, but it would be nice to have the lighting remain static as a user tumbles the artifact around to explore it!

**Comment by cdata** [comment]
This is similar but different to #576 , so maybe it exists in the world of potential auto-rotate configuration options.

**Comment by elalish** [comment]
We now have an example demonstrating this.
