### ISSUE TITLE
Feature Req? Or I can't find doc: How to disable model and only have the button

### ISSUE THREAD

**Issue by drewwiskus** [google/model-viewer#825]
I'm attempting to create a button that would open quick look for ios - safari & chrome as well as on android chrome. Similar to how `<a href={file.usdz} rel="ar" />` works on iOS Safari

example of what I'm looking for `disableModel`: 

```
 <model-viewer src="./file.glb" ios-src="./file.usdz" disableModel={true}>
        <button slot="ar-button">Open Model w/ Button</button> <!-- only thing that renders -->
</model-viewer>
```

is something like this possible in the current version? If not, would this be considered to be added in the future?

**Comment by cdata** [comment]
@drewwiskus we don't have this right now, but we have discussed something like this in this issue: https://github.com/GoogleWebComponents/model-viewer/issues/697#issuecomment-519190084

**Comment by jorgesilva** [comment]
The Quick Look equivalent for Scene Viewer on Android phones is as follows:
```html
<a href="intent://yourdomain.com/models/yourmodel.glb?mode=ar_only&title=A+Title#Intent;scheme=https;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;"><img src="images/your-button.jpg"/></a>
```

**Comment by cdata** [comment]
@jorgesilva indeed!

Now we just need to make a version that handles both Quick Look and Scene Viewer at the same time...

**Comment by elalish** [comment]
This is pretty easy now and we have some Q&As on it.
