### ISSUE TITLE
How do I change the size of the model viewport?

### ISSUE THREAD

**Issue by mister-elliott** [google/model-viewer#830]
I have taken the simplest approach to using model-viewer,  but am unsure 
how set up the html so the model will render larger
in chrome, astronaut renders in a window 300x150, using this:
`    <model-viewer src="./assets/Astronaut.glb"
                  alt="A 3D model of an astronaut"
                  background-color="#ffff00"
                  shadow-intensity="4"
                  camera-controls
                  interaction-prompt="auto"
                  auto-rotate ar magic-leap>
    </model-viewer>`

[renderdimensions.zip](https://github.com/GoogleWebComponents/model-viewer/files/3730783/renderdimensions.zip)

It would be really nice if you had a sample that was stripped down to the barest basics, and then documented how to render with minimal code at some arbitrary window size.  
Code I am using from github is a week old.
png in the zip shows the model-view seems to set the view window to 300x150.

**Comment by cdata** [comment]
@mister-elliott since `<model-viewer>` is just a DOM element, you can change its size the way you would for any other element: with CSS 🎉 

For example:

```html
<style>
model-viewer {
  width: 800px;
  height: 600px;
}
</style>
<model-viewer ...></model-viewer>
```

Will make the viewport 800x600 and scale the model appropriately.

**Comment by mister-elliott** [comment]
nice, thanks.  when I tried to style background-color: #ffff00; in <style>model-viewer {...}, it did not take; I seem to have to set that color in the <model-viewer ....> tag.

**Comment by cdata** [comment]
Yes, unfortunately `background-color` is a special case, because rendering WebGL with transparency has consequences for things like alpha blending. We want to enable rendering in a way that would let you use `background-color` via CSS, but it will always be a trade-off.
