### ISSUE TITLE
Implement loading attribute for better lazy-loading control

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#832]
In v0.7.0 we will have shipped a tweak to our loading behavior so that models not in the render tree do not load their related sources (#815).

We should formalize our loading behavior to line up with the browser-native `loading` attribute that is now available for `<img>` and `<video>` elements ([explainer](https://addyosmani.com/blog/lazy-loading/)).

The proposed behavior of this attribute, when paired with the `reveal` attribute that we already have, would be as follows:

  | reveal=”auto” | reveal=”interaction”
-- | -- | --
**loading=”auto”** | Loads when near viewport.<br>Revealed once loaded. | Loads when the user interacts with it.<br>Revealed once loaded.
**loading=”lazy”** | Loads when near viewport.<br>Revealed once loaded. | Loads when the user interacts with it.<br>Revealed once loaded.
**loading=”eager”** | Loads immediately.<br>Revealed once loaded | Loads immediately.<br>Revealed when the user interacts with it

In this same change, **we will remove the `preload` attribute**.

**Comment by elalish** [comment]
Okay, so if I'm not mistaken this change is actually very small. We will remove the `preload` attribute, replace it with the `loading` attribute, where `auto` and `lazy` are equivalent to `preload = false` and `eager` is equivalent to `preload = true`, correct?
