### ISSUE TITLE
KHR_texture_transform support

### ISSUE THREAD

**Issue by PrisedRabbit** [google/model-viewer#841]
Hi,

Why KHR_texture_transform is mentioned on https://developers.google.com/ar/develop/java/scene-viewer but it doesn't work in AR?
Is it in a plan to fix, or may I fix it by my self?

Tested with TextureTransformTest and my models: mobile AR has no texture scaling (tailing), but web viewers has.

**Comment by cdata** [comment]
Hey, thanks for reporting @broshkin !

This is a known bug in Scene Viewer (the native app that we use to activate AR on Android), and that team is working to address it. Technically this is not directly related to `<model-viewer>`, but I will update here when the issue has been addressed.
