### ISSUE TITLE
Limit the amount of time the interaction prompt is shown.

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#844]
For both the basic and wiggle interaction prompts, continuous movement until user interaction (even with a pause) is an accessibility concern.  This is the case for someone with a cognitive disability, who's easily distracted, or someone having difficulty reaching and interacting with the model in order to cease the animation completely.

We should explore what it could look like to set a max number of wiggles.

**Comment by elalish** [comment]
This can be done externally to MV pretty easily.
