### ISSUE TITLE
Normals in 0.7 on some parts of the mesh look flipped

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#851]
### Description

In 0.7 I'm noticing that parts of my mesh now look flipped.
See here: https://vaulted-jonquil.glitch.me/

This is what it should look like, with the pattern being indented on both wheels. That's how it was in 0.6
<img width="448" alt="Screen Shot 2019-10-23 at 3 51 35 PM" src="https://user-images.githubusercontent.com/190692/67428886-07c4dc00-f5ad-11e9-9d6c-fcb8baff21e8.png">

In 0.7 though one of the wheels has the pattern looking like it's popping out:
<img width="489" alt="Screen Shot 2019-10-23 at 3 51 27 PM" src="https://user-images.githubusercontent.com/190692/67428991-3a6ed480-f5ad-11e9-9bc6-323113665241.png">

@elalish Could this be related to that three.js tangent bug?

### Browser Affected
All

### OS
All

### Versions
- model-viewer: v0.7.0
- three.js: r108

**Comment by pushmatrix** [comment]
In the three.js editor, it loads with double sided face rendering. It looks like this:

<img width="1250" alt="Screen Shot 2019-10-23 at 4 11 53 PM" src="https://user-images.githubusercontent.com/190692/67430269-e9141480-f5af-11e9-9f66-11a52ffe9434.png">

That's the same as what model-viewer is showing.

If I switch to front facing only, it looks correct:

<img width="1222" alt="Screen Shot 2019-10-23 at 4 11 37 PM" src="https://user-images.githubusercontent.com/190692/67430296-f7fac700-f5af-11e9-9d5b-6000a204abec.png">

Back facing:

<img width="1240" alt="Screen Shot 2019-10-23 at 4 11 44 PM" src="https://user-images.githubusercontent.com/190692/67430311-fe893e80-f5af-11e9-9d89-6fd004855963.png">

**Comment by pushmatrix** [comment]
This seems to only affect double sided materials

**Comment by elalish** [comment]
This looks like a change in three, picked up because we bumped the version to r108 in 0.7. We've seen several other bugs related to double-sided materials. The advice from the three.js maintainers is to avoid them (they also cause a performance hit). Is it possible to remove "doubleSided" from the glTFs in this case?

**Comment by pushmatrix** [comment]
@elalish In this case yeah, but we can't control what merchants on our platform are uploading. And if what they see in their authoring tool doesn't match what shows up on their product page, they'll be confused and think something's wrong.

**Comment by elalish** [comment]
I'd also appreciate if you could file this bug on three.js; that's the best way to figure out what's going on and get it fixed. I believe the fundamental problem is with a double-sided material it's not super clear which direction the normal map is supposed to point on each side. It's possible there is a correct answer, but I can see why it's a bug-prone area.

**Comment by pushmatrix** [comment]
https://github.com/mrdoob/three.js/issues/17804

**Comment by pushmatrix** [comment]
Shouldn't it just be in the direction that the normal is?

**Comment by elalish** [comment]
Yeah, looks like you're right: https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#double-sided

**Comment by elalish** [comment]
I fixed this, I think in v0.8 sometime.
