### ISSUE TITLE
Progress bar shows when reveal=interaction and the model hasn't been interacted with

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#876]
I noticed that if you put `reveal="interaction"`, a progress bar will appear even if the model isn't loading. Is this the progress of generating the env map?

![progress](https://user-images.githubusercontent.com/190692/68247155-364ca900-ffe8-11e9-8cf2-49aa547da0bf.gif)

Notice in that gif on page load, you see the progress bar. Then when you click the viewer, it loads the glb and shows a second progress bar.

Try it for yourself:
https://clever-echidna.glitch.me/

This was introduced with 0.7.1

### Browser Affected

- [x] All

### OS

- [x] All
### Versions

- model-viewer: v0.7.2
- three.js: r109

**Comment by cdata** [comment]
@pushmatrix yes, that is most likely what is happening there. "Progress" in our context is prone to discontinuities because we are doing several parallel tasks to prepare a model for rendering. This will probably be addressed in the context of #490 and #832 .

**Comment by elalish** [comment]
I believe this is fixed with the loading updates in v1.1.
