### ISSUE TITLE
Model interactions in Scene Viewer AR mode are very cumbersome

### ISSUE THREAD

**Issue by arzezniczak** [google/model-viewer#878]
Hello,
I'm trying to remix model-viewer sample with my own models created in our BIM software. I've uploaded my simple gltf model with 3 walls, but I've found that I cant move this model around. Every time I try to "catch it" with my finger it's just starts rotating.
Here is demo with my model: [https://wry-diamond.glitch.me/move_issue.html](https://wry-diamond.glitch.me/move_issue.html)

Additionally I would like to ask - is there any model dimension limit that can be viewed in AR? I feel like with bigger model it's always get scaled down but UI tells me thats 100% scale (?)
Here is demo with big model: [https://wry-diamond.glitch.me/big_model.html](https://wry-diamond.glitch.me/big_model.html)

PS. Thank you for all your work, it's a great project; viewing 3D content in AR is now easy like never before!

**EDIT:**
After some further reading and testing I have some thoughts.
First of all - I'm talking about viewing AR on Android, so as far as I know - it's Scene Viewer teritory. I don't know how it's working on iOS Quick Look because I don't have any iOS device to test this out.
I think I can't move model around if there is no enough space for it to fit, If I scale it down it's much easier to move it around.

Second - about model maximum dimensions. I've found some explanations [there](https://developers.google.com/ar/develop/java/scene-viewer): 
> The size of the model is determined by the glTF file, and is clamped to a range between 0.25 and 6 meters, inclusive. In other words, if the value falls outside the required range, it will snap to the closest minimum or maximum value within that range.

But again - it's Scene Viewer limit. Can you tell me if iOS Quick Look have this limitations too?

One question that comes to my mind after all this above - is there any way to interact with Scene Viewer and Quick Look through model-viewer?

**Comment by cdata** [comment]
@arzezniczak thanks for the feedback and for doing that research on your own 👍 

You are correct in your diagnosis: the problems you are having are in Scene Viewer, not `<model-viewer>`.

The interactions I am seeing in Scene Viewer do seem like a bug to me, so I will share this demo with the Scene Viewer team and see what they think. I can't promise anything, but maybe this can be fixed on their side.

> Can you tell me if iOS Quick Look have this limitations too?

AFAIK there are no such limits in Quick Look. I have asked around and will update this thread if I learn more.

> is there any way to interact with Scene Viewer and Quick Look through model-viewer?

Currently this is not possible. We have a limited integration surface area with Scene Viewer, and Apple has full control of Quick Look and does not coordinate with us on API.

One issue I would suggest that you follow is https://github.com/GoogleWebComponents/model-viewer/issues/738. It doesn't have all the answers, but it's probably the next meaningful step that we will be taking on this topic.

Eventually, our experimental WebXR-based AR will become stable. At that time, you will be able to have much more direct control of the AR experience by configuring `<model-viewer>`.

**Comment by elalish** [comment]
I think these issues have been addressed by WebXR, and likely also by SceneViewer.
