### ISSUE TITLE
Add camera marker

### ISSUE THREAD

**Issue by fabioroldan** [google/model-viewer#893]
In some occasions it is still useful to link the model with an AR marker. Example a card or book in which you do not want the user to place the object anywhere but specifically instead on these objects.
As in A-Frame with arjs
"marker-camera preset = 'hiro'"
https://aframe.io/blog/arjs/#add-augmented-reality-in-your-a-frame-project

**Comment by cdata** [comment]
@fabioroldan thanks for the feature request! This is one that I have wanted us to do for a long time, but it's really a matter of priorities that we haven't done it yet. The canonical issue for this is https://github.com/GoogleWebComponents/model-viewer/issues/184

**Comment by elalish** [comment]
Closing as a dupe.
