### ISSUE TITLE
Customizable Controls 

### ISSUE THREAD

**Issue by adaoust** [google/model-viewer#897]
I couldn't find a way to customize certain controls.

More specifically, it would be useful to be able to:

- Limit the rotation around a single axis
(_e.g. only horizontal, can only rotate left-right around the model_)

- Slowly reset the model's position after having been moved
(_i.e. before reinitiating auto-rotate. Maybe this could be doable with additional information such as 'user-interaction-end' in the camera-change event_)

- Change the auto-rotate speed or direction.

- Disable Zooming (_Seems to be covered by #458_)

**Comment by cdata** [comment]
@adaoust thanks for the request!

> Limit the rotation around a single axis

#458 is the issue you want to follow for this

> Slowly reset the model's position after having been moved

It sounds l like augmenting our camera-change event is what is called for here. What if we dispatched an event that signaled when the camera had reached its target?

> Change the auto-rotate speed or direction.

Sounds good. Filed https://github.com/GoogleWebComponents/model-viewer/issues/898 to address this.

> Disable Zooming (Seems to be covered by #458)

Yah, I think #458 is going to be a good one for you to follow.

Anything else?

**Comment by adaoust** [comment]
@cdata thanks for the prompt reply.

> It sounds l like augmenting our camera-change event is what is called for here. What if we dispatched an event that signaled when the camera had reached its target?

This would be perfect 👍

Thanks for everything.

**Comment by elalish** [comment]
I think this is all working now.

**Comment by sprengerst** [comment]
Hi @elalish,
I don't get it, how is #458 solving:

- Limit the rotation around a single axis
(e.g. only horizontal, can only rotate left-right around the model)

#458 is about zoom and field-of-view if I'm right. 
Is there any option if I would like to only be able to rotate an object horizontally?

Best,
Stefan

**Comment by elalish** [comment]
[`camera-orbit`](https://modelviewer.dev/docs/#entrydocs-stagingandcameras-attributes-cameraOrbit) is theta, phi, radius, so horizontal rotation, vertical rotation, zoom. To only allow horizontal rotation, just set both min and max to e.g. `auto 75deg auto`.

**Comment by sprengerst** [comment]
> [`camera-orbit`](https://modelviewer.dev/docs/#entrydocs-stagingandcameras-attributes-cameraOrbit) is theta, phi, radius, so horizontal rotation, vertical rotation, zoom. To only allow horizontal rotation, just set both min and max to e.g. `auto 75deg auto`.

Thank you very much. I wasn't aware of min/max-camera-orbit.
