### ISSUE TITLE
Configuration to control auto-rotate velocity

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#898]
In #897 we received a request to do this. We could probably express this as an `auto-rotate-velocity` attribute that defaults to whatever we currently have baked in.

**Comment by CarlVitasa** [comment]
Is this still being worked on?

**Comment by elalish** [comment]
Actually it was added a while ago, but I forgot to close this issue: https://modelviewer.dev/docs/index.html#entrydocs-stagingandcameras-attributes-rotationPerSecond
