### ISSUE TITLE
Scene Viewer Preview works different to actual on-device Scene Viewer (not model-viewer)

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#906]
### Description

The Scene Viewer preview available at https://vr.google.com/scene-viewer-preview displays models differently than actual Scene Viewer.

Found that after wondering for a couple hours why the model in question breaks there, until I finally decided to test it on an actual device since Scene Viewer Preview is literally the only place we found where this breaks. My assumption is that the web scene viewer displays polycount as **warning**, but actually stops rendering after 100k vertices. The model works totally fine on any device we tried it on.

#### Live Demo
https://glitch.com/edit/#!/marshy-pickle

Scene Viewer Preview:
![image](https://user-images.githubusercontent.com/2693840/69858853-32ccda80-1293-11ea-952b-d7073c49b3ce.png)

Model Viewer:
![image](https://user-images.githubusercontent.com/2693840/69858956-70316800-1293-11ea-8703-96486038011e.png)

On Device (with advent calendar in the background of course): 
![2019-11-29 10 33 58](https://user-images.githubusercontent.com/2693840/69859212-049bca80-1294-11ea-987a-0999f6d9e1ad.png)

### Browser Affected
Desktop (not model-viewer)

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by cdata** [comment]
Thanks for reporting this @soraryu ! I'll forward the issue to the Scene Viewer team and let you know if there are any updates.

**Comment by elalish** [comment]
@tpsiaki Not sure if this has been fixed, but should we consider having the previewer redirect to the editor so we don't have to fix it anymore?
