### ISSUE TITLE
Incorrect rendering in either model-viewer, scene viewer preview or scene viewer

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#909]
### Description

Related to #906 , but in this case there's a difference between "Model Viewer", "Scene Viewer preview" and "Scene Viewer in AR mode". Model Viewer looks as intended (displays vertex colors), and preview as well, looks same as the online previewer tool.

![Screenshot_2019-12-02-14-56-28-076_com android chrome](https://user-images.githubusercontent.com/2693840/69965621-f8727000-1514-11ea-9847-0b8fe4196d56.jpg)
![Screenshot_2019-12-02-14-56-36-865_com google android googlequicksearchbox](https://user-images.githubusercontent.com/2693840/69965629-fad4ca00-1514-11ea-882f-8d74e5188650.jpg)
![Screenshot_2019-12-02-14-57-05-597_com google android googlequicksearchbox](https://user-images.githubusercontent.com/2693840/69965638-fc05f700-1514-11ea-8dcb-16f53576b9a2.jpg)

#### Live Demo
https://glitch.com/edit/#!/literate-ptarmigan

### Browser Affected

- [X] Chrome
- [ ] Edge
- [X] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: latest

**Comment by cdata** [comment]
@soraryu thanks for reporting. I'll pass this along to the Scene Viewer team this morning.
