### ISSUE TITLE
Possibility to move model on 3D view

### ISSUE THREAD

**Issue by suro7** [google/model-viewer#910]
### Description

I think it will make sense to be able to move the model with right click of the mouse when viewing it on desktop browser. Currently we are able only to rotate/zoom model.

**Comment by cdata** [comment]
Thanks for the feedback! We have referred to this as "panning" the camera. I'm going to mark this as a duplicate, as we have already filed #447 to cover camera panning.

**Comment by elalish** [comment]
We now have an example showing this.
