### ISSUE TITLE
Document model size/complexity guidelines

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#913]
In #899 users who are new to presenting 3D content on the web ran into issues when a complex model caused iOS Safari to crash. The remedy was to simplify their model, but our docs do not offer any guidelines to help them.

We should probably refer users to Scene Viewer's docs on this topic. Also, https://vr.google.com/scene-viewer-preview gives helpful warnings about model size/complexity issues.

At any rate, a section in our docs offering guidance and troubleshooting advice to our users on this topic is called for.

**Comment by elalish** [comment]
Would be nice to have actionable feedback in the editor, and eventually tools to help optimize models for the web.
