### ISSUE TITLE
Better visual UX when there is a fatal error loading a model

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#914]
It would be useful for folks who are trying out `<model-viewer>` to get direct visual feedback when a model fails to load or otherwise causes some critical failure without `<model-viewer>`. This might be something akin to when an `<img>` fails to load or parse its source. 

![image](https://user-images.githubusercontent.com/240083/70070332-4a180a80-15a8-11ea-86e4-f3392816b5c2.png)

Although perhaps not as ugly or vague 😛

**Comment by elalish** [comment]
I disagree; the poster is a better fallback than messing up the user's experience. Then 3D is more like a progressive enhancement to an image.
