### ISSUE TITLE
Couldn't load object - cannot enter the Scene Viewer

### ISSUE THREAD

**Issue by JesungKoo** [google/model-viewer#925]
Hello. I've been using `<model-viewer>` for several months and had no problem with it. However, this week I got some awkward problem and couldn't find a solution nor clue to solve this problem.

### Problem

`<model-viewer>` cannot enter the Scene Viewer as expected.

<img src="https://user-images.githubusercontent.com/37990506/70694950-0a69c500-1d04-11ea-8b93-3f73c6514298.jpg" width="180" height="380"><img src="https://user-images.githubusercontent.com/37990506/70694970-135a9680-1d04-11ea-9823-b924b426026c.jpg" width="180" height="380"><img src="https://user-images.githubusercontent.com/37990506/70694974-16558700-1d04-11ea-80fa-526fdf98199d.jpg" width="180" height="380">

### Source Code

Using React.js (jsx)

```jsx
<div style={{ margin: 0, overflow: 'hidden', position: 'fixed', height: '100%', width: '100%' }}>
  <Helmet title={`${brandName} - ${productName} | Spac3D`}>
    <script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js" />
    <script src="https://unpkg.com/fullscreen-polyfill/dist/fullscreen.polyfill.js" />
    <script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js" />
  </Helmet>
  <model-viewer
    src={`/models/${brandCode}/${productCode}/model-no-shadow.gltf`}
    alt={productName}
    ar
    auto-rotate
    camera-controls
    exposure="0.5"
    shadow-intensity="0.4"
    style={{ width: '100%', height: '100%' }}
    quick-look-browsers="safari chrome"
  />
</div>
```

### Model Info

It is a separated GLTF file. There's .gltf, .bin and some textures in textures/ directory. There are some validation points - `MESH_PRIMITIVE_UNUSED_TEXCOORD`, `NODE_EMPTY` and `IMAGE_NPOT_DIMENSIONS` - but other models worked fine with same conditions. I've added the model I have used for demo. [model.zip](https://github.com/GoogleWebComponents/model-viewer/files/3954546/model.zip)

### Live Demo

https://pensive-lalande-75097b.netlify.com/iroche/IRO18AO061/android

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.7.2 & v0.5.1
- three.js: r108

**Comment by EugeneFitzher** [comment]
I have same issue. Did you solve the problem?

**Comment by elalish** [comment]
I believe this is either fixed or the glTF has malformed. Please open a new issue if there's a repro.
