### ISSUE TITLE
Enable rendering to be moved to a worker

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#930]
As a follow-up to https://github.com/GoogleWebComponents/model-viewer/issues/37 we should be able to transfer all rendering (via Three.js or otherwise) into a Worker context.

From a rendering perspective, this is not difficult architecturally, but from an integration perspective it means that all API surface contact with Three.js from the `<model-viewer>` DOM side needs to be made async. So, this work might be good to pair with #337 , which shares a similar requirement that Three.js not be assumed to be synchronously available at the time that DOM APIs try to make use of it.

**Comment by DavidPeicho** [comment]
I am curious how you are going to manage that at a large scale.

Do you plan of having the entire Three.js code running in the worker? (graph updates, camera controllers, etc...).
I am also wondering how much of data you will need to transfer at every frame, and how much this will have an impact?

**Comment by cdata** [comment]
Yes, the idea would be to have all of rendering moved into a worker,
including scene graph and camera controls (basically everything we
currently consider a "three-component", plus some bridge code).

The amount of data we transfer each frame should be limited to sparse
configuration updates (e.g., when the camera-orbit attribute changes we
parse and transfer the new value to the worker) and user interaction events
(e.g., when the user taps, swipes etc. we dispatch a proxy event in the
worker).

In the (best) case where the user is not interacting with the model and
also the configuration is not changing, we would transfer no data each
frame. In the (worst) case where the user is interacting with the model and
maybe also configurations are changing each frame, we still would only be
transferring a very sparse amount of information (like pointer position and
sparse, parsed attribute values).

This will, of course, introduce asynchrony where previously there was none
(reactions to UI events will be delayed by postMessage), but I anticipate
that this will be acceptable in practice. As long as postMessage latency
stays within our frame budget, I doubt users will notice. But, it
definitely warrants testing to make sure.

**Comment by DavidPeicho** [comment]
Sounds pretty good. I guess the async API isn't too bad, at least from my point of view it doesn't sound like a problem.

**Comment by elalish** [comment]
This turned out to be a dead end.

**Comment by DavidPeicho** [comment]
@elalish do you mind explaining a bit what is the issue? 🙂

**Comment by elalish** [comment]
It turns out moving rendering to a worker makes a lot of things difficult, but importantly, the benefit is that 3D rendering can be async with respect to DOM rendering. However, for hotspots and such, we actually want 3D and DOM to be in sync, which a worker would make impossible. In our case there is really no performance benefit.
