### ISSUE TITLE
Enable 3DOM to be lazy loaded

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#931]
Similarly to #337 , we will not always need 3DOM to be available up-front (or at all). 3DOM is only needed in cases where a user has actually specified a worklet script. So, we should eventually make it possible to load the 3DOM-related code lazily.

Note that this may benefit from #927 as that will involve breaking out 3DOM into a sub-project, but does not strictly depend on it.

**Comment by elalish** [comment]
No more 3DOM.
