### ISSUE TITLE
why the back of model is Defect？

### ISSUE THREAD

**Issue by braveheartty** [google/model-viewer#945]
### Description

there is many models, but only this model is abnormal,is it caused by doublesided?
sketchfab is normal,but abnormal in this viewer

my viewer:
<img width="454" alt="EB09D2F5-E04B-46B7-8189-4948AB1978A1" src="https://user-images.githubusercontent.com/49051610/71400480-ea21fa80-2661-11ea-97cb-1b2138df8cb7.png">

sketchfab

<img width="435" alt="9387E965-DF54-48D8-82C7-B2F93066457B" src="https://user-images.githubusercontent.com/49051610/71400520-0c1b7d00-2662-11ea-8afa-74cba004e4a1.png">

#### Live Demo

https://sketchfab.com/3d-models/shell-harpago-chiragra-3e5309f1a099400aa1ce79b449dfdf4b
https://testing.modelvue.growlib.com/index.html?url=https://growlib-model-sk-hk.oss-cn-hongkong.aliyuncs.com/play/103485/scene

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: vX.X.X
- three.js: rXX

**Comment by elalish** [comment]
@braveheartty I'm not getting a repro; your demo renders just fine for me on Chrome Linux. Would you mind filling out the form below your post so we know what platform and version is having trouble? If it's a mobile device, please be specific about the model as sometimes things like this are driver bugs.

**Comment by cdata** [comment]
@braveheartty I'm also not able to reproduce this problem on my mac. Can you share your hardware/browser details with us?
