### ISSUE TITLE
Reduce git clone size of repo

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#957]
Our repo is now a 2.35Gb download, which is pretty ridiculous, especially for a small project. It's almost entirely fidelity golden images, which would be better served by Git LFS. Of course in order to switch, we'll also have to rewrite our history (the idea being to keep it, but simply in a new place). This is dangerous, so I'm thinking I'll fork this into my own repo and give it a shot there so we can see how it works.

We could also save the Goldens elsewhere or only keep the most recent versions in git.

**Comment by MugOfPaul** [comment]
Yes! Thank you!

**Comment by elalish** [comment]
I added `depth=1` to the git clone instructions, which is the cheap way to solve this.
