### ISSUE TITLE
Make it possible to set custom Scene Viewer link and title

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#971]
### Description

I found https://github.com/GoogleWebComponents/model-viewer/pull/855#pullrequestreview-307394678 which is great - it basically allows to pass parameters such as sound= and link= directly into SceneViewer since they get preserved when just appending them to the original source.

However, that pull request mentions that it's not exactly a good idea to append "link" (I guess the parameter will be double then). Is there a "clean" and documented way of adjusting what parameters get passed into SceneViewer?

(link= and title= work right now, I'm just afraid that might change at any point if not documented)

#### Live Demo

https://glitch.com/edit/#!/pfc-modelviewer-audio-tests

**Comment by cdata** [comment]
I am guessing that the current behavior of passing duplicates of the same query param is undefined (@tpsiaki can maybe comment on that).

We can change the way we launch Scene Viewer to check for existing query params that match `title` and `link`. I don't think there is a "clean" way to do it otherwise.

**Comment by elalish** [comment]
Done.

**Comment by sprengerst** [comment]
Hello, is there any reference in the  documentation how to use this feature?

**Comment by elalish** [comment]
Yes: https://developers.google.com/ar/develop/java/scene-viewer

**Comment by sprengerst** [comment]
Hi, thanks for your response I know this one. But, how can one configure „link“ and „title“ with a GLB imported in ModelViewer?

**Comment by elalish** [comment]
Just add those query parameters to your `src` URL.

**Comment by sprengerst** [comment]
Thx. Should the parameters be added url-encoded or plain?

**Comment by elalish** [comment]
I believe you can do them plain. Feel free to file an issue if anything about their use is not very ergonomic. We haven't had a lot of feedback on it.

**Comment by sprengerst** [comment]
I got it now, I always used webxr as ar-mode, therefore none of my scene-viewer arguments were recognized. But thanks for your input :)

**Comment by elalish** [comment]
Ah yes indeed. With WebXR you can do it all with child HTML elements.

**Comment by sprengerst** [comment]
Ah nice. If I would set it to default WebXR I wouldn't have to mess around with scene-viewer. 
If I set it to default are there many devices that can't handle webXR or do all scen-viewer devices also support webXR? ar-modes="webxr" (**only**)

**Comment by elalish** [comment]
I believe any phone that supports scene-viewer also supports WebXR (assuming you're in a Chrome browser), since it's all based on ARCore availability. WebXR actually does better, since many people do not have scene viewer installed.
