### ISSUE TITLE
Google Scene Viewer

### ISSUE THREAD

**Issue by ravsamy** [google/model-viewer#976]
We are developing a learning application for a client and we are using Scene Viewer(https://developers.google.com/ar/develop/java/scene-viewer) with AR functionality as a 3d Model Viewer. The thing is we have develop a Content Management System, where we generate URL of the 3d Model and the button prompt near the article, all the models are fetched from the server and its working seamlessly. 

The thing is and you should please look into it, the models that we are downloading from sketch fab, the Scene Viewer is able to load them and able to view both 3d and in AR, but after a couple of hrs or maybe days, the Sketchfab 3d models are not able to load the model. Sceneviewer throws an error like “Couldn’t load object, Looks like there is something wrong with this object.

We tried to resolve this

by Clearing Cache from the Server
by Clearing Cache from the Android App and Even AR Core 

The only thing that resolves this is that we have to factory reset the phone. 

The only models that are working after the error are the ones from google poly or those who have passed this validation ( https://arvr.google.com/scene-viewer-preview ).

What I want to know is that Scene Viewer clearly has the potential to load heavy models from Sketchfab, but after some time, Why It stops working ?

I am sending you the link of the model,https://sketchfab.com/3d-models/bmw-i8-4b143b95aec045bf8912d99662f8d580 

we were able to load this model from the scene viewer. 

Please let me know your thoughts and solution that you guys can recommend on this.

**Comment by cdata** [comment]
Hi Ravsamy, it sounds like you have an issue with Scene Viewer. If you also have issues with `<model-viewer>`, please let me know. Otherwise, I'm going to refer this issue to the Scene Viewer team. I cannot promise you that they will respond, but sometimes they do :)

cc @tpsiaki any thoughts on above?

**Comment by ravsamy** [comment]
> Hi Ravsamy, it sounds like you have an issue with Scene Viewer. If you also have issues with `<model-viewer>`, please let me know. Otherwise, I'm going to refer this issue to the Scene Viewer team. I cannot promise you that they will respond, but sometimes they do :)
>Thank you so much for your time and for raising the issue to the concern people.
> cc @tpsiaki any thoughts on above?

**Comment by tpsiaki** [comment]
Thanks for the report and the model link.  This is unexpected behavior.  We'll look into it.

**Comment by ravsamy** [comment]
<img width="1604" alt="Screenshot 2020-01-31 at 3 03 34 AM" src="https://user-images.githubusercontent.com/34287705/73515486-7e2e7100-441b-11ea-928f-ab81742b2d4a.png">
<img width="1600" alt="Screenshot 2020-01-31 at 3 04 09 AM" src="https://user-images.githubusercontent.com/34287705/73515487-7ec70780-441b-11ea-9530-4dd3b2c22331.png">
@tpsiaki , These are the logs when we try to open the model.

**Comment by tpsiaki** [comment]
@ravsamy that indicates that your gltf has absolute paths referencing some of its resource files (e.g. bin/png/jpg).  Currently Scene Viewer only supports relative paths to resource files in a gltf so you would need to update your models to use relative paths.

Alternatively if it works for your experience, you could convert these models to glbs (without externally referenced resources) and that would also correct the crash you're seeing.

**Comment by ravsamy** [comment]
@tpsiaki ,Thank you so much for the help, converting the model in glb worked for us and it also worked in the sceneform. 
I think we are sorted for now. can you please tell me more about relative path, so we can make gltf work in future?

**Comment by silvainSayduck** [comment]
Hi! I realise this is most likely not at all the right place to report this, but we have a somewhat simple and valid GLB that does not load properly in Scene Viewer, so I thought I'd report it here first, and hopefully someone can point me to the right place for this kind of things (maybe @tpsiaki?):
[2020.09.09.model.glb.zip](https://github.com/google/model-viewer/files/5193613/2020.09.09.model.glb.zip)

Only the central rod shows up in AR in the Scene Viewer...
Thanks a lot in advance for the help.

**Comment by elalish** [comment]
@silvainSayduck you've mentioned the right person. You're welcome to file things like this as new issues; I'll just mark them with the not-model-viewer flag, but they're still helpful to have visible as others are likely having similar problems.
