### ISSUE TITLE
Disable pointer-events on "occluded" hotspots

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#980]
Per discussion in https://github.com/GoogleWebComponents/model-viewer/issues/974#issuecomment-580393381, we should ensure that hotspots that are considered "occluded" do not accidentally capture pointer events like drag and click.

**Comment by elalish** [comment]
I'm not sure I agree with this one; I believe the purpose of keeping the hotspots visible while occluded is so that the user can interact with them. If the opacity goes to zero, I agree they should be unclickable, but I think only in that situation.

**Comment by elalish** [comment]
I'd say this is working as intended, see my comment above.
