### ISSUE TITLE
Cleanup WebXR placement mode / make it more usable

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#984]

**Comment by elalish** [comment]
Here's a list of features to make the WebXR UX mostly match SceneViewer:

1) Prompt showing to move the phone around until the floor plane is detected.
2) Automatically place object at first screen-center hit result.
3) Box with rounded corners showing projected bounding box on floor; fading out when touch is released.
4) Drag within box to translate the object, drag outside of box to rotate (only uses horizontal drag).
5) Object hops up slightly during translation (and just before auto placement), falling down on placement.
6) Darken shadow to make more visible against camera image.

A later version will consider the additional features:

1) Two-finger scaling (if enabled with `ar-scale` attribute), with scale % note.
2) Apply lighting estimation.
3) Apply occlusion.
