### ISSUE TITLE
modelViewer.getCameraOrbit() always returns the same radius

### ISSUE THREAD

**Issue by fivelive** [google/model-viewer#988]
The function `modelViewer.getCameraOrbit()` always returns the same radius no matter how much we zoom on the model. 

For example here are the values returned for those 2 screenshots:

<img width="601" alt="Screen Shot 2020-02-04 at 11 25 23 AM" src="https://user-images.githubusercontent.com/39774571/73764912-beeef880-4741-11ea-84e5-25c1b014c3a2.png">

returns "-0.5445427266222311rad 1.3142329267517303rad 9.168046334881678m"

AND 

<img width="601" alt="Screen Shot 2020-02-04 at 11 26 35 AM" src="https://user-images.githubusercontent.com/39774571/73764986-e5ad2f00-4741-11ea-8af2-3c00f49c7104.png">

also returns "-0.5445427266222311rad 1.3142329267517303rad 9.168046334881678m"

So as you can see, the camera orbit radius should be different for those 2 screenshots but it is the same. (9.168046334881678)

**Comment by cdata** [comment]
@fivelive yes, this is a subtle and confusing detail of the API. It used to be the case that zooming in caused the radius to change. However, eventually we changed to zoom using field of view (see #729).

So, when you zoom, you can use `getFieldOfView()` to measure the change.

**Comment by fivelive** [comment]
Oh i get it now, it indeed changed and I didn't realize until now. Thank you very much for the info. Keep it up!

**Comment by fivelive** [comment]
Well, ctually, in this case, what is the `radius` field used for in what `getCameraOrbit` returns?

**Comment by cdata** [comment]
The radius is the distance of the camera from the `cameraTarget` position in scene units, which we treat as meters. Since we are using `fieldOfView` to zoom, the `radius` doesn't change. However, you can still change the `radius`, and it will the effect of moving the camera closer to or father away from the `cameraTarget` position.

**Comment by fivelive** [comment]
oh ok I fully understand the nuance now. Thanks again!!
