### ISSUE TITLE
No ability to target annotations / hotspots based on visibility

### ISSUE THREAD

**Issue by theprojectsomething** [google/model-viewer#989]
### Description

Currently there is no easy way to style annotations / hotspots based on their visibility. While some CSS variables are available (`--min-opacity`), these aren't sufficient for e.g. transitions on child elements, etc.

I'd propose including a `[data-occluded]` attribute on the slotted element, as per the `[data-position]` and `[data-normal]` attributes, to allow targeting. The value should probably be binary for performance, so `1 = occluded` and `0 = visible`. Alternatively the value could update as the camera moves `1 > occluded > -1` and trigger an associated event, or remain binary but trigger a detailed event.

#### Live Demo

https://glitch.com/edit/#!/model-viewer

### Browser Affected

- [ x ] Chrome
- [ x ] Edge
- [ x ] Firefox
- [ x ] Helios
- [ x ] IE
- [ x ] Safari

### OS

- [ x ] Android
- [ x ] iOS
- [ x ] Linux
- [ x ] MacOS
- [ x ] Windows

### Versions

- model-viewer: v0.8.1 (master branch)
- three.js: r113.1

**Comment by cdata** [comment]
@theprojectsomething thanks for being proactive and thoughtful with this idea!

On the one hand, doing something like this is probably the only way to easily achieve this feature without requiring the author to add script.

On the other hand, when we manipulate attributes in the "light" DOM, it's possible for us to edit attributes that the user has already set. It's also possible for the user to overwrite the state of these attributes (intentionally or by accident, either way not a good thing).

This is a really interesting problem, and hopefully we can explore a few ideas before we commit to a solution. One thing I would like to play with is leveraging event dispatch + script, just to see how easy (or not) it is.

**Comment by theprojectsomething** [comment]
Agree event dispatch would be useful and less obtrusive to a wider audience. Interested to see what you come up with. Worth noting the rendering test / block in the PR.

**Comment by theprojectsomething** [comment]
Using events in our local build and working well - triggering a bubbling event on each affected slotted element as visibility changes.

It's a toggle style event: `{ detail: { hide: <Boolean> } }` ... didn't have any personal need for the normals delta so didn't include it, tho might be useful as a method??

I've updated the PR to reflect the change - used validated typescript this time too. Nightmare :)
