### ISSUE TITLE
The position of a Scene Viewer 3d model should be updated even when a touch is stationary

### ISSUE THREAD

**Issue by joensaar** [google/model-viewer#994]
### Description

Note: This is more of an issue with the UX of Scene Viewer.

Currently the position of a model is updated only when a touch is in a moving state. This often causes stuttering in translation. It is common for users to move 3d models by physically rotating and moving their device while continuously holding the touch.

If a user wants to move a placed object to some position behind them, the touch will have to be in a moving state for the entire duration of the user's physical rotation (which can last several seconds), otherwise the model's position will not be updated until touch movement is again detected.

I've come across this issue in my own UX research projects, and it's actually quite significant.

Tested modelviewer.dev Scene Viewer sample on Android/Chrome.

edit: it appears that there is a small drag threshold for initial selection (perhaps for entering rotation mode?) The suggestion above should only be applied once the drag threshold has been passed.

**Comment by joensaar** [comment]
Furthermore, the performance cost of this should be very minimal due to the unlikeliness of a touch being completely stationary for several consecutive frames.

**Comment by cdata** [comment]
cc @tpsiaki see above Scene Viewer feedback

**Comment by elalish** [comment]
Fixed.
